
/****** Object:  Table [dbo].[APP_PREFERENCE]    Script Date: 06-05-2026 11:57:19 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[AD_APP_PREFERENCE](
	[ROW_ID] [int] IDENTITY(1,1) NOT NULL,
	[PREF_NAME] [nvarchar](100) NOT NULL,
	[PREF_VALUE] [nvarchar](100) NULL,
	[COMMENTS] [nvarchar](500) NULL,
	[PREF_TYPE] [nvarchar](100) NULL,
	[CREATED_BY] [nvarchar](100) NOT NULL,
	[CREATED_DATE] [datetime] NULL,
	[UPDATED_BY] [nvarchar](100) NULL,
	[UPDATED_DATE] [datetime] NULL,
 CONSTRAINT [PK_AD_APP_PREFERENCE] PRIMARY KEY CLUSTERED 
(
	[ROW_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO