-- Table for User Credentials
-- Database: AUTONOMA

CREATE TABLE USER_CREDENTIALS (
    USER_ID NVARCHAR(50) PRIMARY KEY,
    EMP_ID INT NOT NULL,
    PASSWORD NVARCHAR(255) NOT NULL,
    CREATED_BY NVARCHAR(50),
    CREATED_DATE DATETIME DEFAULT GETDATE(),
    UPDATED_BY NVARCHAR(50),
    UPDATED_DATE DATETIME,
    STATUS INT DEFAULT 1,
    IMG_NAME NVARCHAR(255)
);

-- Sample Data (Optional)
-- INSERT INTO USER_CREDENTIALS (USER_ID, EMP_ID, PASSWORD, CREATED_BY, STATUS)
-- VALUES (N'admin', 1, N'admin123', N'SYSTEM', 1);
