-- Create HR Department Master Table
CREATE TABLE IF NOT EXISTS HR_DEPARTMENT_MASTER (
    ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    DEPT_NO INT UNIQUE NOT NULL,
    DEPT_NAME VARCHAR(50) NOT NULL,
    NDA_CERTIFICATE VARCHAR(3) DEFAULT 'No',
    SEQ_NO INT DEFAULT 0,
    CREATED_BY VARCHAR(50),
    CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_BY VARCHAR(50),
    UPDATED_DATE TIMESTAMP,
    STATUS VARCHAR(10) DEFAULT 'Active'
);

-- Create index on commonly searched columns
CREATE INDEX IF NOT EXISTS IDX_DEPT_MASTER_STATUS ON HR_DEPARTMENT_MASTER(STATUS);
CREATE INDEX IF NOT EXISTS IDX_DEPT_MASTER_NAME ON HR_DEPARTMENT_MASTER(DEPT_NAME);

-- Insert sample departments (matching legacy SUKI ERP data)
INSERT INTO HR_DEPARTMENT_MASTER (DEPT_NO, DEPT_NAME, NDA_CERTIFICATE, SEQ_NO, CREATED_BY, STATUS) VALUES
(10, 'ACCOUNTS', 'No', 0, 'SYSTEM', 'Active'),
(20, 'ADMIN', 'No', 0, 'SYSTEM', 'Active'),
(30, 'PRODUCT DEVELOPMENT', 'No', 0, 'SYSTEM', 'Active'),
(40, 'PURCHASE', 'No', 0, 'SYSTEM', 'Active'),
(50, 'QUALITY', 'No', 0, 'SYSTEM', 'Active'),
(60, 'HRA', 'No', 0, 'SYSTEM', 'Active'),
(70, 'PRODUCTION', 'No', 0, 'SYSTEM', 'Active'),
(80, 'BUSINESS DEVELOPMENT', 'No', 0, 'SYSTEM', 'Active'),
(90, 'MAINTENANCE', 'No', 0, 'SYSTEM', 'Active'),
(150, 'SALES & MARKETING', 'No', 0, 'SYSTEM', 'Active'),
(160, 'ASSEMBLY', 'No', 0, 'SYSTEM', 'Active'),
(170, 'QMS', 'No', 0, 'SYSTEM', 'Active'),
(180, 'DESIGN & DEVELOPMENT', 'No', 0, 'SYSTEM', 'Active'),
(190, 'STORES', 'No', 0, 'SYSTEM', 'Active'),
(200, 'OPERATIONS', 'No', 0, 'SYSTEM', 'Active'),
(220, 'LOGISTICS', 'No', 0, 'SYSTEM', 'Active'),
(240, 'TOP MANAGEMENT', 'No', 0, 'SYSTEM', 'Active'),
(250, 'STRATEGIC PROCUREMENT', 'No', 0, 'SYSTEM', 'Active'),
(260, 'PLANNING', 'No', 0, 'SYSTEM', 'Active'),
(270, 'MANAGEMENT REPRESENTATIVE', 'No', 0, 'SYSTEM', 'Active'),
(280, 'MANAGEMENT', 'No', 0, 'SYSTEM', 'Active');
