-- V3.3 Convert TEXT columns to NVARCHAR(MAX) for DISTINCT compatibility
-- TEXT is deprecated in SQL Server and causes issues with DISTINCT queries used in pagination.

-- 1. QMS_MASTER_CHECKLIST
IF EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID(N'[dbo].[QMS_MASTER_CHECKLIST]') AND name = 'AMENDMENT_REASON')
BEGIN
    ALTER TABLE [dbo].[QMS_MASTER_CHECKLIST] ALTER COLUMN [AMENDMENT_REASON] NVARCHAR(MAX);
END

-- 2. QMS_CHECKLIST_ASSIGNMENT
IF EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID(N'[dbo].[QMS_CHECKLIST_ASSIGNMENT]') AND name = 'REMARKS')
BEGIN
    ALTER TABLE [dbo].[QMS_CHECKLIST_ASSIGNMENT] ALTER COLUMN [REMARKS] NVARCHAR(MAX);
END

-- 3. QMS_CHECKLIST_VERIFICATION
IF EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID(N'[dbo].[QMS_CHECKLIST_VERIFICATION]') AND name = 'REMARKS')
BEGIN
    ALTER TABLE [dbo].[QMS_CHECKLIST_VERIFICATION] ALTER COLUMN [REMARKS] NVARCHAR(MAX);
END
