-- Alter columns of QMS_CHECKLIST_ASSIGNMENT from NVARCHAR(MAX) to NVARCHAR(2000) to allow sorting in window functions
ALTER TABLE QMS_CHECKLIST_ASSIGNMENT ALTER COLUMN REMARKS NVARCHAR(2000);
ALTER TABLE QMS_CHECKLIST_ASSIGNMENT ALTER COLUMN COMMENTS NVARCHAR(2000);
ALTER TABLE QMS_CHECKLIST_ASSIGNMENT ALTER COLUMN FILE_PATHS NVARCHAR(2000);
