-- Optimize column definitions and lengths in Induction module tables

-- 1. IND_INDUCTION_MASTER
IF OBJECT_ID('IND_INDUCTION_MASTER', 'U') IS NOT NULL
BEGIN
    ALTER TABLE IND_INDUCTION_MASTER ALTER COLUMN induction_details NVARCHAR(MAX) NOT NULL;
    ALTER TABLE IND_INDUCTION_MASTER ALTER COLUMN answer NVARCHAR(MAX) NOT NULL;
    ALTER TABLE IND_INDUCTION_MASTER ALTER COLUMN department_codes NVARCHAR(100) NULL;
    ALTER TABLE IND_INDUCTION_MASTER ALTER COLUMN level_codes NVARCHAR(100) NULL;
    ALTER TABLE IND_INDUCTION_MASTER ALTER COLUMN status NVARCHAR(20) NULL;
END

-- 2. IND_INDUCTION_ASSIGNMENT
IF OBJECT_ID('IND_INDUCTION_ASSIGNMENT', 'U') IS NOT NULL
BEGIN
    ALTER TABLE IND_INDUCTION_ASSIGNMENT ALTER COLUMN remarks NVARCHAR(MAX) NULL;
    ALTER TABLE IND_INDUCTION_ASSIGNMENT ALTER COLUMN induction_status NVARCHAR(20) NULL;
END

-- 3. IND_INDUCTION_TRAINING_DETAIL
IF OBJECT_ID('IND_INDUCTION_TRAINING_DETAIL', 'U') IS NOT NULL
BEGIN
    ALTER TABLE IND_INDUCTION_TRAINING_DETAIL ALTER COLUMN trainer_comments NVARCHAR(MAX) NULL;
    ALTER TABLE IND_INDUCTION_TRAINING_DETAIL ALTER COLUMN trainee_comments NVARCHAR(MAX) NULL;
    ALTER TABLE IND_INDUCTION_TRAINING_DETAIL ALTER COLUMN trainer_status NVARCHAR(20) NULL;
    ALTER TABLE IND_INDUCTION_TRAINING_DETAIL ALTER COLUMN trainee_status NVARCHAR(20) NULL;
END
