-- ============================================================
-- V38.0 Database Governance & Standardization (QMS, Checklist, Audit, Induction)
-- ============================================================

-- STEP 1: Drop existing foreign key constraints
ALTER TABLE audit_observation_detail DROP CONSTRAINT IF EXISTS FKFTT16QRXC64EU59W55DUTSN41;
ALTER TABLE qms_mom_attendance DROP CONSTRAINT IF EXISTS FK13BV8YXDW1OGOHN8IKYJ23GB9;
ALTER TABLE qms_mom_attendance DROP CONSTRAINT IF EXISTS FK5KQK3NRA1BOVVL8WHMXN5SD7Y;
ALTER TABLE hr_induction_assignment DROP CONSTRAINT IF EXISTS FK_INDUCTIONASSIGNMENT_EMPLOYEE;
ALTER TABLE qms_meeting_schedule_department DROP CONSTRAINT IF EXISTS FK2VAYWYIIR0GMDAFIC6TRPUN0X;
ALTER TABLE qms_meeting_schedule_department DROP CONSTRAINT IF EXISTS FKKBPB4TOPRDOS94M4I4G5QNYEU;
ALTER TABLE qms_checklist_department DROP CONSTRAINT IF EXISTS FKE3KW3CQLNUYVCGDVUHX040A7K;
ALTER TABLE qms_meeting_schedule DROP CONSTRAINT IF EXISTS FK20YVN65GXS7E9BR14MMG6VU9T;
ALTER TABLE qms_meeting_schedule DROP CONSTRAINT IF EXISTS FKJA75MCA8G4GNJPMBAO3OW0VG0;
ALTER TABLE qms_meeting_schedule DROP CONSTRAINT IF EXISTS FKICSNVQUEPAW9Y5JMPY91R7EU3;
ALTER TABLE qms_mom_master DROP CONSTRAINT IF EXISTS FKDA23FL6D8DC466B0NCLVC2SNB;
ALTER TABLE qms_mom_master DROP CONSTRAINT IF EXISTS FK8YL0T3BEDHQ0QHMTUJ51KA3JK;
ALTER TABLE qms_checklist_verification DROP CONSTRAINT IF EXISTS FKY53DS6TAGOMHU7QN02559U57;
ALTER TABLE qms_checklist_verification DROP CONSTRAINT IF EXISTS FK5544QKVVINDXLK4GE2HPHDXHN;
ALTER TABLE qms_checklist_verification DROP CONSTRAINT IF EXISTS FKOLPVVT64VDKSI67265J6FXASK;
ALTER TABLE qms_meeting_schedule_participant DROP CONSTRAINT IF EXISTS FKJ3FJVJ3MK7K4W584DYTOCGHTJ;
ALTER TABLE qms_meeting_schedule_participant DROP CONSTRAINT IF EXISTS FKB7EWGWKJQN1RKVEE9031U4NXR;
ALTER TABLE qms_mom_detail DROP CONSTRAINT IF EXISTS FKL88GY41BUUYYMSS0855FVPLL5;
ALTER TABLE qms_mom_detail DROP CONSTRAINT IF EXISTS FK8OBKBTI4UUKU12J2E84X41D84;
ALTER TABLE qms_mom_detail DROP CONSTRAINT IF EXISTS FK9NAN3XVB12YFYQ79LXMB79X0;
ALTER TABLE audit_schedule_criteria DROP CONSTRAINT IF EXISTS FK8M0NHBKGNMS52LH6MXKELT1VY;
ALTER TABLE audit_schedule_criteria DROP CONSTRAINT IF EXISTS FK8EM2PMD3KEYAMTHQ8GOSBI342;
ALTER TABLE qms_meeting_user_attendance DROP CONSTRAINT IF EXISTS FKPGAMC2SOFAHMDSKQAQISAELN;
ALTER TABLE qms_meeting_user_attendance DROP CONSTRAINT IF EXISTS FKEJS4CH2JWA6KFV8PHSAUISM9K;
ALTER TABLE qms_checklist_assignment DROP CONSTRAINT IF EXISTS FKLN0U5W8VBXI3OJX7TU3354FQY;
ALTER TABLE qms_checklist_assignment DROP CONSTRAINT IF EXISTS FKJGBCWJ07TVUKUSLIQ7AUKPYE;
ALTER TABLE qms_checklist_assignment DROP CONSTRAINT IF EXISTS FK9GLT0I2UPGH0V6C3W3SHK90EF;
ALTER TABLE qms_checklist_assignment DROP CONSTRAINT IF EXISTS FKMLSQF7HV7R6CXBKF656YSKLDG;
GO

-- STEP 2: Rename tables to UPPERCASE standard format with module prefix
ALTER TABLE audit_area RENAME TO QMS_AUDIT_AREA;
ALTER TABLE audit_attendance RENAME TO QMS_AUDIT_ATTENDANCE;
ALTER TABLE audit_criterion RENAME TO QMS_AUDIT_CRITERIA;
ALTER TABLE audit_observation RENAME TO QMS_AUDIT_OBSERVATION;
ALTER TABLE audit_observation_detail RENAME TO QMS_AUDIT_OBSERVATION_DETAIL;
ALTER TABLE audit_schedule RENAME TO QMS_AUDIT_SCHEDULE;
ALTER TABLE audit_schedule_criteria RENAME TO QMS_AUDIT_SCHEDULE_CRITERIA;
ALTER TABLE audit_type RENAME TO QMS_AUDIT_TYPE;

ALTER TABLE hr_induction_assignment RENAME TO IND_INDUCTION_ASSIGNMENT;
ALTER TABLE hr_induction_master RENAME TO IND_INDUCTION_MASTER;
ALTER TABLE hr_induction_training_detail RENAME TO IND_INDUCTION_TRAINING_DETAIL;

ALTER TABLE ncr_ofi_actions RENAME TO QMS_NCR_OFI_ACTION;
ALTER TABLE ncr_ofi_approval RENAME TO QMS_NCR_OFI_APPROVAL;
ALTER TABLE ncr_ofi_attachments RENAME TO QMS_NCR_OFI_ATTACHMENT;
ALTER TABLE ncr_ofi_master RENAME TO QMS_NCR_OFI_MASTER;

ALTER TABLE qms_checklist_assignment RENAME TO QMS_CHECKLIST_ASSIGNMENT;
ALTER TABLE qms_checklist_department RENAME TO QMS_CHECKLIST_DEPARTMENT;
ALTER TABLE qms_checklist_verification RENAME TO QMS_CHECKLIST_VERIFICATION;
ALTER TABLE qms_checklist_master RENAME TO QMS_CHECKLIST_MASTER;

ALTER TABLE qms_meeting_master RENAME TO QMS_MEETING_MASTER;
ALTER TABLE qms_meeting_schedule RENAME TO QMS_MEETING_SCHEDULE;
ALTER TABLE qms_meeting_schedule_department RENAME TO QMS_MEETING_SCHEDULE_DEPARTMENT;
ALTER TABLE qms_meeting_schedule_participant RENAME TO QMS_MEETING_SCHEDULE_PARTICIPANT;
ALTER TABLE qms_meeting_user_attendance RENAME TO QMS_MEETING_USER_ATTENDANCE;
ALTER TABLE qms_model_name RENAME TO QMS_MODEL_NAME;
ALTER TABLE qms_mom_attendance RENAME TO QMS_MOM_ATTENDANCE;
ALTER TABLE qms_mom_detail RENAME TO QMS_MOM_DETAIL;
ALTER TABLE qms_mom_master RENAME TO QMS_MOM_MASTER;
ALTER TABLE qms_uom RENAME TO QMS_UOM;
GO

-- STEP 3: Standardize audit column names (rename CREATED_AT/UPDATED_AT -> CREATED_DATE/UPDATED_DATE, and CREATED_BY/UPDATED_BY -> CREATED_USER/UPDATED_USER)
ALTER TABLE QMS_AUDIT_AREA RENAME COLUMN CREATED_AT TO CREATED_DATE;
ALTER TABLE QMS_AUDIT_AREA RENAME COLUMN UPDATED_AT TO UPDATED_DATE;
ALTER TABLE QMS_AUDIT_AREA RENAME COLUMN CREATED_BY TO CREATED_USER;
ALTER TABLE QMS_AUDIT_AREA RENAME COLUMN UPDATED_BY TO UPDATED_USER;

ALTER TABLE QMS_AUDIT_CRITERIA RENAME COLUMN CREATED_AT TO CREATED_DATE;
ALTER TABLE QMS_AUDIT_CRITERIA RENAME COLUMN UPDATED_AT TO UPDATED_DATE;
ALTER TABLE QMS_AUDIT_CRITERIA RENAME COLUMN CREATED_BY TO CREATED_USER;
ALTER TABLE QMS_AUDIT_CRITERIA RENAME COLUMN UPDATED_BY TO UPDATED_USER;

ALTER TABLE QMS_AUDIT_OBSERVATION RENAME COLUMN CREATED_AT TO CREATED_DATE;
ALTER TABLE QMS_AUDIT_OBSERVATION RENAME COLUMN UPDATED_AT TO UPDATED_DATE;
ALTER TABLE QMS_AUDIT_OBSERVATION RENAME COLUMN CREATED_BY TO CREATED_USER;
ALTER TABLE QMS_AUDIT_OBSERVATION RENAME COLUMN UPDATED_BY TO UPDATED_USER;

ALTER TABLE QMS_AUDIT_SCHEDULE RENAME COLUMN CREATED_AT TO CREATED_DATE;
ALTER TABLE QMS_AUDIT_SCHEDULE RENAME COLUMN UPDATED_AT TO UPDATED_DATE;
ALTER TABLE QMS_AUDIT_SCHEDULE RENAME COLUMN CREATED_BY TO CREATED_USER;
ALTER TABLE QMS_AUDIT_SCHEDULE RENAME COLUMN UPDATED_BY TO UPDATED_USER;

ALTER TABLE QMS_AUDIT_TYPE RENAME COLUMN CREATED_AT TO CREATED_DATE;
ALTER TABLE QMS_AUDIT_TYPE RENAME COLUMN UPDATED_AT TO UPDATED_DATE;
ALTER TABLE QMS_AUDIT_TYPE RENAME COLUMN CREATED_BY TO CREATED_USER;
ALTER TABLE QMS_AUDIT_TYPE RENAME COLUMN UPDATED_BY TO UPDATED_USER;

ALTER TABLE IND_INDUCTION_ASSIGNMENT RENAME COLUMN CREATED_AT TO CREATED_DATE;
ALTER TABLE IND_INDUCTION_ASSIGNMENT RENAME COLUMN UPDATED_AT TO UPDATED_DATE;
ALTER TABLE IND_INDUCTION_ASSIGNMENT RENAME COLUMN CREATED_BY TO CREATED_USER;
ALTER TABLE IND_INDUCTION_ASSIGNMENT RENAME COLUMN UPDATED_BY TO UPDATED_USER;

ALTER TABLE IND_INDUCTION_MASTER RENAME COLUMN CREATED_AT TO CREATED_DATE;
ALTER TABLE IND_INDUCTION_MASTER RENAME COLUMN UPDATED_AT TO UPDATED_DATE;
ALTER TABLE IND_INDUCTION_MASTER RENAME COLUMN CREATED_BY TO CREATED_USER;
ALTER TABLE IND_INDUCTION_MASTER RENAME COLUMN UPDATED_BY TO UPDATED_USER;

ALTER TABLE IND_INDUCTION_TRAINING_DETAIL RENAME COLUMN CREATED_AT TO CREATED_DATE;
ALTER TABLE IND_INDUCTION_TRAINING_DETAIL RENAME COLUMN UPDATED_AT TO UPDATED_DATE;
ALTER TABLE IND_INDUCTION_TRAINING_DETAIL RENAME COLUMN CREATED_BY TO CREATED_USER;
ALTER TABLE IND_INDUCTION_TRAINING_DETAIL RENAME COLUMN UPDATED_BY TO UPDATED_USER;

ALTER TABLE QMS_CHECKLIST_MASTER RENAME COLUMN CREATED_AT TO CREATED_DATE;
ALTER TABLE QMS_CHECKLIST_MASTER RENAME COLUMN UPDATED_AT TO UPDATED_DATE;
ALTER TABLE QMS_CHECKLIST_MASTER RENAME COLUMN CREATED_BY TO CREATED_USER;
ALTER TABLE QMS_CHECKLIST_MASTER RENAME COLUMN UPDATED_BY TO UPDATED_USER;

ALTER TABLE QMS_MEETING_MASTER RENAME COLUMN CREATED_AT TO CREATED_DATE;
ALTER TABLE QMS_MEETING_MASTER RENAME COLUMN UPDATED_AT TO UPDATED_DATE;
ALTER TABLE QMS_MEETING_MASTER RENAME COLUMN CREATED_BY TO CREATED_USER;
ALTER TABLE QMS_MEETING_MASTER RENAME COLUMN UPDATED_BY TO UPDATED_USER;

ALTER TABLE QMS_MEETING_SCHEDULE RENAME COLUMN CREATED_AT TO CREATED_DATE;
ALTER TABLE QMS_MEETING_SCHEDULE RENAME COLUMN UPDATED_AT TO UPDATED_DATE;
ALTER TABLE QMS_MEETING_SCHEDULE RENAME COLUMN CREATED_BY TO CREATED_USER;
ALTER TABLE QMS_MEETING_SCHEDULE RENAME COLUMN UPDATED_BY TO UPDATED_USER;

ALTER TABLE QMS_MEETING_USER_ATTENDANCE RENAME COLUMN CREATED_AT TO CREATED_DATE;
ALTER TABLE QMS_MEETING_USER_ATTENDANCE RENAME COLUMN UPDATED_AT TO UPDATED_DATE;
ALTER TABLE QMS_MEETING_USER_ATTENDANCE RENAME COLUMN CREATED_BY TO CREATED_USER;
ALTER TABLE QMS_MEETING_USER_ATTENDANCE RENAME COLUMN UPDATED_BY TO UPDATED_USER;

ALTER TABLE QMS_MODEL_NAME RENAME COLUMN CREATED_AT TO CREATED_DATE;
ALTER TABLE QMS_MODEL_NAME RENAME COLUMN UPDATED_AT TO UPDATED_DATE;
ALTER TABLE QMS_MODEL_NAME RENAME COLUMN CREATED_BY TO CREATED_USER;
ALTER TABLE QMS_MODEL_NAME RENAME COLUMN UPDATED_BY TO UPDATED_USER;

ALTER TABLE QMS_MOM_DETAIL RENAME COLUMN CREATED_AT TO CREATED_DATE;
ALTER TABLE QMS_MOM_DETAIL RENAME COLUMN UPDATED_AT TO UPDATED_DATE;
ALTER TABLE QMS_MOM_DETAIL RENAME COLUMN CREATED_BY TO CREATED_USER;
ALTER TABLE QMS_MOM_DETAIL RENAME COLUMN UPDATED_BY TO UPDATED_USER;

ALTER TABLE QMS_MOM_MASTER RENAME COLUMN CREATED_AT TO CREATED_DATE;
ALTER TABLE QMS_MOM_MASTER RENAME COLUMN UPDATED_AT TO UPDATED_DATE;
ALTER TABLE QMS_MOM_MASTER RENAME COLUMN CREATED_BY TO CREATED_USER;
ALTER TABLE QMS_MOM_MASTER RENAME COLUMN UPDATED_BY TO UPDATED_USER;

ALTER TABLE QMS_UOM RENAME COLUMN CREATED_AT TO CREATED_DATE;
ALTER TABLE QMS_UOM RENAME COLUMN UPDATED_AT TO UPDATED_DATE;
ALTER TABLE QMS_UOM RENAME COLUMN CREATED_BY TO CREATED_USER;
ALTER TABLE QMS_UOM RENAME COLUMN UPDATED_BY TO UPDATED_USER;
GO

-- STEP 4: Add missing audit columns to tables that lack them (using CREATED_USER/UPDATED_USER instead of CREATED_BY/UPDATED_BY)
ALTER TABLE QMS_AUDIT_OBSERVATION_DETAIL ADD COLUMN IF NOT EXISTS CREATED_USER VARCHAR(100);
ALTER TABLE QMS_AUDIT_OBSERVATION_DETAIL ADD COLUMN IF NOT EXISTS CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE QMS_AUDIT_OBSERVATION_DETAIL ADD COLUMN IF NOT EXISTS UPDATED_USER VARCHAR(100);
ALTER TABLE QMS_AUDIT_OBSERVATION_DETAIL ADD COLUMN IF NOT EXISTS UPDATED_DATE TIMESTAMP;

ALTER TABLE QMS_AUDIT_SCHEDULE_CRITERIA ADD COLUMN IF NOT EXISTS CREATED_USER VARCHAR(100);
ALTER TABLE QMS_AUDIT_SCHEDULE_CRITERIA ADD COLUMN IF NOT EXISTS CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE QMS_AUDIT_SCHEDULE_CRITERIA ADD COLUMN IF NOT EXISTS UPDATED_USER VARCHAR(100);
ALTER TABLE QMS_AUDIT_SCHEDULE_CRITERIA ADD COLUMN IF NOT EXISTS UPDATED_DATE TIMESTAMP;

ALTER TABLE QMS_NCR_OFI_ACTION ADD COLUMN IF NOT EXISTS CREATED_USER VARCHAR(100);
ALTER TABLE QMS_NCR_OFI_ACTION ADD COLUMN IF NOT EXISTS UPDATED_USER VARCHAR(100);
ALTER TABLE QMS_NCR_OFI_ACTION ADD COLUMN IF NOT EXISTS UPDATED_DATE TIMESTAMP;

ALTER TABLE QMS_NCR_OFI_APPROVAL ADD COLUMN IF NOT EXISTS CREATED_USER VARCHAR(100);
ALTER TABLE QMS_NCR_OFI_APPROVAL ADD COLUMN IF NOT EXISTS CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE QMS_NCR_OFI_APPROVAL ADD COLUMN IF NOT EXISTS UPDATED_USER VARCHAR(100);
ALTER TABLE QMS_NCR_OFI_APPROVAL ADD COLUMN IF NOT EXISTS UPDATED_DATE TIMESTAMP;

ALTER TABLE QMS_NCR_OFI_ATTACHMENT ADD COLUMN IF NOT EXISTS CREATED_USER VARCHAR(100);
ALTER TABLE QMS_NCR_OFI_ATTACHMENT ADD COLUMN IF NOT EXISTS CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE QMS_NCR_OFI_ATTACHMENT ADD COLUMN IF NOT EXISTS UPDATED_USER VARCHAR(100);
ALTER TABLE QMS_NCR_OFI_ATTACHMENT ADD COLUMN IF NOT EXISTS UPDATED_DATE TIMESTAMP;

ALTER TABLE QMS_CHECKLIST_ASSIGNMENT ADD COLUMN IF NOT EXISTS CREATED_USER VARCHAR(100);
ALTER TABLE QMS_CHECKLIST_ASSIGNMENT ADD COLUMN IF NOT EXISTS CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE QMS_CHECKLIST_VERIFICATION ADD COLUMN IF NOT EXISTS CREATED_USER VARCHAR(100);
ALTER TABLE QMS_CHECKLIST_VERIFICATION ADD COLUMN IF NOT EXISTS CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE QMS_CHECKLIST_VERIFICATION ADD COLUMN IF NOT EXISTS UPDATED_USER VARCHAR(100);
ALTER TABLE QMS_CHECKLIST_VERIFICATION ADD COLUMN IF NOT EXISTS UPDATED_DATE TIMESTAMP;

ALTER TABLE QMS_MOM_ATTENDANCE ADD COLUMN IF NOT EXISTS CREATED_USER VARCHAR(100);
ALTER TABLE QMS_MOM_ATTENDANCE ADD COLUMN IF NOT EXISTS CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE QMS_MOM_ATTENDANCE ADD COLUMN IF NOT EXISTS UPDATED_USER VARCHAR(100);
ALTER TABLE QMS_MOM_ATTENDANCE ADD COLUMN IF NOT EXISTS UPDATED_DATE TIMESTAMP;
GO

-- STEP 5: Backfill added audit columns where historical columns exist
UPDATE QMS_NCR_OFI_APPROVAL SET CREATED_DATE = APPROVAL_DATE WHERE CREATED_DATE IS NULL;
UPDATE QMS_NCR_OFI_ATTACHMENT SET CREATED_USER = UPLOADED_BY, CREATED_DATE = UPLOADED_DATE WHERE CREATED_DATE IS NULL;
UPDATE QMS_CHECKLIST_ASSIGNMENT SET CREATED_USER = ASSIGNED_BY, CREATED_DATE = ASSIGNED_DATE WHERE CREATED_DATE IS NULL;
UPDATE QMS_CHECKLIST_VERIFICATION SET CREATED_USER = VERIFIED_BY, CREATED_DATE = VERIFIED_DATE WHERE CREATED_DATE IS NULL;
GO

-- STEP 6: Re-create standard foreign key relationships
ALTER TABLE QMS_AUDIT_OBSERVATION_DETAIL ADD CONSTRAINT FK_QMS_AUDIT_OBSERVATION_DETAIL_QMS_AUDIT_OBSERVATION FOREIGN KEY (OBSERVATION_ID) REFERENCES QMS_AUDIT_OBSERVATION(ID) ON DELETE CASCADE;
ALTER TABLE QMS_AUDIT_SCHEDULE_CRITERIA ADD CONSTRAINT FK_QMS_AUDIT_SCHEDULE_CRITERIA_QMS_AUDIT_SCHEDULE FOREIGN KEY (AUDIT_SCHEDULE_ID) REFERENCES QMS_AUDIT_SCHEDULE(ID) ON DELETE CASCADE;

ALTER TABLE QMS_NCR_OFI_MASTER ADD CONSTRAINT FK_QMS_NCR_OFI_MASTER_QMS_AUDIT_OBSERVATION FOREIGN KEY (OBSERVATION_ID) REFERENCES QMS_AUDIT_OBSERVATION(ID);
ALTER TABLE QMS_NCR_OFI_MASTER ADD CONSTRAINT FK_QMS_NCR_OFI_MASTER_QMS_AUDIT_OBSERVATION_DETAIL FOREIGN KEY (OBSERVATION_DETAIL_ID) REFERENCES QMS_AUDIT_OBSERVATION_DETAIL(ID);

ALTER TABLE QMS_NCR_OFI_ACTION ADD CONSTRAINT FK_QMS_NCR_OFI_ACTION_QMS_NCR_OFI_MASTER FOREIGN KEY (NCR_OFI_ID) REFERENCES QMS_NCR_OFI_MASTER(ID) ON DELETE CASCADE;
ALTER TABLE QMS_NCR_OFI_APPROVAL ADD CONSTRAINT FK_QMS_NCR_OFI_APPROVAL_QMS_NCR_OFI_MASTER FOREIGN KEY (NCR_OFI_ID) REFERENCES QMS_NCR_OFI_MASTER(ID) ON DELETE CASCADE;
ALTER TABLE QMS_NCR_OFI_ATTACHMENT ADD CONSTRAINT FK_QMS_NCR_OFI_ATTACHMENT_QMS_NCR_OFI_MASTER FOREIGN KEY (NCR_OFI_ID) REFERENCES QMS_NCR_OFI_MASTER(ID) ON DELETE CASCADE;

ALTER TABLE QMS_CHECKLIST_DEPARTMENT ADD CONSTRAINT FK_QMS_CHECKLIST_DEPARTMENT_QMS_CHECKLIST_MASTER FOREIGN KEY (CHECKLIST_ID) REFERENCES QMS_CHECKLIST_MASTER(ID) ON DELETE CASCADE;
ALTER TABLE QMS_CHECKLIST_ASSIGNMENT ADD CONSTRAINT FK_QMS_CHECKLIST_ASSIGNMENT_QMS_CHECKLIST_MASTER FOREIGN KEY (CHECKLIST_ID) REFERENCES QMS_CHECKLIST_MASTER(ID) ON DELETE CASCADE;
ALTER TABLE QMS_CHECKLIST_VERIFICATION ADD CONSTRAINT FK_QMS_CHECKLIST_VERIFICATION_QMS_CHECKLIST_ASSIGNMENT FOREIGN KEY (ASSIGNMENT_ID) REFERENCES QMS_CHECKLIST_ASSIGNMENT(ID) ON DELETE CASCADE;

ALTER TABLE QMS_MEETING_SCHEDULE ADD CONSTRAINT FK_QMS_MEETING_SCHEDULE_QMS_MEETING_MASTER FOREIGN KEY (MEETING_TYPE_ID) REFERENCES QMS_MEETING_MASTER(ID);
ALTER TABLE QMS_MEETING_SCHEDULE_DEPARTMENT ADD CONSTRAINT FK_QMS_MEETING_SCHEDULE_DEPARTMENT_QMS_MEETING_SCHEDULE FOREIGN KEY (SCHEDULE_ID) REFERENCES QMS_MEETING_SCHEDULE(ID) ON DELETE CASCADE;
ALTER TABLE QMS_MEETING_SCHEDULE_PARTICIPANT ADD CONSTRAINT FK_QMS_MEETING_SCHEDULE_PARTICIPANT_QMS_MEETING_SCHEDULE FOREIGN KEY (SCHEDULE_ID) REFERENCES QMS_MEETING_SCHEDULE(ID) ON DELETE CASCADE;
ALTER TABLE QMS_MEETING_USER_ATTENDANCE ADD CONSTRAINT FK_QMS_MEETING_USER_ATTENDANCE_QMS_MEETING_SCHEDULE FOREIGN KEY (SCHEDULE_ID) REFERENCES QMS_MEETING_SCHEDULE(ID) ON DELETE CASCADE;

ALTER TABLE QMS_MOM_MASTER ADD CONSTRAINT FK_QMS_MOM_MASTER_QMS_MEETING_SCHEDULE FOREIGN KEY (SCHEDULE_ID) REFERENCES QMS_MEETING_SCHEDULE(ID);
ALTER TABLE QMS_MOM_DETAIL ADD CONSTRAINT FK_QMS_MOM_DETAIL_QMS_MOM_MASTER FOREIGN KEY (MOM_ID) REFERENCES QMS_MOM_MASTER(ID) ON DELETE CASCADE;
ALTER TABLE QMS_MOM_ATTENDANCE ADD CONSTRAINT FK_QMS_MOM_ATTENDANCE_QMS_MOM_MASTER FOREIGN KEY (MOM_ID) REFERENCES QMS_MOM_MASTER(ID) ON DELETE CASCADE;

ALTER TABLE IND_INDUCTION_TRAINING_DETAIL ADD CONSTRAINT FK_IND_INDUCTION_TRAINING_DETAIL_IND_INDUCTION_ASSIGNMENT FOREIGN KEY (ASSIGNMENT_ID) REFERENCES IND_INDUCTION_ASSIGNMENT(ID) ON DELETE CASCADE;
ALTER TABLE IND_INDUCTION_TRAINING_DETAIL ADD CONSTRAINT FK_IND_INDUCTION_TRAINING_DETAIL_IND_INDUCTION_MASTER FOREIGN KEY (INDUCTION_MASTER_ID) REFERENCES IND_INDUCTION_MASTER(ID) ON DELETE CASCADE;
GO
