-- Add tested_by field to TICKET_TRACEABILITY_CENTER table
IF OBJECT_ID(N'[dbo].[TICKET_TRACEABILITY_CENTER]', 'U') IS NOT NULL
BEGIN
    IF NOT EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID(N'[dbo].[TICKET_TRACEABILITY_CENTER]') AND name = 'tested_by')
    BEGIN
        ALTER TABLE TICKET_TRACEABILITY_CENTER ADD tested_by VARCHAR(255);
    END
END
