-- 🚀 Migration Script: Increase Induction Master column lengths to prevent truncation issues
-- Author: TIS Team
-- Date: 2026-06-04

IF COL_LENGTH('HR_INDUCTION', 'DEPARTMENT_CODES') IS NOT NULL
BEGIN
    ALTER TABLE HR_INDUCTION ALTER COLUMN DEPARTMENT_CODES NVARCHAR(500) NULL;
END
GO

IF COL_LENGTH('HR_INDUCTION', 'LEVEL_CODES') IS NOT NULL
BEGIN
    ALTER TABLE HR_INDUCTION ALTER COLUMN LEVEL_CODES NVARCHAR(500) NULL;
END
GO
