-- ============================================================
-- Migration: Create HR_INDUCTION_REASSIGNMENT_LOG table
-- Purpose: Log induction reassignment audit trail
-- Constraint: Enforce at most one active assignment per trainee + round
-- Date: 2026-06-04
-- ============================================================

IF OBJECT_ID('HR_INDUCTION_REASSIGNMENT_LOG', 'U') IS NULL
BEGIN
    CREATE TABLE HR_INDUCTION_REASSIGNMENT_LOG (
        ID BIGINT IDENTITY(1,1) PRIMARY KEY,
        TRAINEE_NAME NVARCHAR(200) NULL,
        TRAINEE_EMP_CODE NVARCHAR(50) NULL,
        INDUCTION_ROUND NVARCHAR(50) NULL,
        PREVIOUS_ASSESSOR NVARCHAR(200) NULL,
        PREVIOUS_ASSESSOR_EMP_CODE NVARCHAR(50) NULL,
        NEW_ASSESSOR NVARCHAR(200) NULL,
        NEW_ASSESSOR_EMP_CODE NVARCHAR(50) NULL,
        REASSIGNMENT_REASON NVARCHAR(MAX) NULL,
        REASSIGNED_BY NVARCHAR(100) NULL,
        REASSIGNED_DATE_TIME DATETIME NULL
    );
END
GO

IF OBJECT_ID('HR_INDUCTION_ASSIGNMENT', 'U') IS NOT NULL
BEGIN
    IF NOT EXISTS (SELECT * FROM sys.indexes WHERE name = 'UX_HR_INDUCTION_ASSIGNMENT_ACTIVE' AND object_id = OBJECT_ID('HR_INDUCTION_ASSIGNMENT'))
    BEGIN
        CREATE UNIQUE INDEX UX_HR_INDUCTION_ASSIGNMENT_ACTIVE 
        ON HR_INDUCTION_ASSIGNMENT (EMP_CODE, INDUCTION_ROUND) 
        WHERE INDUCTION_STATUS = 'ACTIVE';
    END
END
GO
