-- V77.0: Add IS_ACTIVE column to QMS_MEETING_USER_ATTENDANCE table
IF OBJECT_ID('QMS_MEETING_USER_ATTENDANCE', 'U') IS NOT NULL
BEGIN
    IF COL_LENGTH('QMS_MEETING_USER_ATTENDANCE', 'IS_ACTIVE') IS NULL
    BEGIN
        ALTER TABLE QMS_MEETING_USER_ATTENDANCE ADD IS_ACTIVE BIT DEFAULT 1;
        PRINT 'Added IS_ACTIVE column to QMS_MEETING_USER_ATTENDANCE table';
    END
END
GO
