-- Seed requested departments if they don't exist
DECLARE @depts TABLE (name NVARCHAR(100));
INSERT INTO @depts (name) VALUES 
('ACCOUNTS'), ('ADMIN'), ('ASSEMBLY'), ('BUSINESS DEVELOPMENT'), ('DESIGN & DEVELOPMENT'),
('HRA'), ('LOGISTICS'), ('MAINTENANCE'), ('MANAGEMENT'), ('MANAGEMENT REPRESENTATIVE'),
('OPERATIONS'), ('PLANNING'), ('PRODUCT DEVELOPMENT'), ('PRODUCTION'), ('PURCHASE'),
('QMS'), ('QUALITY'), ('SALES & MARKETING'), ('STORES'), ('STRATEGIC PROCUREMENT'),
('TOP MANAGEMENT');

DECLARE @name NVARCHAR(100);
DECLARE @seq INT;
DECLARE @dept_no NVARCHAR(20);

DECLARE cur CURSOR FOR SELECT name FROM @depts;
OPEN cur;
FETCH NEXT FROM cur INTO @name;
WHILE @@FETCH_STATUS = 0
BEGIN
    -- Check if department name exists (case-insensitive)
    IF NOT EXISTS (SELECT 1 FROM HR_DEPARTMENT WHERE UPPER(DEPARTMENT_NAME) = UPPER(@name))
    BEGIN
        -- Generate next sequence
        SELECT @seq = COALESCE(MAX(CAST(SUBSTRING(DEPARTMENT_NO, 6, 3) AS INT)), 0) + 1 FROM HR_DEPARTMENT;
        SET @dept_no = 'DEPT-' + RIGHT('000' + CAST(@seq AS NVARCHAR(10)), 3);
        
        INSERT INTO HR_DEPARTMENT (DEPARTMENT_NO, DEPARTMENT_NAME, NDA_CERTIFICATE, SEQUENCE_NO, STATUS, CREATED_BY, CREATED_DATE, IS_ACTIVE)
        VALUES (@dept_no, @name, 'No', @seq, 'Active', 'SYSTEM', GETDATE(), 1);
    END
    FETCH NEXT FROM cur INTO @name;
END;
CLOSE cur;
DEALLOCATE cur;
GO
