-- Add Task Tester fields to Employee Master table
IF OBJECT_ID(N'[dbo].[HR_EMPLOYEE]', 'U') IS NOT NULL
BEGIN
    IF NOT EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID(N'[dbo].[HR_EMPLOYEE]') AND name = 'IS_TASK_TESTER')
    BEGIN
        ALTER TABLE HR_EMPLOYEE ADD IS_TASK_TESTER VARCHAR(10) DEFAULT 'NO';
        ALTER TABLE HR_EMPLOYEE ADD TASK_TESTER_TYPE VARCHAR(255);
        ALTER TABLE HR_EMPLOYEE ADD TASK_TESTER_FILE_INFO NVARCHAR(MAX);
    END
END
ELSE IF OBJECT_ID(N'[dbo].[HR_EMPLOYEE_MASTER]', 'U') IS NOT NULL
BEGIN
    IF NOT EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID(N'[dbo].[HR_EMPLOYEE_MASTER]') AND name = 'IS_TASK_TESTER')
    BEGIN
        ALTER TABLE HR_EMPLOYEE_MASTER ADD IS_TASK_TESTER VARCHAR(10) DEFAULT 'NO';
        ALTER TABLE HR_EMPLOYEE_MASTER ADD TASK_TESTER_TYPE VARCHAR(255);
        ALTER TABLE HR_EMPLOYEE_MASTER ADD TASK_TESTER_FILE_INFO NVARCHAR(MAX);
    END
END
