-- Add L6 and L7 levels to HR_DESIGNATION_LEVEL if they do not exist
IF NOT EXISTS (SELECT 1 FROM HR_DESIGNATION_LEVEL WHERE LEVEL = 'L6')
BEGIN
    INSERT INTO HR_DESIGNATION_LEVEL (LEVEL, BASIC, DA, HRA, SCREENING_LEVEL, CREATED_BY, CREATED_DATE, IS_ACTIVE)
    VALUES ('L6', 120000.0, 24000.0, 36000.0, 6, 'SYSTEM', GETDATE(), 1);
END

IF NOT EXISTS (SELECT 1 FROM HR_DESIGNATION_LEVEL WHERE LEVEL = 'L7')
BEGIN
    INSERT INTO HR_DESIGNATION_LEVEL (LEVEL, BASIC, DA, HRA, SCREENING_LEVEL, CREATED_BY, CREATED_DATE, IS_ACTIVE)
    VALUES ('L7', 150000.0, 30000.0, 45000.0, 7, 'SYSTEM', GETDATE(), 1);
END
GO
