-- V70.0 Add Input Case Style to Company Credential

IF NOT EXISTS (
    SELECT 1 FROM sys.columns 
    WHERE object_id = OBJECT_ID('AD_COMPANY_CREDENTIAL') 
      AND name = 'INPUT_CASE_STYLE'
)
BEGIN
    ALTER TABLE AD_COMPANY_CREDENTIAL ADD INPUT_CASE_STYLE NVARCHAR(50) DEFAULT 'UPPER_CASE';
END
GO

-- Update existing records to have 'UPPER_CASE' if null
UPDATE AD_COMPANY_CREDENTIAL SET INPUT_CASE_STYLE = 'UPPER_CASE' WHERE INPUT_CASE_STYLE IS NULL;
GO
