-- Add ATTACHMENT_REQ to QMS_AUDIT_SCHEDULE_CRITERIA if missing
IF OBJECT_ID('QMS_AUDIT_SCHEDULE_CRITERIA', 'U') IS NOT NULL
BEGIN
    IF NOT EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID('QMS_AUDIT_SCHEDULE_CRITERIA') AND name = 'ATTACHMENT_REQ')
    BEGIN
        ALTER TABLE QMS_AUDIT_SCHEDULE_CRITERIA ADD ATTACHMENT_REQ NVARCHAR(50);
    END
END
GO
