-- Add new fields to Segment and Sub Segment masters
IF NOT EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID('SM_SEGMENT') AND name = 'SEGMENT_DESCRIPTION')
BEGIN
    ALTER TABLE SM_SEGMENT ADD SEGMENT_DESCRIPTION NVARCHAR(500);
END

IF NOT EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID('SM_SUB_SEGMENT') AND name = 'SEGMENT_NAME')
BEGIN
    ALTER TABLE SM_SUB_SEGMENT ADD SEGMENT_NAME NVARCHAR(100);
END

IF NOT EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID('SM_SUB_SEGMENT') AND name = 'SUB_SEGMENT_DESCRIPTION')
BEGIN
    ALTER TABLE SM_SUB_SEGMENT ADD SUB_SEGMENT_DESCRIPTION NVARCHAR(500);
END
