-- ============================================================
-- V38.0 Database Governance & Standardization
-- QMS, Checklist, Audit, Induction
-- Fully idempotent - safe to re-run on SQL Server (Docker)
-- ============================================================
USE [AUTONOMA];
GO

-- ===========================================================
-- STEP 1: Drop old FK constraints (only if the old-name tables still exist)
-- ===========================================================
IF OBJECT_ID('audit_observation_detail', 'U') IS NOT NULL
    ALTER TABLE audit_observation_detail DROP CONSTRAINT IF EXISTS FKFTT16QRXC64EU59W55DUTSN41;
IF OBJECT_ID('QMS_AUDIT_OBSERVATION_DETAIL', 'U') IS NOT NULL
    ALTER TABLE QMS_AUDIT_OBSERVATION_DETAIL DROP CONSTRAINT IF EXISTS FKFTT16QRXC64EU59W55DUTSN41;

IF OBJECT_ID('qms_mom_attendance', 'U') IS NOT NULL
BEGIN
    ALTER TABLE qms_mom_attendance DROP CONSTRAINT IF EXISTS FK13BV8YXDW1OGOHN8IKYJ23GB9;
    ALTER TABLE qms_mom_attendance DROP CONSTRAINT IF EXISTS FK5KQK3NRA1BOVVL8WHMXN5SD7Y;
END
IF OBJECT_ID('QMS_MOM_ATTENDANCE', 'U') IS NOT NULL
BEGIN
    ALTER TABLE QMS_MOM_ATTENDANCE DROP CONSTRAINT IF EXISTS FK13BV8YXDW1OGOHN8IKYJ23GB9;
    ALTER TABLE QMS_MOM_ATTENDANCE DROP CONSTRAINT IF EXISTS FK5KQK3NRA1BOVVL8WHMXN5SD7Y;
END

IF OBJECT_ID('hr_induction_assignment', 'U') IS NOT NULL
    ALTER TABLE hr_induction_assignment DROP CONSTRAINT IF EXISTS FK_INDUCTIONASSIGNMENT_EMPLOYEE;
IF OBJECT_ID('IND_INDUCTION_ASSIGNMENT', 'U') IS NOT NULL
    ALTER TABLE IND_INDUCTION_ASSIGNMENT DROP CONSTRAINT IF EXISTS FK_INDUCTIONASSIGNMENT_EMPLOYEE;

IF OBJECT_ID('qms_meeting_schedule_department', 'U') IS NOT NULL
BEGIN
    ALTER TABLE qms_meeting_schedule_department DROP CONSTRAINT IF EXISTS FK2VAYWYIIR0GMDAFIC6TRPUN0X;
    ALTER TABLE qms_meeting_schedule_department DROP CONSTRAINT IF EXISTS FKKBPB4TOPRDOS94M4I4G5QNYEU;
END
IF OBJECT_ID('QMS_MEETING_SCHEDULE_DEPARTMENT', 'U') IS NOT NULL
BEGIN
    ALTER TABLE QMS_MEETING_SCHEDULE_DEPARTMENT DROP CONSTRAINT IF EXISTS FK2VAYWYIIR0GMDAFIC6TRPUN0X;
    ALTER TABLE QMS_MEETING_SCHEDULE_DEPARTMENT DROP CONSTRAINT IF EXISTS FKKBPB4TOPRDOS94M4I4G5QNYEU;
END

IF OBJECT_ID('qms_checklist_department', 'U') IS NOT NULL
    ALTER TABLE qms_checklist_department DROP CONSTRAINT IF EXISTS FKE3KW3CQLNUYVCGDVUHX040A7K;
IF OBJECT_ID('QMS_CHECKLIST_DEPARTMENT', 'U') IS NOT NULL
    ALTER TABLE QMS_CHECKLIST_DEPARTMENT DROP CONSTRAINT IF EXISTS FKE3KW3CQLNUYVCGDVUHX040A7K;

IF OBJECT_ID('qms_meeting_schedule', 'U') IS NOT NULL
BEGIN
    ALTER TABLE qms_meeting_schedule DROP CONSTRAINT IF EXISTS FK20YVN65GXS7E9BR14MMG6VU9T;
    ALTER TABLE qms_meeting_schedule DROP CONSTRAINT IF EXISTS FKJA75MCA8G4GNJPMBAO3OW0VG0;
    ALTER TABLE qms_meeting_schedule DROP CONSTRAINT IF EXISTS FKICSNVQUEPAW9Y5JMPY91R7EU3;
END
IF OBJECT_ID('QMS_MEETING_SCHEDULE', 'U') IS NOT NULL
BEGIN
    ALTER TABLE QMS_MEETING_SCHEDULE DROP CONSTRAINT IF EXISTS FK20YVN65GXS7E9BR14MMG6VU9T;
    ALTER TABLE QMS_MEETING_SCHEDULE DROP CONSTRAINT IF EXISTS FKJA75MCA8G4GNJPMBAO3OW0VG0;
    ALTER TABLE QMS_MEETING_SCHEDULE DROP CONSTRAINT IF EXISTS FKICSNVQUEPAW9Y5JMPY91R7EU3;
END

IF OBJECT_ID('qms_mom_master', 'U') IS NOT NULL
BEGIN
    ALTER TABLE qms_mom_master DROP CONSTRAINT IF EXISTS FKDA23FL6D8DC466B0NCLVC2SNB;
    ALTER TABLE qms_mom_master DROP CONSTRAINT IF EXISTS FK8YL0T3BEDHQ0QHMTUJ51KA3JK;
END
IF OBJECT_ID('QMS_MOM_MASTER', 'U') IS NOT NULL
BEGIN
    ALTER TABLE QMS_MOM_MASTER DROP CONSTRAINT IF EXISTS FKDA23FL6D8DC466B0NCLVC2SNB;
    ALTER TABLE QMS_MOM_MASTER DROP CONSTRAINT IF EXISTS FK8YL0T3BEDHQ0QHMTUJ51KA3JK;
END

IF OBJECT_ID('qms_checklist_verification', 'U') IS NOT NULL
BEGIN
    ALTER TABLE qms_checklist_verification DROP CONSTRAINT IF EXISTS FKY53DS6TAGOMHU7QN02559U57;
    ALTER TABLE qms_checklist_verification DROP CONSTRAINT IF EXISTS FK5544QKVVINDXLK4GE2HPHDXHN;
    ALTER TABLE qms_checklist_verification DROP CONSTRAINT IF EXISTS FKOLPVVT64VDKSI67265J6FXASK;
END
IF OBJECT_ID('QMS_CHECKLIST_VERIFICATION', 'U') IS NOT NULL
BEGIN
    ALTER TABLE QMS_CHECKLIST_VERIFICATION DROP CONSTRAINT IF EXISTS FKY53DS6TAGOMHU7QN02559U57;
    ALTER TABLE QMS_CHECKLIST_VERIFICATION DROP CONSTRAINT IF EXISTS FK5544QKVVINDXLK4GE2HPHDXHN;
    ALTER TABLE QMS_CHECKLIST_VERIFICATION DROP CONSTRAINT IF EXISTS FKOLPVVT64VDKSI67265J6FXASK;
END

IF OBJECT_ID('qms_meeting_schedule_participant', 'U') IS NOT NULL
BEGIN
    ALTER TABLE qms_meeting_schedule_participant DROP CONSTRAINT IF EXISTS FKJ3FJVJ3MK7K4W584DYTOCGHTJ;
    ALTER TABLE qms_meeting_schedule_participant DROP CONSTRAINT IF EXISTS FKB7EWGWKJQN1RKVEE9031U4NXR;
END
IF OBJECT_ID('QMS_MEETING_SCHEDULE_PARTICIPANT', 'U') IS NOT NULL
BEGIN
    ALTER TABLE QMS_MEETING_SCHEDULE_PARTICIPANT DROP CONSTRAINT IF EXISTS FKJ3FJVJ3MK7K4W584DYTOCGHTJ;
    ALTER TABLE QMS_MEETING_SCHEDULE_PARTICIPANT DROP CONSTRAINT IF EXISTS FKB7EWGWKJQN1RKVEE9031U4NXR;
END

IF OBJECT_ID('qms_mom_detail', 'U') IS NOT NULL
BEGIN
    ALTER TABLE qms_mom_detail DROP CONSTRAINT IF EXISTS FKL88GY41BUUYYMSS0855FVPLL5;
    ALTER TABLE qms_mom_detail DROP CONSTRAINT IF EXISTS FK8OBKBTI4UUKU12J2E84X41D84;
    ALTER TABLE qms_mom_detail DROP CONSTRAINT IF EXISTS FK9NAN3XVB12YFYQ79LXMB79X0;
END
IF OBJECT_ID('QMS_MOM_DETAIL', 'U') IS NOT NULL
BEGIN
    ALTER TABLE QMS_MOM_DETAIL DROP CONSTRAINT IF EXISTS FKL88GY41BUUYYMSS0855FVPLL5;
    ALTER TABLE QMS_MOM_DETAIL DROP CONSTRAINT IF EXISTS FK8OBKBTI4UUKU12J2E84X41D84;
    ALTER TABLE QMS_MOM_DETAIL DROP CONSTRAINT IF EXISTS FK9NAN3XVB12YFYQ79LXMB79X0;
END

IF OBJECT_ID('audit_schedule_criteria', 'U') IS NOT NULL
BEGIN
    ALTER TABLE audit_schedule_criteria DROP CONSTRAINT IF EXISTS FK8M0NHBKGNMS52LH6MXKELT1VY;
    ALTER TABLE audit_schedule_criteria DROP CONSTRAINT IF EXISTS FK8EM2PMD3KEYAMTHQ8GOSBI342;
END
IF OBJECT_ID('QMS_AUDIT_SCHEDULE_CRITERIA', 'U') IS NOT NULL
BEGIN
    ALTER TABLE QMS_AUDIT_SCHEDULE_CRITERIA DROP CONSTRAINT IF EXISTS FK8M0NHBKGNMS52LH6MXKELT1VY;
    ALTER TABLE QMS_AUDIT_SCHEDULE_CRITERIA DROP CONSTRAINT IF EXISTS FK8EM2PMD3KEYAMTHQ8GOSBI342;
    ALTER TABLE QMS_AUDIT_SCHEDULE_CRITERIA DROP CONSTRAINT IF EXISTS FK_AuditSchedule_Criteria;
END

IF OBJECT_ID('qms_meeting_user_attendance', 'U') IS NOT NULL
BEGIN
    ALTER TABLE qms_meeting_user_attendance DROP CONSTRAINT IF EXISTS FKPGAMC2SOFAHMDSKQAQISAELN;
    ALTER TABLE qms_meeting_user_attendance DROP CONSTRAINT IF EXISTS FKEJS4CH2JWA6KFV8PHSAUISM9K;
    ALTER TABLE qms_meeting_user_attendance DROP CONSTRAINT IF EXISTS fk_mua_schedule;
    ALTER TABLE qms_meeting_user_attendance DROP CONSTRAINT IF EXISTS fk_mua_employee;
END
IF OBJECT_ID('QMS_MEETING_USER_ATTENDANCE', 'U') IS NOT NULL
BEGIN
    ALTER TABLE QMS_MEETING_USER_ATTENDANCE DROP CONSTRAINT IF EXISTS FKPGAMC2SOFAHMDSKQAQISAELN;
    ALTER TABLE QMS_MEETING_USER_ATTENDANCE DROP CONSTRAINT IF EXISTS FKEJS4CH2JWA6KFV8PHSAUISM9K;
END

IF OBJECT_ID('qms_checklist_assignment', 'U') IS NOT NULL
BEGIN
    ALTER TABLE qms_checklist_assignment DROP CONSTRAINT IF EXISTS FKLN0U5W8VBXI3OJX7TU3354FQY;
    ALTER TABLE qms_checklist_assignment DROP CONSTRAINT IF EXISTS FKJGBCWJ07TVUKUSLIQ7AUKPYE;
    ALTER TABLE qms_checklist_assignment DROP CONSTRAINT IF EXISTS FK9GLT0I2UPGH0V6C3W3SHK90EF;
    ALTER TABLE qms_checklist_assignment DROP CONSTRAINT IF EXISTS FKMLSQF7HV7R6CXBKF656YSKLDG;
    ALTER TABLE qms_checklist_assignment DROP CONSTRAINT IF EXISTS FK_Assignment_Checklist_Master;
    ALTER TABLE qms_checklist_assignment DROP CONSTRAINT IF EXISTS FK_Assignment_Status;
END
IF OBJECT_ID('QMS_CHECKLIST_ASSIGNMENT', 'U') IS NOT NULL
BEGIN
    ALTER TABLE QMS_CHECKLIST_ASSIGNMENT DROP CONSTRAINT IF EXISTS FKLN0U5W8VBXI3OJX7TU3354FQY;
    ALTER TABLE QMS_CHECKLIST_ASSIGNMENT DROP CONSTRAINT IF EXISTS FKJGBCWJ07TVUKUSLIQ7AUKPYE;
    ALTER TABLE QMS_CHECKLIST_ASSIGNMENT DROP CONSTRAINT IF EXISTS FK9GLT0I2UPGH0V6C3W3SHK90EF;
    ALTER TABLE QMS_CHECKLIST_ASSIGNMENT DROP CONSTRAINT IF EXISTS FKMLSQF7HV7R6CXBKF656YSKLDG;
END

-- Also drop old FK on audit_observation_detail (real name used by Hibernate)
IF OBJECT_ID('QMS_AUDIT_OBSERVATION_DETAIL', 'U') IS NOT NULL
BEGIN
    ALTER TABLE QMS_AUDIT_OBSERVATION_DETAIL DROP CONSTRAINT IF EXISTS FK_audit_observation_detail_audit_observation;
END
GO

-- ===========================================================
-- STEP 2: Rename tables to UPPERCASE standard with module prefix (safe, idempotent)
-- ===========================================================
IF OBJECT_ID('audit_area', 'U') IS NOT NULL AND OBJECT_ID('QMS_AUDIT_AREA', 'U') IS NULL
    EXEC sp_rename 'audit_area', 'QMS_AUDIT_AREA';
IF OBJECT_ID('audit_attendance', 'U') IS NOT NULL AND OBJECT_ID('QMS_AUDIT_ATTENDANCE', 'U') IS NULL
    EXEC sp_rename 'audit_attendance', 'QMS_AUDIT_ATTENDANCE';
IF OBJECT_ID('audit_criterion', 'U') IS NOT NULL AND OBJECT_ID('QMS_AUDIT_CRITERIA', 'U') IS NULL
    EXEC sp_rename 'audit_criterion', 'QMS_AUDIT_CRITERIA';
IF OBJECT_ID('audit_observation', 'U') IS NOT NULL AND OBJECT_ID('QMS_AUDIT_OBSERVATION', 'U') IS NULL
    EXEC sp_rename 'audit_observation', 'QMS_AUDIT_OBSERVATION';
IF OBJECT_ID('audit_observation_detail', 'U') IS NOT NULL AND OBJECT_ID('QMS_AUDIT_OBSERVATION_DETAIL', 'U') IS NULL
    EXEC sp_rename 'audit_observation_detail', 'QMS_AUDIT_OBSERVATION_DETAIL';
IF OBJECT_ID('audit_schedule', 'U') IS NOT NULL AND OBJECT_ID('QMS_AUDIT_SCHEDULE', 'U') IS NULL
    EXEC sp_rename 'audit_schedule', 'QMS_AUDIT_SCHEDULE';
IF OBJECT_ID('audit_schedule_criteria', 'U') IS NOT NULL AND OBJECT_ID('QMS_AUDIT_SCHEDULE_CRITERIA', 'U') IS NULL
    EXEC sp_rename 'audit_schedule_criteria', 'QMS_AUDIT_SCHEDULE_CRITERIA';
IF OBJECT_ID('audit_type', 'U') IS NOT NULL AND OBJECT_ID('QMS_AUDIT_TYPE', 'U') IS NULL
    EXEC sp_rename 'audit_type', 'QMS_AUDIT_TYPE';

IF OBJECT_ID('hr_induction_assignment', 'U') IS NOT NULL AND OBJECT_ID('IND_INDUCTION_ASSIGNMENT', 'U') IS NULL
    EXEC sp_rename 'hr_induction_assignment', 'IND_INDUCTION_ASSIGNMENT';
IF OBJECT_ID('hr_induction_master', 'U') IS NOT NULL AND OBJECT_ID('IND_INDUCTION_MASTER', 'U') IS NULL
    EXEC sp_rename 'hr_induction_master', 'IND_INDUCTION_MASTER';
IF OBJECT_ID('hr_induction_training_detail', 'U') IS NOT NULL AND OBJECT_ID('IND_INDUCTION_TRAINING_DETAIL', 'U') IS NULL
    EXEC sp_rename 'hr_induction_training_detail', 'IND_INDUCTION_TRAINING_DETAIL';

IF OBJECT_ID('ncr_ofi_actions', 'U') IS NOT NULL AND OBJECT_ID('QMS_NCR_OFI_ACTION', 'U') IS NULL
    EXEC sp_rename 'ncr_ofi_actions', 'QMS_NCR_OFI_ACTION';
IF OBJECT_ID('ncr_ofi_approval', 'U') IS NOT NULL AND OBJECT_ID('QMS_NCR_OFI_APPROVAL', 'U') IS NULL
    EXEC sp_rename 'ncr_ofi_approval', 'QMS_NCR_OFI_APPROVAL';
IF OBJECT_ID('ncr_ofi_attachments', 'U') IS NOT NULL AND OBJECT_ID('QMS_NCR_OFI_ATTACHMENT', 'U') IS NULL
    EXEC sp_rename 'ncr_ofi_attachments', 'QMS_NCR_OFI_ATTACHMENT';
IF OBJECT_ID('ncr_ofi_master', 'U') IS NOT NULL AND OBJECT_ID('QMS_NCR_OFI_MASTER', 'U') IS NULL
    EXEC sp_rename 'ncr_ofi_master', 'QMS_NCR_OFI_MASTER';

IF OBJECT_ID('qms_checklist_assignment', 'U') IS NOT NULL AND OBJECT_ID('QMS_CHECKLIST_ASSIGNMENT', 'U') IS NULL
    EXEC sp_rename 'qms_checklist_assignment', 'QMS_CHECKLIST_ASSIGNMENT';
IF OBJECT_ID('qms_checklist_department', 'U') IS NOT NULL AND OBJECT_ID('QMS_CHECKLIST_DEPARTMENT', 'U') IS NULL
    EXEC sp_rename 'qms_checklist_department', 'QMS_CHECKLIST_DEPARTMENT';
IF OBJECT_ID('qms_checklist_verification', 'U') IS NOT NULL AND OBJECT_ID('QMS_CHECKLIST_VERIFICATION', 'U') IS NULL
    EXEC sp_rename 'qms_checklist_verification', 'QMS_CHECKLIST_VERIFICATION';
IF OBJECT_ID('qms_checklist_master', 'U') IS NOT NULL AND OBJECT_ID('QMS_CHECKLIST_MASTER', 'U') IS NULL
    EXEC sp_rename 'qms_checklist_master', 'QMS_CHECKLIST_MASTER';

IF OBJECT_ID('qms_meeting_master', 'U') IS NOT NULL AND OBJECT_ID('QMS_MEETING_MASTER', 'U') IS NULL
    EXEC sp_rename 'qms_meeting_master', 'QMS_MEETING_MASTER';
IF OBJECT_ID('qms_meeting_schedule', 'U') IS NOT NULL AND OBJECT_ID('QMS_MEETING_SCHEDULE', 'U') IS NULL
    EXEC sp_rename 'qms_meeting_schedule', 'QMS_MEETING_SCHEDULE';
IF OBJECT_ID('qms_meeting_schedule_department', 'U') IS NOT NULL AND OBJECT_ID('QMS_MEETING_SCHEDULE_DEPARTMENT', 'U') IS NULL
    EXEC sp_rename 'qms_meeting_schedule_department', 'QMS_MEETING_SCHEDULE_DEPARTMENT';
IF OBJECT_ID('qms_meeting_schedule_participant', 'U') IS NOT NULL AND OBJECT_ID('QMS_MEETING_SCHEDULE_PARTICIPANT', 'U') IS NULL
    EXEC sp_rename 'qms_meeting_schedule_participant', 'QMS_MEETING_SCHEDULE_PARTICIPANT';
IF OBJECT_ID('qms_meeting_user_attendance', 'U') IS NOT NULL AND OBJECT_ID('QMS_MEETING_USER_ATTENDANCE', 'U') IS NULL
    EXEC sp_rename 'qms_meeting_user_attendance', 'QMS_MEETING_USER_ATTENDANCE';
IF OBJECT_ID('qms_model_name', 'U') IS NOT NULL AND OBJECT_ID('QMS_MODEL_NAME', 'U') IS NULL
    EXEC sp_rename 'qms_model_name', 'QMS_MODEL_NAME';
IF OBJECT_ID('qms_mom_attendance', 'U') IS NOT NULL AND OBJECT_ID('QMS_MOM_ATTENDANCE', 'U') IS NULL
    EXEC sp_rename 'qms_mom_attendance', 'QMS_MOM_ATTENDANCE';
IF OBJECT_ID('qms_mom_detail', 'U') IS NOT NULL AND OBJECT_ID('QMS_MOM_DETAIL', 'U') IS NULL
    EXEC sp_rename 'qms_mom_detail', 'QMS_MOM_DETAIL';
IF OBJECT_ID('qms_mom_master', 'U') IS NOT NULL AND OBJECT_ID('QMS_MOM_MASTER', 'U') IS NULL
    EXEC sp_rename 'qms_mom_master', 'QMS_MOM_MASTER';
IF OBJECT_ID('qms_uom', 'U') IS NOT NULL AND OBJECT_ID('QMS_UOM', 'U') IS NULL
    EXEC sp_rename 'qms_uom', 'QMS_UOM';
GO

-- ===========================================================
-- Create helper: Safe column rename (idempotent)
-- ===========================================================
IF OBJECT_ID('dbo.sp_RenameColSafe', 'P') IS NOT NULL
    DROP PROCEDURE dbo.sp_RenameColSafe;
GO
CREATE PROCEDURE dbo.sp_RenameColSafe
    @tbl NVARCHAR(200),
    @old NVARCHAR(100),
    @new NVARCHAR(100)
AS
BEGIN
    IF EXISTS (SELECT 1 FROM sys.columns WHERE object_id = OBJECT_ID(@tbl) AND name = @old)
       AND NOT EXISTS (SELECT 1 FROM sys.columns WHERE object_id = OBJECT_ID(@tbl) AND name = @new)
    BEGIN
        DECLARE @full NVARCHAR(300) = @tbl + '.' + @old;
        EXEC sp_rename @full, @new, 'COLUMN';
    END
END
GO

-- ===========================================================
-- STEP 3: Standardize audit column names on all team tables
-- CREATED_AT/UPDATED_AT -> CREATED_DATE/UPDATED_DATE
-- CREATED_BY/UPDATED_BY -> CREATED_USER/UPDATED_USER
-- ===========================================================
EXEC dbo.sp_RenameColSafe 'QMS_AUDIT_AREA', 'CREATED_AT', 'CREATED_DATE';
EXEC dbo.sp_RenameColSafe 'QMS_AUDIT_AREA', 'UPDATED_AT', 'UPDATED_DATE';
EXEC dbo.sp_RenameColSafe 'QMS_AUDIT_AREA', 'CREATED_BY', 'CREATED_USER';
EXEC dbo.sp_RenameColSafe 'QMS_AUDIT_AREA', 'UPDATED_BY', 'UPDATED_USER';
EXEC dbo.sp_RenameColSafe 'QMS_AUDIT_AREA', 'created_at', 'CREATED_DATE';
EXEC dbo.sp_RenameColSafe 'QMS_AUDIT_AREA', 'updated_at', 'UPDATED_DATE';
EXEC dbo.sp_RenameColSafe 'QMS_AUDIT_AREA', 'created_by', 'CREATED_USER';
EXEC dbo.sp_RenameColSafe 'QMS_AUDIT_AREA', 'updated_by', 'UPDATED_USER';

EXEC dbo.sp_RenameColSafe 'QMS_AUDIT_CRITERIA', 'CREATED_AT', 'CREATED_DATE';
EXEC dbo.sp_RenameColSafe 'QMS_AUDIT_CRITERIA', 'UPDATED_AT', 'UPDATED_DATE';
EXEC dbo.sp_RenameColSafe 'QMS_AUDIT_CRITERIA', 'CREATED_BY', 'CREATED_USER';
EXEC dbo.sp_RenameColSafe 'QMS_AUDIT_CRITERIA', 'UPDATED_BY', 'UPDATED_USER';
EXEC dbo.sp_RenameColSafe 'QMS_AUDIT_CRITERIA', 'created_at', 'CREATED_DATE';
EXEC dbo.sp_RenameColSafe 'QMS_AUDIT_CRITERIA', 'updated_at', 'UPDATED_DATE';
EXEC dbo.sp_RenameColSafe 'QMS_AUDIT_CRITERIA', 'created_by', 'CREATED_USER';
EXEC dbo.sp_RenameColSafe 'QMS_AUDIT_CRITERIA', 'updated_by', 'UPDATED_USER';

EXEC dbo.sp_RenameColSafe 'QMS_AUDIT_OBSERVATION', 'CREATED_AT', 'CREATED_DATE';
EXEC dbo.sp_RenameColSafe 'QMS_AUDIT_OBSERVATION', 'UPDATED_AT', 'UPDATED_DATE';
EXEC dbo.sp_RenameColSafe 'QMS_AUDIT_OBSERVATION', 'CREATED_BY', 'CREATED_USER';
EXEC dbo.sp_RenameColSafe 'QMS_AUDIT_OBSERVATION', 'UPDATED_BY', 'UPDATED_USER';
EXEC dbo.sp_RenameColSafe 'QMS_AUDIT_OBSERVATION', 'created_at', 'CREATED_DATE';
EXEC dbo.sp_RenameColSafe 'QMS_AUDIT_OBSERVATION', 'updated_at', 'UPDATED_DATE';
EXEC dbo.sp_RenameColSafe 'QMS_AUDIT_OBSERVATION', 'created_by', 'CREATED_USER';
EXEC dbo.sp_RenameColSafe 'QMS_AUDIT_OBSERVATION', 'updated_by', 'UPDATED_USER';

EXEC dbo.sp_RenameColSafe 'QMS_AUDIT_SCHEDULE', 'CREATED_AT', 'CREATED_DATE';
EXEC dbo.sp_RenameColSafe 'QMS_AUDIT_SCHEDULE', 'UPDATED_AT', 'UPDATED_DATE';
EXEC dbo.sp_RenameColSafe 'QMS_AUDIT_SCHEDULE', 'CREATED_BY', 'CREATED_USER';
EXEC dbo.sp_RenameColSafe 'QMS_AUDIT_SCHEDULE', 'UPDATED_BY', 'UPDATED_USER';
EXEC dbo.sp_RenameColSafe 'QMS_AUDIT_SCHEDULE', 'created_at', 'CREATED_DATE';
EXEC dbo.sp_RenameColSafe 'QMS_AUDIT_SCHEDULE', 'updated_at', 'UPDATED_DATE';
EXEC dbo.sp_RenameColSafe 'QMS_AUDIT_SCHEDULE', 'created_by', 'CREATED_USER';
EXEC dbo.sp_RenameColSafe 'QMS_AUDIT_SCHEDULE', 'updated_by', 'UPDATED_USER';

EXEC dbo.sp_RenameColSafe 'QMS_AUDIT_TYPE', 'CREATED_AT', 'CREATED_DATE';
EXEC dbo.sp_RenameColSafe 'QMS_AUDIT_TYPE', 'UPDATED_AT', 'UPDATED_DATE';
EXEC dbo.sp_RenameColSafe 'QMS_AUDIT_TYPE', 'CREATED_BY', 'CREATED_USER';
EXEC dbo.sp_RenameColSafe 'QMS_AUDIT_TYPE', 'UPDATED_BY', 'UPDATED_USER';
EXEC dbo.sp_RenameColSafe 'QMS_AUDIT_TYPE', 'created_at', 'CREATED_DATE';
EXEC dbo.sp_RenameColSafe 'QMS_AUDIT_TYPE', 'updated_at', 'UPDATED_DATE';
EXEC dbo.sp_RenameColSafe 'QMS_AUDIT_TYPE', 'created_by', 'CREATED_USER';
EXEC dbo.sp_RenameColSafe 'QMS_AUDIT_TYPE', 'updated_by', 'UPDATED_USER';

EXEC dbo.sp_RenameColSafe 'IND_INDUCTION_ASSIGNMENT', 'CREATED_AT', 'CREATED_DATE';
EXEC dbo.sp_RenameColSafe 'IND_INDUCTION_ASSIGNMENT', 'UPDATED_AT', 'UPDATED_DATE';
EXEC dbo.sp_RenameColSafe 'IND_INDUCTION_ASSIGNMENT', 'CREATED_BY', 'CREATED_USER';
EXEC dbo.sp_RenameColSafe 'IND_INDUCTION_ASSIGNMENT', 'UPDATED_BY', 'UPDATED_USER';
EXEC dbo.sp_RenameColSafe 'IND_INDUCTION_ASSIGNMENT', 'created_at', 'CREATED_DATE';
EXEC dbo.sp_RenameColSafe 'IND_INDUCTION_ASSIGNMENT', 'updated_at', 'UPDATED_DATE';
EXEC dbo.sp_RenameColSafe 'IND_INDUCTION_ASSIGNMENT', 'created_by', 'CREATED_USER';
EXEC dbo.sp_RenameColSafe 'IND_INDUCTION_ASSIGNMENT', 'updated_by', 'UPDATED_USER';

EXEC dbo.sp_RenameColSafe 'IND_INDUCTION_MASTER', 'CREATED_AT', 'CREATED_DATE';
EXEC dbo.sp_RenameColSafe 'IND_INDUCTION_MASTER', 'UPDATED_AT', 'UPDATED_DATE';
EXEC dbo.sp_RenameColSafe 'IND_INDUCTION_MASTER', 'CREATED_BY', 'CREATED_USER';
EXEC dbo.sp_RenameColSafe 'IND_INDUCTION_MASTER', 'UPDATED_BY', 'UPDATED_USER';
EXEC dbo.sp_RenameColSafe 'IND_INDUCTION_MASTER', 'created_at', 'CREATED_DATE';
EXEC dbo.sp_RenameColSafe 'IND_INDUCTION_MASTER', 'updated_at', 'UPDATED_DATE';
EXEC dbo.sp_RenameColSafe 'IND_INDUCTION_MASTER', 'created_by', 'CREATED_USER';
EXEC dbo.sp_RenameColSafe 'IND_INDUCTION_MASTER', 'updated_by', 'UPDATED_USER';

EXEC dbo.sp_RenameColSafe 'IND_INDUCTION_TRAINING_DETAIL', 'CREATED_AT', 'CREATED_DATE';
EXEC dbo.sp_RenameColSafe 'IND_INDUCTION_TRAINING_DETAIL', 'UPDATED_AT', 'UPDATED_DATE';
EXEC dbo.sp_RenameColSafe 'IND_INDUCTION_TRAINING_DETAIL', 'CREATED_BY', 'CREATED_USER';
EXEC dbo.sp_RenameColSafe 'IND_INDUCTION_TRAINING_DETAIL', 'UPDATED_BY', 'UPDATED_USER';
EXEC dbo.sp_RenameColSafe 'IND_INDUCTION_TRAINING_DETAIL', 'created_at', 'CREATED_DATE';
EXEC dbo.sp_RenameColSafe 'IND_INDUCTION_TRAINING_DETAIL', 'updated_at', 'UPDATED_DATE';
EXEC dbo.sp_RenameColSafe 'IND_INDUCTION_TRAINING_DETAIL', 'created_by', 'CREATED_USER';
EXEC dbo.sp_RenameColSafe 'IND_INDUCTION_TRAINING_DETAIL', 'updated_by', 'UPDATED_USER';

EXEC dbo.sp_RenameColSafe 'QMS_CHECKLIST_MASTER', 'CREATED_AT', 'CREATED_DATE';
EXEC dbo.sp_RenameColSafe 'QMS_CHECKLIST_MASTER', 'UPDATED_AT', 'UPDATED_DATE';
EXEC dbo.sp_RenameColSafe 'QMS_CHECKLIST_MASTER', 'CREATED_BY', 'CREATED_USER';
EXEC dbo.sp_RenameColSafe 'QMS_CHECKLIST_MASTER', 'UPDATED_BY', 'UPDATED_USER';
EXEC dbo.sp_RenameColSafe 'QMS_CHECKLIST_MASTER', 'created_at', 'CREATED_DATE';
EXEC dbo.sp_RenameColSafe 'QMS_CHECKLIST_MASTER', 'updated_at', 'UPDATED_DATE';
EXEC dbo.sp_RenameColSafe 'QMS_CHECKLIST_MASTER', 'created_by', 'CREATED_USER';
EXEC dbo.sp_RenameColSafe 'QMS_CHECKLIST_MASTER', 'updated_by', 'UPDATED_USER';

EXEC dbo.sp_RenameColSafe 'QMS_MEETING_MASTER', 'CREATED_AT', 'CREATED_DATE';
EXEC dbo.sp_RenameColSafe 'QMS_MEETING_MASTER', 'UPDATED_AT', 'UPDATED_DATE';
EXEC dbo.sp_RenameColSafe 'QMS_MEETING_MASTER', 'CREATED_BY', 'CREATED_USER';
EXEC dbo.sp_RenameColSafe 'QMS_MEETING_MASTER', 'UPDATED_BY', 'UPDATED_USER';
EXEC dbo.sp_RenameColSafe 'QMS_MEETING_MASTER', 'created_at', 'CREATED_DATE';
EXEC dbo.sp_RenameColSafe 'QMS_MEETING_MASTER', 'updated_at', 'UPDATED_DATE';
EXEC dbo.sp_RenameColSafe 'QMS_MEETING_MASTER', 'created_by', 'CREATED_USER';
EXEC dbo.sp_RenameColSafe 'QMS_MEETING_MASTER', 'updated_by', 'UPDATED_USER';

EXEC dbo.sp_RenameColSafe 'QMS_MEETING_SCHEDULE', 'CREATED_AT', 'CREATED_DATE';
EXEC dbo.sp_RenameColSafe 'QMS_MEETING_SCHEDULE', 'UPDATED_AT', 'UPDATED_DATE';
EXEC dbo.sp_RenameColSafe 'QMS_MEETING_SCHEDULE', 'CREATED_BY', 'CREATED_USER';
EXEC dbo.sp_RenameColSafe 'QMS_MEETING_SCHEDULE', 'UPDATED_BY', 'UPDATED_USER';
EXEC dbo.sp_RenameColSafe 'QMS_MEETING_SCHEDULE', 'created_at', 'CREATED_DATE';
EXEC dbo.sp_RenameColSafe 'QMS_MEETING_SCHEDULE', 'updated_at', 'UPDATED_DATE';
EXEC dbo.sp_RenameColSafe 'QMS_MEETING_SCHEDULE', 'created_by', 'CREATED_USER';
EXEC dbo.sp_RenameColSafe 'QMS_MEETING_SCHEDULE', 'updated_by', 'UPDATED_USER';

EXEC dbo.sp_RenameColSafe 'QMS_MEETING_USER_ATTENDANCE', 'CREATED_AT', 'CREATED_DATE';
EXEC dbo.sp_RenameColSafe 'QMS_MEETING_USER_ATTENDANCE', 'UPDATED_AT', 'UPDATED_DATE';
EXEC dbo.sp_RenameColSafe 'QMS_MEETING_USER_ATTENDANCE', 'CREATED_BY', 'CREATED_USER';
EXEC dbo.sp_RenameColSafe 'QMS_MEETING_USER_ATTENDANCE', 'UPDATED_BY', 'UPDATED_USER';
EXEC dbo.sp_RenameColSafe 'QMS_MEETING_USER_ATTENDANCE', 'created_at', 'CREATED_DATE';
EXEC dbo.sp_RenameColSafe 'QMS_MEETING_USER_ATTENDANCE', 'updated_at', 'UPDATED_DATE';
EXEC dbo.sp_RenameColSafe 'QMS_MEETING_USER_ATTENDANCE', 'created_by', 'CREATED_USER';
EXEC dbo.sp_RenameColSafe 'QMS_MEETING_USER_ATTENDANCE', 'updated_by', 'UPDATED_USER';

EXEC dbo.sp_RenameColSafe 'QMS_MODEL_NAME', 'CREATED_AT', 'CREATED_DATE';
EXEC dbo.sp_RenameColSafe 'QMS_MODEL_NAME', 'UPDATED_AT', 'UPDATED_DATE';
EXEC dbo.sp_RenameColSafe 'QMS_MODEL_NAME', 'CREATED_BY', 'CREATED_USER';
EXEC dbo.sp_RenameColSafe 'QMS_MODEL_NAME', 'UPDATED_BY', 'UPDATED_USER';
EXEC dbo.sp_RenameColSafe 'QMS_MODEL_NAME', 'created_at', 'CREATED_DATE';
EXEC dbo.sp_RenameColSafe 'QMS_MODEL_NAME', 'updated_at', 'UPDATED_DATE';
EXEC dbo.sp_RenameColSafe 'QMS_MODEL_NAME', 'created_by', 'CREATED_USER';
EXEC dbo.sp_RenameColSafe 'QMS_MODEL_NAME', 'updated_by', 'UPDATED_USER';

EXEC dbo.sp_RenameColSafe 'QMS_MOM_DETAIL', 'CREATED_AT', 'CREATED_DATE';
EXEC dbo.sp_RenameColSafe 'QMS_MOM_DETAIL', 'UPDATED_AT', 'UPDATED_DATE';
EXEC dbo.sp_RenameColSafe 'QMS_MOM_DETAIL', 'CREATED_BY', 'CREATED_USER';
EXEC dbo.sp_RenameColSafe 'QMS_MOM_DETAIL', 'UPDATED_BY', 'UPDATED_USER';
EXEC dbo.sp_RenameColSafe 'QMS_MOM_DETAIL', 'created_at', 'CREATED_DATE';
EXEC dbo.sp_RenameColSafe 'QMS_MOM_DETAIL', 'updated_at', 'UPDATED_DATE';
EXEC dbo.sp_RenameColSafe 'QMS_MOM_DETAIL', 'created_by', 'CREATED_USER';
EXEC dbo.sp_RenameColSafe 'QMS_MOM_DETAIL', 'updated_by', 'UPDATED_USER';

EXEC dbo.sp_RenameColSafe 'QMS_MOM_MASTER', 'CREATED_AT', 'CREATED_DATE';
EXEC dbo.sp_RenameColSafe 'QMS_MOM_MASTER', 'UPDATED_AT', 'UPDATED_DATE';
EXEC dbo.sp_RenameColSafe 'QMS_MOM_MASTER', 'CREATED_BY', 'CREATED_USER';
EXEC dbo.sp_RenameColSafe 'QMS_MOM_MASTER', 'UPDATED_BY', 'UPDATED_USER';
EXEC dbo.sp_RenameColSafe 'QMS_MOM_MASTER', 'created_at', 'CREATED_DATE';
EXEC dbo.sp_RenameColSafe 'QMS_MOM_MASTER', 'updated_at', 'UPDATED_DATE';
EXEC dbo.sp_RenameColSafe 'QMS_MOM_MASTER', 'created_by', 'CREATED_USER';
EXEC dbo.sp_RenameColSafe 'QMS_MOM_MASTER', 'updated_by', 'UPDATED_USER';

EXEC dbo.sp_RenameColSafe 'QMS_UOM', 'CREATED_AT', 'CREATED_DATE';
EXEC dbo.sp_RenameColSafe 'QMS_UOM', 'UPDATED_AT', 'UPDATED_DATE';
EXEC dbo.sp_RenameColSafe 'QMS_UOM', 'CREATED_BY', 'CREATED_USER';
EXEC dbo.sp_RenameColSafe 'QMS_UOM', 'UPDATED_BY', 'UPDATED_USER';
EXEC dbo.sp_RenameColSafe 'QMS_UOM', 'created_at', 'CREATED_DATE';
EXEC dbo.sp_RenameColSafe 'QMS_UOM', 'updated_at', 'UPDATED_DATE';
EXEC dbo.sp_RenameColSafe 'QMS_UOM', 'created_by', 'CREATED_USER';
EXEC dbo.sp_RenameColSafe 'QMS_UOM', 'updated_by', 'UPDATED_USER';
GO

-- Drop rename helper
IF OBJECT_ID('dbo.sp_RenameColSafe', 'P') IS NOT NULL
    DROP PROCEDURE dbo.sp_RenameColSafe;
GO

-- ===========================================================
-- Create helper: Safe column add (idempotent)
-- ===========================================================
IF OBJECT_ID('dbo.sp_AddColSafe', 'P') IS NOT NULL
    DROP PROCEDURE dbo.sp_AddColSafe;
GO
CREATE PROCEDURE dbo.sp_AddColSafe
    @tbl NVARCHAR(200),
    @col NVARCHAR(100),
    @def NVARCHAR(250)
AS
BEGIN
    -- Only run if the table actually exists
    IF OBJECT_ID(@tbl) IS NULL RETURN;
    IF NOT EXISTS (SELECT 1 FROM sys.columns WHERE object_id = OBJECT_ID(@tbl) AND name = @col)
    BEGIN
        DECLARE @sql NVARCHAR(MAX) = 'ALTER TABLE ' + QUOTENAME(@tbl) + ' ADD ' + QUOTENAME(@col) + ' ' + @def;
        EXEC(@sql);
    END
END
GO

-- ===========================================================
-- STEP 4: Add missing audit columns (skips if table doesn't exist)
-- ===========================================================
EXEC dbo.sp_AddColSafe 'QMS_AUDIT_OBSERVATION_DETAIL', 'CREATED_USER', 'NVARCHAR(100)';
EXEC dbo.sp_AddColSafe 'QMS_AUDIT_OBSERVATION_DETAIL', 'CREATED_DATE', 'DATETIME DEFAULT GETDATE()';
EXEC dbo.sp_AddColSafe 'QMS_AUDIT_OBSERVATION_DETAIL', 'UPDATED_USER', 'NVARCHAR(100)';
EXEC dbo.sp_AddColSafe 'QMS_AUDIT_OBSERVATION_DETAIL', 'UPDATED_DATE', 'DATETIME';

EXEC dbo.sp_AddColSafe 'QMS_AUDIT_SCHEDULE_CRITERIA', 'CREATED_USER', 'NVARCHAR(100)';
EXEC dbo.sp_AddColSafe 'QMS_AUDIT_SCHEDULE_CRITERIA', 'CREATED_DATE', 'DATETIME DEFAULT GETDATE()';
EXEC dbo.sp_AddColSafe 'QMS_AUDIT_SCHEDULE_CRITERIA', 'UPDATED_USER', 'NVARCHAR(100)';
EXEC dbo.sp_AddColSafe 'QMS_AUDIT_SCHEDULE_CRITERIA', 'UPDATED_DATE', 'DATETIME';

EXEC dbo.sp_AddColSafe 'QMS_NCR_OFI_ACTION', 'CREATED_USER', 'NVARCHAR(100)';
EXEC dbo.sp_AddColSafe 'QMS_NCR_OFI_ACTION', 'UPDATED_USER', 'NVARCHAR(100)';
EXEC dbo.sp_AddColSafe 'QMS_NCR_OFI_ACTION', 'UPDATED_DATE', 'DATETIME';

EXEC dbo.sp_AddColSafe 'QMS_NCR_OFI_APPROVAL', 'CREATED_USER', 'NVARCHAR(100)';
EXEC dbo.sp_AddColSafe 'QMS_NCR_OFI_APPROVAL', 'CREATED_DATE', 'DATETIME DEFAULT GETDATE()';
EXEC dbo.sp_AddColSafe 'QMS_NCR_OFI_APPROVAL', 'UPDATED_USER', 'NVARCHAR(100)';
EXEC dbo.sp_AddColSafe 'QMS_NCR_OFI_APPROVAL', 'UPDATED_DATE', 'DATETIME';

EXEC dbo.sp_AddColSafe 'QMS_NCR_OFI_ATTACHMENT', 'CREATED_USER', 'NVARCHAR(100)';
EXEC dbo.sp_AddColSafe 'QMS_NCR_OFI_ATTACHMENT', 'CREATED_DATE', 'DATETIME DEFAULT GETDATE()';
EXEC dbo.sp_AddColSafe 'QMS_NCR_OFI_ATTACHMENT', 'UPDATED_USER', 'NVARCHAR(100)';
EXEC dbo.sp_AddColSafe 'QMS_NCR_OFI_ATTACHMENT', 'UPDATED_DATE', 'DATETIME';

EXEC dbo.sp_AddColSafe 'QMS_CHECKLIST_ASSIGNMENT', 'CREATED_USER', 'NVARCHAR(100)';
EXEC dbo.sp_AddColSafe 'QMS_CHECKLIST_ASSIGNMENT', 'CREATED_DATE', 'DATETIME DEFAULT GETDATE()';

EXEC dbo.sp_AddColSafe 'QMS_CHECKLIST_VERIFICATION', 'CREATED_USER', 'NVARCHAR(100)';
EXEC dbo.sp_AddColSafe 'QMS_CHECKLIST_VERIFICATION', 'CREATED_DATE', 'DATETIME DEFAULT GETDATE()';
EXEC dbo.sp_AddColSafe 'QMS_CHECKLIST_VERIFICATION', 'UPDATED_USER', 'NVARCHAR(100)';
EXEC dbo.sp_AddColSafe 'QMS_CHECKLIST_VERIFICATION', 'UPDATED_DATE', 'DATETIME';

EXEC dbo.sp_AddColSafe 'QMS_MOM_ATTENDANCE', 'CREATED_USER', 'NVARCHAR(100)';
EXEC dbo.sp_AddColSafe 'QMS_MOM_ATTENDANCE', 'CREATED_DATE', 'DATETIME DEFAULT GETDATE()';
EXEC dbo.sp_AddColSafe 'QMS_MOM_ATTENDANCE', 'UPDATED_USER', 'NVARCHAR(100)';
EXEC dbo.sp_AddColSafe 'QMS_MOM_ATTENDANCE', 'UPDATED_DATE', 'DATETIME';
GO

-- Drop add column helper
IF OBJECT_ID('dbo.sp_AddColSafe', 'P') IS NOT NULL
    DROP PROCEDURE dbo.sp_AddColSafe;
GO

-- ===========================================================
-- STEP 5: Backfill audit columns from legacy columns (dynamic SQL to avoid compile errors)
-- ===========================================================
IF OBJECT_ID('QMS_NCR_OFI_APPROVAL', 'U') IS NOT NULL
    AND EXISTS (SELECT 1 FROM sys.columns WHERE object_id = OBJECT_ID('QMS_NCR_OFI_APPROVAL') AND name = 'APPROVAL_DATE')
BEGIN
    EXEC('UPDATE QMS_NCR_OFI_APPROVAL SET CREATED_DATE = APPROVAL_DATE WHERE CREATED_DATE IS NULL');
END

IF OBJECT_ID('QMS_NCR_OFI_ATTACHMENT', 'U') IS NOT NULL
    AND EXISTS (SELECT 1 FROM sys.columns WHERE object_id = OBJECT_ID('QMS_NCR_OFI_ATTACHMENT') AND name = 'UPLOADED_BY')
BEGIN
    EXEC('UPDATE QMS_NCR_OFI_ATTACHMENT SET CREATED_USER = UPLOADED_BY, CREATED_DATE = UPLOADED_DATE WHERE CREATED_DATE IS NULL');
END

IF OBJECT_ID('QMS_CHECKLIST_ASSIGNMENT', 'U') IS NOT NULL
    AND EXISTS (SELECT 1 FROM sys.columns WHERE object_id = OBJECT_ID('QMS_CHECKLIST_ASSIGNMENT') AND name = 'ASSIGNED_BY')
BEGIN
    EXEC('UPDATE QMS_CHECKLIST_ASSIGNMENT SET CREATED_USER = ASSIGNED_BY, CREATED_DATE = ASSIGNED_DATE WHERE CREATED_DATE IS NULL');
END

IF OBJECT_ID('QMS_CHECKLIST_VERIFICATION', 'U') IS NOT NULL
    AND EXISTS (SELECT 1 FROM sys.columns WHERE object_id = OBJECT_ID('QMS_CHECKLIST_VERIFICATION') AND name = 'VERIFIED_BY')
BEGIN
    EXEC('UPDATE QMS_CHECKLIST_VERIFICATION SET CREATED_USER = VERIFIED_BY, CREATED_DATE = VERIFIED_DATE WHERE CREATED_DATE IS NULL');
END
GO

-- ===========================================================
-- STEP 6: Re-create standard FK relationships (fully safe)
-- Uses lowercase column names matching actual Hibernate-created schema
-- Skips if ANY FK on same column already exists
-- ===========================================================

-- QMS_AUDIT_OBSERVATION_DETAIL -> QMS_AUDIT_OBSERVATION (on observation_id)
IF OBJECT_ID('QMS_AUDIT_OBSERVATION_DETAIL', 'U') IS NOT NULL
   AND OBJECT_ID('QMS_AUDIT_OBSERVATION', 'U') IS NOT NULL
   AND NOT EXISTS (
       SELECT 1 FROM sys.foreign_keys fk
       INNER JOIN sys.foreign_key_columns fkc ON fk.object_id = fkc.constraint_object_id
       WHERE fk.parent_object_id = OBJECT_ID('QMS_AUDIT_OBSERVATION_DETAIL')
         AND COL_NAME(fkc.parent_object_id, fkc.parent_column_id) IN ('observation_id', 'OBSERVATION_ID')
   )
   ALTER TABLE QMS_AUDIT_OBSERVATION_DETAIL
       ADD CONSTRAINT FK_QMS_AUDIT_OBS_DETAIL_OBS
       FOREIGN KEY (observation_id) REFERENCES QMS_AUDIT_OBSERVATION(id);

-- QMS_AUDIT_SCHEDULE_CRITERIA -> QMS_AUDIT_SCHEDULE (on audit_schedule_id)
IF OBJECT_ID('QMS_AUDIT_SCHEDULE_CRITERIA', 'U') IS NOT NULL
   AND OBJECT_ID('QMS_AUDIT_SCHEDULE', 'U') IS NOT NULL
   AND NOT EXISTS (
       SELECT 1 FROM sys.foreign_keys fk
       INNER JOIN sys.foreign_key_columns fkc ON fk.object_id = fkc.constraint_object_id
       WHERE fk.parent_object_id = OBJECT_ID('QMS_AUDIT_SCHEDULE_CRITERIA')
         AND COL_NAME(fkc.parent_object_id, fkc.parent_column_id) IN ('audit_schedule_id', 'AUDIT_SCHEDULE_ID')
   )
   ALTER TABLE QMS_AUDIT_SCHEDULE_CRITERIA
       ADD CONSTRAINT FK_QMS_AUDIT_SCHEDULE_CRITERIA_SCHEDULE
       FOREIGN KEY (audit_schedule_id) REFERENCES QMS_AUDIT_SCHEDULE(id);

-- QMS_NCR_OFI_ACTION -> QMS_NCR_OFI_MASTER (on ncr_ofi_id)
IF OBJECT_ID('QMS_NCR_OFI_ACTION', 'U') IS NOT NULL
   AND OBJECT_ID('QMS_NCR_OFI_MASTER', 'U') IS NOT NULL
   AND NOT EXISTS (
       SELECT 1 FROM sys.foreign_keys WHERE parent_object_id = OBJECT_ID('QMS_NCR_OFI_ACTION')
         AND referenced_object_id = OBJECT_ID('QMS_NCR_OFI_MASTER')
   )
   ALTER TABLE QMS_NCR_OFI_ACTION
       ADD CONSTRAINT FK_QMS_NCR_OFI_ACTION_MASTER
       FOREIGN KEY (ncr_ofi_id) REFERENCES QMS_NCR_OFI_MASTER(id) ON DELETE CASCADE;

-- QMS_NCR_OFI_APPROVAL -> QMS_NCR_OFI_MASTER
IF OBJECT_ID('QMS_NCR_OFI_APPROVAL', 'U') IS NOT NULL
   AND OBJECT_ID('QMS_NCR_OFI_MASTER', 'U') IS NOT NULL
   AND NOT EXISTS (
       SELECT 1 FROM sys.foreign_keys WHERE parent_object_id = OBJECT_ID('QMS_NCR_OFI_APPROVAL')
         AND referenced_object_id = OBJECT_ID('QMS_NCR_OFI_MASTER')
   )
   ALTER TABLE QMS_NCR_OFI_APPROVAL
       ADD CONSTRAINT FK_QMS_NCR_OFI_APPROVAL_MASTER
       FOREIGN KEY (ncr_ofi_id) REFERENCES QMS_NCR_OFI_MASTER(id) ON DELETE CASCADE;

-- QMS_NCR_OFI_ATTACHMENT -> QMS_NCR_OFI_MASTER
IF OBJECT_ID('QMS_NCR_OFI_ATTACHMENT', 'U') IS NOT NULL
   AND OBJECT_ID('QMS_NCR_OFI_MASTER', 'U') IS NOT NULL
   AND NOT EXISTS (
       SELECT 1 FROM sys.foreign_keys WHERE parent_object_id = OBJECT_ID('QMS_NCR_OFI_ATTACHMENT')
         AND referenced_object_id = OBJECT_ID('QMS_NCR_OFI_MASTER')
   )
   ALTER TABLE QMS_NCR_OFI_ATTACHMENT
       ADD CONSTRAINT FK_QMS_NCR_OFI_ATTACHMENT_MASTER
       FOREIGN KEY (ncr_ofi_id) REFERENCES QMS_NCR_OFI_MASTER(id) ON DELETE CASCADE;

-- QMS_CHECKLIST_ASSIGNMENT -> QMS_CHECKLIST_MASTER (on checklist_id)
IF OBJECT_ID('QMS_CHECKLIST_ASSIGNMENT', 'U') IS NOT NULL
   AND OBJECT_ID('QMS_CHECKLIST_MASTER', 'U') IS NOT NULL
   AND NOT EXISTS (
       SELECT 1 FROM sys.foreign_keys fk
       INNER JOIN sys.foreign_key_columns fkc ON fk.object_id = fkc.constraint_object_id
       WHERE fk.parent_object_id = OBJECT_ID('QMS_CHECKLIST_ASSIGNMENT')
         AND fk.referenced_object_id = OBJECT_ID('QMS_CHECKLIST_MASTER')
   )
   ALTER TABLE QMS_CHECKLIST_ASSIGNMENT
       ADD CONSTRAINT FK_QMS_CHECKLIST_ASSIGNMENT_MASTER
       FOREIGN KEY (checklist_id) REFERENCES QMS_CHECKLIST_MASTER(id) ON DELETE CASCADE;

-- QMS_CHECKLIST_VERIFICATION -> QMS_CHECKLIST_ASSIGNMENT (on assignment_id)
IF OBJECT_ID('QMS_CHECKLIST_VERIFICATION', 'U') IS NOT NULL
   AND OBJECT_ID('QMS_CHECKLIST_ASSIGNMENT', 'U') IS NOT NULL
   AND NOT EXISTS (
       SELECT 1 FROM sys.foreign_keys fk
       WHERE fk.parent_object_id = OBJECT_ID('QMS_CHECKLIST_VERIFICATION')
         AND fk.referenced_object_id = OBJECT_ID('QMS_CHECKLIST_ASSIGNMENT')
   )
   ALTER TABLE QMS_CHECKLIST_VERIFICATION
       ADD CONSTRAINT FK_QMS_CHECKLIST_VERIFICATION_ASSIGNMENT
       FOREIGN KEY (assignment_id) REFERENCES QMS_CHECKLIST_ASSIGNMENT(id) ON DELETE CASCADE;

-- QMS_MOM_DETAIL -> QMS_MOM_MASTER (on mom_id)
IF OBJECT_ID('QMS_MOM_DETAIL', 'U') IS NOT NULL
   AND OBJECT_ID('QMS_MOM_MASTER', 'U') IS NOT NULL
   AND NOT EXISTS (
       SELECT 1 FROM sys.foreign_keys fk
       WHERE fk.parent_object_id = OBJECT_ID('QMS_MOM_DETAIL')
         AND fk.referenced_object_id = OBJECT_ID('QMS_MOM_MASTER')
   )
   ALTER TABLE QMS_MOM_DETAIL
       ADD CONSTRAINT FK_QMS_MOM_DETAIL_MASTER
       FOREIGN KEY (mom_id) REFERENCES QMS_MOM_MASTER(id) ON DELETE CASCADE;

-- QMS_MOM_ATTENDANCE -> QMS_MOM_MASTER (on mom_id)
IF OBJECT_ID('QMS_MOM_ATTENDANCE', 'U') IS NOT NULL
   AND OBJECT_ID('QMS_MOM_MASTER', 'U') IS NOT NULL
   AND NOT EXISTS (
       SELECT 1 FROM sys.foreign_keys fk
       INNER JOIN sys.foreign_key_columns fkc ON fk.object_id = fkc.constraint_object_id
       WHERE fk.parent_object_id = OBJECT_ID('QMS_MOM_ATTENDANCE')
         AND fk.referenced_object_id = OBJECT_ID('QMS_MOM_MASTER')
   )
   ALTER TABLE QMS_MOM_ATTENDANCE
       ADD CONSTRAINT FK_QMS_MOM_ATTENDANCE_MASTER
       FOREIGN KEY (mom_id) REFERENCES QMS_MOM_MASTER(id) ON DELETE CASCADE;

-- QMS_MEETING_SCHEDULE_DEPARTMENT -> QMS_MEETING_SCHEDULE (on schedule_id)
IF OBJECT_ID('QMS_MEETING_SCHEDULE_DEPARTMENT', 'U') IS NOT NULL
   AND OBJECT_ID('QMS_MEETING_SCHEDULE', 'U') IS NOT NULL
   AND NOT EXISTS (
       SELECT 1 FROM sys.foreign_keys fk
       WHERE fk.parent_object_id = OBJECT_ID('QMS_MEETING_SCHEDULE_DEPARTMENT')
         AND fk.referenced_object_id = OBJECT_ID('QMS_MEETING_SCHEDULE')
   )
   ALTER TABLE QMS_MEETING_SCHEDULE_DEPARTMENT
       ADD CONSTRAINT FK_QMS_MEETING_SCHED_DEPT_SCHEDULE
       FOREIGN KEY (schedule_id) REFERENCES QMS_MEETING_SCHEDULE(id) ON DELETE CASCADE;

-- QMS_MEETING_SCHEDULE_PARTICIPANT -> QMS_MEETING_SCHEDULE (on schedule_id)
IF OBJECT_ID('QMS_MEETING_SCHEDULE_PARTICIPANT', 'U') IS NOT NULL
   AND OBJECT_ID('QMS_MEETING_SCHEDULE', 'U') IS NOT NULL
   AND NOT EXISTS (
       SELECT 1 FROM sys.foreign_keys fk
       WHERE fk.parent_object_id = OBJECT_ID('QMS_MEETING_SCHEDULE_PARTICIPANT')
         AND fk.referenced_object_id = OBJECT_ID('QMS_MEETING_SCHEDULE')
   )
   ALTER TABLE QMS_MEETING_SCHEDULE_PARTICIPANT
       ADD CONSTRAINT FK_QMS_MEETING_SCHED_PART_SCHEDULE
       FOREIGN KEY (schedule_id) REFERENCES QMS_MEETING_SCHEDULE(id) ON DELETE CASCADE;

-- QMS_MEETING_USER_ATTENDANCE -> QMS_MEETING_SCHEDULE (on schedule_id)
IF OBJECT_ID('QMS_MEETING_USER_ATTENDANCE', 'U') IS NOT NULL
   AND OBJECT_ID('QMS_MEETING_SCHEDULE', 'U') IS NOT NULL
   AND NOT EXISTS (
       SELECT 1 FROM sys.foreign_keys fk
       INNER JOIN sys.foreign_key_columns fkc ON fk.object_id = fkc.constraint_object_id
       WHERE fk.parent_object_id = OBJECT_ID('QMS_MEETING_USER_ATTENDANCE')
         AND fk.referenced_object_id = OBJECT_ID('QMS_MEETING_SCHEDULE')
   )
   ALTER TABLE QMS_MEETING_USER_ATTENDANCE
       ADD CONSTRAINT FK_QMS_MEETING_USER_ATT_SCHEDULE
       FOREIGN KEY (schedule_id) REFERENCES QMS_MEETING_SCHEDULE(id) ON DELETE CASCADE;

-- IND_INDUCTION_TRAINING_DETAIL -> IND_INDUCTION_ASSIGNMENT
IF OBJECT_ID('IND_INDUCTION_TRAINING_DETAIL', 'U') IS NOT NULL
   AND OBJECT_ID('IND_INDUCTION_ASSIGNMENT', 'U') IS NOT NULL
   AND NOT EXISTS (
       SELECT 1 FROM sys.foreign_keys fk
       WHERE fk.parent_object_id = OBJECT_ID('IND_INDUCTION_TRAINING_DETAIL')
         AND fk.referenced_object_id = OBJECT_ID('IND_INDUCTION_ASSIGNMENT')
   )
   ALTER TABLE IND_INDUCTION_TRAINING_DETAIL
       ADD CONSTRAINT FK_IND_TRAINING_DETAIL_ASSIGNMENT
       FOREIGN KEY (assignment_id) REFERENCES IND_INDUCTION_ASSIGNMENT(id) ON DELETE CASCADE;

-- IND_INDUCTION_TRAINING_DETAIL -> IND_INDUCTION_MASTER
IF OBJECT_ID('IND_INDUCTION_TRAINING_DETAIL', 'U') IS NOT NULL
   AND OBJECT_ID('IND_INDUCTION_MASTER', 'U') IS NOT NULL
   AND NOT EXISTS (
       SELECT 1 FROM sys.foreign_keys fk
       WHERE fk.parent_object_id = OBJECT_ID('IND_INDUCTION_TRAINING_DETAIL')
         AND fk.referenced_object_id = OBJECT_ID('IND_INDUCTION_MASTER')
   )
   ALTER TABLE IND_INDUCTION_TRAINING_DETAIL
       ADD CONSTRAINT FK_IND_TRAINING_DETAIL_MASTER
       FOREIGN KEY (induction_master_id) REFERENCES IND_INDUCTION_MASTER(id) ON DELETE CASCADE;

PRINT 'V38.0 Team Database Standardization completed successfully.';
GO
