-- Add new fields to Segment and Sub Segment masters
ALTER TABLE SM_SEGMENT ADD SEGMENT_DESCRIPTION NVARCHAR(500);

ALTER TABLE SM_SUB_SEGMENT ADD SEGMENT_NAME NVARCHAR(100);
ALTER TABLE SM_SUB_SEGMENT ADD SUB_SEGMENT_DESCRIPTION NVARCHAR(500);
