-- Add Amendment Reason and Level IDs to QMS_MASTER_CHECKLIST
IF NOT EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID(N'[dbo].[QMS_MASTER_CHECKLIST]') AND name = 'AMENDMENT_REASON')
BEGIN
    ALTER TABLE [dbo].[QMS_MASTER_CHECKLIST] ADD [AMENDMENT_REASON] TEXT;
END

IF NOT EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID(N'[dbo].[QMS_MASTER_CHECKLIST]') AND name = 'LEVEL_IDS')
BEGIN
    ALTER TABLE [dbo].[QMS_MASTER_CHECKLIST] ADD [LEVEL_IDS] NVARCHAR(100);
END
