-- Add missing IS_ACTIVE column to QMS_CHECKLIST_ASSIGNMENT table
IF OBJECT_ID('QMS_CHECKLIST_ASSIGNMENT', 'U') IS NOT NULL
BEGIN
    IF COL_LENGTH('QMS_CHECKLIST_ASSIGNMENT', 'IS_ACTIVE') IS NULL
    BEGIN
        ALTER TABLE QMS_CHECKLIST_ASSIGNMENT ADD IS_ACTIVE BIT DEFAULT 1;
    END
END
GO
