-- Create Sales & Marketing Lookup Tables

-- 1. Currency Master
CREATE TABLE SM_CURRENCY (
    id BIGINT IDENTITY(1,1) PRIMARY KEY,
    CURRENCY_CODE NVARCHAR(10),
    CURRENCY_NAME NVARCHAR(100),
    SYMBOL NVARCHAR(10),
    STATUS NVARCHAR(20) DEFAULT 'Active'
);

-- 2. Delivery Terms Master
CREATE TABLE SM_DELIVERY_TERMS (
    id BIGINT IDENTITY(1,1) PRIMARY KEY,
    TERM_CODE NVARCHAR(50),
    TERM_NAME NVARCHAR(100),
    DESCRIPTION NVARCHAR(500),
    STATUS NVARCHAR(20) DEFAULT 'Active'
);

-- 3. Payment Terms Master
CREATE TABLE SM_PAYMENT_TERMS (
    id BIGINT IDENTITY(1,1) PRIMARY KEY,
    TERM_CODE NVARCHAR(50),
    TERM_NAME NVARCHAR(100),
    DUE_DAYS INT,
    DESCRIPTION NVARCHAR(500),
    STATUS NVARCHAR(20) DEFAULT 'Active'
);

-- 4. Type of Service Master
CREATE TABLE SM_TYPE_OF_SERVICE (
    id BIGINT IDENTITY(1,1) PRIMARY KEY,
    SERVICE_CODE NVARCHAR(50),
    SERVICE_NAME NVARCHAR(100),
    DESCRIPTION NVARCHAR(500),
    STATUS NVARCHAR(20) DEFAULT 'Active'
);

-- 5. Segment Master
CREATE TABLE SM_SEGMENT (
    id BIGINT IDENTITY(1,1) PRIMARY KEY,
    SEGMENT_CODE NVARCHAR(50),
    SEGMENT_NAME NVARCHAR(100),
    STATUS NVARCHAR(20) DEFAULT 'Active'
);

-- 6. Sub Segment Master
CREATE TABLE SM_SUB_SEGMENT (
    id BIGINT IDENTITY(1,1) PRIMARY KEY,
    SUB_SEGMENT_CODE NVARCHAR(50),
    SUB_SEGMENT_NAME NVARCHAR(100),
    STATUS NVARCHAR(20) DEFAULT 'Active'
);
