-- Add verified_by and verified_date columns to QMS_CHECKLIST_ASSIGNMENT table if they do not exist
IF OBJECT_ID('QMS_CHECKLIST_ASSIGNMENT', 'U') IS NOT NULL
BEGIN
    IF NOT EXISTS (SELECT 1 FROM sys.columns WHERE object_id = OBJECT_ID('QMS_CHECKLIST_ASSIGNMENT') AND name = 'VERIFIED_BY')
    BEGIN
        ALTER TABLE QMS_CHECKLIST_ASSIGNMENT ADD VERIFIED_BY NVARCHAR(100);
    END

    IF NOT EXISTS (SELECT 1 FROM sys.columns WHERE object_id = OBJECT_ID('QMS_CHECKLIST_ASSIGNMENT') AND name = 'VERIFIED_DATE')
    BEGIN
        ALTER TABLE QMS_CHECKLIST_ASSIGNMENT ADD VERIFIED_DATE DATETIME;
    END
END
