-- V78.0: Add audit columns to QMS_MEETING_SCHEDULE_DEPARTMENT and QMS_MEETING_SCHEDULE_PARTICIPANT tables
IF OBJECT_ID('QMS_MEETING_SCHEDULE_DEPARTMENT', 'U') IS NOT NULL
BEGIN
    IF COL_LENGTH('QMS_MEETING_SCHEDULE_DEPARTMENT', 'CREATED_USER') IS NULL
    BEGIN
        ALTER TABLE QMS_MEETING_SCHEDULE_DEPARTMENT ADD CREATED_USER NVARCHAR(100);
        ALTER TABLE QMS_MEETING_SCHEDULE_DEPARTMENT ADD CREATED_DATE DATETIME2 DEFAULT GETDATE();
        ALTER TABLE QMS_MEETING_SCHEDULE_DEPARTMENT ADD UPDATED_USER NVARCHAR(100);
        ALTER TABLE QMS_MEETING_SCHEDULE_DEPARTMENT ADD UPDATED_DATE DATETIME2 DEFAULT GETDATE();
        PRINT 'Added audit columns to QMS_MEETING_SCHEDULE_DEPARTMENT';
    END
END
GO

IF OBJECT_ID('QMS_MEETING_SCHEDULE_PARTICIPANT', 'U') IS NOT NULL
BEGIN
    IF COL_LENGTH('QMS_MEETING_SCHEDULE_PARTICIPANT', 'CREATED_USER') IS NULL
    BEGIN
        ALTER TABLE QMS_MEETING_SCHEDULE_PARTICIPANT ADD CREATED_USER NVARCHAR(100);
        ALTER TABLE QMS_MEETING_SCHEDULE_PARTICIPANT ADD CREATED_DATE DATETIME2 DEFAULT GETDATE();
        ALTER TABLE QMS_MEETING_SCHEDULE_PARTICIPANT ADD UPDATED_USER NVARCHAR(100);
        ALTER TABLE QMS_MEETING_SCHEDULE_PARTICIPANT ADD UPDATED_DATE DATETIME2 DEFAULT GETDATE();
        PRINT 'Added audit columns to QMS_MEETING_SCHEDULE_PARTICIPANT';
    END
END
GO
