-- Add 17 new configuration columns to AD_COMPANY_CREDENTIAL
ALTER TABLE AD_COMPANY_CREDENTIAL ADD 
    REGISTRATION_NO NVARCHAR(100) NULL,
    PAN_NO NVARCHAR(50) NULL,
    MOBILE_NO NVARCHAR(20) NULL,
    PHONE_NO NVARCHAR(20) NULL,
    EMAIL_ID NVARCHAR(100) NULL,
    WEBSITE NVARCHAR(100) NULL,
    GMAPLINK NVARCHAR(500) NULL,
    DECIMAL_PLACES INT NULL,
    CURRENCY_CODE NVARCHAR(10) NULL,
    SMTP_HOST NVARCHAR(100) NULL,
    SMTP_PORT INT NULL,
    SMTP_USERNAME NVARCHAR(100) NULL,
    SMTP_PASSWORD NVARCHAR(255) NULL,
    SMTP_SSL_ENABLED BIT DEFAULT 0,
    SUPPORT_EMAIL NVARCHAR(100) NULL,
    SUPPORT_PHONE NVARCHAR(20) NULL,
    AUDIT_LOG_ENABLED BIT DEFAULT 0;
GO
