-- V77.0 Add Audit Schedule Frequency Columns
IF OBJECT_ID('QMS_AUDIT_SCHEDULE', 'U') IS NOT NULL
BEGIN
    IF NOT EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID(N'[dbo].[QMS_AUDIT_SCHEDULE]') AND name = 'WEEK_DAYS')
    BEGIN
        ALTER TABLE [dbo].[QMS_AUDIT_SCHEDULE] ADD [WEEK_DAYS] NVARCHAR(255) NULL;
    END

    IF NOT EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID(N'[dbo].[QMS_AUDIT_SCHEDULE]') AND name = 'REPEAT_EVERY_VALUE')
    BEGIN
        ALTER TABLE [dbo].[QMS_AUDIT_SCHEDULE] ADD [REPEAT_EVERY_VALUE] INT NULL;
    END

    IF NOT EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID(N'[dbo].[QMS_AUDIT_SCHEDULE]') AND name = 'REPEAT_EVERY_UNIT')
    BEGIN
        ALTER TABLE [dbo].[QMS_AUDIT_SCHEDULE] ADD [REPEAT_EVERY_UNIT] NVARCHAR(50) NULL;
    END
END
