-- Add DEPARTMENT_MAIL_ID column to HR_DEPARTMENT table
IF NOT EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID('HR_DEPARTMENT') AND name = 'DEPARTMENT_MAIL_ID')
BEGIN
    ALTER TABLE HR_DEPARTMENT ADD DEPARTMENT_MAIL_ID NVARCHAR(255) NOT NULL DEFAULT '';
END
GO

-- Seed default department emails if they are empty
UPDATE HR_DEPARTMENT SET DEPARTMENT_MAIL_ID = 'hr@autonoma.com' WHERE id = 1 AND DEPARTMENT_MAIL_ID = '';
UPDATE HR_DEPARTMENT SET DEPARTMENT_MAIL_ID = 'it@autonoma.com' WHERE id = 2 AND DEPARTMENT_MAIL_ID = '';
UPDATE HR_DEPARTMENT SET DEPARTMENT_MAIL_ID = 'sales@autonoma.com' WHERE id = 3 AND DEPARTMENT_MAIL_ID = '';
UPDATE HR_DEPARTMENT SET DEPARTMENT_MAIL_ID = 'finance@autonoma.com' WHERE id = 4 AND DEPARTMENT_MAIL_ID = '';
UPDATE HR_DEPARTMENT SET DEPARTMENT_MAIL_ID = 'qms@autonoma.com' WHERE id = 5 AND DEPARTMENT_MAIL_ID = '';
GO
