-- Add comments and file_paths columns to QMS_CHECKLIST_ASSIGNMENT table if they do not exist
IF OBJECT_ID('QMS_CHECKLIST_ASSIGNMENT', 'U') IS NOT NULL
BEGIN
    IF NOT EXISTS (SELECT 1 FROM sys.columns WHERE object_id = OBJECT_ID('QMS_CHECKLIST_ASSIGNMENT') AND name = 'COMMENTS')
    BEGIN
        ALTER TABLE QMS_CHECKLIST_ASSIGNMENT ADD COMMENTS NVARCHAR(MAX);
    END

    IF NOT EXISTS (SELECT 1 FROM sys.columns WHERE object_id = OBJECT_ID('QMS_CHECKLIST_ASSIGNMENT') AND name = 'FILE_PATHS')
    BEGIN
        ALTER TABLE QMS_CHECKLIST_ASSIGNMENT ADD FILE_PATHS NVARCHAR(MAX);
    END
END
