-- Add RESCHEDULE_COUNT to QMS_AUDIT_SCHEDULE table
IF OBJECT_ID('QMS_AUDIT_SCHEDULE', 'U') IS NOT NULL
BEGIN
    IF NOT EXISTS (
        SELECT * FROM sys.columns 
        WHERE object_id = OBJECT_ID(N'[dbo].[QMS_AUDIT_SCHEDULE]') 
          AND name = 'RESCHEDULE_COUNT'
     )
     BEGIN
         ALTER TABLE QMS_AUDIT_SCHEDULE ADD RESCHEDULE_COUNT INT NULL;
     END
END
GO

-- Backfill default value for existing rows
IF OBJECT_ID('QMS_AUDIT_SCHEDULE', 'U') IS NOT NULL
BEGIN
    EXEC('UPDATE QMS_AUDIT_SCHEDULE SET RESCHEDULE_COUNT = 0 WHERE RESCHEDULE_COUNT IS NULL');
END
GO
