CREATE TABLE SM_CUSTOMER_ADDRESS (
    id BIGINT IDENTITY(1,1) PRIMARY KEY,
    customer_id BIGINT,
    customer_name NVARCHAR(200),
    invoice_name NVARCHAR(200),
    shipment NVARCHAR(100),
    address NVARCHAR(MAX),
    city NVARCHAR(100),
    district NVARCHAR(100),
    state NVARCHAR(100),
    country NVARCHAR(100),
    pincode NVARCHAR(20),
    distance FLOAT,
    contact_name NVARCHAR(200),
    contact_no NVARCHAR(50),
    status NVARCHAR(50) DEFAULT 'Active',
    created_by NVARCHAR(100),
    created_date DATETIME2,
    updated_by NVARCHAR(100),
    updated_date DATETIME2
);
