-- V68.0 Add TENANT_ID to AD_USER_CREDENTIAL table

IF NOT EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID(N'[dbo].[AD_USER_CREDENTIAL]') AND name = 'TENANT_ID')
BEGIN
    ALTER TABLE [dbo].[AD_USER_CREDENTIAL]
    ADD [TENANT_ID] NVARCHAR(50) DEFAULT 'AUTONOMA';
END
GO
