-- Create Session Monitoring Table
IF OBJECT_ID('AD_USER_SESSION_AUDIT', 'U') IS NULL
BEGIN
    CREATE TABLE AD_USER_SESSION_AUDIT (
        ID BIGINT IDENTITY(1,1) PRIMARY KEY,
        USER_ID NVARCHAR(50),
        IP_ADDRESS NVARCHAR(50),
        LOGIN_TIME DATETIME,
        LOGOUT_TIME DATETIME,
        USER_AGENT NVARCHAR(255),
        SESSION_STATUS NVARCHAR(20)
    );
END

-- Index for performance on searches
IF NOT EXISTS (SELECT * FROM sys.indexes WHERE name = 'IDX_USER_SESSION_USER_ID' AND object_id = OBJECT_ID('AD_USER_SESSION_AUDIT'))
BEGIN
    CREATE INDEX IDX_USER_SESSION_USER_ID ON AD_USER_SESSION_AUDIT(USER_ID);
END

IF NOT EXISTS (SELECT * FROM sys.indexes WHERE name = 'IDX_USER_SESSION_LOGIN_TIME' AND object_id = OBJECT_ID('AD_USER_SESSION_AUDIT'))
BEGIN
    CREATE INDEX IDX_USER_SESSION_LOGIN_TIME ON AD_USER_SESSION_AUDIT(LOGIN_TIME DESC);
END
