-- V2.6__Add_Employee_Abilities
ALTER TABLE [dbo].[HRM_EMPLOYEE_MASTER] ADD 
    [is_auditor] NVARCHAR(10) DEFAULT 'NO',
    [auditor_type] NVARCHAR(255),
    [auditor_file_info] NVARCHAR(MAX),
    [is_auditee] NVARCHAR(10) DEFAULT 'NO',
    [auditee_type] NVARCHAR(255),
    [auditee_file_info] NVARCHAR(MAX),
    [is_ncr_approver] NVARCHAR(10) DEFAULT 'NO',
    [ncr_approver_type] NVARCHAR(255),
    [ncr_approver_file_info] NVARCHAR(MAX),
    [is_chaired] NVARCHAR(10) DEFAULT 'NO',
    [chaired_type] NVARCHAR(255),
    [is_host] NVARCHAR(10) DEFAULT 'NO',
    [host_type] NVARCHAR(255),
    [is_participants] NVARCHAR(10) DEFAULT 'NO',
    [participants_type] NVARCHAR(255),
    [segment] NVARCHAR(255),
    [sub_segment] NVARCHAR(255),
    [is_first_aid] NVARCHAR(10) DEFAULT 'NO',
    [first_aid_file_info] NVARCHAR(MAX),
    [is_fire_fighter] NVARCHAR(10) DEFAULT 'NO',
    [fire_fighter_file_info] NVARCHAR(MAX),
    [is_two_wheeler] NVARCHAR(10) DEFAULT 'NO',
    [two_wheeler_file_info] NVARCHAR(MAX),
    [is_four_wheeler] NVARCHAR(10) DEFAULT 'NO',
    [four_wheeler_file_info] NVARCHAR(MAX),
    [is_induction_eligible] NVARCHAR(10) DEFAULT 'NO',
    [is_interviewer] NVARCHAR(10) DEFAULT 'NO',
    [is_enquiry_assignee] NVARCHAR(10) DEFAULT 'NO',
    [is_pr_assignee] NVARCHAR(10) DEFAULT 'NO';
