-- Create User Session Activity Tracking Table
CREATE TABLE AD_USER_SESSION_ACTIVITY (
    ID BIGINT IDENTITY(1,1) PRIMARY KEY,
    USER_ID NVARCHAR(50),
    PAGE_NAME NVARCHAR(100),
    PAGE_URL NVARCHAR(255),
    ENTRY_TIME DATETIME,
    EXIT_TIME DATETIME,
    DURATION_MS BIGINT
);

-- Index for performance on analytics queries
CREATE INDEX IDX_USER_ACTIVITY_USER_ID ON AD_USER_SESSION_ACTIVITY(USER_ID);
CREATE INDEX IDX_USER_ACTIVITY_ENTRY_TIME ON AD_USER_SESSION_ACTIVITY(ENTRY_TIME DESC);
