-- 1. ALTER TABLES to set CREATED_BY to NVARCHAR(50) NOT NULL
IF OBJECT_ID('AD_APP_PREFERENCE', 'U') IS NOT NULL ALTER TABLE [AD_APP_PREFERENCE] ALTER COLUMN [CREATED_BY] NVARCHAR(50) NOT NULL;
IF OBJECT_ID('hr_induction_round_master', 'U') IS NOT NULL ALTER TABLE [hr_induction_round_master] ALTER COLUMN [CREATED_BY] NVARCHAR(50) NOT NULL;
IF OBJECT_ID('VND_CUSTOMER_MAPPING', 'U') IS NOT NULL ALTER TABLE [VND_CUSTOMER_MAPPING] ALTER COLUMN [CREATED_BY] NVARCHAR(50) NOT NULL;
IF OBJECT_ID('HR_DEPARTMENT', 'U') IS NOT NULL ALTER TABLE [HR_DEPARTMENT] ALTER COLUMN [CREATED_BY] NVARCHAR(50) NOT NULL;
IF OBJECT_ID('HR_DESIGNATION', 'U') IS NOT NULL ALTER TABLE [HR_DESIGNATION] ALTER COLUMN [CREATED_BY] NVARCHAR(50) NOT NULL;
IF OBJECT_ID('MST_PRODUCT', 'U') IS NOT NULL ALTER TABLE [MST_PRODUCT] ALTER COLUMN [CREATED_BY] NVARCHAR(50) NOT NULL;
IF OBJECT_ID('AD_COMPANY_CREDENTIAL', 'U') IS NOT NULL ALTER TABLE [AD_COMPANY_CREDENTIAL] ALTER COLUMN [CREATED_BY] NVARCHAR(50) NOT NULL;
IF OBJECT_ID('HR_EMPLOYEE', 'U') IS NOT NULL ALTER TABLE [HR_EMPLOYEE] ALTER COLUMN [CREATED_BY] NVARCHAR(50) NOT NULL;
IF OBJECT_ID('HR_EMPLOYEE_MANAGER_MAPPING', 'U') IS NOT NULL ALTER TABLE [HR_EMPLOYEE_MANAGER_MAPPING] ALTER COLUMN [CREATED_BY] NVARCHAR(50) NOT NULL;
IF OBJECT_ID('HR_EMPLOYEE_PERSONAL', 'U') IS NOT NULL ALTER TABLE [HR_EMPLOYEE_PERSONAL] ALTER COLUMN [CREATED_BY] NVARCHAR(50) NOT NULL;
IF OBJECT_ID('HR_EMPLOYEE_TYPE', 'U') IS NOT NULL ALTER TABLE [HR_EMPLOYEE_TYPE] ALTER COLUMN [CREATED_BY] NVARCHAR(50) NOT NULL;
IF OBJECT_ID('HR_INDUCTION_ROUND', 'U') IS NOT NULL ALTER TABLE [HR_INDUCTION_ROUND] ALTER COLUMN [CREATED_BY] NVARCHAR(50) NOT NULL;
IF OBJECT_ID('TICKET_TRACEABILITY_CENTER', 'U') IS NOT NULL ALTER TABLE [TICKET_TRACEABILITY_CENTER] ALTER COLUMN [CREATED_BY] NVARCHAR(50) NOT NULL;
IF OBJECT_ID('HR_LEVEL', 'U') IS NOT NULL ALTER TABLE [HR_LEVEL] ALTER COLUMN [CREATED_BY] NVARCHAR(50) NOT NULL;
IF OBJECT_ID('MST_COUNTRY', 'U') IS NOT NULL ALTER TABLE [MST_COUNTRY] ALTER COLUMN [CREATED_BY] NVARCHAR(50) NOT NULL;
IF OBJECT_ID('HR_ORG_POSITION', 'U') IS NOT NULL ALTER TABLE [HR_ORG_POSITION] ALTER COLUMN [CREATED_BY] NVARCHAR(50) NOT NULL;
IF OBJECT_ID('MST_DESPATCH_MODE', 'U') IS NOT NULL ALTER TABLE [MST_DESPATCH_MODE] ALTER COLUMN [CREATED_BY] NVARCHAR(50) NOT NULL;
IF OBJECT_ID('SM_CUSTOMER_ADDRESS', 'U') IS NOT NULL ALTER TABLE [SM_CUSTOMER_ADDRESS] ALTER COLUMN [CREATED_BY] NVARCHAR(50) NOT NULL;
IF OBJECT_ID('MST_FREIGHT', 'U') IS NOT NULL ALTER TABLE [MST_FREIGHT] ALTER COLUMN [CREATED_BY] NVARCHAR(50) NOT NULL;
IF OBJECT_ID('MST_STATE', 'U') IS NOT NULL ALTER TABLE [MST_STATE] ALTER COLUMN [CREATED_BY] NVARCHAR(50) NOT NULL;
IF OBJECT_ID('SM_SUPPLIER_MASTER', 'U') IS NOT NULL ALTER TABLE [SM_SUPPLIER_MASTER] ALTER COLUMN [CREATED_BY] NVARCHAR(50) NOT NULL;
IF OBJECT_ID('MODE_OF_DESPATCH', 'U') IS NOT NULL ALTER TABLE [MODE_OF_DESPATCH] ALTER COLUMN [CREATED_BY] NVARCHAR(50) NOT NULL;
IF OBJECT_ID('FREIGHT_MASTER', 'U') IS NOT NULL ALTER TABLE [FREIGHT_MASTER] ALTER COLUMN [CREATED_BY] NVARCHAR(50) NOT NULL;
IF OBJECT_ID('SLS_CUSTOMER', 'U') IS NOT NULL ALTER TABLE [SLS_CUSTOMER] ALTER COLUMN [CREATED_BY] NVARCHAR(50) NOT NULL;
IF OBJECT_ID('SM_CURRENCY', 'U') IS NOT NULL ALTER TABLE [SM_CURRENCY] ALTER COLUMN [CREATED_BY] NVARCHAR(50) NOT NULL;
IF OBJECT_ID('EMPLOYEE_MANAGER_MAPPING', 'U') IS NOT NULL ALTER TABLE [EMPLOYEE_MANAGER_MAPPING] ALTER COLUMN [CREATED_BY] NVARCHAR(50) NOT NULL;
IF OBJECT_ID('SLS_CUSTOMER_ADDRESS', 'U') IS NOT NULL ALTER TABLE [SLS_CUSTOMER_ADDRESS] ALTER COLUMN [CREATED_BY] NVARCHAR(50) NOT NULL;
IF OBJECT_ID('SM_DELIVERY_TERMS', 'U') IS NOT NULL ALTER TABLE [SM_DELIVERY_TERMS] ALTER COLUMN [CREATED_BY] NVARCHAR(50) NOT NULL;
IF OBJECT_ID('SLS_CUSTOMER_POTENTIAL', 'U') IS NOT NULL ALTER TABLE [SLS_CUSTOMER_POTENTIAL] ALTER COLUMN [CREATED_BY] NVARCHAR(50) NOT NULL;
IF OBJECT_ID('HR_DEPARTMENT_MASTER', 'U') IS NOT NULL ALTER TABLE [HR_DEPARTMENT_MASTER] ALTER COLUMN [CREATED_BY] NVARCHAR(50) NOT NULL;
IF OBJECT_ID('SM_PAYMENT_TERMS', 'U') IS NOT NULL ALTER TABLE [SM_PAYMENT_TERMS] ALTER COLUMN [CREATED_BY] NVARCHAR(50) NOT NULL;
IF OBJECT_ID('HR_DESIGNATION_LEVEL', 'U') IS NOT NULL ALTER TABLE [HR_DESIGNATION_LEVEL] ALTER COLUMN [CREATED_BY] NVARCHAR(50) NOT NULL;
IF OBJECT_ID('SM_TYPE_OF_SERVICE', 'U') IS NOT NULL ALTER TABLE [SM_TYPE_OF_SERVICE] ALTER COLUMN [CREATED_BY] NVARCHAR(50) NOT NULL;
IF OBJECT_ID('HR_DESIGNATION_MASTER', 'U') IS NOT NULL ALTER TABLE [HR_DESIGNATION_MASTER] ALTER COLUMN [CREATED_BY] NVARCHAR(50) NOT NULL;
IF OBJECT_ID('SM_CUSTOMER_POTENTIAL', 'U') IS NOT NULL ALTER TABLE [SM_CUSTOMER_POTENTIAL] ALTER COLUMN [CREATED_BY] NVARCHAR(50) NOT NULL;
IF OBJECT_ID('HR_EMPLOYEE_ACTIVITY', 'U') IS NOT NULL ALTER TABLE [HR_EMPLOYEE_ACTIVITY] ALTER COLUMN [CREATED_BY] NVARCHAR(50) NOT NULL;
IF OBJECT_ID('VND_VENDOR', 'U') IS NOT NULL ALTER TABLE [VND_VENDOR] ALTER COLUMN [CREATED_BY] NVARCHAR(50) NOT NULL;
IF OBJECT_ID('SM_SEGMENT', 'U') IS NOT NULL ALTER TABLE [SM_SEGMENT] ALTER COLUMN [CREATED_BY] NVARCHAR(50) NOT NULL;
IF OBJECT_ID('HR_EMPLOYEE_ASSET', 'U') IS NOT NULL ALTER TABLE [HR_EMPLOYEE_ASSET] ALTER COLUMN [CREATED_BY] NVARCHAR(50) NOT NULL;
IF OBJECT_ID('SM_SUB_SEGMENT', 'U') IS NOT NULL ALTER TABLE [SM_SUB_SEGMENT] ALTER COLUMN [CREATED_BY] NVARCHAR(50) NOT NULL;
IF OBJECT_ID('HR_EMPLOYEE_CONTACT', 'U') IS NOT NULL ALTER TABLE [HR_EMPLOYEE_CONTACT] ALTER COLUMN [CREATED_BY] NVARCHAR(50) NOT NULL;
IF OBJECT_ID('HR_EMPLOYEE_DEPENDENT', 'U') IS NOT NULL ALTER TABLE [HR_EMPLOYEE_DEPENDENT] ALTER COLUMN [CREATED_BY] NVARCHAR(50) NOT NULL;
IF OBJECT_ID('MASTER_COUNTRY', 'U') IS NOT NULL ALTER TABLE [MASTER_COUNTRY] ALTER COLUMN [CREATED_BY] NVARCHAR(50) NOT NULL;
IF OBJECT_ID('SM_CONTACT_MASTER', 'U') IS NOT NULL ALTER TABLE [SM_CONTACT_MASTER] ALTER COLUMN [CREATED_BY] NVARCHAR(50) NOT NULL;
IF OBJECT_ID('HR_EMPLOYEE_EDUCATION', 'U') IS NOT NULL ALTER TABLE [HR_EMPLOYEE_EDUCATION] ALTER COLUMN [CREATED_BY] NVARCHAR(50) NOT NULL;
IF OBJECT_ID('MASTER_STATE', 'U') IS NOT NULL ALTER TABLE [MASTER_STATE] ALTER COLUMN [CREATED_BY] NVARCHAR(50) NOT NULL;
IF OBJECT_ID('HR_EMPLOYEE_EMERGENCY_CONTACT', 'U') IS NOT NULL ALTER TABLE [HR_EMPLOYEE_EMERGENCY_CONTACT] ALTER COLUMN [CREATED_BY] NVARCHAR(50) NOT NULL;
IF OBJECT_ID('HR_EMPLOYEE_EXPERIENCE', 'U') IS NOT NULL ALTER TABLE [HR_EMPLOYEE_EXPERIENCE] ALTER COLUMN [CREATED_BY] NVARCHAR(50) NOT NULL;
IF OBJECT_ID('HR_EMPLOYEE_JOB_PROFILE', 'U') IS NOT NULL ALTER TABLE [HR_EMPLOYEE_JOB_PROFILE] ALTER COLUMN [CREATED_BY] NVARCHAR(50) NOT NULL;
IF OBJECT_ID('AD_DIVISION', 'U') IS NOT NULL ALTER TABLE [AD_DIVISION] ALTER COLUMN [CREATED_BY] NVARCHAR(50) NOT NULL;
IF OBJECT_ID('HR_EMPLOYEE_KYC', 'U') IS NOT NULL ALTER TABLE [HR_EMPLOYEE_KYC] ALTER COLUMN [CREATED_BY] NVARCHAR(50) NOT NULL;
IF OBJECT_ID('AD_AUDIT_TRAIL', 'U') IS NOT NULL ALTER TABLE [AD_AUDIT_TRAIL] ALTER COLUMN [CREATED_BY] NVARCHAR(50) NOT NULL;
IF OBJECT_ID('AD_PREFIX_CREDENTIALS', 'U') IS NOT NULL ALTER TABLE [AD_PREFIX_CREDENTIALS] ALTER COLUMN [CREATED_BY] NVARCHAR(50) NOT NULL;
IF OBJECT_ID('AD_USER_COMPANY_MAPPING', 'U') IS NOT NULL ALTER TABLE [AD_USER_COMPANY_MAPPING] ALTER COLUMN [CREATED_BY] NVARCHAR(50) NOT NULL;
IF OBJECT_ID('AD_USER_CREDENTIAL', 'U') IS NOT NULL ALTER TABLE [AD_USER_CREDENTIAL] ALTER COLUMN [CREATED_BY] NVARCHAR(50) NOT NULL;
IF OBJECT_ID('AD_USER_DIVISION_MAPPING', 'U') IS NOT NULL ALTER TABLE [AD_USER_DIVISION_MAPPING] ALTER COLUMN [CREATED_BY] NVARCHAR(50) NOT NULL;
IF OBJECT_ID('CH_ROOM', 'U') IS NOT NULL ALTER TABLE [CH_ROOM] ALTER COLUMN [CREATED_BY] NVARCHAR(50) NOT NULL;
IF OBJECT_ID('COMM_CHANNEL', 'U') IS NOT NULL ALTER TABLE [COMM_CHANNEL] ALTER COLUMN [CREATED_BY] NVARCHAR(50) NOT NULL;
IF OBJECT_ID('FILE_TRACEABILITY_MANAGEMENT', 'U') IS NOT NULL ALTER TABLE [FILE_TRACEABILITY_MANAGEMENT] ALTER COLUMN [CREATED_BY] NVARCHAR(50) NOT NULL;
IF OBJECT_ID('HR_EMPLOYEE_KYC_DOCUMENT', 'U') IS NOT NULL ALTER TABLE [HR_EMPLOYEE_KYC_DOCUMENT] ALTER COLUMN [CREATED_BY] NVARCHAR(50) NOT NULL;
IF OBJECT_ID('HR_EMPLOYEE_MASTER', 'U') IS NOT NULL ALTER TABLE [HR_EMPLOYEE_MASTER] ALTER COLUMN [CREATED_BY] NVARCHAR(50) NOT NULL;
IF OBJECT_ID('HR_EMPLOYEE_PASSPORT', 'U') IS NOT NULL ALTER TABLE [HR_EMPLOYEE_PASSPORT] ALTER COLUMN [CREATED_BY] NVARCHAR(50) NOT NULL;
IF OBJECT_ID('HR_EMPLOYEE_PERSONAL_DETAIL', 'U') IS NOT NULL ALTER TABLE [HR_EMPLOYEE_PERSONAL_DETAIL] ALTER COLUMN [CREATED_BY] NVARCHAR(50) NOT NULL;
IF OBJECT_ID('HR_EMPLOYEE_TYPE_MASTER', 'U') IS NOT NULL ALTER TABLE [HR_EMPLOYEE_TYPE_MASTER] ALTER COLUMN [CREATED_BY] NVARCHAR(50) NOT NULL;
IF OBJECT_ID('HR_GRADE_DETAIL', 'U') IS NOT NULL ALTER TABLE [HR_GRADE_DETAIL] ALTER COLUMN [CREATED_BY] NVARCHAR(50) NOT NULL;

-- 2. UPDATE invalid data to 'admin' dynamically for all tables containing CREATED_BY
DECLARE @SQL NVARCHAR(MAX) = '';

SELECT @SQL = @SQL + '
IF OBJECT_ID(''' + t.name + ''', ''U'') IS NOT NULL
BEGIN
    UPDATE [' + t.name + ']
    SET CREATED_BY = ''admin''
    WHERE CREATED_BY IS NOT NULL
    AND CREATED_BY NOT IN (
        SELECT USER_ID
        FROM AD_USER_CREDENTIAL
    );
END
'
FROM sys.tables t
INNER JOIN sys.columns c
    ON t.object_id = c.object_id
WHERE c.name = 'CREATED_BY';

EXEC sp_executesql @SQL;

-- 3. ADD FOREIGN KEY constraints
IF OBJECT_ID('AD_COMPANY_CREDENTIAL', 'U') IS NOT NULL AND NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = 'FK_AD_COMPANY_CREDENTIAL_CREATED_BY') BEGIN ALTER TABLE [AD_COMPANY_CREDENTIAL] ADD CONSTRAINT FK_AD_COMPANY_CREDENTIAL_CREATED_BY FOREIGN KEY (CREATED_BY) REFERENCES AD_USER_CREDENTIAL(USER_ID); END
IF OBJECT_ID('HR_EMPLOYEE_TYPE', 'U') IS NOT NULL AND NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = 'FK_HR_EMPLOYEE_TYPE_CREATED_BY') BEGIN ALTER TABLE [HR_EMPLOYEE_TYPE] ADD CONSTRAINT FK_HR_EMPLOYEE_TYPE_CREATED_BY FOREIGN KEY (CREATED_BY) REFERENCES AD_USER_CREDENTIAL(USER_ID); END
IF OBJECT_ID('HR_INDUCTION_ROUND', 'U') IS NOT NULL AND NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = 'FK_HR_INDUCTION_ROUND_CREATED_BY') BEGIN ALTER TABLE [HR_INDUCTION_ROUND] ADD CONSTRAINT FK_HR_INDUCTION_ROUND_CREATED_BY FOREIGN KEY (CREATED_BY) REFERENCES AD_USER_CREDENTIAL(USER_ID); END
IF OBJECT_ID('TICKET_TRACEABILITY_CENTER', 'U') IS NOT NULL AND NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = 'FK_TICKET_TRACEABILITY_CENTER_CREATED_BY') BEGIN ALTER TABLE [TICKET_TRACEABILITY_CENTER] ADD CONSTRAINT FK_TICKET_TRACEABILITY_CENTER_CREATED_BY FOREIGN KEY (CREATED_BY) REFERENCES AD_USER_CREDENTIAL(USER_ID); END
IF OBJECT_ID('HR_LEVEL', 'U') IS NOT NULL AND NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = 'FK_HR_LEVEL_CREATED_BY') BEGIN ALTER TABLE [HR_LEVEL] ADD CONSTRAINT FK_HR_LEVEL_CREATED_BY FOREIGN KEY (CREATED_BY) REFERENCES AD_USER_CREDENTIAL(USER_ID); END
IF OBJECT_ID('MST_COUNTRY', 'U') IS NOT NULL AND NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = 'FK_MST_COUNTRY_CREATED_BY') BEGIN ALTER TABLE [MST_COUNTRY] ADD CONSTRAINT FK_MST_COUNTRY_CREATED_BY FOREIGN KEY (CREATED_BY) REFERENCES AD_USER_CREDENTIAL(USER_ID); END
IF OBJECT_ID('HR_ORG_POSITION', 'U') IS NOT NULL AND NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = 'FK_HR_ORG_POSITION_CREATED_BY') BEGIN ALTER TABLE [HR_ORG_POSITION] ADD CONSTRAINT FK_HR_ORG_POSITION_CREATED_BY FOREIGN KEY (CREATED_BY) REFERENCES AD_USER_CREDENTIAL(USER_ID); END
IF OBJECT_ID('MST_DESPATCH_MODE', 'U') IS NOT NULL AND NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = 'FK_MST_DESPATCH_MODE_CREATED_BY') BEGIN ALTER TABLE [MST_DESPATCH_MODE] ADD CONSTRAINT FK_MST_DESPATCH_MODE_CREATED_BY FOREIGN KEY (CREATED_BY) REFERENCES AD_USER_CREDENTIAL(USER_ID); END
IF OBJECT_ID('SM_CUSTOMER_ADDRESS', 'U') IS NOT NULL AND NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = 'FK_SM_CUSTOMER_ADDRESS_CREATED_BY') BEGIN ALTER TABLE [SM_CUSTOMER_ADDRESS] ADD CONSTRAINT FK_SM_CUSTOMER_ADDRESS_CREATED_BY FOREIGN KEY (CREATED_BY) REFERENCES AD_USER_CREDENTIAL(USER_ID); END
IF OBJECT_ID('MST_FREIGHT', 'U') IS NOT NULL AND NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = 'FK_MST_FREIGHT_CREATED_BY') BEGIN ALTER TABLE [MST_FREIGHT] ADD CONSTRAINT FK_MST_FREIGHT_CREATED_BY FOREIGN KEY (CREATED_BY) REFERENCES AD_USER_CREDENTIAL(USER_ID); END
IF OBJECT_ID('MST_STATE', 'U') IS NOT NULL AND NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = 'FK_MST_STATE_CREATED_BY') BEGIN ALTER TABLE [MST_STATE] ADD CONSTRAINT FK_MST_STATE_CREATED_BY FOREIGN KEY (CREATED_BY) REFERENCES AD_USER_CREDENTIAL(USER_ID); END
IF OBJECT_ID('SM_SUPPLIER_MASTER', 'U') IS NOT NULL AND NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = 'FK_SM_SUPPLIER_MASTER_CREATED_BY') BEGIN ALTER TABLE [SM_SUPPLIER_MASTER] ADD CONSTRAINT FK_SM_SUPPLIER_MASTER_CREATED_BY FOREIGN KEY (CREATED_BY) REFERENCES AD_USER_CREDENTIAL(USER_ID); END
IF OBJECT_ID('MODE_OF_DESPATCH', 'U') IS NOT NULL AND NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = 'FK_MODE_OF_DESPATCH_CREATED_BY') BEGIN ALTER TABLE [MODE_OF_DESPATCH] ADD CONSTRAINT FK_MODE_OF_DESPATCH_CREATED_BY FOREIGN KEY (CREATED_BY) REFERENCES AD_USER_CREDENTIAL(USER_ID); END
IF OBJECT_ID('FREIGHT_MASTER', 'U') IS NOT NULL AND NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = 'FK_FREIGHT_MASTER_CREATED_BY') BEGIN ALTER TABLE [FREIGHT_MASTER] ADD CONSTRAINT FK_FREIGHT_MASTER_CREATED_BY FOREIGN KEY (CREATED_BY) REFERENCES AD_USER_CREDENTIAL(USER_ID); END
IF OBJECT_ID('SLS_CUSTOMER', 'U') IS NOT NULL AND NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = 'FK_SLS_CUSTOMER_CREATED_BY') BEGIN ALTER TABLE [SLS_CUSTOMER] ADD CONSTRAINT FK_SLS_CUSTOMER_CREATED_BY FOREIGN KEY (CREATED_BY) REFERENCES AD_USER_CREDENTIAL(USER_ID); END
IF OBJECT_ID('SM_CURRENCY', 'U') IS NOT NULL AND NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = 'FK_SM_CURRENCY_CREATED_BY') BEGIN ALTER TABLE [SM_CURRENCY] ADD CONSTRAINT FK_SM_CURRENCY_CREATED_BY FOREIGN KEY (CREATED_BY) REFERENCES AD_USER_CREDENTIAL(USER_ID); END
IF OBJECT_ID('EMPLOYEE_MANAGER_MAPPING', 'U') IS NOT NULL AND NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = 'FK_EMPLOYEE_MANAGER_MAPPING_CREATED_BY') BEGIN ALTER TABLE [EMPLOYEE_MANAGER_MAPPING] ADD CONSTRAINT FK_EMPLOYEE_MANAGER_MAPPING_CREATED_BY FOREIGN KEY (CREATED_BY) REFERENCES AD_USER_CREDENTIAL(USER_ID); END
IF OBJECT_ID('SLS_CUSTOMER_ADDRESS', 'U') IS NOT NULL AND NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = 'FK_SLS_CUSTOMER_ADDRESS_CREATED_BY') BEGIN ALTER TABLE [SLS_CUSTOMER_ADDRESS] ADD CONSTRAINT FK_SLS_CUSTOMER_ADDRESS_CREATED_BY FOREIGN KEY (CREATED_BY) REFERENCES AD_USER_CREDENTIAL(USER_ID); END
IF OBJECT_ID('SM_DELIVERY_TERMS', 'U') IS NOT NULL AND NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = 'FK_SM_DELIVERY_TERMS_CREATED_BY') BEGIN ALTER TABLE [SM_DELIVERY_TERMS] ADD CONSTRAINT FK_SM_DELIVERY_TERMS_CREATED_BY FOREIGN KEY (CREATED_BY) REFERENCES AD_USER_CREDENTIAL(USER_ID); END
IF OBJECT_ID('SLS_CUSTOMER_POTENTIAL', 'U') IS NOT NULL AND NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = 'FK_SLS_CUSTOMER_POTENTIAL_CREATED_BY') BEGIN ALTER TABLE [SLS_CUSTOMER_POTENTIAL] ADD CONSTRAINT FK_SLS_CUSTOMER_POTENTIAL_CREATED_BY FOREIGN KEY (CREATED_BY) REFERENCES AD_USER_CREDENTIAL(USER_ID); END
IF OBJECT_ID('HR_DEPARTMENT_MASTER', 'U') IS NOT NULL AND NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = 'FK_HR_DEPARTMENT_MASTER_CREATED_BY') BEGIN ALTER TABLE [HR_DEPARTMENT_MASTER] ADD CONSTRAINT FK_HR_DEPARTMENT_MASTER_CREATED_BY FOREIGN KEY (CREATED_BY) REFERENCES AD_USER_CREDENTIAL(USER_ID); END
IF OBJECT_ID('SM_PAYMENT_TERMS', 'U') IS NOT NULL AND NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = 'FK_SM_PAYMENT_TERMS_CREATED_BY') BEGIN ALTER TABLE [SM_PAYMENT_TERMS] ADD CONSTRAINT FK_SM_PAYMENT_TERMS_CREATED_BY FOREIGN KEY (CREATED_BY) REFERENCES AD_USER_CREDENTIAL(USER_ID); END
IF OBJECT_ID('HR_DESIGNATION_LEVEL', 'U') IS NOT NULL AND NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = 'FK_HR_DESIGNATION_LEVEL_CREATED_BY') BEGIN ALTER TABLE [HR_DESIGNATION_LEVEL] ADD CONSTRAINT FK_HR_DESIGNATION_LEVEL_CREATED_BY FOREIGN KEY (CREATED_BY) REFERENCES AD_USER_CREDENTIAL(USER_ID); END
IF OBJECT_ID('SM_TYPE_OF_SERVICE', 'U') IS NOT NULL AND NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = 'FK_SM_TYPE_OF_SERVICE_CREATED_BY') BEGIN ALTER TABLE [SM_TYPE_OF_SERVICE] ADD CONSTRAINT FK_SM_TYPE_OF_SERVICE_CREATED_BY FOREIGN KEY (CREATED_BY) REFERENCES AD_USER_CREDENTIAL(USER_ID); END
IF OBJECT_ID('HR_DESIGNATION_MASTER', 'U') IS NOT NULL AND NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = 'FK_HR_DESIGNATION_MASTER_CREATED_BY') BEGIN ALTER TABLE [HR_DESIGNATION_MASTER] ADD CONSTRAINT FK_HR_DESIGNATION_MASTER_CREATED_BY FOREIGN KEY (CREATED_BY) REFERENCES AD_USER_CREDENTIAL(USER_ID); END
IF OBJECT_ID('SM_CUSTOMER_POTENTIAL', 'U') IS NOT NULL AND NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = 'FK_SM_CUSTOMER_POTENTIAL_CREATED_BY') BEGIN ALTER TABLE [SM_CUSTOMER_POTENTIAL] ADD CONSTRAINT FK_SM_CUSTOMER_POTENTIAL_CREATED_BY FOREIGN KEY (CREATED_BY) REFERENCES AD_USER_CREDENTIAL(USER_ID); END
IF OBJECT_ID('HR_EMPLOYEE_ACTIVITY', 'U') IS NOT NULL AND NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = 'FK_HR_EMPLOYEE_ACTIVITY_CREATED_BY') BEGIN ALTER TABLE [HR_EMPLOYEE_ACTIVITY] ADD CONSTRAINT FK_HR_EMPLOYEE_ACTIVITY_CREATED_BY FOREIGN KEY (CREATED_BY) REFERENCES AD_USER_CREDENTIAL(USER_ID); END
IF OBJECT_ID('VND_VENDOR', 'U') IS NOT NULL AND NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = 'FK_VND_VENDOR_CREATED_BY') BEGIN ALTER TABLE [VND_VENDOR] ADD CONSTRAINT FK_VND_VENDOR_CREATED_BY FOREIGN KEY (CREATED_BY) REFERENCES AD_USER_CREDENTIAL(USER_ID); END
IF OBJECT_ID('SM_SEGMENT', 'U') IS NOT NULL AND NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = 'FK_SM_SEGMENT_CREATED_BY') BEGIN ALTER TABLE [SM_SEGMENT] ADD CONSTRAINT FK_SM_SEGMENT_CREATED_BY FOREIGN KEY (CREATED_BY) REFERENCES AD_USER_CREDENTIAL(USER_ID); END
IF OBJECT_ID('HR_EMPLOYEE_ASSET', 'U') IS NOT NULL AND NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = 'FK_HR_EMPLOYEE_ASSET_CREATED_BY') BEGIN ALTER TABLE [HR_EMPLOYEE_ASSET] ADD CONSTRAINT FK_HR_EMPLOYEE_ASSET_CREATED_BY FOREIGN KEY (CREATED_BY) REFERENCES AD_USER_CREDENTIAL(USER_ID); END
IF OBJECT_ID('SM_SUB_SEGMENT', 'U') IS NOT NULL AND NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = 'FK_SM_SUB_SEGMENT_CREATED_BY') BEGIN ALTER TABLE [SM_SUB_SEGMENT] ADD CONSTRAINT FK_SM_SUB_SEGMENT_CREATED_BY FOREIGN KEY (CREATED_BY) REFERENCES AD_USER_CREDENTIAL(USER_ID); END
IF OBJECT_ID('HR_EMPLOYEE_CONTACT', 'U') IS NOT NULL AND NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = 'FK_HR_EMPLOYEE_CONTACT_CREATED_BY') BEGIN ALTER TABLE [HR_EMPLOYEE_CONTACT] ADD CONSTRAINT FK_HR_EMPLOYEE_CONTACT_CREATED_BY FOREIGN KEY (CREATED_BY) REFERENCES AD_USER_CREDENTIAL(USER_ID); END
IF OBJECT_ID('HR_EMPLOYEE_DEPENDENT', 'U') IS NOT NULL AND NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = 'FK_HR_EMPLOYEE_DEPENDENT_CREATED_BY') BEGIN ALTER TABLE [HR_EMPLOYEE_DEPENDENT] ADD CONSTRAINT FK_HR_EMPLOYEE_DEPENDENT_CREATED_BY FOREIGN KEY (CREATED_BY) REFERENCES AD_USER_CREDENTIAL(USER_ID); END
IF OBJECT_ID('MASTER_COUNTRY', 'U') IS NOT NULL AND NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = 'FK_MASTER_COUNTRY_CREATED_BY') BEGIN ALTER TABLE [MASTER_COUNTRY] ADD CONSTRAINT FK_MASTER_COUNTRY_CREATED_BY FOREIGN KEY (CREATED_BY) REFERENCES AD_USER_CREDENTIAL(USER_ID); END
IF OBJECT_ID('SM_CONTACT_MASTER', 'U') IS NOT NULL AND NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = 'FK_SM_CONTACT_MASTER_CREATED_BY') BEGIN ALTER TABLE [SM_CONTACT_MASTER] ADD CONSTRAINT FK_SM_CONTACT_MASTER_CREATED_BY FOREIGN KEY (CREATED_BY) REFERENCES AD_USER_CREDENTIAL(USER_ID); END
IF OBJECT_ID('HR_EMPLOYEE_EDUCATION', 'U') IS NOT NULL AND NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = 'FK_HR_EMPLOYEE_EDUCATION_CREATED_BY') BEGIN ALTER TABLE [HR_EMPLOYEE_EDUCATION] ADD CONSTRAINT FK_HR_EMPLOYEE_EDUCATION_CREATED_BY FOREIGN KEY (CREATED_BY) REFERENCES AD_USER_CREDENTIAL(USER_ID); END
IF OBJECT_ID('MASTER_STATE', 'U') IS NOT NULL AND NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = 'FK_MASTER_STATE_CREATED_BY') BEGIN ALTER TABLE [MASTER_STATE] ADD CONSTRAINT FK_MASTER_STATE_CREATED_BY FOREIGN KEY (CREATED_BY) REFERENCES AD_USER_CREDENTIAL(USER_ID); END
IF OBJECT_ID('HR_EMPLOYEE_EMERGENCY_CONTACT', 'U') IS NOT NULL AND NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = 'FK_HR_EMPLOYEE_EMERGENCY_CONTACT_CREATED_BY') BEGIN ALTER TABLE [HR_EMPLOYEE_EMERGENCY_CONTACT] ADD CONSTRAINT FK_HR_EMPLOYEE_EMERGENCY_CONTACT_CREATED_BY FOREIGN KEY (CREATED_BY) REFERENCES AD_USER_CREDENTIAL(USER_ID); END
IF OBJECT_ID('HR_EMPLOYEE_EXPERIENCE', 'U') IS NOT NULL AND NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = 'FK_HR_EMPLOYEE_EXPERIENCE_CREATED_BY') BEGIN ALTER TABLE [HR_EMPLOYEE_EXPERIENCE] ADD CONSTRAINT FK_HR_EMPLOYEE_EXPERIENCE_CREATED_BY FOREIGN KEY (CREATED_BY) REFERENCES AD_USER_CREDENTIAL(USER_ID); END
IF OBJECT_ID('HR_EMPLOYEE_JOB_PROFILE', 'U') IS NOT NULL AND NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = 'FK_HR_EMPLOYEE_JOB_PROFILE_CREATED_BY') BEGIN ALTER TABLE [HR_EMPLOYEE_JOB_PROFILE] ADD CONSTRAINT FK_HR_EMPLOYEE_JOB_PROFILE_CREATED_BY FOREIGN KEY (CREATED_BY) REFERENCES AD_USER_CREDENTIAL(USER_ID); END
IF OBJECT_ID('AD_DIVISION', 'U') IS NOT NULL AND NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = 'FK_AD_DIVISION_CREATED_BY') BEGIN ALTER TABLE [AD_DIVISION] ADD CONSTRAINT FK_AD_DIVISION_CREATED_BY FOREIGN KEY (CREATED_BY) REFERENCES AD_USER_CREDENTIAL(USER_ID); END
IF OBJECT_ID('HR_EMPLOYEE_KYC', 'U') IS NOT NULL AND NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = 'FK_HR_EMPLOYEE_KYC_CREATED_BY') BEGIN ALTER TABLE [HR_EMPLOYEE_KYC] ADD CONSTRAINT FK_HR_EMPLOYEE_KYC_CREATED_BY FOREIGN KEY (CREATED_BY) REFERENCES AD_USER_CREDENTIAL(USER_ID); END
IF OBJECT_ID('CH_ROOM', 'U') IS NOT NULL AND NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = 'FK_CH_ROOM_CREATED_BY') BEGIN ALTER TABLE [CH_ROOM] ADD CONSTRAINT FK_CH_ROOM_CREATED_BY FOREIGN KEY (CREATED_BY) REFERENCES AD_USER_CREDENTIAL(USER_ID); END
IF OBJECT_ID('COMM_CHANNEL', 'U') IS NOT NULL AND NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = 'FK_COMM_CHANNEL_CREATED_BY') BEGIN ALTER TABLE [COMM_CHANNEL] ADD CONSTRAINT FK_COMM_CHANNEL_CREATED_BY FOREIGN KEY (CREATED_BY) REFERENCES AD_USER_CREDENTIAL(USER_ID); END
IF OBJECT_ID('HR_EMPLOYEE_KYC_DOCUMENT', 'U') IS NOT NULL AND NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = 'FK_HR_EMPLOYEE_KYC_DOCUMENT_CREATED_BY') BEGIN ALTER TABLE [HR_EMPLOYEE_KYC_DOCUMENT] ADD CONSTRAINT FK_HR_EMPLOYEE_KYC_DOCUMENT_CREATED_BY FOREIGN KEY (CREATED_BY) REFERENCES AD_USER_CREDENTIAL(USER_ID); END
IF OBJECT_ID('HR_EMPLOYEE_MASTER', 'U') IS NOT NULL AND NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = 'FK_HR_EMPLOYEE_MASTER_CREATED_BY') BEGIN ALTER TABLE [HR_EMPLOYEE_MASTER] ADD CONSTRAINT FK_HR_EMPLOYEE_MASTER_CREATED_BY FOREIGN KEY (CREATED_BY) REFERENCES AD_USER_CREDENTIAL(USER_ID); END
IF OBJECT_ID('HR_EMPLOYEE_PASSPORT', 'U') IS NOT NULL AND NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = 'FK_HR_EMPLOYEE_PASSPORT_CREATED_BY') BEGIN ALTER TABLE [HR_EMPLOYEE_PASSPORT] ADD CONSTRAINT FK_HR_EMPLOYEE_PASSPORT_CREATED_BY FOREIGN KEY (CREATED_BY) REFERENCES AD_USER_CREDENTIAL(USER_ID); END
IF OBJECT_ID('HR_EMPLOYEE_PERSONAL_DETAIL', 'U') IS NOT NULL AND NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = 'FK_HR_EMPLOYEE_PERSONAL_DETAIL_CREATED_BY') BEGIN ALTER TABLE [HR_EMPLOYEE_PERSONAL_DETAIL] ADD CONSTRAINT FK_HR_EMPLOYEE_PERSONAL_DETAIL_CREATED_BY FOREIGN KEY (CREATED_BY) REFERENCES AD_USER_CREDENTIAL(USER_ID); END
IF OBJECT_ID('HR_EMPLOYEE_TYPE_MASTER', 'U') IS NOT NULL AND NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = 'FK_HR_EMPLOYEE_TYPE_MASTER_CREATED_BY') BEGIN ALTER TABLE [HR_EMPLOYEE_TYPE_MASTER] ADD CONSTRAINT FK_HR_EMPLOYEE_TYPE_MASTER_CREATED_BY FOREIGN KEY (CREATED_BY) REFERENCES AD_USER_CREDENTIAL(USER_ID); END
IF OBJECT_ID('HR_GRADE_DETAIL', 'U') IS NOT NULL AND NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = 'FK_HR_GRADE_DETAIL_CREATED_BY') BEGIN ALTER TABLE [HR_GRADE_DETAIL] ADD CONSTRAINT FK_HR_GRADE_DETAIL_CREATED_BY FOREIGN KEY (CREATED_BY) REFERENCES AD_USER_CREDENTIAL(USER_ID); END
IF OBJECT_ID('FILE_TRACEABILITY_MANAGEMENT', 'U') IS NOT NULL AND NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = 'FK_FILE_TRACEABILITY_MANAGEMENT_CREATED_BY') BEGIN ALTER TABLE [FILE_TRACEABILITY_MANAGEMENT] ADD CONSTRAINT FK_FILE_TRACEABILITY_MANAGEMENT_CREATED_BY FOREIGN KEY (CREATED_BY) REFERENCES AD_USER_CREDENTIAL(USER_ID); END
IF OBJECT_ID('AD_PREFIX_CREDENTIALS', 'U') IS NOT NULL AND NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = 'FK_AD_PREFIX_CREDENTIALS_CREATED_BY') BEGIN ALTER TABLE [AD_PREFIX_CREDENTIALS] ADD CONSTRAINT FK_AD_PREFIX_CREDENTIALS_CREATED_BY FOREIGN KEY (CREATED_BY) REFERENCES AD_USER_CREDENTIAL(USER_ID); END
IF OBJECT_ID('AD_USER_COMPANY_MAPPING', 'U') IS NOT NULL AND NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = 'FK_AD_USER_COMPANY_MAPPING_CREATED_BY') BEGIN ALTER TABLE [AD_USER_COMPANY_MAPPING] ADD CONSTRAINT FK_AD_USER_COMPANY_MAPPING_CREATED_BY FOREIGN KEY (CREATED_BY) REFERENCES AD_USER_CREDENTIAL(USER_ID); END
IF OBJECT_ID('AD_USER_DIVISION_MAPPING', 'U') IS NOT NULL AND NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = 'FK_AD_USER_DIVISION_MAPPING_CREATED_BY') BEGIN ALTER TABLE [AD_USER_DIVISION_MAPPING] ADD CONSTRAINT FK_AD_USER_DIVISION_MAPPING_CREATED_BY FOREIGN KEY (CREATED_BY) REFERENCES AD_USER_CREDENTIAL(USER_ID); END
IF OBJECT_ID('AD_AUDIT_TRAIL', 'U') IS NOT NULL AND NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = 'FK_AD_AUDIT_TRAIL_CREATED_BY') BEGIN ALTER TABLE [AD_AUDIT_TRAIL] ADD CONSTRAINT FK_AD_AUDIT_TRAIL_CREATED_BY FOREIGN KEY (CREATED_BY) REFERENCES AD_USER_CREDENTIAL(USER_ID); END
