IF OBJECT_ID('HR_EMPLOYEE', 'U') IS NOT NULL
BEGIN
    DELETE FROM QMS_MEETING_SCHEDULE WHERE host_by_id IS NOT NULL AND host_by_id NOT IN (SELECT id FROM HR_EMPLOYEE);
END
ELSE IF OBJECT_ID('HR_EMPLOYEE_MASTER', 'U') IS NOT NULL
BEGIN
    DELETE FROM QMS_MEETING_SCHEDULE WHERE host_by_id IS NOT NULL AND host_by_id NOT IN (SELECT id FROM HR_EMPLOYEE_MASTER);
END
ELSE IF OBJECT_ID('hrm_employee_master', 'U') IS NOT NULL
BEGIN
    DELETE FROM QMS_MEETING_SCHEDULE WHERE host_by_id IS NOT NULL AND host_by_id NOT IN (SELECT id FROM hrm_employee_master);
END
GO
