-- 20260527_V55.0__Convert_Checklist_Assignment_Text_To_Nvarchar.sql
-- Convert TEXT/NTEXT columns to NVARCHAR(MAX) in QMS_CHECKLIST_ASSIGNMENT and QMS_CHECKLIST_MASTER tables to allow comparison and sorting in distinct queries.

-- 1. QMS_CHECKLIST_ASSIGNMENT table
IF EXISTS (SELECT 1 FROM sys.columns WHERE object_id = OBJECT_ID(N'[dbo].[QMS_CHECKLIST_ASSIGNMENT]') AND name = 'REMARKS')
BEGIN
    ALTER TABLE [dbo].[QMS_CHECKLIST_ASSIGNMENT] ALTER COLUMN [REMARKS] NVARCHAR(MAX);
END

IF EXISTS (SELECT 1 FROM sys.columns WHERE object_id = OBJECT_ID(N'[dbo].[QMS_CHECKLIST_ASSIGNMENT]') AND name = 'COMMENTS')
BEGIN
    ALTER TABLE [dbo].[QMS_CHECKLIST_ASSIGNMENT] ALTER COLUMN [COMMENTS] NVARCHAR(MAX);
END

IF EXISTS (SELECT 1 FROM sys.columns WHERE object_id = OBJECT_ID(N'[dbo].[QMS_CHECKLIST_ASSIGNMENT]') AND name = 'FILE_PATHS')
BEGIN
    ALTER TABLE [dbo].[QMS_CHECKLIST_ASSIGNMENT] ALTER COLUMN [FILE_PATHS] NVARCHAR(MAX);
END

-- 2. QMS_CHECKLIST_MASTER table
IF EXISTS (SELECT 1 FROM sys.columns WHERE object_id = OBJECT_ID(N'[dbo].[QMS_CHECKLIST_MASTER]') AND name = 'DESCRIPTION')
BEGIN
    ALTER TABLE [dbo].[QMS_CHECKLIST_MASTER] ALTER COLUMN [DESCRIPTION] NVARCHAR(MAX);
END

IF EXISTS (SELECT 1 FROM sys.columns WHERE object_id = OBJECT_ID(N'[dbo].[QMS_CHECKLIST_MASTER]') AND name = 'AMENDMENT_REASON')
BEGIN
    ALTER TABLE [dbo].[QMS_CHECKLIST_MASTER] ALTER COLUMN [AMENDMENT_REASON] NVARCHAR(MAX);
END

IF EXISTS (SELECT 1 FROM sys.columns WHERE object_id = OBJECT_ID(N'[dbo].[QMS_CHECKLIST_MASTER]') AND name = 'UPLOADED_FILES')
BEGIN
    ALTER TABLE [dbo].[QMS_CHECKLIST_MASTER] ALTER COLUMN [UPLOADED_FILES] NVARCHAR(MAX);
END

IF EXISTS (SELECT 1 FROM sys.columns WHERE object_id = OBJECT_ID(N'[dbo].[QMS_CHECKLIST_MASTER]') AND name = 'SCANNED_FILES')
BEGIN
    ALTER TABLE [dbo].[QMS_CHECKLIST_MASTER] ALTER COLUMN [SCANNED_FILES] NVARCHAR(MAX);
END
GO
