-- Add Idle tracking columns to User Session Activity
IF OBJECT_ID('AD_USER_SESSION_ACTIVITY', 'U') IS NOT NULL
BEGIN
    IF NOT EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID(N'[dbo].[AD_USER_SESSION_ACTIVITY]') AND name = 'IS_IDLE')
    BEGIN
        ALTER TABLE AD_USER_SESSION_ACTIVITY ADD IS_IDLE BIT DEFAULT 0;
    END

    IF NOT EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID(N'[dbo].[AD_USER_SESSION_ACTIVITY]') AND name = 'IDLE_TIME_MS')
    BEGIN
        ALTER TABLE AD_USER_SESSION_ACTIVITY ADD IDLE_TIME_MS BIGINT DEFAULT 0;
    END
END
