-- Add Task Verifier fields to HR_EMPLOYEE_MASTER table
IF NOT EXISTS (
    SELECT * FROM sys.columns 
    WHERE object_id = OBJECT_ID(N'[dbo].[HR_EMPLOYEE_MASTER]') 
      AND name = 'IS_TASK_VERIFIER'
)
BEGIN
    ALTER TABLE HR_EMPLOYEE_MASTER ADD IS_TASK_VERIFIER VARCHAR(10) DEFAULT 'NO';
    ALTER TABLE HR_EMPLOYEE_MASTER ADD TASK_VERIFIER_TYPE VARCHAR(255);
    ALTER TABLE HR_EMPLOYEE_MASTER ADD TASK_VERIFIER_FILE_INFO NVARCHAR(MAX);
END
ELSE IF OBJECT_ID(N'[dbo].[HR_EMPLOYEE_MASTER]', 'U') IS NOT NULL
BEGIN
    IF NOT EXISTS (
        SELECT * FROM sys.columns 
        WHERE object_id = OBJECT_ID(N'[dbo].[HR_EMPLOYEE_MASTER]') 
          AND name = 'IS_TASK_VERIFIER'
    )
    BEGIN
        ALTER TABLE HR_EMPLOYEE_MASTER ADD IS_TASK_VERIFIER VARCHAR(10) DEFAULT 'NO';
        ALTER TABLE HR_EMPLOYEE_MASTER ADD TASK_VERIFIER_TYPE VARCHAR(255);
        ALTER TABLE HR_EMPLOYEE_MASTER ADD TASK_VERIFIER_FILE_INFO NVARCHAR(MAX);
    END
END

