-- Seed QMS Audit Types
-- Compatible with both H2 and SQL Server database engines
-- Ensures duplicate records are not inserted

INSERT INTO QMS_AUDIT_TYPE (audit_type, status, criteria_type, criteria_min_count, created_user, created_date)
SELECT val.audit_type, 'ACTIVE', 'Fixed', 1, '1001', CURRENT_TIMESTAMP
FROM (
    SELECT '5S - BLUE ZONE' AS audit_type UNION ALL
    SELECT '5S - GREEN ZONE' UNION ALL
    SELECT '5S - VIOLET ZONE' UNION ALL
    SELECT '5S - YELLOW ZONE' UNION ALL
    SELECT 'CUSTOMER AUDIT' UNION ALL
    SELECT 'ERP SCREEN AUDIT' UNION ALL
    SELECT 'ISO /RECERTIFICATION/SURVEILLANCE AUDIT' UNION ALL
    SELECT 'ISO 14001 (EMS)' UNION ALL
    SELECT 'ISO 45001(OHSMS/SAFETY)' UNION ALL
    SELECT 'ISO 9001(QMS)' UNION ALL
    SELECT 'ISO CERTIFICATION/RECERTIFICATION/SURVEILLANCE AUDIT' UNION ALL
    SELECT 'PROCESS AUDIT' UNION ALL
    SELECT 'PRODUCT AUDIT' UNION ALL
    SELECT 'RECORD ROOM AUDIT' UNION ALL
    SELECT 'STOCK AUDIT (LOCATION)' UNION ALL
    SELECT 'STOCK AUDIT (QTY)' UNION ALL
    SELECT 'SUBCONTRACTOR AUDIT' UNION ALL
    SELECT 'SUPPLIER ASSESSMENT AUDIT' UNION ALL
    SELECT 'SUPPLIER AUDIT' UNION ALL
    SELECT 'SURPRISE AUDITS'
) AS val
WHERE NOT EXISTS (
    SELECT 1 FROM QMS_AUDIT_TYPE WHERE UPPER(audit_type) = UPPER(val.audit_type)
);
