-- ============================================================
-- V39.0 ATS / Induction Database Governance & Standardization (Email, Interview, Verification)
-- ============================================================

-- STEP 1: Rename tables to UPPERCASE standard format with module prefix
ALTER TABLE hr_email_content RENAME TO IND_EMAIL_CONTENT;
ALTER TABLE hr_interview_master RENAME TO IND_INTERVIEW_MASTER;
ALTER TABLE hr_verification_criteria RENAME TO IND_VERIFICATION_CRITERIA;
GO

-- STEP 2: Standardize audit column names (rename created_at/updated_at -> CREATED_DATE/UPDATED_DATE, and created_by/updated_by -> CREATED_USER/UPDATED_USER)
ALTER TABLE IND_EMAIL_CONTENT RENAME COLUMN created_at TO CREATED_DATE;
ALTER TABLE IND_EMAIL_CONTENT RENAME COLUMN updated_at TO UPDATED_DATE;
ALTER TABLE IND_EMAIL_CONTENT RENAME COLUMN created_by TO CREATED_USER;
ALTER TABLE IND_EMAIL_CONTENT RENAME COLUMN updated_by TO UPDATED_USER;

ALTER TABLE IND_INTERVIEW_MASTER RENAME COLUMN created_at TO CREATED_DATE;
ALTER TABLE IND_INTERVIEW_MASTER RENAME COLUMN updated_at TO UPDATED_DATE;
ALTER TABLE IND_INTERVIEW_MASTER RENAME COLUMN created_by TO CREATED_USER;
ALTER TABLE IND_INTERVIEW_MASTER RENAME COLUMN updated_by TO UPDATED_USER;

ALTER TABLE IND_VERIFICATION_CRITERIA RENAME COLUMN created_at TO CREATED_DATE;
ALTER TABLE IND_VERIFICATION_CRITERIA RENAME COLUMN updated_at TO UPDATED_DATE;
ALTER TABLE IND_VERIFICATION_CRITERIA RENAME COLUMN created_by TO CREATED_USER;
ALTER TABLE IND_VERIFICATION_CRITERIA RENAME COLUMN updated_by TO UPDATED_USER;
GO
