-- V9.1: Create QMS_CHECKLIST_ASSIGNMENT_FILES table for storing actual files linked to assignments
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'QMS_CHECKLIST_ASSIGNMENT_FILES')
BEGIN
    CREATE TABLE QMS_CHECKLIST_ASSIGNMENT_FILES (
        ASSIGNMENT_ID BIGINT NOT NULL,
        FILE_PATH NVARCHAR(MAX),
        FOREIGN KEY (ASSIGNMENT_ID) REFERENCES qms_checklist_assignment(id) ON DELETE CASCADE
    );
END
