USE [AUTONOMA];
GO

CREATE TABLE [dbo].[HR_ORG_POSITION](
    [id] [bigint] IDENTITY(1,1) NOT NULL,
    [POSITION_TITLE] [varchar](100) NOT NULL,
    [DEPARTMENT_ID] [bigint] NULL,
    [PARENT_POSITION_ID] [bigint] NULL,
    [ASSIGNED_EMPLOYEE_ID] [bigint] NULL,
    [STATUS] [varchar](20) NULL DEFAULT 'Active',
    [CREATED_BY] [varchar](100) NULL,
    [CREATED_DATE] [datetime] NULL,
    [UPDATED_BY] [varchar](100) NULL,
    [UPDATED_DATE] [datetime] NULL,
 CONSTRAINT [PK_HR_ORG_POSITION] PRIMARY KEY CLUSTERED 
(
    [id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
