-- ==========================================
-- Customer & Vendor Master Database Backup
-- Target Database: AUTONOMA
-- Generation Date: 2026-05-26
-- ==========================================

-- ------------------------------------------
-- 1. DATA FOR TABLE: sm_customer_master
-- ------------------------------------------
PRINT 'Inserting data into sm_customer_master...';

SET IDENTITY_INSERT sm_customer_master ON;

INSERT INTO sm_customer_master (
    id, 
    customer_code, 
    customer_name, 
    customer_print_name, 
    accounts_ledger, 
    group_name, 
    invoice_name, 
    short_name, 
    segment, 
    sub_segment, 
    domain_name, 
    address, 
    pincode, 
    city, 
    state, 
    state_code, 
    country, 
    prime_customer, 
    pan_no, 
    pan_file_info, 
    website, 
    register_no, 
    cin_no, 
    distance, 
    gstin, 
    vendor_code, 
    iso_number, 
    iso_expiry, 
    nda_required, 
    dispatch_mode, 
    currency, 
    payment_terms, 
    delivery_terms, 
    freight, 
    negotiate_customer, 
    daily_dispatch_mail, 
    file_upload, 
    location, 
    ld_applicable, 
    status, 
    created_by, 
    created_at, 
    updated_by, 
    updated_at
) VALUES 
(
    1, 
    'CUST001', 
    'TechSprint Solutions', 
    NULL, 
    NULL, 
    NULL, 
    'TechSprint Solutions Pvt Ltd', 
    'TechSprint', 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    'Chennai', 
    'Tamil Nadu', 
    NULL, 
    'India', 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    '33AABCT1234A1Z1', 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    'Active', 
    'Admin', 
    '2026-05-24T22:10:43.990', 
    NULL, 
    NULL
),
(
    2, 
    'CUST002', 
    'Global Wind Systems', 
    NULL, 
    NULL, 
    NULL, 
    'Global Wind Systems LLC', 
    'GlobalWind', 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    'Bangalore', 
    'Karnataka', 
    NULL, 
    'India', 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    '29AABCG5678B1Z2', 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    'Active', 
    'Admin', 
    '2026-05-24T22:10:44.030', 
    NULL, 
    NULL
),
(
    3, 
    'CUST003', 
    'Nutech Energy', 
    NULL, 
    NULL, 
    NULL, 
    'Nutech Energy Corp', 
    'Nutech', 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    'Pune', 
    'Maharashtra', 
    NULL, 
    'India', 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    '27AABCH9012C1Z3', 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    'Active', 
    'Admin', 
    '2026-05-24T22:10:44.043', 
    NULL, 
    NULL
);

SET IDENTITY_INSERT sm_customer_master OFF;

PRINT 'sm_customer_master import completed.';
GO


-- ------------------------------------------
-- 2. DATA FOR TABLE: sm_supplier_master
-- ------------------------------------------
PRINT 'Inserting data into sm_supplier_master...';

SET IDENTITY_INSERT sm_supplier_master ON;

INSERT INTO sm_supplier_master (
    id, 
    supplier_code, 
    GST_NO, 
    supplier_name, 
    ledger_name, 
    short_name, 
    supplier_print_name, 
    address, 
    city, 
    state, 
    country, 
    pincode, 
    mobile_no, 
    contact_person, 
    email_id, 
    website, 
    pan_no, 
    pan_file_info, 
    msme_no, 
    msme_file_info, 
    iso_no, 
    iso_file_info, 
    iso_expiry_date, 
    approved_supplier, 
    nda_required, 
    delivery_terms, 
    type_of_service, 
    payment_terms, 
    prime_supplier, 
    freight_required, 
    currency, 
    due_days, 
    is_auditor_consultant, 
    account_no, 
    account_name, 
    bank_name, 
    branch_name, 
    ifsc_code, 
    swift_code, 
    account_type, 
    status, 
    upload_files, 
    created_by, 
    created_at, 
    updated_by, 
    updated_at
) VALUES 
(
    1, 
    'S-26-00001', 
    '', 
    'fdhdhfhg', 
    '', 
    '', 
    '', 
    'VG nagar', 
    'karaikal', 
    'pondicherry', 
    'India', 
    '609602', 
    '06380184656', 
    'Balamurugan B', 
    'balamurugankkl2905@gmail.com', 
    '', 
    '', 
    '', 
    '', 
    '', 
    '', 
    '', 
    '', 
    'No', 
    'No', 
    '', 
    '', 
    '', 
    'No', 
    'No', 
    '', 
    '', 
    'No', 
    '', 
    '', 
    '', 
    '', 
    '', 
    '', 
    '', 
    'Active', 
    '', 
    '', 
    '2026-05-26T22:38:53.753', 
    '', 
    NULL
);

SET IDENTITY_INSERT sm_supplier_master OFF;

PRINT 'sm_supplier_master import completed.';
GO
