services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: erp-db
    user: root
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=SKP@pravin2583
    ports:
      - "1433:1433"
    platform: linux/amd64

  backend:
    build: ./Autonoma_Backend
    container_name: erp-backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:sqlserver://db:1433;databaseName=AUTONOMA;trustServerCertificate=true
      - SPRING_DATASOURCE_USERNAME=sa
      - SPRING_DATASOURCE_PASSWORD=SKP@pravin2583
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    depends_on:
      - db

  frontend:
    build: ./Autonoma_ERP
    container_name: erp-frontend
    ports:
      - "3000:3000"
    environment:
      - VITE_APP_API_URL=http://localhost:8080/
    depends_on:
      - backend
