-- Safe casing/naming update for HR_DESIGNATION table
-- Version: V20260601__fix_designation_columns.sql

IF COL_LENGTH('HR_DESIGNATION', 'created_at') IS NOT NULL AND COL_LENGTH('HR_DESIGNATION', 'CREATED_DATE') IS NULL
BEGIN
    EXEC sp_rename 'HR_DESIGNATION.created_at', 'CREATED_DATE', 'COLUMN';
END
GO

IF COL_LENGTH('HR_DESIGNATION', 'updated_at') IS NOT NULL AND COL_LENGTH('HR_DESIGNATION', 'UPDATED_DATE') IS NULL
BEGIN
    EXEC sp_rename 'HR_DESIGNATION.updated_at', 'UPDATED_DATE', 'COLUMN';
END
GO

IF COL_LENGTH('HR_DESIGNATION', 'is_active') IS NOT NULL AND COL_LENGTH('HR_DESIGNATION', 'IS_ACTIVE') IS NULL
BEGIN
    EXEC sp_rename 'HR_DESIGNATION.is_active', 'IS_ACTIVE', 'COLUMN';
END
GO

IF COL_LENGTH('HR_DESIGNATION', 'org_sequence_no') IS NOT NULL AND COL_LENGTH('HR_DESIGNATION', 'ORG_SEQUENCE_NO') IS NULL
BEGIN
    EXEC sp_rename 'HR_DESIGNATION.org_sequence_no', 'ORG_SEQUENCE_NO', 'COLUMN';
END
GO
