package com.autonoma.erp.controller;

import com.autonoma.erp.model.*;
import com.autonoma.erp.service.EmployeeMasterService;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;
import com.autonoma.erp.security.RequirePagePermission;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.tags.Tag;

import java.util.List;
import java.util.Map;

@RestController
@RequestMapping("/api/master/employee")
@CrossOrigin(origins = "*", maxAge = 3600)
@Tag(name = "HRM - Employee Master", description = "Full Employee Master CRUD with sub-resources")
public class EmployeeMasterController {

    @Autowired
    private EmployeeMasterService service;

    @Autowired
    private com.autonoma.erp.repository.EmployeeManagerMappingRepository managerMappingRepository;

    @Autowired
    private com.autonoma.erp.repository.admin.UserRepository userRepository;

    @Autowired
    private com.autonoma.erp.repository.DesignationLevelRepository designationLevelRepository;

    // ======================== EMPLOYEE MASTER ========================

    @GetMapping
    @Operation(summary = "List all employees")
    public List<EmployeeMaster> getAllEmployees() {
        return service.getAllEmployees();
    }

    @GetMapping("/filter/active")
    @Operation(summary = "List only active employees")
    public List<EmployeeMaster> getActiveEmployees() {
        return service.getActiveEmployees();
    }

    @GetMapping("/next-no")
    @Operation(summary = "Get next autogenerated employee code")
    public ResponseEntity<String> getNextEmpCode() {
        return ResponseEntity.ok(service.getNextEmpCode());
    }

    @GetMapping("/{id}")
    @Operation(summary = "Get employee by ID")
    public ResponseEntity<EmployeeMaster> getEmployeeById(@PathVariable Long id) {
        EmployeeMaster emp = service.getEmployeeById(id);
        return emp != null ? ResponseEntity.ok(emp) : ResponseEntity.notFound().build();
    }

    @GetMapping("/{id}/full")
    @Operation(summary = "Get employee with ALL sub-resources (full form load)")
    public ResponseEntity<Map<String, Object>> getEmployeeFull(@PathVariable Long id) {
        Map<String, Object> data = service.getEmployeeFull(id);
        return data != null ? ResponseEntity.ok(data) : ResponseEntity.notFound().build();
    }

    @PostMapping
    @RequirePagePermission(pageCode = "M2210", action = "write")
    @Operation(summary = "Create new employee")
    public EmployeeMaster createEmployee(@RequestBody EmployeeMaster employee) {
        return service.createEmployee(employee);
    }

    @PutMapping("/{id}")
    @RequirePagePermission(pageCode = "M2210", action = "write")
    @Operation(summary = "Update employee")
    public ResponseEntity<EmployeeMaster> updateEmployee(@PathVariable Long id, @RequestBody EmployeeMaster details) {
        EmployeeMaster updated = service.updateEmployee(id, details);
        return updated != null ? ResponseEntity.ok(updated) : ResponseEntity.notFound().build();
    }

    @DeleteMapping("/{id}")
    @RequirePagePermission(pageCode = "M2210", action = "delete")
    @Operation(summary = "Delete employee and all sub-resources")
    public ResponseEntity<Void> deleteEmployee(@PathVariable Long id) {
        service.deleteEmployee(id);
        return ResponseEntity.ok().build();
    }

    // ======================== PERSONAL DETAIL ========================

    @GetMapping("/{id}/personal")
    @Operation(summary = "Get personal details")
    public ResponseEntity<?> getPersonalDetail(@PathVariable Long id) {
        EmployeePersonalDetail detail = service.getPersonalDetail(id);
        return detail != null ? ResponseEntity.ok(detail) : ResponseEntity.ok().build();
    }

    @PostMapping("/{id}/personal")
    @RequirePagePermission(pageCode = "M2210", action = "write")
    @Operation(summary = "Save/update personal details")
    public EmployeePersonalDetail savePersonalDetail(@PathVariable Long id, @RequestBody EmployeePersonalDetail detail) {
        return service.savePersonalDetail(id, detail);
    }

    // ======================== CONTACT ========================

    @GetMapping("/{id}/contact")
    @Operation(summary = "Get contact details")
    public ResponseEntity<?> getContact(@PathVariable Long id) {
        EmployeeContact contact = service.getContact(id);
        return contact != null ? ResponseEntity.ok(contact) : ResponseEntity.ok().build();
    }

    @PostMapping("/{id}/contact")
    @RequirePagePermission(pageCode = "M2210", action = "write")
    @Operation(summary = "Save/update contact details")
    public EmployeeContact saveContact(@PathVariable Long id, @RequestBody EmployeeContact contact) {
        return service.saveContact(id, contact);
    }

    // ======================== JOB PROFILE ========================

    @GetMapping("/{id}/job-profile")
    @Operation(summary = "Get job profile")
    public ResponseEntity<?> getJobProfile(@PathVariable Long id) {
        EmployeeJobProfile profile = service.getJobProfile(id);
        return profile != null ? ResponseEntity.ok(profile) : ResponseEntity.ok().build();
    }

    @PostMapping("/{id}/job-profile")
    @RequirePagePermission(pageCode = "M2210", action = "write")
    @Operation(summary = "Save/update job profile")
    public EmployeeJobProfile saveJobProfile(@PathVariable Long id, @RequestBody EmployeeJobProfile profile) {
        return service.saveJobProfile(id, profile);
    }

    // ======================== EDUCATION (1:N) ========================

    @GetMapping("/{id}/education")
    @Operation(summary = "Get all education records")
    public List<EmployeeEducation> getEducation(@PathVariable Long id) {
        return service.getEducation(id);
    }

    @PostMapping("/{id}/education")
    @RequirePagePermission(pageCode = "M2210", action = "write")
    @Operation(summary = "Add/update education record")
    public EmployeeEducation saveEducation(@PathVariable Long id, @RequestBody EmployeeEducation edu) {
        return service.saveEducation(id, edu);
    }

    @DeleteMapping("/education/{eduId}")
    @RequirePagePermission(pageCode = "M2210", action = "delete")
    @Operation(summary = "Delete education record")
    public ResponseEntity<Void> deleteEducation(@PathVariable Long eduId) {
        service.deleteEducation(eduId);
        return ResponseEntity.ok().build();
    }

    // ======================== EXPERIENCE (1:N) ========================

    @GetMapping("/{id}/experience")
    @Operation(summary = "Get all experience records")
    public List<EmployeeExperience> getExperience(@PathVariable Long id) {
        return service.getExperience(id);
    }

    @PostMapping("/{id}/experience")
    @RequirePagePermission(pageCode = "M2210", action = "write")
    @Operation(summary = "Add/update experience record")
    public EmployeeExperience saveExperience(@PathVariable Long id, @RequestBody EmployeeExperience exp) {
        return service.saveExperience(id, exp);
    }

    @DeleteMapping("/experience/{expId}")
    @RequirePagePermission(pageCode = "M2210", action = "delete")
    @Operation(summary = "Delete experience record")
    public ResponseEntity<Void> deleteExperience(@PathVariable Long expId) {
        service.deleteExperience(expId);
        return ResponseEntity.ok().build();
    }

    // ======================== EMERGENCY CONTACT (1:N) ========================

    @GetMapping("/{id}/emergency-contact")
    @Operation(summary = "Get all emergency contacts")
    public List<EmployeeEmergencyContact> getEmergencyContacts(@PathVariable Long id) {
        return service.getEmergencyContacts(id);
    }

    @PostMapping("/{id}/emergency-contact")
    @RequirePagePermission(pageCode = "M2210", action = "write")
    @Operation(summary = "Add/update emergency contact")
    public EmployeeEmergencyContact saveEmergencyContact(@PathVariable Long id, @RequestBody EmployeeEmergencyContact ec) {
        return service.saveEmergencyContact(id, ec);
    }

    @DeleteMapping("/emergency-contact/{ecId}")
    @RequirePagePermission(pageCode = "M2210", action = "delete")
    @Operation(summary = "Delete emergency contact")
    public ResponseEntity<Void> deleteEmergencyContact(@PathVariable Long ecId) {
        service.deleteEmergencyContact(ecId);
        return ResponseEntity.ok().build();
    }

    // ======================== PASSPORT ========================

    @GetMapping("/{id}/passport")
    @Operation(summary = "Get passport details")
    public ResponseEntity<?> getPassport(@PathVariable Long id) {
        EmployeePassport passport = service.getPassport(id);
        return passport != null ? ResponseEntity.ok(passport) : ResponseEntity.ok().build();
    }

    @PostMapping("/{id}/passport")
    @RequirePagePermission(pageCode = "M2210", action = "write")
    @Operation(summary = "Save/update passport details")
    public EmployeePassport savePassport(@PathVariable Long id, @RequestBody EmployeePassport passport) {
        return service.savePassport(id, passport);
    }

    // ======================== DEPENDENT (1:N) ========================

    @GetMapping("/{id}/dependent")
    @Operation(summary = "Get all dependents")
    public List<EmployeeDependent> getDependents(@PathVariable Long id) {
        return service.getDependents(id);
    }

    @PostMapping("/{id}/dependent")
    @RequirePagePermission(pageCode = "M2210", action = "write")
    @Operation(summary = "Add/update dependent")
    public EmployeeDependent saveDependent(@PathVariable Long id, @RequestBody EmployeeDependent dep) {
        return service.saveDependent(id, dep);
    }

    @DeleteMapping("/dependent/{depId}")
    @RequirePagePermission(pageCode = "M2210", action = "delete")
    @Operation(summary = "Delete dependent")
    public ResponseEntity<Void> deleteDependent(@PathVariable Long depId) {
        service.deleteDependent(depId);
        return ResponseEntity.ok().build();
    }

    // ======================== ASSET (1:N) ========================

    @GetMapping("/{id}/asset")
    @Operation(summary = "Get all assets")
    public List<EmployeeAsset> getAssets(@PathVariable Long id) {
        return service.getAssets(id);
    }

    @PostMapping("/{id}/asset")
    @RequirePagePermission(pageCode = "M2210", action = "write")
    @Operation(summary = "Add/update asset")
    public EmployeeAsset saveAsset(@PathVariable Long id, @RequestBody EmployeeAsset asset) {
        return service.saveAsset(id, asset);
    }

    @DeleteMapping("/asset/{assetId}")
    @RequirePagePermission(pageCode = "M2210", action = "delete")
    @Operation(summary = "Delete asset")
    public ResponseEntity<Void> deleteAsset(@PathVariable Long assetId) {
        service.deleteAsset(assetId);
        return ResponseEntity.ok().build();
    }

    // ======================== KYC ========================

    @GetMapping("/{id}/kyc")
    @Operation(summary = "Get KYC details")
    public ResponseEntity<?> getKyc(@PathVariable Long id) {
        EmployeeKyc kyc = service.getKyc(id);
        return kyc != null ? ResponseEntity.ok(kyc) : ResponseEntity.ok().build();
    }

    @PostMapping("/{id}/kyc")
    @RequirePagePermission(pageCode = "M2210", action = "write")
    @Operation(summary = "Save/update KYC details")
    public EmployeeKyc saveKyc(@PathVariable Long id, @RequestBody EmployeeKyc kyc) {
        return service.saveKyc(id, kyc);
    }

    // ======================== KYC DOCUMENT (1:N) ========================

    @GetMapping("/{id}/kyc-document")
    @Operation(summary = "Get all KYC documents")
    public List<EmployeeKycDocument> getKycDocuments(@PathVariable Long id) {
        return service.getKycDocuments(id);
    }

    @PostMapping("/{id}/kyc-document")
    @RequirePagePermission(pageCode = "M2210", action = "write")
    @Operation(summary = "Add/update KYC document")
    public EmployeeKycDocument saveKycDocument(@PathVariable Long id, @RequestBody EmployeeKycDocument doc) {
        return service.saveKycDocument(id, doc);
    }

    @DeleteMapping("/kyc-document/{docId}")
    @RequirePagePermission(pageCode = "M2210", action = "delete")
    @Operation(summary = "Delete KYC document")
    public ResponseEntity<Void> deleteKycDocument(@PathVariable Long docId) {
        service.deleteKycDocument(docId);
        return ResponseEntity.ok().build();
    }

    // ======================== ACTIVITY (1:N) ========================

    @GetMapping("/{id}/activity")
    @Operation(summary = "Get all activities")
    public List<EmployeeActivity> getActivities(@PathVariable Long id) {
        return service.getActivities(id);
    }

    @PostMapping("/{id}/activity")
    @RequirePagePermission(pageCode = "M2210", action = "write")
    @Operation(summary = "Add/update activity")
    public EmployeeActivity saveActivity(@PathVariable Long id, @RequestBody EmployeeActivity activity) {
        return service.saveActivity(id, activity);
    }

    @DeleteMapping("/activity/{actId}")
    @RequirePagePermission(pageCode = "M2210", action = "delete")
    @Operation(summary = "Delete activity")
    public ResponseEntity<Void> deleteActivity(@PathVariable Long actId) {
        service.deleteActivity(actId);
        return ResponseEntity.ok().build();
    }

    // ======================== EMPLOYEE MANAGER MAPPING ========================

    @GetMapping("/manager-mapping")
    @Operation(summary = "Get all employee manager mappings")
    public ResponseEntity<List<EmployeeManagerMapping>> getAllManagerMappings() {
        return ResponseEntity.ok(managerMappingRepository.findAll());
    }

    @GetMapping("/manager-mapping/{empId}")
    @Operation(summary = "Get employee manager mapping")
    public ResponseEntity<EmployeeManagerMapping> getManagerMapping(@PathVariable Long empId) {
        return ResponseEntity.ok(managerMappingRepository.findByEmpId(empId)
                .orElse(new EmployeeManagerMapping(null, empId, null, null, null, null, null, null, null, null, "Active")));
    }

    @PostMapping("/manager-mapping")
    @RequirePagePermission(pageCode = "M2210", action = "write")
    @Operation(summary = "Create or update employee manager mapping")
    public ResponseEntity<EmployeeManagerMapping> saveManagerMapping(@RequestBody EmployeeManagerMapping mapping) {
        EmployeeManagerMapping existing = managerMappingRepository.findByEmpId(mapping.getEmpId()).orElse(null);
        if (existing != null) {
            existing.setHomeManagerId(mapping.getHomeManagerId());
            existing.setBusinessManagerId(mapping.getBusinessManagerId());
            existing.setVerticalHeadId(mapping.getVerticalHeadId());
            existing.setHrId(mapping.getHrId());
            existing.setUpdatedBy(com.autonoma.erp.util.SecurityUtils.getCurrentUserId());
            existing.setUpdatedAt(new java.util.Date());
            return ResponseEntity.ok(managerMappingRepository.save(existing));
        } else {
            mapping.setCreatedBy(com.autonoma.erp.util.SecurityUtils.getCurrentUserId());
            mapping.setCreatedAt(new java.util.Date());
            return ResponseEntity.ok(managerMappingRepository.save(mapping));
        }
    }

    @GetMapping("/manager-mapping/eligible-managers")
    @Operation(summary = "Get eligible managers based on designation level criteria")
    public ResponseEntity<List<EmployeeMaster>> getEligibleManagers(@RequestParam(required = false) Long empId) {
        int empLevelVal = 0;
        if (empId != null) {
            EmployeeMaster emp = service.getEmployeeById(empId);
            if (emp != null && emp.getEmpLevelId() != null) {
                DesignationLevel dLevel = designationLevelRepository.findById(emp.getEmpLevelId()).orElse(null);
                if (dLevel != null) {
                    empLevelVal = parseLevelNumber(dLevel.getLevel());
                }
            }
        }

        List<EmployeeMaster> active = service.getActiveEmployees();
        List<EmployeeMaster> eligible = new java.util.ArrayList<>();
        // Cache level values for sorting
        java.util.Map<Long, Integer> levelCache = new java.util.HashMap<>();

        for (EmployeeMaster candidate : active) {
            // 0. Exclude the selected employee themselves
            if (empId != null && candidate.getId().equals(empId)) {
                continue;
            }
            // 1. User credentials created
            if (!userRepository.existsByEmpId(candidate.getId())) {
                continue;
            }
            // 2. Induction completed
            if (candidate.getInductionStatus() == null || !candidate.getInductionStatus().equalsIgnoreCase("COMPLETED")) {
                continue;
            }
            // 3. Level condition: candidateLevelVal must be STRICTLY GREATER than empLevelVal
            if (candidate.getEmpLevelId() != null) {
                DesignationLevel candLevelObj = designationLevelRepository.findById(candidate.getEmpLevelId()).orElse(null);
                if (candLevelObj != null) {
                    int candLevelVal = parseLevelNumber(candLevelObj.getLevel());
                    if (candLevelVal > empLevelVal) {
                        eligible.add(candidate);
                        levelCache.put(candidate.getId(), candLevelVal);
                    }
                }
            }
        }

        // Sort: highest level first, then employee name ascending
        eligible.sort((a, b) -> {
            int levelA = levelCache.getOrDefault(a.getId(), 0);
            int levelB = levelCache.getOrDefault(b.getId(), 0);
            if (levelB != levelA) return Integer.compare(levelB, levelA); // descending level
            String nameA = a.getEmployeeName() != null ? a.getEmployeeName() : "";
            String nameB = b.getEmployeeName() != null ? b.getEmployeeName() : "";
            return nameA.compareToIgnoreCase(nameB); // ascending name
        });

        return ResponseEntity.ok(eligible);
    }

    private int parseLevelNumber(String levelName) {
        if (levelName == null || levelName.isEmpty()) return 0;
        try {
            return Integer.parseInt(levelName.replaceAll("[^0-9]", ""));
        } catch (Exception e) {
            return 0;
        }
    }
}
