package com.autonoma.erp.controller;

import com.autonoma.erp.model.*;
import com.autonoma.erp.repository.*;
import com.autonoma.erp.security.RequirePagePermission;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.tags.Tag;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;
import org.springframework.transaction.annotation.Transactional;
import com.autonoma.erp.repository.admin.CompanyCredentialRepository;
import com.autonoma.erp.repository.admin.UserRepository;
import com.autonoma.erp.model.admin.CompanyCredential;
import com.autonoma.erp.service.JwtService;
import org.springframework.mail.javamail.JavaMailSenderImpl;
import org.springframework.mail.javamail.MimeMessageHelper;
import jakarta.mail.internet.MimeMessage;
import java.util.Properties;

import java.math.BigDecimal;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Optional;

@RestController
@RequestMapping("/api/hra/applicants")
@CrossOrigin(origins = "*")
@Tag(name = "HRA - Application Tracking System", description = "Endpoints for applicant management")
public class HraApplicantController {

    @Autowired
    private EmployeeMasterRepository employeeRepo;

    @Autowired
    private EmployeePersonalDetailRepository personalRepo;

    @Autowired
    private EmployeeContactRepository contactRepo;

    @Autowired
    private EmployeeJobProfileRepository jobProfileRepo;

    @Autowired
    private EmployeeExperienceRepository experienceRepo;

    @Autowired
    private EmployeeEducationRepository educationRepo;

    @Autowired
    private EmployeeKycDocumentRepository kycDocumentRepo;

    @Autowired
    private EmployeeActivityRepository activityRepo;

    @Autowired
    private com.autonoma.erp.service.EmployeeMasterService employeeMasterService;

    @Autowired
    private CompanyCredentialRepository companyCredentialRepo;

    @Autowired
    private UserRepository userRepo;

    @Autowired
    private JwtService jwtService;

    @Autowired
    private DepartmentRepository departmentRepo;

    @GetMapping
    @RequirePagePermission(pageCode = "HA1110", action = "read")
    @Operation(summary = "Get all applicants")
    public List<Map<String, Object>> getAllApplicants() {
        List<EmployeeMaster> applicants = employeeRepo.findByEmpCodeStartingWith("ATS-");
        List<Map<String, Object>> result = new ArrayList<>();
        for (EmployeeMaster emp : applicants) {
            result.add(mapEmployeeToFullMap(emp));
        }
        return result;
    }

    @GetMapping("/{id}")
    @RequirePagePermission(pageCode = "HA1110", action = "read")
    @Operation(summary = "Get applicant by ID")
    public ResponseEntity<Map<String, Object>> getApplicantById(@PathVariable Long id) {
        return employeeRepo.findById(id)
                .map(emp -> ResponseEntity.ok(mapEmployeeToFullMap(emp)))
                .orElse(ResponseEntity.notFound().build());
    }

    @GetMapping("/next-code")
    @RequirePagePermission(pageCode = "HA1110", action = "read")
    @Operation(summary = "Calculate next autogenerated candidate code")
    public ResponseEntity<String> getNextEnrolledNo() {
        List<EmployeeMaster> lastOpt = employeeRepo.findByEmpCodeStartingWith("ATS-");
        if (!lastOpt.isEmpty()) {
            int maxSeq = 0;
            for (EmployeeMaster emp : lastOpt) {
                String code = emp.getEmpCode();
                String[] parts = code.split("-");
                if (parts.length == 3) {
                    try {
                        int seq = Integer.parseInt(parts[2]);
                        if (seq > maxSeq) {
                            maxSeq = seq;
                        }
                    } catch (NumberFormatException e) {
                        // ignore
                    }
                }
            }
            return ResponseEntity.ok(String.format("ATS-2026-%03d", maxSeq + 1));
        }
        return ResponseEntity.ok("ATS-2026-001");
    }

    @PostMapping
    @RequirePagePermission(pageCode = "HA1110", action = "write")
    @Operation(summary = "Create new applicant")
    @Transactional
    public ResponseEntity<?> saveApplicant(@RequestBody Map<String, Object> payload) {
        // Validation for unique Aadhaar number if duplicateAadhar is false
        String aadharNo = getStringValue(payload, "aadharNo");
        Boolean duplicateAadhar = (Boolean) payload.get("duplicateAadhar");
        if (aadharNo != null && !aadharNo.isEmpty() && !Boolean.TRUE.equals(duplicateAadhar)) {
            if (personalRepo.existsByAadharNumber(aadharNo)) {
                return ResponseEntity.badRequest().body("Aadhaar Number already exists in records!");
            }
        }

        // Unique EnRolledNo check
        String enRolledNo = getStringValue(payload, "enRolledNo");
        if (enRolledNo == null || enRolledNo.isEmpty()) {
            enRolledNo = getNextEnrolledNo().getBody();
        } else if (employeeRepo.existsByEmpCode(enRolledNo)) {
            return ResponseEntity.badRequest().body("Enrollment Number already exists!");
        }

        EmployeeMaster emp = new EmployeeMaster();
        emp.setEmpCode(enRolledNo);
        emp.setCreatedBy(com.autonoma.erp.util.SecurityUtils.getCurrentUserId());
        
        saveOrUpdateApplicantDetails(emp, payload);
        
        return ResponseEntity.ok(mapEmployeeToFullMap(emp));
    }

    @PostMapping("/send-call-letter")
    @RequirePagePermission(pageCode = "HA1110", action = "write")
    @Operation(summary = "Send applicant call letter email")
    @Transactional
    public ResponseEntity<?> sendCallLetter(@RequestBody Map<String, Object> payload) {
        Long applicantId = Long.valueOf(payload.get("id").toString());
        String interviewDateStr = getStringValue(payload, "interviewDate");
        String interviewTimeStr = getStringValue(payload, "interviewTime");
        String fromEmail = getStringValue(payload, "fromEmail");
        String toEmail = getStringValue(payload, "toEmail");
        String ccEmail = getStringValue(payload, "ccEmail");

        EmployeeMaster applicant = employeeRepo.findById(applicantId)
                .orElseThrow(() -> new RuntimeException("Applicant not found with ID: " + applicantId));

        // Format Date nicely for display (e.g. from yyyy-MM-dd to dd-MM-yyyy)
        String formattedDate = interviewDateStr;
        try {
            Date parsedDate = new SimpleDateFormat("yyyy-MM-dd").parse(interviewDateStr);
            formattedDate = new SimpleDateFormat("dd-MM-yyyy").format(parsedDate);
        } catch (Exception e) {
            // fallback to original
        }

        // Get sender name (logged-in user)
        String currentUserId = com.autonoma.erp.util.SecurityUtils.getCurrentUserId();
        String senderName = "HR TEAM";
        if (currentUserId != null) {
            Optional<com.autonoma.erp.model.admin.UserCredential> userCredOpt = userRepo.findByUserId(currentUserId);
            if (userCredOpt.isPresent() && userCredOpt.get().getEmpId() != null) {
                Optional<EmployeeMaster> senderEmpOpt = employeeRepo.findById(userCredOpt.get().getEmpId());
                if (senderEmpOpt.isPresent()) {
                    senderName = senderEmpOpt.get().getEmployeeName();
                }
            }
        }

        // Get department name
        String departmentName = "HR";
        if (applicant.getDepartmentId() != null) {
            Optional<Department> deptOpt = departmentRepo.findById(applicant.getDepartmentId());
            if (deptOpt.isPresent()) {
                departmentName = deptOpt.get().getDepartmentName();
            }
        }

        // Get company credentials for SMTP configuration & Venue details
        List<CompanyCredential> companyList = companyCredentialRepo.findAll();
        if (companyList.isEmpty()) {
            return ResponseEntity.badRequest().body("Company Profile credentials are not configured! Cannot send email.");
        }
        CompanyCredential company = companyList.get(0);

        // Verify SMTP configuration is present
        if (company.getSmtpHost() == null || company.getSmtpHost().isEmpty() ||
            company.getSmtpUsername() == null || company.getSmtpUsername().isEmpty()) {
            return ResponseEntity.badRequest().body("SMTP host or username is not configured in the Company Profile!");
        }

        // Generate temporary portal access link with JWT token (2 hours expiration)
        String token = jwtService.generateApplicantToken(applicant.getEmpCode());
        String portalLink = String.format("%s/candidate/login?token=%s", company.getWebsite() != null && !company.getWebsite().isEmpty() ? company.getWebsite() : "http://localhost:3000", token);

        // Update applicant call letter status and interview details
        applicant.setCallStatus("SENT");
        applicant.setStatus("INTERVIEWING");
        employeeRepo.save(applicant);

        // Configure JavaMailSender dynamically
        JavaMailSenderImpl mailSender = new JavaMailSenderImpl();
        mailSender.setHost(company.getSmtpHost());
        if (company.getSmtpPort() != null) {
            mailSender.setPort(company.getSmtpPort());
        }
        mailSender.setUsername(company.getSmtpUsername());
        mailSender.setPassword(company.getSmtpPassword());

        Properties props = mailSender.getJavaMailProperties();
        props.put("mail.transport.protocol", "smtp");
        props.put("mail.smtp.auth", "true");
        props.put("mail.smtp.starttls.enable", "true");
        if (Boolean.TRUE.equals(company.getSmtpSslEnabled())) {
            props.put("mail.smtp.ssl.enable", "true");
        }

        try {
            MimeMessage mimeMessage = mailSender.createMimeMessage();
            MimeMessageHelper helper = new MimeMessageHelper(mimeMessage, true, "UTF-8");

            helper.setFrom(fromEmail);
            helper.setTo(toEmail);
            if (ccEmail != null && !ccEmail.trim().isEmpty()) {
                helper.setCc(ccEmail);
            }
            helper.setSubject("CALL LETTER FOR INTERVIEW SCHEDULE");

            // Build HTML content using template details
            String candidateFullName = (applicant.getFirstName() != null ? applicant.getFirstName() : "") + " " + (applicant.getLastName() != null ? applicant.getLastName() : "");
            candidateFullName = candidateFullName.trim();
            if (candidateFullName.isEmpty()) {
                candidateFullName = "Shortlisted Candidate";
            }

            String positionName = applicant.getPositionLookFor() != null ? applicant.getPositionLookFor() : "Shortlisted Position";

            String companyAddress = (company.getAddress() != null ? company.getAddress() : "") + ", " + 
                                    (company.getCity() != null ? company.getCity() : "") + " - " + 
                                    (company.getPincode() != null ? company.getPincode() : "");

            String htmlBody = "<!DOCTYPE html>\n" +
                "<html>\n" +
                "<head>\n" +
                "    <meta charset=\"utf-8\">\n" +
                "</head>\n" +
                "<body style=\"font-family: Arial, sans-serif; line-height: 1.6; color: #333333;\">\n" +
                "    <div style=\"max-width: 600px; margin: 0 auto; padding: 20px; border: 1px solid #e0e0e0; border-radius: 10px;\">\n" +
                "        <h2 style=\"color: #2b3a42; border-bottom: 2px solid #2b3a42; padding-bottom: 10px; margin-top: 0;\">\n" +
                "            Interview Invitation (" + positionName.toUpperCase() + ")\n" +
                "        </h2>\n" +
                "        <p>Dear Mr./Ms. " + candidateFullName.toUpperCase() + ",</p>\n" +
                "        <p>Greetings of the day!</p>\n" +
                "        <p>We are pleased to inform you that your profile has been shortlisted for one of our vacant positions. Congratulations!</p>\n" +
                "        \n" +
                "        <table style=\"width: 100%; border-collapse: collapse; margin: 20px 0;\">\n" +
                "            <tr>\n" +
                "                <td style=\"padding: 8px; font-weight: bold; width: 150px; border-bottom: 1px solid #f0f0f0;\">Position:</td>\n" +
                "                <td style=\"padding: 8px; border-bottom: 1px solid #f0f0f0;\">" + positionName + "</td>\n" +
                "            </tr>\n" +
                "            <tr>\n" +
                "                <td style=\"padding: 8px; font-weight: bold; border-bottom: 1px solid #f0f0f0;\">Department:</td>\n" +
                "                <td style=\"padding: 8px; border-bottom: 1px solid #f0f0f0;\">" + departmentName + "</td>\n" +
                "            </tr>\n" +
                "            <tr>\n" +
                "                <td style=\"padding: 8px; font-weight: bold; border-bottom: 1px solid #f0f0f0;\">Interview Date:</td>\n" +
                "                <td style=\"padding: 8px; border-bottom: 1px solid #f0f0f0;\">" + formattedDate + "</td>\n" +
                "            </tr>\n" +
                "            <tr>\n" +
                "                <td style=\"padding: 8px; font-weight: bold; border-bottom: 1px solid #f0f0f0;\">Interview Time:</td>\n" +
                "                <td style=\"padding: 8px; border-bottom: 1px solid #f0f0f0;\">" + interviewTimeStr + "</td>\n" +
                "            </tr>\n" +
                "            <tr>\n" +
                "                <td style=\"padding: 8px; font-weight: bold; border-bottom: 1px solid #f0f0f0;\">Venue:</td>\n" +
                "                <td style=\"padding: 8px; border-bottom: 1px solid #f0f0f0;\">\n" +
                "                    <strong>" + company.getCompanyName() + "</strong><br/>\n" +
                "                    " + companyAddress + "\n" +
                "                </td>\n" +
                "            </tr>\n" +
                "        </table>\n" +
                "\n" +
                "        <div style=\"margin: 25px 0; padding: 15px; background-color: #f7f9fa; border-left: 4px solid #17a2b8; border-radius: 4px;\">\n" +
                "            <h4 style=\"margin-top: 0; color: #2b3a42;\">Portal Access (Valid for 2 Hours)</h4>\n" +
                "            <p style=\"margin-bottom: 15px;\">Before the interview, kindly fill your details through the below portal:</p>\n" +
                "            <p style=\"margin-bottom: 20px; text-align: center;\">\n" +
                "                <a href=\"" + portalLink + "\" style=\"background-color: #007bff; color: white; padding: 10px 20px; text-decoration: none; border-radius: 5px; font-weight: bold; display: inline-block;\">\n" +
                "                    Click here to access the portal\n" +
                "                </a>\n" +
                "            </p>\n" +
                "            <p style=\"margin-bottom: 5px;\"><strong>Login Credentials:</strong></p>\n" +
                "            <p style=\"margin: 0;\"><strong>User ID:</strong> " + applicant.getEmpCode() + "</p>\n" +
                "            <p style=\"margin: 0;\"><strong>Password:</strong> Last 4 digits of your mobile number</p>\n" +
                "        </div>\n" +
                "\n" +
                "        <div style=\"margin: 20px 0; font-size: 0.9em; color: #666666;\">\n" +
                "            <p style=\"margin-bottom: 5px;\"><strong>Important Instructions:</strong></p>\n" +
                "            <ul style=\"margin-top: 0; padding-left: 20px;\">\n" +
                "                <li>Use a laptop/desktop/mobile (if using Mobile, please enable desktop mode).</li>\n" +
                "                <li>Prepare these documents for upload:\n" +
                "                    <ul style=\"margin-top: 5px;\">\n" +
                "                        <li>Latest passport-sized photo</li>\n" +
                "                        <li>Aadhaar card</li>\n" +
                "                        <li>Current/previous company salary slip</li>\n" +
                "                        <li>Latest resume</li>\n" +
                "                    </ul>\n" +
                "                </li>\n" +
                "                <li>If you face issues or need a fresh link, contact us for assistance.</li>\n" +
                "            </ul>\n" +
                "        </div>\n" +
                "\n" +
                "        <p>We look forward to meeting you.</p>\n" +
                "        \n" +
                "        <p style=\"margin-top: 25px; margin-bottom: 0;\">Yours Windfully,</p>\n" +
                "        <p style=\"margin: 0; font-weight: bold; color: #2b3a42;\">" + senderName + "</p>\n" +
                "        <p style=\"margin: 0; font-size: 0.9em; color: #666666;\">HR Department</p>\n" +
                "        <p style=\"margin: 0; font-size: 0.9em; color: #666666;\">Email: " + fromEmail + "</p>\n" +
                "\n" +
                "        <p style=\"margin-top: 20px; border-top: 1px solid #f0f0f0; padding-top: 15px; font-size: 0.8em; color: #999999; text-align: center;\">\n" +
                "            Note: This is a system-generated email. Please do not reply to this email ID.\n" +
                "        </p>\n" +
                "    </div>\n" +
                "</body>\n" +
                "</html>";

            helper.setText(htmlBody, true);
            mailSender.send(mimeMessage);
        } catch (Exception e) {
            e.printStackTrace();
            return ResponseEntity.badRequest().body("Failed to send call letter email: " + e.getMessage());
        }

        return ResponseEntity.ok(Map.of("message", "Call letter email successfully sent."));
    }

    @PostMapping("/portal/login")
    @Operation(summary = "Login to candidate portal")
    public ResponseEntity<?> portalLogin(@RequestBody Map<String, Object> payload) {
        String token = getStringValue(payload, "token");
        String userId = getStringValue(payload, "userId"); // ATS-2026-001
        String password = getStringValue(payload, "password"); // last 4 digits of phone

        if (token == null || token.isEmpty()) {
            return ResponseEntity.status(401).body("Missing verification token!");
        }

        try {
            // Validate the token signature and expiration
            String subject = jwtService.extractUsername(token);
            if (subject == null || !subject.equals(userId)) {
                return ResponseEntity.status(401).body("Invalid or expired session token!");
            }
        } catch (Exception e) {
            return ResponseEntity.status(401).body("Invalid or expired session token!");
        }

        // Load the candidate
        EmployeeMaster applicant = employeeRepo.findByEmpCode(userId)
                .orElse(null);
        if (applicant == null) {
            return ResponseEntity.status(401).body("Invalid User ID!");
        }

        // Load contact information to verify last 4 digits of phone
        Optional<EmployeeContact> contactOpt = contactRepo.findByEmployeeId(applicant.getId());
        if (contactOpt.isEmpty()) {
            return ResponseEntity.status(401).body("Candidate contact information not found!");
        }

        String phone = contactOpt.get().getMobile();
        if (phone == null || phone.length() < 4) {
            return ResponseEntity.status(401).body("Candidate phone number not set in records!");
        }

        String lastFour = phone.substring(phone.length() - 4);
        if (!lastFour.equals(password)) {
            return ResponseEntity.status(401).body("Invalid password! Hint: Last 4 digits of your mobile number.");
        }

        // Return confirmation details and a candidate session token
        String candidateSessionToken = jwtService.generateApplicantToken(userId); // Re-use 2 hour token
        return ResponseEntity.ok(Map.of(
            "token", candidateSessionToken,
            "applicant", mapEmployeeToFullMap(applicant)
        ));
    }

    @PostMapping("/portal/submit")
    @Operation(summary = "Submit candidate self-assessment answers")
    @Transactional
    public ResponseEntity<?> portalSubmit(@RequestBody Map<String, Object> payload) {
        String token = getStringValue(payload, "token");
        if (token == null || token.isEmpty()) {
            return ResponseEntity.status(401).body("Authentication token missing!");
        }

        String applicantCode;
        try {
            applicantCode = jwtService.extractUsername(token);
        } catch (Exception e) {
            return ResponseEntity.status(401).body("Session expired or invalid!");
        }

        EmployeeMaster applicant = employeeRepo.findByEmpCode(applicantCode)
                .orElseThrow(() -> new RuntimeException("Applicant not found"));

        // Save self assessment fields (Q1 to Q40)
        applicant.setQ1_native(getStringValue(payload, "q1_native"));
        applicant.setQ2_presentAddress(getStringValue(payload, "q2_present_address"));
        applicant.setQ3_permanentAddress(getStringValue(payload, "q3_permanent_address"));
        applicant.setQ4_fatherOccupation(getStringValue(payload, "q4_father_occupation"));
        applicant.setQ5_motherOccupation(getStringValue(payload, "q5_mother_occupation"));
        applicant.setQ6_maritalStatus(getStringValue(payload, "q6_marital_status"));
        applicant.setQ7_spouseOccupation(getStringValue(payload, "q7_spouse_occupation"));
        applicant.setQ8_children(getStringValue(payload, "q8_children"));
        applicant.setQ9_hasRelativesInCompany(getStringValue(payload, "q9_has_relatives"));
        applicant.setQ10_relativesDetails(getStringValue(payload, "q10_relatives_details"));
        applicant.setQ11_siblingsOccupations(getStringValue(payload, "q11_siblings_occupations"));
        applicant.setQ12_hasTwoWheeler(getStringValue(payload, "q12_has_two_wheeler"));
        applicant.setQ13_hasAndroidPhone(getStringValue(payload, "q13_has_android_phone"));
        applicant.setQ14_knowsCarDriving(getStringValue(payload, "q14_knows_car_driving"));
        applicant.setQ15_willingToTravel(getStringValue(payload, "q15_willing_to_travel"));
        applicant.setQ16_covidVaccination(getStringValue(payload, "q16_covid_vaccination"));
        applicant.setQ17_positivePoints(getStringValue(payload, "q17_positive_points"));
        applicant.setQ18_negativePoints(getStringValue(payload, "q18_negative_points"));
        applicant.setQ19_lifeGoals(getStringValue(payload, "q19_life_goals"));
        applicant.setQ20_improvementSuggestions(getStringValue(payload, "q20_improvement_suggestions"));
        applicant.setQ21_isExperienced(getStringValue(payload, "q21_is_experienced"));
        applicant.setQ22_totalExperience(getStringValue(payload, "q22_total_experience"));
        applicant.setQ23_coreExperience(getStringValue(payload, "q23_core_experience"));
        applicant.setQ24_prevNetSalary(getStringValue(payload, "q24_prev_net_salary"));
        applicant.setQ25_prevGrossSalary(getStringValue(payload, "q25_prev_gross_salary"));
        applicant.setQ26_expectedNetSalary(getStringValue(payload, "q26_expected_net_salary"));
        applicant.setQ27_expectedGrossSalary(getStringValue(payload, "q27_expected_gross_salary"));
        applicant.setQ28_pfHigherPension(getStringValue(payload, "q28_pf_higher_pension"));
        applicant.setQ29_pfDeductionAmount(getStringValue(payload, "q29_pf_deduction_amount"));
        applicant.setQ30_alternativeDepartment(getStringValue(payload, "q30_alternative_department"));
        applicant.setQ31_prevLocation(getStringValue(payload, "q31_prev_location"));
        applicant.setQ32_prevShift(getStringValue(payload, "q32_prev_shift"));
        applicant.setQ33_reasonForLeaving(getStringValue(payload, "q33_reason_for_leaving"));
        applicant.setQ34_noticePeriod(getStringValue(payload, "q34_notice_period"));
        applicant.setQ35_prevDeptPosition(getStringValue(payload, "q35_prev_dept_position"));
        applicant.setQ36_prevDeptCount(getStringValue(payload, "q36_prev_dept_count"));
        applicant.setQ37_prevReportingTo(getStringValue(payload, "q37_prev_reporting_to"));
        applicant.setQ38_handleMistake(getStringValue(payload, "q38_handle_mistake"));
        applicant.setQ39_handleOpinionDifference(getStringValue(payload, "q39_handle_opinion_difference"));
        applicant.setQ40_computerSelfRating(getStringValue(payload, "q40_computer_self_rating"));

        employeeRepo.save(applicant);

        return ResponseEntity.ok(Map.of("message", "Self assessment submitted successfully!"));
    }

    @PutMapping("/{id}")
    @RequirePagePermission(pageCode = "HA1110", action = "write")
    @Operation(summary = "Update applicant details")
    @Transactional
    public ResponseEntity<?> updateApplicant(@PathVariable Long id, @RequestBody Map<String, Object> payload) {
        return employeeRepo.findById(id).map(existing -> {
            // Validation for unique Aadhaar number
            String aadharNo = getStringValue(payload, "aadharNo");
            Boolean duplicateAadhar = (Boolean) payload.get("duplicateAadhar");
            if (aadharNo != null && !aadharNo.isEmpty() && !Boolean.TRUE.equals(duplicateAadhar)) {
                if (personalRepo.existsByAadharNumberAndEmployeeIdNot(aadharNo, id)) {
                    return ResponseEntity.badRequest().body("Aadhaar Number already exists in another record!");
                }
            }

            saveOrUpdateApplicantDetails(existing, payload);
            return ResponseEntity.ok(mapEmployeeToFullMap(existing));
        }).orElse(ResponseEntity.notFound().build());
    }

    @DeleteMapping("/{id}")
    @RequirePagePermission(pageCode = "HA1110", action = "delete")
    @Operation(summary = "Delete applicant and nested details")
    @Transactional
    public ResponseEntity<Void> deleteApplicant(@PathVariable Long id) {
        if (employeeRepo.existsById(id)) {
            personalRepo.deleteByEmployeeId(id);
            contactRepo.deleteByEmployeeId(id);
            jobProfileRepo.deleteByEmployeeId(id);
            educationRepo.deleteByEmployeeId(id);
            experienceRepo.deleteByEmployeeId(id);
            kycDocumentRepo.deleteByEmployeeId(id);
            activityRepo.deleteByEmployeeId(id);
            employeeRepo.deleteById(id);
            return ResponseEntity.ok().build();
        }
        return ResponseEntity.notFound().build();
    }

    @PostMapping("/bulk-action")
    @RequirePagePermission(pageCode = "HA1110", action = "write")
    @Operation(summary = "Perform bulk pipeline stage updates on selected candidates")
    @Transactional
    public ResponseEntity<?> bulkAction(@RequestBody Map<String, Object> payload) {
        List<?> rawIds = (List<?>) payload.get("ids");
        String action = (String) payload.get("action"); // "CALL", "INTERVIEW", "OFFER", "PUSH-ON-ROLL"

        if (rawIds == null || rawIds.isEmpty() || action == null) {
            return ResponseEntity.badRequest().body("Invalid request payload parameters.");
        }

        for (Object rawId : rawIds) {
            Long id = Long.valueOf(rawId.toString());
            employeeRepo.findById(id).ifPresent(applicant -> {
                switch (action.toUpperCase()) {
                    case "CALL":
                        applicant.setCallStatus("SENT");
                        break;
                    case "INTERVIEW":
                        applicant.setInterviewStatus("SCHEDULED");
                        applicant.setStatus("INTERVIEWING");
                        break;
                    case "OFFER":
                        applicant.setOfferStatus("ISSUED");
                        applicant.setStatus("OFFERED");
                        break;
                    case "PUSH-ON-ROLL":
                        applicant.setVerificationStatus("VERIFIED");
                        applicant.setStatus("Active");
                        applicant.setEmpCode(getNextEmpCode());
                        applicant.setDateOfJoining(new Date());
                        break;
                    default:
                        break;
                }
                employeeRepo.save(applicant);
            });
        }

        return ResponseEntity.ok(Map.of("message", "Bulk action executed successfully."));
    }

    // Helper method to generate next Employee Code starting with EMP-
    private String getNextEmpCode() {
        List<EmployeeMaster> list = employeeRepo.findByEmpCodeStartingWith("EMP-");
        if (list.isEmpty()) {
            return "EMP-001";
        }
        int maxSeq = 0;
        for (EmployeeMaster emp : list) {
            String code = emp.getEmpCode();
            String[] parts = code.split("-");
            if (parts.length == 2) {
                try {
                    int seq = Integer.parseInt(parts[1]);
                    if (seq > maxSeq) {
                        maxSeq = seq;
                    }
                } catch (NumberFormatException e) {
                    // ignore
                }
            }
        }
        return String.format("EMP-%03d", maxSeq + 1);
    }

    // Utility methods to extract types from payload Map
    private String getStringValue(Map<String, Object> map, String key) {
        Object val = map.get(key);
        return val == null ? null : val.toString();
    }

    private Date getDateValue(Map<String, Object> map, String key) {
        Object val = map.get(key);
        if (val == null || val.toString().isEmpty()) return null;
        try {
            String str = val.toString();
            if (str.contains("T")) {
                str = str.substring(0, str.indexOf("T"));
            }
            return new SimpleDateFormat("yyyy-MM-dd").parse(str);
        } catch (Exception e) {
            return null;
        }
    }

    private BigDecimal getBigDecimalValue(Map<String, Object> map, String key) {
        Object val = map.get(key);
        if (val == null || val.toString().isEmpty()) return null;
        try {
            return new BigDecimal(val.toString());
        } catch (Exception e) {
            return null;
        }
    }

    private Map<String, Object> mapEmployeeToFullMap(EmployeeMaster emp) {
        Map<String, Object> map = new HashMap<>();
        map.put("id", emp.getId());
        map.put("enRolledNo", emp.getEmpCode());
        map.put("empCode", emp.getEmpCode());
        map.put("applicantDate", emp.getApplicantDate());
        map.put("positionLookFor", emp.getPositionLookFor());
        map.put("title", emp.getTitle());
        map.put("firstName", emp.getFirstName());
        map.put("lastName", emp.getLastName());
        map.put("department", emp.getDepartmentId() != null ? emp.getDepartmentId().toString() : "");
        map.put("departmentId", emp.getDepartmentId());
        map.put("callStatus", emp.getCallStatus());
        map.put("call", emp.getCallStatus());
        map.put("interviewStatus", emp.getInterviewStatus());
        map.put("interview", emp.getInterviewStatus());
        map.put("offerStatus", emp.getOfferStatus());
        map.put("offer", emp.getOfferStatus());
        map.put("verificationStatus", emp.getVerificationStatus());
        map.put("verification", emp.getVerificationStatus());
        map.put("status", emp.getStatus());
        map.put("age", emp.getAge());
        map.put("payslipPath", emp.getPayslipPath());
        map.put("referMode", emp.getReferMode());
        map.put("refMode", emp.getReferMode());
        map.put("refComments", emp.getReferenceComments());
        map.put("referenceComments", emp.getReferenceComments());

        // Tab 8 Self Assessment fields
        map.put("q1_native", emp.getQ1_native());
        map.put("q2_present_address", emp.getQ2_presentAddress());
        map.put("q3_permanent_address", emp.getQ3_permanentAddress());
        map.put("q4_father_occupation", emp.getQ4_fatherOccupation());
        map.put("q5_mother_occupation", emp.getQ5_motherOccupation());
        map.put("q6_marital_status", emp.getQ6_maritalStatus());
        map.put("q7_spouse_occupation", emp.getQ7_spouseOccupation());
        map.put("q8_children", emp.getQ8_children());
        map.put("q9_has_relatives", emp.getQ9_hasRelativesInCompany());
        map.put("q10_relatives_details", emp.getQ10_relativesDetails());
        map.put("q11_siblings_occupations", emp.getQ11_siblingsOccupations());
        map.put("q12_has_two_wheeler", emp.getQ12_hasTwoWheeler());
        map.put("q13_has_android_phone", emp.getQ13_hasAndroidPhone());
        map.put("q14_knows_car_driving", emp.getQ14_knowsCarDriving());
        map.put("q15_willing_to_travel", emp.getQ15_willingToTravel());
        map.put("q16_covid_vaccination", emp.getQ16_covidVaccination());
        map.put("q17_positive_points", emp.getQ17_positivePoints());
        map.put("q18_negative_points", emp.getQ18_negativePoints());
        map.put("q19_life_goals", emp.getQ19_lifeGoals());
        map.put("q20_improvement_suggestions", emp.getQ20_improvementSuggestions());
        map.put("q21_is_experienced", emp.getQ21_isExperienced());
        map.put("q22_total_experience", emp.getQ22_totalExperience());
        map.put("q23_core_experience", emp.getQ23_coreExperience());
        map.put("q24_prev_net_salary", emp.getQ24_prevNetSalary());
        map.put("q25_prev_gross_salary", emp.getQ25_prevGrossSalary());
        map.put("q26_expected_net_salary", emp.getQ26_expectedNetSalary());
        map.put("q27_expected_gross_salary", emp.getQ27_expectedGrossSalary());
        map.put("q28_pf_higher_pension", emp.getQ28_pfHigherPension());
        map.put("q29_pf_deduction_amount", emp.getQ29_pfDeductionAmount());
        map.put("q30_alternative_department", emp.getQ30_alternativeDepartment());
        map.put("q31_prev_location", emp.getQ31_prevLocation());
        map.put("q32_prev_shift", emp.getQ32_prevShift());
        map.put("q33_reason_for_leaving", emp.getQ33_reasonForLeaving());
        map.put("q34_notice_period", emp.getQ34_noticePeriod());
        map.put("q35_prev_dept_position", emp.getQ35_prevDeptPosition());
        map.put("q36_prev_dept_count", emp.getQ36_prevDeptCount());
        map.put("q37_prev_reporting_to", emp.getQ37_prevReportingTo());
        map.put("q38_handle_mistake", emp.getQ38_handleMistake());
        map.put("q39_handle_opinion_difference", emp.getQ39_handleOpinionDifference());
        map.put("q40_computer_self_rating", emp.getQ40_computerSelfRating());

        // Fetch personal detail
        Optional<EmployeePersonalDetail> personalOpt = personalRepo.findByEmployeeId(emp.getId());
        if (personalOpt.isPresent()) {
            EmployeePersonalDetail p = personalOpt.get();
            map.put("gender", p.getGender());
            map.put("maritalStatus", p.getMaritalStatus());
            map.put("panNo", p.getPanNumber());
            map.put("birthDate", p.getBirthDate());
            map.put("nationality", p.getNationality());
            map.put("religion", p.getReligion());
            map.put("aadharNo", p.getAadharNumber());
        }

        // Fetch contact
        Optional<EmployeeContact> contactOpt = contactRepo.findByEmployeeId(emp.getId());
        if (contactOpt.isPresent()) {
            EmployeeContact c = contactOpt.get();
            map.put("mobileNo", c.getMobile());
            map.put("emailId", personalOpt.map(EmployeePersonalDetail::getPersonalEmail).orElse(null));
            map.put("officePhoneNo", c.getAlternateMobile());
            map.put("phoneNo", c.getAlternateMobile());
            map.put("permAdd1", c.getAddress());
            map.put("city", c.getCity());
            map.put("state", c.getState());
            map.put("persAdd1", c.getCommAddress());
            map.put("contactAddress1", c.getCommAddress());
            map.put("contactCity", c.getCommCity());
            map.put("contactMobile", c.getMobile());
            map.put("contactPhone", c.getAlternateMobile());
        }

        // Fetch job profile for salary components
        Optional<EmployeeJobProfile> jpOpt = jobProfileRepo.findByEmployeeId(emp.getId());
        if (jpOpt.isPresent()) {
            EmployeeJobProfile jp = jpOpt.get();
            map.put("basic", jp.getBasicSalary());
            map.put("da", jp.getDa());
            map.put("hra", jp.getHra());
            map.put("splAllowance", jp.getSpecialAllowance());
            map.put("perfIncentive", jp.getPerformanceIncentive());
            map.put("canteenAllowance", jp.getCanteenAllowance());
            map.put("pfEmployee", jp.getPfEmployee());
            map.put("esiEmployee", jp.getEsiEmployee());
            map.put("profTax", jp.getProfessionalTaxAmount());
            map.put("grossSalary", jp.getGrossSalary());
            map.put("netSalary", jp.getNetSalary());
            map.put("ctc", jp.getMonthlyCtc());
            map.put("uniform", jp.getUniformAllowance());
            map.put("shoes", jp.getShoeAllowance());
            map.put("mobileCug", jp.getMobileAllowanceCug());
            map.put("pfEmployer", jp.getEmployerPf());
            map.put("esiEmployer", jp.getEmployerEsi());
            map.put("canteenDeduct", jp.getCanteenDeduction());
        }

        // Fetch lists: education, experience, kyc, skills
        List<EmployeeEducation> eduList = educationRepo.findByEmployeeId(emp.getId());
        List<Map<String, Object>> eduFrontend = new ArrayList<>();
        for (EmployeeEducation edu : eduList) {
            Map<String, Object> m = new HashMap<>();
            m.put("id", edu.getId());
            m.put("education", edu.getEducation());
            m.put("institutionName", edu.getInstitutionName());
            m.put("type", edu.getType());
            m.put("yearOfPassing", edu.getYearOfPassing());
            m.put("grade", edu.getPercentageGrade());
            m.put("filePath", edu.getCertificateFile());
            eduFrontend.add(m);
        }
        map.put("education", eduFrontend);

        List<EmployeeExperience> expList = experienceRepo.findByEmployeeId(emp.getId());
        List<Map<String, Object>> expFrontend = new ArrayList<>();
        for (EmployeeExperience exp : expList) {
            Map<String, Object> m = new HashMap<>();
            m.put("id", exp.getId());
            m.put("companyName", exp.getCompanyName());
            m.put("location", exp.getLocation());
            m.put("fromDate", exp.getFromDate());
            m.put("toDate", exp.getToDate());
            m.put("expYears", exp.getTotalExperienceMonths() != null ? exp.getTotalExperienceMonths().toString() : "");
            m.put("filePath", exp.getDocuments());
            expFrontend.add(m);
        }
        map.put("experience", expFrontend);

        List<EmployeeKycDocument> kycList = kycDocumentRepo.findByEmployeeId(emp.getId());
        List<Map<String, Object>> kycFrontend = new ArrayList<>();
        for (EmployeeKycDocument kyc : kycList) {
            Map<String, Object> m = new HashMap<>();
            m.put("id", kyc.getId());
            m.put("seqNo", kyc.getSeqNo());
            m.put("docName", kyc.getDocumentName());
            m.put("docNo", kyc.getDocumentNumber());
            m.put("filePath", kyc.getAttachment());
            kycFrontend.add(m);
        }
        map.put("kyc", kycFrontend);

        List<EmployeeActivity> actList = activityRepo.findByEmployeeId(emp.getId());
        List<Map<String, Object>> actFrontend = new ArrayList<>();
        for (EmployeeActivity act : actList) {
            Map<String, Object> m = new HashMap<>();
            m.put("id", act.getId());
            m.put("activityDetails", act.getActivityDetails());
            actFrontend.add(m);
        }
        map.put("skills", actFrontend);

        return map;
    }

    @SuppressWarnings("unchecked")
    private void saveOrUpdateApplicantDetails(EmployeeMaster emp, Map<String, Object> payload) {
        emp.setFirstName(getStringValue(payload, "firstName"));
        emp.setLastName(getStringValue(payload, "lastName"));
        emp.setTitle(getStringValue(payload, "title"));
        
        String deptStr = getStringValue(payload, "department");
        if (deptStr != null && !deptStr.isEmpty()) {
            try {
                emp.setDepartmentId(Long.parseLong(deptStr));
            } catch (NumberFormatException e) {
                // ignore
            }
        }
        
        emp.setPositionLookFor(getStringValue(payload, "positionLookFor"));
        emp.setReferMode(getStringValue(payload, "refMode"));
        emp.setReferenceComments(getStringValue(payload, "refComments"));
        emp.setApplicantDate(getDateValue(payload, "applicantDate"));
        
        Object ageObj = payload.get("age");
        if (ageObj != null) {
            try {
                emp.setAge(Integer.parseInt(ageObj.toString()));
            } catch (NumberFormatException e) {
                // ignore
            }
        }
        
        emp.setCallStatus(getStringValue(payload, "callStatus"));
        if (emp.getCallStatus() == null) emp.setCallStatus(getStringValue(payload, "call"));
        if (emp.getCallStatus() == null) emp.setCallStatus("PENDING");
        
        emp.setInterviewStatus(getStringValue(payload, "interviewStatus"));
        if (emp.getInterviewStatus() == null) emp.setInterviewStatus(getStringValue(payload, "interview"));
        if (emp.getInterviewStatus() == null) emp.setInterviewStatus("PENDING");
        
        emp.setOfferStatus(getStringValue(payload, "offerStatus"));
        if (emp.getOfferStatus() == null) emp.setOfferStatus(getStringValue(payload, "offer"));
        if (emp.getOfferStatus() == null) emp.setOfferStatus("PENDING");
        
        emp.setVerificationStatus(getStringValue(payload, "verificationStatus"));
        if (emp.getVerificationStatus() == null) emp.setVerificationStatus(getStringValue(payload, "verification"));
        if (emp.getVerificationStatus() == null) emp.setVerificationStatus("PENDING");
        
        emp.setStatus(getStringValue(payload, "status"));
        if (emp.getStatus() == null) emp.setStatus("APPLICANT");

        // Tab 8 Self Assessment fields
        emp.setQ1_native(getStringValue(payload, "q1_native"));
        emp.setQ2_presentAddress(getStringValue(payload, "q2_present_address"));
        emp.setQ3_permanentAddress(getStringValue(payload, "q3_permanent_address"));
        emp.setQ4_fatherOccupation(getStringValue(payload, "q4_father_occupation"));
        emp.setQ5_motherOccupation(getStringValue(payload, "q5_mother_occupation"));
        emp.setQ6_maritalStatus(getStringValue(payload, "q6_marital_status"));
        emp.setQ7_spouseOccupation(getStringValue(payload, "q7_spouse_occupation"));
        emp.setQ8_children(getStringValue(payload, "q8_children"));
        emp.setQ9_hasRelativesInCompany(getStringValue(payload, "q9_has_relatives"));
        emp.setQ10_relativesDetails(getStringValue(payload, "q10_relatives_details"));
        emp.setQ11_siblingsOccupations(getStringValue(payload, "q11_siblings_occupations"));
        emp.setQ12_hasTwoWheeler(getStringValue(payload, "q12_has_two_wheeler"));
        emp.setQ13_hasAndroidPhone(getStringValue(payload, "q13_has_android_phone"));
        emp.setQ14_knowsCarDriving(getStringValue(payload, "q14_knows_car_driving"));
        emp.setQ15_willingToTravel(getStringValue(payload, "q15_willing_to_travel"));
        emp.setQ16_covidVaccination(getStringValue(payload, "q16_covid_vaccination"));
        emp.setQ17_positivePoints(getStringValue(payload, "q17_positive_points"));
        emp.setQ18_negativePoints(getStringValue(payload, "q18_negative_points"));
        emp.setQ19_lifeGoals(getStringValue(payload, "q19_life_goals"));
        emp.setQ20_improvementSuggestions(getStringValue(payload, "q20_improvement_suggestions"));
        emp.setQ21_isExperienced(getStringValue(payload, "q21_is_experienced"));
        emp.setQ22_totalExperience(getStringValue(payload, "q22_total_experience"));
        emp.setQ23_coreExperience(getStringValue(payload, "q23_core_experience"));
        emp.setQ24_prevNetSalary(getStringValue(payload, "q24_prev_net_salary"));
        emp.setQ25_prevGrossSalary(getStringValue(payload, "q25_prev_gross_salary"));
        emp.setQ26_expectedNetSalary(getStringValue(payload, "q26_expected_net_salary"));
        emp.setQ27_expectedGrossSalary(getStringValue(payload, "q27_expected_gross_salary"));
        emp.setQ28_pfHigherPension(getStringValue(payload, "q28_pf_higher_pension"));
        emp.setQ29_pfDeductionAmount(getStringValue(payload, "q29_pf_deduction_amount"));
        emp.setQ30_alternativeDepartment(getStringValue(payload, "q30_alternative_department"));
        emp.setQ31_prevLocation(getStringValue(payload, "q31_prev_location"));
        emp.setQ32_prevShift(getStringValue(payload, "q32_prev_shift"));
        emp.setQ33_reasonForLeaving(getStringValue(payload, "q33_reason_for_leaving"));
        emp.setQ34_noticePeriod(getStringValue(payload, "q34_notice_period"));
        emp.setQ35_prevDeptPosition(getStringValue(payload, "q35_prev_dept_position"));
        emp.setQ36_prevDeptCount(getStringValue(payload, "q36_prev_dept_count"));
        emp.setQ37_prevReportingTo(getStringValue(payload, "q37_prev_reporting_to"));
        emp.setQ38_handleMistake(getStringValue(payload, "q38_handle_mistake"));
        emp.setQ39_handleOpinionDifference(getStringValue(payload, "q39_handle_opinion_difference"));
        emp.setQ40_computerSelfRating(getStringValue(payload, "q40_computer_self_rating"));
        emp.setPayslipPath(getStringValue(payload, "payslipPath"));

        employeeRepo.save(emp);
        Long empId = emp.getId();

        EmployeePersonalDetail p = personalRepo.findByEmployeeId(empId).orElse(new EmployeePersonalDetail());
        p.setEmployeeId(empId);
        p.setGender(getStringValue(payload, "gender"));
        p.setMaritalStatus(getStringValue(payload, "maritalStatus"));
        p.setPanNumber(getStringValue(payload, "panNo"));
        p.setBirthDate(getDateValue(payload, "birthDate"));
        p.setNationality(getStringValue(payload, "nationality"));
        p.setReligion(getStringValue(payload, "religion"));
        p.setAadharNumber(getStringValue(payload, "aadharNo"));
        p.setPersonalEmail(getStringValue(payload, "emailId"));
        personalRepo.save(p);

        EmployeeContact c = contactRepo.findByEmployeeId(empId).orElse(new EmployeeContact());
        c.setEmployeeId(empId);
        c.setMobile(getStringValue(payload, "mobileNo"));
        c.setAlternateMobile(getStringValue(payload, "officePhoneNo"));
        if (c.getAlternateMobile() == null) c.setAlternateMobile(getStringValue(payload, "phoneNo"));
        c.setAddress(getStringValue(payload, "permAdd1"));
        c.setCity(getStringValue(payload, "city"));
        c.setState(getStringValue(payload, "state"));
        c.setCommAddress(getStringValue(payload, "persAdd1"));
        if (c.getCommAddress() == null) c.setCommAddress(getStringValue(payload, "contactAddress1"));
        c.setCommCity(getStringValue(payload, "contactCity"));
        contactRepo.save(c);

        EmployeeJobProfile jp = jobProfileRepo.findByEmployeeId(empId).orElse(new EmployeeJobProfile());
        jp.setEmployeeId(empId);
        jp.setBasicSalary(getBigDecimalValue(payload, "basic"));
        jp.setDa(getBigDecimalValue(payload, "da"));
        jp.setHra(getBigDecimalValue(payload, "hra"));
        jp.setSpecialAllowance(getBigDecimalValue(payload, "splAllowance"));
        jp.setPerformanceIncentive(getBigDecimalValue(payload, "perfIncentive"));
        jp.setCanteenAllowance(getBigDecimalValue(payload, "canteenAllowance"));
        jp.setPfEmployee(getBigDecimalValue(payload, "pfEmployee"));
        jp.setEsiEmployee(getBigDecimalValue(payload, "esiEmployee"));
        jp.setProfessionalTaxAmount(getBigDecimalValue(payload, "profTax"));
        jp.setGrossSalary(getBigDecimalValue(payload, "grossSalary"));
        jp.setNetSalary(getBigDecimalValue(payload, "netSalary"));
        jp.setMonthlyCtc(getBigDecimalValue(payload, "ctc"));
        jp.setUniformAllowance(getBigDecimalValue(payload, "uniform"));
        jp.setShoeAllowance(getBigDecimalValue(payload, "shoes"));
        jp.setMobileAllowanceCug(getBigDecimalValue(payload, "mobileCug"));
        jp.setEmployerPf(getBigDecimalValue(payload, "pfEmployer"));
        jp.setEmployerEsi(getBigDecimalValue(payload, "esiEmployer"));
        jp.setCanteenDeduction(getBigDecimalValue(payload, "canteenDeduct"));
        jobProfileRepo.save(jp);

        educationRepo.deleteByEmployeeId(empId);
        List<Map<String, Object>> eduList = (List<Map<String, Object>>) payload.get("education");
        if (eduList != null) {
            for (Map<String, Object> eduMap : eduList) {
                EmployeeEducation edu = new EmployeeEducation();
                edu.setEmployeeId(empId);
                edu.setEducation(getStringValue(eduMap, "education"));
                edu.setInstitutionName(getStringValue(eduMap, "institutionName"));
                edu.setType(getStringValue(eduMap, "type"));
                edu.setYearOfPassing(getStringValue(eduMap, "yearOfPassing"));
                edu.setPercentageGrade(getStringValue(eduMap, "grade"));
                edu.setCertificateFile(getStringValue(eduMap, "filePath"));
                educationRepo.save(edu);
            }
        }

        experienceRepo.deleteByEmployeeId(empId);
        List<Map<String, Object>> expList = (List<Map<String, Object>>) payload.get("experience");
        if (expList != null) {
            for (Map<String, Object> expMap : expList) {
                EmployeeExperience exp = new EmployeeExperience();
                exp.setEmployeeId(empId);
                exp.setCompanyName(getStringValue(expMap, "companyName"));
                exp.setLocation(getStringValue(expMap, "location"));
                exp.setFromDate(getDateValue(expMap, "fromDate"));
                exp.setToDate(getDateValue(expMap, "toDate"));
                String expYearsStr = getStringValue(expMap, "expYears");
                if (expYearsStr != null && !expYearsStr.isEmpty()) {
                    try {
                        exp.setTotalExperienceMonths(Integer.parseInt(expYearsStr));
                    } catch (NumberFormatException e) {
                        // ignore
                    }
                }
                exp.setDocuments(getStringValue(expMap, "filePath"));
                experienceRepo.save(exp);
            }
        }

        kycDocumentRepo.deleteByEmployeeId(empId);
        List<Map<String, Object>> kycList = (List<Map<String, Object>>) payload.get("kyc");
        if (kycList != null) {
            for (Map<String, Object> kycMap : kycList) {
                EmployeeKycDocument kyc = new EmployeeKycDocument();
                kyc.setEmployeeId(empId);
                Object seqObj = kycMap.get("seqNo");
                if (seqObj != null) {
                    try {
                        kyc.setSeqNo(Integer.parseInt(seqObj.toString()));
                    } catch (NumberFormatException e) {
                        // ignore
                    }
                }
                kyc.setDocumentName(getStringValue(kycMap, "docName"));
                kyc.setDocumentNumber(getStringValue(kycMap, "docNo"));
                kyc.setAttachment(getStringValue(kycMap, "filePath"));
                kycDocumentRepo.save(kyc);
            }
        }

        activityRepo.deleteByEmployeeId(empId);
        List<Map<String, Object>> skillList = (List<Map<String, Object>>) payload.get("skills");
        if (skillList != null) {
            for (Map<String, Object> skillMap : skillList) {
                EmployeeActivity act = new EmployeeActivity();
                act.setEmployeeId(empId);
                act.setActivityDetails(getStringValue(skillMap, "activityDetails"));
                activityRepo.save(act);
            }
        }
    }
}
