package com.autonoma.erp.config;

import org.springframework.boot.CommandLineRunner;
import org.springframework.core.annotation.Order;
import org.springframework.core.io.Resource;
import org.springframework.core.io.support.PathMatchingResourcePatternResolver;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.stereotype.Component;

import java.io.BufferedReader;
import java.io.InputStreamReader;
import java.nio.charset.StandardCharsets;
import java.util.Arrays;
import java.util.List;
import java.util.stream.Collectors;

@Component
@Order(1)
public class SqlMigrationRunner implements CommandLineRunner {

    private final JdbcTemplate jdbcTemplate;

    public SqlMigrationRunner(JdbcTemplate jdbcTemplate) {
        this.jdbcTemplate = jdbcTemplate;
    }

    @Override
    public void run(String... args) throws Exception {
        runMigrations(this.jdbcTemplate);
    }

    public void runMigrations(JdbcTemplate targetJdbcTemplate) throws Exception {
        System.out.println("======================================");
        System.out.println("SQL MIGRATION STARTED FOR DYNAMIC TEMPLATE");
        System.out.println("======================================");

        createMigrationTables(targetJdbcTemplate);

        PathMatchingResourcePatternResolver resolver = new PathMatchingResourcePatternResolver();

        Resource[] resources = resolver.getResources("classpath:dbscripts/*.sql");

        List<Resource> sortedResources = Arrays.stream(resources)
                .sorted((r1, r2) -> {
                    String f1 = r1.getFilename();
                    String f2 = r2.getFilename();

                    if (f1 == null || f2 == null) {
                        return 0;
                    }

                    return f1.compareToIgnoreCase(f2);
                })
                .collect(Collectors.toList());

        for (Resource resource : sortedResources) {

            String fileName = resource.getFilename();

            try {

                if (isAlreadyExecuted(targetJdbcTemplate, fileName)) {

                    System.out.println("ALREADY EXECUTED : " + fileName);

                    continue;
                }

                System.out.println("EXECUTING : " + fileName);

                String sql = readSqlFile(resource);

                sql = removeUseStatements(sql);

                String[] batches = sql.split("(?im)^\\s*GO\\s*$");

                for (String batch : batches) {

                    if (batch == null || batch.trim().isEmpty()) {
                        continue;
                    }

                    if (shouldSkipBatch(targetJdbcTemplate, batch)) {

                        System.out.println("SKIPPED BATCH");

                        continue;
                    }

                    try {

                        targetJdbcTemplate.execute(batch);

                    } catch (Exception e) {

                        System.out.println("BATCH FAILED BUT CONTINUING");
                        System.out.println("REASON : " + e.getMessage());

                    }
                }

                markAsExecuted(targetJdbcTemplate, fileName);

                System.out.println("COMPLETED : " + fileName);

            } catch (Exception e) {

                System.out.println("FAILED FILE : " + fileName);

                System.out.println("ERROR : " + e.getMessage());

                insertFailedScript(targetJdbcTemplate, fileName, e.getMessage());
            }
        }

        System.out.println("======================================");
        System.out.println("SQL MIGRATION COMPLETED FOR DYNAMIC TEMPLATE");
        System.out.println("======================================");
    }

    private void createMigrationTables(JdbcTemplate targetJdbcTemplate) {
        boolean isH2 = false;
        try {
            String url = targetJdbcTemplate.getDataSource().getConnection().getMetaData().getURL();
            if (url != null && url.contains(":h2:")) {
                isH2 = true;
            }
        } catch (Exception e) {
            // Default to SQL Server if check fails
        }

        if (isH2) {
            targetJdbcTemplate.execute("""
                CREATE TABLE IF NOT EXISTS ERP_EXECUTED_SCRIPTS (
                    ID BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    SCRIPT_NAME VARCHAR(500) UNIQUE,
                    EXECUTED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
                )
            """);

            targetJdbcTemplate.execute("""
                CREATE TABLE IF NOT EXISTS ERP_FAILED_SCRIPTS (
                    ID BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    SCRIPT_NAME VARCHAR(500),
                    ERROR_MESSAGE CLOB,
                    FAILED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
                )
            """);
        } else {


            targetJdbcTemplate.execute("""
                        IF OBJECT_ID('ERP_EXECUTED_SCRIPTS', 'U') IS NULL
                        BEGIN
                            CREATE TABLE ERP_EXECUTED_SCRIPTS (
                                ID BIGINT IDENTITY(1,1) PRIMARY KEY,
                                SCRIPT_NAME NVARCHAR(500) UNIQUE,
                                EXECUTED_AT DATETIME DEFAULT GETDATE()
                            )
                        END
                    """);

            targetJdbcTemplate.execute("""
                        IF OBJECT_ID('ERP_FAILED_SCRIPTS', 'U') IS NULL
                        BEGIN
                            CREATE TABLE ERP_FAILED_SCRIPTS (
                                ID BIGINT IDENTITY(1,1) PRIMARY KEY,
                                SCRIPT_NAME NVARCHAR(500),
                                ERROR_MESSAGE NVARCHAR(MAX),
                                FAILED_AT DATETIME DEFAULT GETDATE()
                            )
                        END
                    """);
        }
    }


    private boolean isAlreadyExecuted(JdbcTemplate targetJdbcTemplate, String fileName) {

        Integer count = targetJdbcTemplate.queryForObject(
                "SELECT COUNT(*) FROM ERP_EXECUTED_SCRIPTS WHERE SCRIPT_NAME = ?",
                Integer.class,
                fileName);

        if (count != null && count > 0) {
            return true;
        }

        // Backward compatibility: If the file is date-prefixed (e.g. 20260512_V3.4_1__...),
        // check if it has already been executed under its old unprefixed name.
        if (fileName != null && fileName.matches("^\\d{8}_.*")) {
            String suffixName = fileName.substring(9); // strip YYYYMMDD_ (9 chars)
            Integer suffixCount = targetJdbcTemplate.queryForObject(
                    "SELECT COUNT(*) FROM ERP_EXECUTED_SCRIPTS WHERE SCRIPT_NAME = ?",
                    Integer.class,
                    suffixName);
            if (suffixCount != null && suffixCount > 0) {
                // Self-healing: mark the new prefixed name as executed to prevent redundant queries in the future
                try {
                    markAsExecuted(targetJdbcTemplate, fileName);
                } catch (Exception e) {
                    // Ignore constraint/duplicate issues
                }
                return true;
            }
        }

        return false;
    }

    private void markAsExecuted(JdbcTemplate targetJdbcTemplate, String fileName) {

        targetJdbcTemplate.update(
                "INSERT INTO ERP_EXECUTED_SCRIPTS (SCRIPT_NAME) VALUES (?)",
                fileName);
    }

    private void insertFailedScript(JdbcTemplate targetJdbcTemplate, String fileName, String errorMessage) {

        targetJdbcTemplate.update(
                "INSERT INTO ERP_FAILED_SCRIPTS (SCRIPT_NAME, ERROR_MESSAGE) VALUES (?, ?)",
                fileName,
                errorMessage);
    }

    private String readSqlFile(Resource resource) throws Exception {

        return new BufferedReader(
                new InputStreamReader(
                        resource.getInputStream(),
                        StandardCharsets.UTF_8))
                .lines().collect(Collectors.joining("\n"));
    }

    private String removeUseStatements(String sql) {

        return sql.replaceAll(
                "(?im)^\\s*USE\\s+[\\[\\]a-zA-Z0-9_]+;?\\s*$",
                "");
    }

    private boolean shouldSkipBatch(JdbcTemplate targetJdbcTemplate, String sql) {

        try {

            String upperSql = sql.toUpperCase();

            // ALTER TABLE ADD COLUMN CHECK
            if (upperSql.contains("ALTER TABLE")
                    && upperSql.contains(" ADD ")) {

                String tableName = extractTableName(sql);

                String columnName = extractColumnName(sql);

                if (tableName != null && columnName != null) {

                    Integer count = targetJdbcTemplate.queryForObject("""
                                SELECT COUNT(*)
                                FROM INFORMATION_SCHEMA.COLUMNS
                                WHERE TABLE_NAME = ?
                                AND COLUMN_NAME = ?
                            """, Integer.class, tableName, columnName);

                    if (count != null && count > 0) {

                        System.out.println(
                                "COLUMN ALREADY EXISTS : "
                                        + tableName + "." + columnName);

                        return true;
                    }
                }
            }

        } catch (Exception e) {

            System.out.println(
                    "VALIDATION FAILED : " + e.getMessage());
        }

        return false;
    }

    private String extractTableName(String sql) {

        try {

            String upperSql = sql.toUpperCase();

            int alterIndex = upperSql.indexOf("ALTER TABLE");

            int addIndex = upperSql.indexOf(" ADD ");

            if (alterIndex == -1 || addIndex == -1) {
                return null;
            }

            return sql.substring(alterIndex + 11, addIndex)
                    .replace("[", "")
                    .replace("]", "")
                    .replace("dbo.", "")
                    .trim();

        } catch (Exception e) {

            return null;
        }
    }

    private String extractColumnName(String sql) {

        try {

            String upperSql = sql.toUpperCase();

            int addIndex = upperSql.indexOf(" ADD ");

            if (addIndex == -1) {
                return null;
            }

            String columnPart = sql.substring(addIndex + 5).trim();

            return columnPart.split("\\s+")[0]
                    .replace("[", "")
                    .replace("]", "")
                    .replace(",", "")
                    .trim();

        } catch (Exception e) {

            return null;
        }
    }
}