import * as XLSX from 'xlsx';
import { saveAs } from 'file-saver';

/**
 * Standard BOS Excel Export with Header Metadata
 * @param {Array} data - Array of objects to export
 * @param {String} fileName - Name of the file
 * @param {Object} headerInfo - Optional metadata { userName: string }
 */
export const exportToExcel = (data, fileName, headerInfo = {}) => {
  const sheetName = 'BOS Report';
  const timestamp = new Date().toLocaleString('en-GB', { 
    day: '2-digit', month: 'short', year: 'numeric', 
    hour: '2-digit', minute: '2-digit', second: '2-digit' 
  });

  // 1. Create a worksheet from the JSON data
  const worksheet = XLSX.utils.json_to_sheet([]);

  // 2. Add Header Information at the top
  XLSX.utils.sheet_add_aoa(worksheet, [
    ['AUTONOMA BUSINESS OPERATING SYSTEM'],
    [`Report Name: ${fileName.replace(/_/g, ' ')}`],
    [`Generated By: ${headerInfo.userName || 'System'}`],
    [`Generated On: ${timestamp}`],
    [] // Empty row spacer
  ], { origin: 'A1' });

  // 3. Add the main data starting from row 6
  XLSX.utils.sheet_add_json(worksheet, data, { origin: 'A6', skipHeader: false });

  // 4. Auto-calculate column widths
  const colWidths = Object.keys(data[0] || {}).map(key => {
    const headerLen = key.length;
    const maxDataLen = data.reduce((max, row) => {
      const val = row[key] ? String(row[key]).length : 0;
      return Math.max(max, val);
    }, 0);
    return { wch: Math.max(headerLen, maxDataLen, 10) + 2 };
  });
  worksheet['!cols'] = colWidths;

  // 5. Stylize the header (basic XLSX style support is limited in community version, so we focus on structure)
  const workbook = XLSX.utils.book_new();
  XLSX.utils.book_append_sheet(workbook, worksheet, sheetName);

  // 6. Finalize and Save
  const excelBuffer = XLSX.write(workbook, { bookType: 'xlsx', type: 'array' });
  const dataBlob = new Blob([excelBuffer], { type: 'application/octet-stream' });
  saveAs(dataBlob, `${fileName}_${new Date().getTime()}.xlsx`);
};
