-- Sync QMS_MASTER_CHECKLIST table with Java Entity
-- Adding missing columns required by the MasterChecklist model

IF NOT EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID(N'[dbo].[QMS_MASTER_CHECKLIST]') AND name = 'LAST_COMPLETED_DATE')
BEGIN
    ALTER TABLE [dbo].[QMS_MASTER_CHECKLIST] ADD [LAST_COMPLETED_DATE] DATE;
END

IF NOT EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID(N'[dbo].[QMS_MASTER_CHECKLIST]') AND name = 'NEXT_DUE_DATE')
BEGIN
    ALTER TABLE [dbo].[QMS_MASTER_CHECKLIST] ADD [NEXT_DUE_DATE] DATE;
END

IF NOT EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID(N'[dbo].[QMS_MASTER_CHECKLIST]') AND name = 'TASK_STATUS')
BEGIN
    ALTER TABLE [dbo].[QMS_MASTER_CHECKLIST] ADD [TASK_STATUS] NVARCHAR(50);
END

IF NOT EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID(N'[dbo].[QMS_MASTER_CHECKLIST]') AND name = 'VERIFY_STATUS')
BEGIN
    ALTER TABLE [dbo].[QMS_MASTER_CHECKLIST] ADD [VERIFY_STATUS] NVARCHAR(50);
END

IF NOT EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID(N'[dbo].[QMS_MASTER_CHECKLIST]') AND name = 'VERIFIED_BY')
BEGIN
    ALTER TABLE [dbo].[QMS_MASTER_CHECKLIST] ADD [VERIFIED_BY] NVARCHAR(100);
END

IF NOT EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID(N'[dbo].[QMS_MASTER_CHECKLIST]') AND name = 'VERIFIED_DATE')
BEGIN
    ALTER TABLE [dbo].[QMS_MASTER_CHECKLIST] ADD [VERIFIED_DATE] DATETIME;
END

IF NOT EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID(N'[dbo].[QMS_MASTER_CHECKLIST]') AND name = 'REJ_REASON')
BEGIN
    ALTER TABLE [dbo].[QMS_MASTER_CHECKLIST] ADD [REJ_REASON] NVARCHAR(MAX);
END

IF NOT EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID(N'[dbo].[QMS_MASTER_CHECKLIST]') AND name = 'ASSIGN_TO')
BEGIN
    ALTER TABLE [dbo].[QMS_MASTER_CHECKLIST] ADD [ASSIGN_TO] NVARCHAR(100);
END

IF NOT EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID(N'[dbo].[QMS_MASTER_CHECKLIST]') AND name = 'ASSIGN_DATE')
BEGIN
    ALTER TABLE [dbo].[QMS_MASTER_CHECKLIST] ADD [ASSIGN_DATE] DATE;
END

IF NOT EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID(N'[dbo].[QMS_MASTER_CHECKLIST]') AND name = 'ITEM_CODE')
BEGIN
    ALTER TABLE [dbo].[QMS_MASTER_CHECKLIST] ADD [ITEM_CODE] NVARCHAR(100);
END

IF NOT EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID(N'[dbo].[QMS_MASTER_CHECKLIST]') AND name = 'QTY')
BEGIN
    ALTER TABLE [dbo].[QMS_MASTER_CHECKLIST] ADD [QTY] NVARCHAR(50);
END

IF NOT EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID(N'[dbo].[QMS_MASTER_CHECKLIST]') AND name = 'DUAL_CHECK')
BEGIN
    ALTER TABLE [dbo].[QMS_MASTER_CHECKLIST] ADD [DUAL_CHECK] NVARCHAR(10) DEFAULT 'NO';
END

IF NOT EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID(N'[dbo].[QMS_MASTER_CHECKLIST]') AND name = 'CARRY_FORWARD')
BEGIN
    ALTER TABLE [dbo].[QMS_MASTER_CHECKLIST] ADD [CARRY_FORWARD] NVARCHAR(10) DEFAULT 'NO';
END
