-- Add Attachment columns to QMS_MASTER_CHECKLIST
IF NOT EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID(N'[dbo].[QMS_MASTER_CHECKLIST]') AND name = 'UPLOADED_FILES')
BEGIN
    ALTER TABLE [dbo].[QMS_MASTER_CHECKLIST] ADD [UPLOADED_FILES] NVARCHAR(MAX);
END

IF NOT EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID(N'[dbo].[QMS_MASTER_CHECKLIST]') AND name = 'SCANNED_FILES')
BEGIN
    ALTER TABLE [dbo].[QMS_MASTER_CHECKLIST] ADD [SCANNED_FILES] NVARCHAR(MAX);
END
