-- V003__HR_Master_Module.sql
-- Phase 3: HR Department & Designation Masters Schema Standardization
-- Renames and normalizes:
-- 1. HR_DEPARTMENT_MASTER -> HR_DEPARTMENT
-- 2. HR_DESIGNATION_MASTER -> HR_DESIGNATION
-- 3. HR_DESIGNATION_LEVEL
-- 4. HR_LEVEL_MASTER -> HR_LEVEL
-- 5. HR_EMPLOYEE_TYPE_MASTER -> HR_EMPLOYEE_TYPE

-- ==========================================
-- Drop referencing Foreign Key constraints dynamically to avoid cascade/drop errors
-- ==========================================
DECLARE @sql NVARCHAR(MAX) = N'';
SELECT @sql += N'ALTER TABLE ' + QUOTENAME(OBJECT_SCHEMA_NAME(parent_object_id)) + '.' + QUOTENAME(OBJECT_NAME(parent_object_id)) + 
               ' DROP CONSTRAINT ' + QUOTENAME(name) + ';' + CHAR(13) + CHAR(10)
FROM sys.foreign_keys
WHERE referenced_object_id IN (
    OBJECT_ID('HR_DEPARTMENT_MASTER'),
    OBJECT_ID('hrm_department_master'),
    OBJECT_ID('HR_DESIGNATION_MASTER'),
    OBJECT_ID('hrm_designation_master'),
    OBJECT_ID('HR_DESIGNATION_LEVEL'),
    OBJECT_ID('hrm_designation_level'),
    OBJECT_ID('HR_LEVEL_MASTER'),
    OBJECT_ID('hrm_level_master'),
    OBJECT_ID('HR_EMPLOYEE_TYPE_MASTER'),
    OBJECT_ID('hrm_employee_type_master')
);
IF @sql <> N''
BEGIN
    EXEC sp_executesql @sql;
END
GO

-- ==========================================
-- 1. HR_DEPARTMENT
-- ==========================================
IF OBJECT_ID('dbo.sp_RenameTableCasingAndPrefix', 'P') IS NOT NULL
BEGIN
    EXEC dbo.sp_RenameTableCasingAndPrefix 'HR_DEPARTMENT_MASTER', 'HR_DEPARTMENT';
END
ELSE
BEGIN
    IF OBJECT_ID('HR_DEPARTMENT_MASTER', 'U') IS NOT NULL AND OBJECT_ID('HR_DEPARTMENT', 'U') IS NULL
        EXEC sp_rename 'HR_DEPARTMENT_MASTER', 'HR_DEPARTMENT';
END
GO

IF COL_LENGTH('HR_DEPARTMENT', 'dept_no') IS NOT NULL
    EXEC sp_rename 'HR_DEPARTMENT.dept_no', 'DEPARTMENT_NO', 'COLUMN';
GO
IF COL_LENGTH('HR_DEPARTMENT', 'DEPT_NO') IS NOT NULL
    EXEC sp_rename 'HR_DEPARTMENT.DEPT_NO', 'DEPARTMENT_NO', 'COLUMN';
GO

IF COL_LENGTH('HR_DEPARTMENT', 'dept_name') IS NOT NULL
    EXEC sp_rename 'HR_DEPARTMENT.dept_name', 'DEPARTMENT_NAME', 'COLUMN';
GO
IF COL_LENGTH('HR_DEPARTMENT', 'DEPT_NAME') IS NOT NULL
    EXEC sp_rename 'HR_DEPARTMENT.DEPT_NAME', 'DEPARTMENT_NAME', 'COLUMN';
GO

IF COL_LENGTH('HR_DEPARTMENT', 'nda_certificate') IS NOT NULL
    EXEC sp_rename 'HR_DEPARTMENT.nda_certificate', 'NDA_CERTIFICATE', 'COLUMN';
GO
IF COL_LENGTH('HR_DEPARTMENT', 'NDA_CERTIFICATE') IS NOT NULL
    EXEC sp_rename 'HR_DEPARTMENT.NDA_CERTIFICATE', 'NDA_CERTIFICATE', 'COLUMN';
GO

IF COL_LENGTH('HR_DEPARTMENT', 'seq_no') IS NOT NULL
    EXEC sp_rename 'HR_DEPARTMENT.seq_no', 'SEQUENCE_NO', 'COLUMN';
GO
IF COL_LENGTH('HR_DEPARTMENT', 'SEQ_NO') IS NOT NULL
    EXEC sp_rename 'HR_DEPARTMENT.SEQ_NO', 'SEQUENCE_NO', 'COLUMN';
GO

IF COL_LENGTH('HR_DEPARTMENT', 'status') IS NOT NULL
    EXEC sp_rename 'HR_DEPARTMENT.status', 'STATUS', 'COLUMN';
GO
IF COL_LENGTH('HR_DEPARTMENT', 'STATUS') IS NOT NULL
    EXEC sp_rename 'HR_DEPARTMENT.STATUS', 'STATUS', 'COLUMN';
GO

IF COL_LENGTH('HR_DEPARTMENT', 'created_by') IS NOT NULL
    EXEC sp_rename 'HR_DEPARTMENT.created_by', 'CREATED_BY', 'COLUMN';
GO
IF COL_LENGTH('HR_DEPARTMENT', 'CREATED_BY') IS NOT NULL
    EXEC sp_rename 'HR_DEPARTMENT.CREATED_BY', 'CREATED_BY', 'COLUMN';
GO

IF COL_LENGTH('HR_DEPARTMENT', 'created_at') IS NOT NULL
    EXEC sp_rename 'HR_DEPARTMENT.created_at', 'CREATED_DATE', 'COLUMN';
GO
IF COL_LENGTH('HR_DEPARTMENT', 'CREATED_DATE') IS NOT NULL
    EXEC sp_rename 'HR_DEPARTMENT.CREATED_DATE', 'CREATED_DATE', 'COLUMN';
GO

IF COL_LENGTH('HR_DEPARTMENT', 'updated_by') IS NOT NULL
    EXEC sp_rename 'HR_DEPARTMENT.updated_by', 'UPDATED_BY', 'COLUMN';
GO
IF COL_LENGTH('HR_DEPARTMENT', 'UPDATED_BY') IS NOT NULL
    EXEC sp_rename 'HR_DEPARTMENT.UPDATED_BY', 'UPDATED_BY', 'COLUMN';
GO

IF COL_LENGTH('HR_DEPARTMENT', 'updated_at') IS NOT NULL
    EXEC sp_rename 'HR_DEPARTMENT.updated_at', 'UPDATED_DATE', 'COLUMN';
GO
IF COL_LENGTH('HR_DEPARTMENT', 'UPDATED_DATE') IS NOT NULL
    EXEC sp_rename 'HR_DEPARTMENT.UPDATED_DATE', 'UPDATED_DATE', 'COLUMN';
GO

IF OBJECT_ID('HR_DEPARTMENT', 'U') IS NOT NULL
BEGIN
    ALTER TABLE HR_DEPARTMENT ALTER COLUMN DEPARTMENT_NO NVARCHAR(20) NOT NULL;
    ALTER TABLE HR_DEPARTMENT ALTER COLUMN DEPARTMENT_NAME NVARCHAR(100) NOT NULL;
    ALTER TABLE HR_DEPARTMENT ALTER COLUMN NDA_CERTIFICATE NVARCHAR(10);
    ALTER TABLE HR_DEPARTMENT ALTER COLUMN STATUS NVARCHAR(20);
    ALTER TABLE HR_DEPARTMENT ALTER COLUMN CREATED_BY NVARCHAR(100);
    ALTER TABLE HR_DEPARTMENT ALTER COLUMN CREATED_DATE DATETIME;
    ALTER TABLE HR_DEPARTMENT ALTER COLUMN UPDATED_BY NVARCHAR(100);
    ALTER TABLE HR_DEPARTMENT ALTER COLUMN UPDATED_DATE DATETIME;

    IF COL_LENGTH('HR_DEPARTMENT', 'IS_ACTIVE') IS NULL
    BEGIN
        ALTER TABLE HR_DEPARTMENT ADD IS_ACTIVE BIT DEFAULT 1;
    END
END
GO

IF OBJECT_ID('HR_DEPARTMENT', 'U') IS NOT NULL
BEGIN
    DECLARE @dept_pk NVARCHAR(256);
    SELECT TOP 1 @dept_pk = name 
    FROM sys.key_constraints 
    WHERE parent_object_id = OBJECT_ID('HR_DEPARTMENT') AND type = 'PK';
    
    IF @dept_pk IS NOT NULL AND @dept_pk <> 'PK_HR_DEPARTMENT' AND NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE referenced_object_id = OBJECT_ID('HR_DEPARTMENT'))
    BEGIN
        DECLARE @drop_dept_pk NVARCHAR(MAX) = 'ALTER TABLE HR_DEPARTMENT DROP CONSTRAINT ' + @dept_pk;
        EXEC(@drop_dept_pk);
    END
    
    IF NOT EXISTS (SELECT 1 FROM sys.key_constraints WHERE parent_object_id = OBJECT_ID('HR_DEPARTMENT') AND type = 'PK')
    BEGIN
        ALTER TABLE HR_DEPARTMENT ADD CONSTRAINT PK_HR_DEPARTMENT PRIMARY KEY (id);
    END
END
GO


-- ==========================================
-- 2. HR_DESIGNATION
-- ==========================================
IF OBJECT_ID('dbo.sp_RenameTableCasingAndPrefix', 'P') IS NOT NULL
BEGIN
    EXEC dbo.sp_RenameTableCasingAndPrefix 'HR_DESIGNATION_MASTER', 'HR_DESIGNATION';
END
ELSE
BEGIN
    IF OBJECT_ID('HR_DESIGNATION_MASTER', 'U') IS NOT NULL AND OBJECT_ID('HR_DESIGNATION', 'U') IS NULL
        EXEC sp_rename 'HR_DESIGNATION_MASTER', 'HR_DESIGNATION';
END
GO

IF COL_LENGTH('HR_DESIGNATION', 'designation_code') IS NOT NULL
    EXEC sp_rename 'HR_DESIGNATION.designation_code', 'DESIGNATION_CODE', 'COLUMN';
GO
IF COL_LENGTH('HR_DESIGNATION', 'designationCode') IS NOT NULL
    EXEC sp_rename 'HR_DESIGNATION.designationCode', 'DESIGNATION_CODE', 'COLUMN';
GO

IF COL_LENGTH('HR_DESIGNATION', 'designation_name') IS NOT NULL
    EXEC sp_rename 'HR_DESIGNATION.designation_name', 'DESIGNATION_NAME', 'COLUMN';
GO
IF COL_LENGTH('HR_DESIGNATION', 'designationName') IS NOT NULL
    EXEC sp_rename 'HR_DESIGNATION.designationName', 'DESIGNATION_NAME', 'COLUMN';
GO

IF COL_LENGTH('HR_DESIGNATION', 'sub_category_level') IS NOT NULL
    EXEC sp_rename 'HR_DESIGNATION.sub_category_level', 'SUB_CATEGORY_LEVEL', 'COLUMN';
GO
IF COL_LENGTH('HR_DESIGNATION', 'subCategoryLevel') IS NOT NULL
    EXEC sp_rename 'HR_DESIGNATION.subCategoryLevel', 'SUB_CATEGORY_LEVEL', 'COLUMN';
GO

IF COL_LENGTH('HR_DESIGNATION', 'experience') IS NOT NULL
    EXEC sp_rename 'HR_DESIGNATION.experience', 'EXPERIENCE', 'COLUMN';
GO

IF COL_LENGTH('HR_DESIGNATION', 'appear_in_competency') IS NOT NULL
    EXEC sp_rename 'HR_DESIGNATION.appear_in_competency', 'APPEAR_IN_COMPETENCY', 'COLUMN';
GO
IF COL_LENGTH('HR_DESIGNATION', 'appearInCompetency') IS NOT NULL
    EXEC sp_rename 'HR_DESIGNATION.appearInCompetency', 'APPEAR_IN_COMPETENCY', 'COLUMN';
GO

IF COL_LENGTH('HR_DESIGNATION', 'display_sl_no') IS NOT NULL
    EXEC sp_rename 'HR_DESIGNATION.display_sl_no', 'DISPLAY_SL_NO', 'COLUMN';
GO
IF COL_LENGTH('HR_DESIGNATION', 'displaySlNo') IS NOT NULL
    EXEC sp_rename 'HR_DESIGNATION.displaySlNo', 'DISPLAY_SL_NO', 'COLUMN';
GO

IF COL_LENGTH('HR_DESIGNATION', 'qualification') IS NOT NULL
    EXEC sp_rename 'HR_DESIGNATION.qualification', 'QUALIFICATION', 'COLUMN';
GO

IF COL_LENGTH('HR_DESIGNATION', 'job_description') IS NOT NULL
    EXEC sp_rename 'HR_DESIGNATION.job_description', 'JOB_DESCRIPTION', 'COLUMN';
GO
IF COL_LENGTH('HR_DESIGNATION', 'jobDescription') IS NOT NULL
    EXEC sp_rename 'HR_DESIGNATION.jobDescription', 'JOB_DESCRIPTION', 'COLUMN';
GO

IF COL_LENGTH('HR_DESIGNATION', 'org_seq_no') IS NOT NULL
    EXEC sp_rename 'HR_DESIGNATION.org_seq_no', 'ORG_SEQUENCE_NO', 'COLUMN';
GO
IF COL_LENGTH('HR_DESIGNATION', 'orgSeqNo') IS NOT NULL
    EXEC sp_rename 'HR_DESIGNATION.orgSeqNo', 'ORG_SEQUENCE_NO', 'COLUMN';
GO

IF COL_LENGTH('HR_DESIGNATION', 'budgeted_positions') IS NOT NULL
    EXEC sp_rename 'HR_DESIGNATION.budgeted_positions', 'BUDGETED_POSITIONS', 'COLUMN';
GO
IF COL_LENGTH('HR_DESIGNATION', 'budgetedPositions') IS NOT NULL
    EXEC sp_rename 'HR_DESIGNATION.budgetedPositions', 'BUDGETED_POSITIONS', 'COLUMN';
GO

IF COL_LENGTH('HR_DESIGNATION', 'created_by') IS NOT NULL
    EXEC sp_rename 'HR_DESIGNATION.created_by', 'CREATED_BY', 'COLUMN';
GO
IF COL_LENGTH('HR_DESIGNATION', 'createdBy') IS NOT NULL
    EXEC sp_rename 'HR_DESIGNATION.createdBy', 'CREATED_BY', 'COLUMN';
GO

IF COL_LENGTH('HR_DESIGNATION', 'created_date') IS NOT NULL
    EXEC sp_rename 'HR_DESIGNATION.created_date', 'CREATED_DATE', 'COLUMN';
GO
IF COL_LENGTH('HR_DESIGNATION', 'createdDate') IS NOT NULL
    EXEC sp_rename 'HR_DESIGNATION.createdDate', 'CREATED_DATE', 'COLUMN';
GO

IF COL_LENGTH('HR_DESIGNATION', 'updated_by') IS NOT NULL
    EXEC sp_rename 'HR_DESIGNATION.updated_by', 'UPDATED_BY', 'COLUMN';
GO
IF COL_LENGTH('HR_DESIGNATION', 'updatedBy') IS NOT NULL
    EXEC sp_rename 'HR_DESIGNATION.updatedBy', 'UPDATED_BY', 'COLUMN';
GO

IF COL_LENGTH('HR_DESIGNATION', 'updated_date') IS NOT NULL
    EXEC sp_rename 'HR_DESIGNATION.updated_date', 'UPDATED_DATE', 'COLUMN';
GO
IF COL_LENGTH('HR_DESIGNATION', 'updatedDate') IS NOT NULL
    EXEC sp_rename 'HR_DESIGNATION.updatedDate', 'UPDATED_DATE', 'COLUMN';
GO

IF OBJECT_ID('HR_DESIGNATION', 'U') IS NOT NULL
BEGIN
    ALTER TABLE HR_DESIGNATION ALTER COLUMN DESIGNATION_CODE NVARCHAR(50);
    ALTER TABLE HR_DESIGNATION ALTER COLUMN DESIGNATION_NAME NVARCHAR(100);
    ALTER TABLE HR_DESIGNATION ALTER COLUMN SUB_CATEGORY_LEVEL NVARCHAR(50);
    ALTER TABLE HR_DESIGNATION ALTER COLUMN EXPERIENCE NVARCHAR(50);
    ALTER TABLE HR_DESIGNATION ALTER COLUMN APPEAR_IN_COMPETENCY NVARCHAR(10);
    ALTER TABLE HR_DESIGNATION ALTER COLUMN QUALIFICATION NVARCHAR(100);
    ALTER TABLE HR_DESIGNATION ALTER COLUMN JOB_DESCRIPTION NVARCHAR(MAX);
    ALTER TABLE HR_DESIGNATION ALTER COLUMN CREATED_BY NVARCHAR(100);
    ALTER TABLE HR_DESIGNATION ALTER COLUMN CREATED_DATE DATETIME;
    ALTER TABLE HR_DESIGNATION ALTER COLUMN UPDATED_BY NVARCHAR(100);
    ALTER TABLE HR_DESIGNATION ALTER COLUMN UPDATED_DATE DATETIME;

    IF COL_LENGTH('HR_DESIGNATION', 'IS_ACTIVE') IS NULL
    BEGIN
        ALTER TABLE HR_DESIGNATION ADD IS_ACTIVE BIT DEFAULT 1;
    END
END
GO

IF OBJECT_ID('HR_DESIGNATION', 'U') IS NOT NULL
BEGIN
    DECLARE @desg_pk NVARCHAR(256);
    SELECT TOP 1 @desg_pk = name 
    FROM sys.key_constraints 
    WHERE parent_object_id = OBJECT_ID('HR_DESIGNATION') AND type = 'PK';
    
    IF @desg_pk IS NOT NULL AND @desg_pk <> 'PK_HR_DESIGNATION' AND NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE referenced_object_id = OBJECT_ID('HR_DESIGNATION'))
    BEGIN
        DECLARE @drop_desg_pk NVARCHAR(MAX) = 'ALTER TABLE HR_DESIGNATION DROP CONSTRAINT ' + @desg_pk;
        EXEC(@drop_desg_pk);
    END
    
    IF NOT EXISTS (SELECT 1 FROM sys.key_constraints WHERE parent_object_id = OBJECT_ID('HR_DESIGNATION') AND type = 'PK')
    BEGIN
        ALTER TABLE HR_DESIGNATION ADD CONSTRAINT PK_HR_DESIGNATION PRIMARY KEY (id);
    END
END
GO


-- ==========================================
-- 3. HR_DESIGNATION_LEVEL
-- ==========================================
IF COL_LENGTH('HR_DESIGNATION_LEVEL', 'row_id') IS NOT NULL
    EXEC sp_rename 'HR_DESIGNATION_LEVEL.row_id', 'ROW_ID', 'COLUMN';
GO
IF COL_LENGTH('HR_DESIGNATION_LEVEL', 'level') IS NOT NULL
    EXEC sp_rename 'HR_DESIGNATION_LEVEL.level', 'LEVEL', 'COLUMN';
GO
IF COL_LENGTH('HR_DESIGNATION_LEVEL', 'basic') IS NOT NULL
    EXEC sp_rename 'HR_DESIGNATION_LEVEL.basic', 'BASIC', 'COLUMN';
GO
IF COL_LENGTH('HR_DESIGNATION_LEVEL', 'da') IS NOT NULL
    EXEC sp_rename 'HR_DESIGNATION_LEVEL.da', 'DA', 'COLUMN';
GO
IF COL_LENGTH('HR_DESIGNATION_LEVEL', 'hra') IS NOT NULL
    EXEC sp_rename 'HR_DESIGNATION_LEVEL.hra', 'HRA', 'COLUMN';
GO
IF COL_LENGTH('HR_DESIGNATION_LEVEL', 'screening_level') IS NOT NULL
    EXEC sp_rename 'HR_DESIGNATION_LEVEL.screening_level', 'SCREENING_LEVEL', 'COLUMN';
GO
IF COL_LENGTH('HR_DESIGNATION_LEVEL', 'created_by') IS NOT NULL
    EXEC sp_rename 'HR_DESIGNATION_LEVEL.created_by', 'CREATED_BY', 'COLUMN';
GO
IF COL_LENGTH('HR_DESIGNATION_LEVEL', 'created_at') IS NOT NULL
    EXEC sp_rename 'HR_DESIGNATION_LEVEL.created_at', 'CREATED_DATE', 'COLUMN';
GO
IF COL_LENGTH('HR_DESIGNATION_LEVEL', 'createdDate') IS NOT NULL
    EXEC sp_rename 'HR_DESIGNATION_LEVEL.createdDate', 'CREATED_DATE', 'COLUMN';
GO
IF COL_LENGTH('HR_DESIGNATION_LEVEL', 'updated_by') IS NOT NULL
    EXEC sp_rename 'HR_DESIGNATION_LEVEL.updated_by', 'UPDATED_BY', 'COLUMN';
GO
IF COL_LENGTH('HR_DESIGNATION_LEVEL', 'updated_at') IS NOT NULL
    EXEC sp_rename 'HR_DESIGNATION_LEVEL.updated_at', 'UPDATED_DATE', 'COLUMN';
GO
IF COL_LENGTH('HR_DESIGNATION_LEVEL', 'updatedDate') IS NOT NULL
    EXEC sp_rename 'HR_DESIGNATION_LEVEL.updatedDate', 'UPDATED_DATE', 'COLUMN';
GO

IF OBJECT_ID('HR_DESIGNATION_LEVEL', 'U') IS NOT NULL
BEGIN
    ALTER TABLE HR_DESIGNATION_LEVEL ALTER COLUMN LEVEL NVARCHAR(10);
    ALTER TABLE HR_DESIGNATION_LEVEL ALTER COLUMN CREATED_BY NVARCHAR(100);
    ALTER TABLE HR_DESIGNATION_LEVEL ALTER COLUMN CREATED_DATE DATETIME;
    ALTER TABLE HR_DESIGNATION_LEVEL ALTER COLUMN UPDATED_BY NVARCHAR(100);
    ALTER TABLE HR_DESIGNATION_LEVEL ALTER COLUMN UPDATED_DATE DATETIME;

    IF COL_LENGTH('HR_DESIGNATION_LEVEL', 'IS_ACTIVE') IS NULL
    BEGIN
        ALTER TABLE HR_DESIGNATION_LEVEL ADD IS_ACTIVE BIT DEFAULT 1;
    END
END
GO

IF OBJECT_ID('HR_DESIGNATION_LEVEL', 'U') IS NOT NULL
BEGIN
    DECLARE @dl_pk NVARCHAR(256);
    SELECT TOP 1 @dl_pk = name FROM sys.key_constraints WHERE parent_object_id = OBJECT_ID('HR_DESIGNATION_LEVEL') AND type = 'PK';
    IF @dl_pk IS NOT NULL AND @dl_pk <> 'PK_HR_DESIGNATION_LEVEL' AND NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE referenced_object_id = OBJECT_ID('HR_DESIGNATION_LEVEL'))
    BEGIN
        DECLARE @drop_dl_pk NVARCHAR(MAX) = 'ALTER TABLE HR_DESIGNATION_LEVEL DROP CONSTRAINT ' + @dl_pk;
        EXEC(@drop_dl_pk);
    END
    IF NOT EXISTS (SELECT 1 FROM sys.key_constraints WHERE parent_object_id = OBJECT_ID('HR_DESIGNATION_LEVEL') AND type = 'PK')
    BEGIN
        ALTER TABLE HR_DESIGNATION_LEVEL ADD CONSTRAINT PK_HR_DESIGNATION_LEVEL PRIMARY KEY (ROW_ID);
    END
END
GO


-- ==========================================
-- 4. HR_LEVEL
-- ==========================================
IF OBJECT_ID('dbo.sp_RenameTableCasingAndPrefix', 'P') IS NOT NULL
BEGIN
    EXEC dbo.sp_RenameTableCasingAndPrefix 'HR_LEVEL_MASTER', 'HR_LEVEL';
END
ELSE
BEGIN
    IF OBJECT_ID('HR_LEVEL_MASTER', 'U') IS NOT NULL AND OBJECT_ID('HR_LEVEL', 'U') IS NULL
        EXEC sp_rename 'HR_LEVEL_MASTER', 'HR_LEVEL';
END
GO

IF COL_LENGTH('HR_LEVEL', 'level_name') IS NOT NULL
    EXEC sp_rename 'HR_LEVEL.level_name', 'LEVEL_NAME', 'COLUMN';
GO

IF OBJECT_ID('HR_LEVEL', 'U') IS NOT NULL
BEGIN
    DECLARE @index_name NVARCHAR(256);
    SELECT @index_name = i.name
    FROM sys.indexes i
    JOIN sys.index_columns ic ON i.object_id = ic.object_id AND i.index_id = ic.index_id
    JOIN sys.columns c ON ic.object_id = c.object_id AND ic.column_id = c.column_id
    WHERE i.object_id = OBJECT_ID('HR_LEVEL') AND c.name = 'LEVEL_NAME';
    
    IF @index_name IS NOT NULL
    BEGIN
        DECLARE @drop_sql NVARCHAR(MAX) = '';
        IF EXISTS (SELECT 1 FROM sys.objects WHERE name = @index_name AND parent_object_id = OBJECT_ID('HR_LEVEL') AND type = 'UQ')
            SET @drop_sql = 'ALTER TABLE HR_LEVEL DROP CONSTRAINT ' + QUOTENAME(@index_name);
        ELSE
            SET @drop_sql = 'DROP INDEX ' + QUOTENAME(@index_name) + ' ON HR_LEVEL';
        EXEC(@drop_sql);
    END

    ALTER TABLE HR_LEVEL ALTER COLUMN LEVEL_NAME NVARCHAR(100) NOT NULL;

    IF NOT EXISTS (SELECT 1 FROM sys.key_constraints WHERE parent_object_id = OBJECT_ID('HR_LEVEL') AND name = 'UQ_HR_LEVEL_LEVEL_NAME')
       AND NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID('HR_LEVEL') AND name = 'UQ_HR_LEVEL_LEVEL_NAME')
    BEGIN
        ALTER TABLE HR_LEVEL ADD CONSTRAINT UQ_HR_LEVEL_LEVEL_NAME UNIQUE (LEVEL_NAME);
    END

    IF COL_LENGTH('HR_LEVEL', 'CREATED_BY') IS NULL
        ALTER TABLE HR_LEVEL ADD CREATED_BY NVARCHAR(100);
    IF COL_LENGTH('HR_LEVEL', 'CREATED_DATE') IS NULL
        ALTER TABLE HR_LEVEL ADD CREATED_DATE DATETIME;
    IF COL_LENGTH('HR_LEVEL', 'UPDATED_BY') IS NULL
        ALTER TABLE HR_LEVEL ADD UPDATED_BY NVARCHAR(100);
    IF COL_LENGTH('HR_LEVEL', 'UPDATED_DATE') IS NULL
        ALTER TABLE HR_LEVEL ADD UPDATED_DATE DATETIME;
    IF COL_LENGTH('HR_LEVEL', 'IS_ACTIVE') IS NULL
        ALTER TABLE HR_LEVEL ADD IS_ACTIVE BIT DEFAULT 1;
END
GO

IF OBJECT_ID('HR_LEVEL', 'U') IS NOT NULL
BEGIN
    DECLARE @lvl_pk NVARCHAR(256);
    SELECT TOP 1 @lvl_pk = name FROM sys.key_constraints WHERE parent_object_id = OBJECT_ID('HR_LEVEL') AND type = 'PK';
    IF @lvl_pk IS NOT NULL AND @lvl_pk <> 'PK_HR_LEVEL' AND NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE referenced_object_id = OBJECT_ID('HR_LEVEL'))
    BEGIN
        DECLARE @drop_lvl_pk NVARCHAR(MAX) = 'ALTER TABLE HR_LEVEL DROP CONSTRAINT ' + @lvl_pk;
        EXEC(@drop_lvl_pk);
    END
    IF NOT EXISTS (SELECT 1 FROM sys.key_constraints WHERE parent_object_id = OBJECT_ID('HR_LEVEL') AND type = 'PK')
    BEGIN
        ALTER TABLE HR_LEVEL ADD CONSTRAINT PK_HR_LEVEL PRIMARY KEY (id);
    END
END
GO


-- ==========================================
-- 5. HR_EMPLOYEE_TYPE
-- ==========================================
IF OBJECT_ID('dbo.sp_RenameTableCasingAndPrefix', 'P') IS NOT NULL
BEGIN
    EXEC dbo.sp_RenameTableCasingAndPrefix 'HR_EMPLOYEE_TYPE_MASTER', 'HR_EMPLOYEE_TYPE';
END
ELSE
BEGIN
    IF OBJECT_ID('HR_EMPLOYEE_TYPE_MASTER', 'U') IS NOT NULL AND OBJECT_ID('HR_EMPLOYEE_TYPE', 'U') IS NULL
        EXEC sp_rename 'HR_EMPLOYEE_TYPE_MASTER', 'HR_EMPLOYEE_TYPE';
END
GO

IF COL_LENGTH('HR_EMPLOYEE_TYPE', 'type_name') IS NOT NULL
    EXEC sp_rename 'HR_EMPLOYEE_TYPE.type_name', 'TYPE_NAME', 'COLUMN';
GO
IF COL_LENGTH('HR_EMPLOYEE_TYPE', 'description') IS NOT NULL
    EXEC sp_rename 'HR_EMPLOYEE_TYPE.description', 'DESCRIPTION', 'COLUMN';
GO
IF COL_LENGTH('HR_EMPLOYEE_TYPE', 'status') IS NOT NULL
    EXEC sp_rename 'HR_EMPLOYEE_TYPE.status', 'STATUS', 'COLUMN';
GO
IF COL_LENGTH('HR_EMPLOYEE_TYPE', 'created_by') IS NOT NULL
    EXEC sp_rename 'HR_EMPLOYEE_TYPE.created_by', 'CREATED_BY', 'COLUMN';
GO
IF COL_LENGTH('HR_EMPLOYEE_TYPE', 'created_at') IS NOT NULL
    EXEC sp_rename 'HR_EMPLOYEE_TYPE.created_at', 'CREATED_DATE', 'COLUMN';
GO
IF COL_LENGTH('HR_EMPLOYEE_TYPE', 'createdDate') IS NOT NULL
    EXEC sp_rename 'HR_EMPLOYEE_TYPE.createdDate', 'CREATED_DATE', 'COLUMN';
GO
IF COL_LENGTH('HR_EMPLOYEE_TYPE', 'updated_by') IS NOT NULL
    EXEC sp_rename 'HR_EMPLOYEE_TYPE.updated_by', 'UPDATED_BY', 'COLUMN';
GO
IF COL_LENGTH('HR_EMPLOYEE_TYPE', 'updated_at') IS NOT NULL
    EXEC sp_rename 'HR_EMPLOYEE_TYPE.updated_at', 'UPDATED_DATE', 'COLUMN';
GO
IF COL_LENGTH('HR_EMPLOYEE_TYPE', 'updatedDate') IS NOT NULL
    EXEC sp_rename 'HR_EMPLOYEE_TYPE.updatedDate', 'UPDATED_DATE', 'COLUMN';
GO

IF OBJECT_ID('HR_EMPLOYEE_TYPE', 'U') IS NOT NULL
BEGIN
    DECLARE @index_name NVARCHAR(256);
    SELECT @index_name = i.name
    FROM sys.indexes i
    JOIN sys.index_columns ic ON i.object_id = ic.object_id AND i.index_id = ic.index_id
    JOIN sys.columns c ON ic.object_id = c.object_id AND ic.column_id = c.column_id
    WHERE i.object_id = OBJECT_ID('HR_EMPLOYEE_TYPE') AND c.name = 'TYPE_NAME';
    
    IF @index_name IS NOT NULL
    BEGIN
        DECLARE @drop_sql NVARCHAR(MAX) = '';
        IF EXISTS (SELECT 1 FROM sys.objects WHERE name = @index_name AND parent_object_id = OBJECT_ID('HR_EMPLOYEE_TYPE') AND type = 'UQ')
            SET @drop_sql = 'ALTER TABLE HR_EMPLOYEE_TYPE DROP CONSTRAINT ' + QUOTENAME(@index_name);
        ELSE
            SET @drop_sql = 'DROP INDEX ' + QUOTENAME(@index_name) + ' ON HR_EMPLOYEE_TYPE';
        EXEC(@drop_sql);
    END

    ALTER TABLE HR_EMPLOYEE_TYPE ALTER COLUMN TYPE_NAME NVARCHAR(100) NOT NULL;

    IF NOT EXISTS (SELECT 1 FROM sys.key_constraints WHERE parent_object_id = OBJECT_ID('HR_EMPLOYEE_TYPE') AND name = 'UQ_HR_EMPLOYEE_TYPE_TYPE_NAME')
       AND NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID('HR_EMPLOYEE_TYPE') AND name = 'UQ_HR_EMPLOYEE_TYPE_TYPE_NAME')
    BEGIN
        ALTER TABLE HR_EMPLOYEE_TYPE ADD CONSTRAINT UQ_HR_EMPLOYEE_TYPE_TYPE_NAME UNIQUE (TYPE_NAME);
    END

    ALTER TABLE HR_EMPLOYEE_TYPE ALTER COLUMN DESCRIPTION NVARCHAR(500);
    ALTER TABLE HR_EMPLOYEE_TYPE ALTER COLUMN STATUS NVARCHAR(20);
    ALTER TABLE HR_EMPLOYEE_TYPE ALTER COLUMN CREATED_BY NVARCHAR(100);
    ALTER TABLE HR_EMPLOYEE_TYPE ALTER COLUMN CREATED_DATE DATETIME;
    ALTER TABLE HR_EMPLOYEE_TYPE ALTER COLUMN UPDATED_BY NVARCHAR(100);
    ALTER TABLE HR_EMPLOYEE_TYPE ALTER COLUMN UPDATED_DATE DATETIME;

    IF COL_LENGTH('HR_EMPLOYEE_TYPE', 'IS_ACTIVE') IS NULL
    BEGIN
        ALTER TABLE HR_EMPLOYEE_TYPE ADD IS_ACTIVE BIT DEFAULT 1;
    END
END
GO

IF OBJECT_ID('HR_EMPLOYEE_TYPE', 'U') IS NOT NULL
BEGIN
    DECLARE @et_pk NVARCHAR(256);
    SELECT TOP 1 @et_pk = name FROM sys.key_constraints WHERE parent_object_id = OBJECT_ID('HR_EMPLOYEE_TYPE') AND type = 'PK';
    IF @et_pk IS NOT NULL AND @et_pk <> 'PK_HR_EMPLOYEE_TYPE' AND NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE referenced_object_id = OBJECT_ID('HR_EMPLOYEE_TYPE'))
    BEGIN
        DECLARE @drop_et_pk NVARCHAR(MAX) = 'ALTER TABLE HR_EMPLOYEE_TYPE DROP CONSTRAINT ' + @et_pk;
        EXEC(@drop_et_pk);
    END
    IF NOT EXISTS (SELECT 1 FROM sys.key_constraints WHERE parent_object_id = OBJECT_ID('HR_EMPLOYEE_TYPE') AND type = 'PK')
    BEGIN
        ALTER TABLE HR_EMPLOYEE_TYPE ADD CONSTRAINT PK_HR_EMPLOYEE_TYPE PRIMARY KEY (id);
    END
END
GO

-- ==========================================
-- 6. Seed Default Employee Types
-- ==========================================
IF NOT EXISTS (SELECT 1 FROM HR_EMPLOYEE_TYPE WHERE TYPE_NAME = 'Permanent')
    INSERT INTO HR_EMPLOYEE_TYPE (TYPE_NAME, DESCRIPTION, STATUS, IS_ACTIVE, CREATED_BY, CREATED_DATE)
    VALUES ('Permanent', 'Full-time permanent employee', 'ACTIVE', 1, 'SYSTEM', GETDATE());

IF NOT EXISTS (SELECT 1 FROM HR_EMPLOYEE_TYPE WHERE TYPE_NAME = 'Temporary')
    INSERT INTO HR_EMPLOYEE_TYPE (TYPE_NAME, DESCRIPTION, STATUS, IS_ACTIVE, CREATED_BY, CREATED_DATE)
    VALUES ('Temporary', 'Short-term temporary employee', 'ACTIVE', 1, 'SYSTEM', GETDATE());

IF NOT EXISTS (SELECT 1 FROM HR_EMPLOYEE_TYPE WHERE TYPE_NAME = 'Trainee')
    INSERT INTO HR_EMPLOYEE_TYPE (TYPE_NAME, DESCRIPTION, STATUS, IS_ACTIVE, CREATED_BY, CREATED_DATE)
    VALUES ('Trainee', 'Employee under training program', 'ACTIVE', 1, 'SYSTEM', GETDATE());

IF NOT EXISTS (SELECT 1 FROM HR_EMPLOYEE_TYPE WHERE TYPE_NAME = 'Probation')
    INSERT INTO HR_EMPLOYEE_TYPE (TYPE_NAME, DESCRIPTION, STATUS, IS_ACTIVE, CREATED_BY, CREATED_DATE)
    VALUES ('Probation', 'Employee under probation period', 'ACTIVE', 1, 'SYSTEM', GETDATE());
GO
