-- V012__Cleanup_Remaining_Legacy_Tables.sql
-- Safely migrate data and drop remaining legacy HRM/Designation tables

-- 1. Drop foreign keys referencing legacy tables if any to prevent locking
DECLARE @sql NVARCHAR(MAX) = N'';
SELECT @sql += N'ALTER TABLE ' + QUOTENAME(OBJECT_SCHEMA_NAME(parent_object_id)) + '.' + QUOTENAME(OBJECT_NAME(parent_object_id)) + 
               ' DROP CONSTRAINT ' + QUOTENAME(name) + ';' + CHAR(13) + CHAR(10)
FROM sys.foreign_keys
WHERE OBJECT_NAME(referenced_object_id) IN (
    'DesignationMaster', 'HRM_DESIG_LEVEL', 'HRM_CATEGORY_MASTER', 'HRM_DEPARTMENT_MASTER', 
    'HRM_EMP_ACTIVITY', 'HRM_EMP_ASSET', 'HRM_EMP_CONTACT', 'HRM_EMP_DEPENDENT', 
    'HRM_EMP_EDUCATION', 'HRM_EMP_EMERGENCY_CONTACT', 'HRM_EMP_EXPERIENCE', 'HRM_EMP_JOB_PROFILE', 
    'HRM_EMP_KYC', 'HRM_EMP_KYC_DOCUMENT', 'HRM_EMP_PASSPORT', 'HRM_EMP_PERSONAL_DETAIL', 
    'HRM_GRADE_DETAILS', 'HRM_LEVEL_MASTER', 'HRM_TYPE_MASTER'
) OR OBJECT_NAME(parent_object_id) IN (
    'DesignationMaster', 'HRM_DESIG_LEVEL', 'HRM_CATEGORY_MASTER', 'HRM_DEPARTMENT_MASTER', 
    'HRM_EMP_ACTIVITY', 'HRM_EMP_ASSET', 'HRM_EMP_CONTACT', 'HRM_EMP_DEPENDENT', 
    'HRM_EMP_EDUCATION', 'HRM_EMP_EMERGENCY_CONTACT', 'HRM_EMP_EXPERIENCE', 'HRM_EMP_JOB_PROFILE', 
    'HRM_EMP_KYC', 'HRM_EMP_KYC_DOCUMENT', 'HRM_EMP_PASSPORT', 'HRM_EMP_PERSONAL_DETAIL', 
    'HRM_GRADE_DETAILS', 'HRM_LEVEL_MASTER', 'HRM_TYPE_MASTER'
);
IF @sql <> N''
BEGIN
    EXEC sp_executesql @sql;
END
GO

-- 2. Migrate levels from HRM_LEVEL_MASTER to HR_LEVEL if HR_LEVEL is currently empty
IF OBJECT_ID('HRM_LEVEL_MASTER', 'U') IS NOT NULL AND OBJECT_ID('HR_LEVEL', 'U') IS NOT NULL
BEGIN
    IF (SELECT COUNT(*) FROM HR_LEVEL) = 0 AND (SELECT COUNT(*) FROM HRM_LEVEL_MASTER) > 0
    BEGIN
        SET IDENTITY_INSERT HR_LEVEL ON;
        INSERT INTO HR_LEVEL (id, LEVEL_NAME, IS_ACTIVE)
        SELECT id, level_name, 1 FROM HRM_LEVEL_MASTER;
        SET IDENTITY_INSERT HR_LEVEL OFF;
    END
END
GO

-- 3. Drop obsolete legacy tables (standard tables and ticketing tables remain untouched)
IF OBJECT_ID('DesignationMaster', 'U') IS NOT NULL DROP TABLE DesignationMaster;
IF OBJECT_ID('HRM_DESIG_LEVEL', 'U') IS NOT NULL DROP TABLE HRM_DESIG_LEVEL;
IF OBJECT_ID('HRM_CATEGORY_MASTER', 'U') IS NOT NULL DROP TABLE HRM_CATEGORY_MASTER;
IF OBJECT_ID('HRM_DEPARTMENT_MASTER', 'U') IS NOT NULL DROP TABLE HRM_DEPARTMENT_MASTER;
IF OBJECT_ID('HRM_EMP_ACTIVITY', 'U') IS NOT NULL DROP TABLE HRM_EMP_ACTIVITY;
IF OBJECT_ID('HRM_EMP_ASSET', 'U') IS NOT NULL DROP TABLE HRM_EMP_ASSET;
IF OBJECT_ID('HRM_EMP_CONTACT', 'U') IS NOT NULL DROP TABLE HRM_EMP_CONTACT;
IF OBJECT_ID('HRM_EMP_DEPENDENT', 'U') IS NOT NULL DROP TABLE HRM_EMP_DEPENDENT;
IF OBJECT_ID('HRM_EMP_EDUCATION', 'U') IS NOT NULL DROP TABLE HRM_EMP_EDUCATION;
IF OBJECT_ID('HRM_EMP_EMERGENCY_CONTACT', 'U') IS NOT NULL DROP TABLE HRM_EMP_EMERGENCY_CONTACT;
IF OBJECT_ID('HRM_EMP_EXPERIENCE', 'U') IS NOT NULL DROP TABLE HRM_EMP_EXPERIENCE;
IF OBJECT_ID('HRM_EMP_JOB_PROFILE', 'U') IS NOT NULL DROP TABLE HRM_EMP_JOB_PROFILE;
IF OBJECT_ID('HRM_EMP_KYC', 'U') IS NOT NULL DROP TABLE HRM_EMP_KYC;
IF OBJECT_ID('HRM_EMP_KYC_DOCUMENT', 'U') IS NOT NULL DROP TABLE HRM_EMP_KYC_DOCUMENT;
IF OBJECT_ID('HRM_EMP_PASSPORT', 'U') IS NOT NULL DROP TABLE HRM_EMP_PASSPORT;
IF OBJECT_ID('HRM_EMP_PERSONAL_DETAIL', 'U') IS NOT NULL DROP TABLE HRM_EMP_PERSONAL_DETAIL;
IF OBJECT_ID('HRM_GRADE_DETAILS', 'U') IS NOT NULL DROP TABLE HRM_GRADE_DETAILS;
IF OBJECT_ID('HRM_LEVEL_MASTER', 'U') IS NOT NULL DROP TABLE HRM_LEVEL_MASTER;
IF OBJECT_ID('HRM_TYPE_MASTER', 'U') IS NOT NULL DROP TABLE HRM_TYPE_MASTER;
GO
