-- Sync AD_COMPANY_CREDENTIAL table with Java Entity
-- Adding missing columns and renaming to match CompanyCredential model

IF NOT EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID(N'[dbo].[AD_COMPANY_CREDENTIAL]') AND name = 'ADDRESS')
BEGIN
    ALTER TABLE [dbo].[AD_COMPANY_CREDENTIAL] ADD [ADDRESS] NVARCHAR(500);
END

IF NOT EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID(N'[dbo].[AD_COMPANY_CREDENTIAL]') AND name = 'DIR_PATH')
BEGIN
    ALTER TABLE [dbo].[AD_COMPANY_CREDENTIAL] ADD [DIR_PATH] NVARCHAR(200);
END

IF NOT EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID(N'[dbo].[AD_COMPANY_CREDENTIAL]') AND name = 'CREATED_BY')
BEGIN
    ALTER TABLE [dbo].[AD_COMPANY_CREDENTIAL] ADD [CREATED_BY] NVARCHAR(50);
END

IF NOT EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID(N'[dbo].[AD_COMPANY_CREDENTIAL]') AND name = 'CREATED_DATE')
BEGIN
    ALTER TABLE [dbo].[AD_COMPANY_CREDENTIAL] ADD [CREATED_DATE] DATETIME;
END

IF NOT EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID(N'[dbo].[AD_COMPANY_CREDENTIAL]') AND name = 'UPDATED_BY')
BEGIN
    ALTER TABLE [dbo].[AD_COMPANY_CREDENTIAL] ADD [UPDATED_BY] NVARCHAR(50);
END

IF NOT EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID(N'[dbo].[AD_COMPANY_CREDENTIAL]') AND name = 'UPDATED_DATE')
BEGIN
    ALTER TABLE [dbo].[AD_COMPANY_CREDENTIAL] ADD [UPDATED_DATE] DATETIME;
END

-- Migrate ADDRESS_1 to ADDRESS if ADDRESS is empty
IF EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID(N'[dbo].[AD_COMPANY_CREDENTIAL]') AND name = 'ADDRESS_1')
AND EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID(N'[dbo].[AD_COMPANY_CREDENTIAL]') AND name = 'ADDRESS')
BEGIN
    EXEC sp_executesql N'UPDATE [dbo].[AD_COMPANY_CREDENTIAL] SET [ADDRESS] = [ADDRESS_1] WHERE [ADDRESS] IS NULL';
END
