-- Make Employee fields nullable to support optional form fields
ALTER TABLE [dbo].[HRM_EMPLOYEE_MASTER] ALTER COLUMN [emp_level_id] BIGINT NULL;
ALTER TABLE [dbo].[HRM_EMPLOYEE_MASTER] ALTER COLUMN [father_husband_name] NVARCHAR(100) NULL;
ALTER TABLE [dbo].[HRM_EMPLOYEE_MASTER] ALTER COLUMN [old_emp_code] NVARCHAR(50) NULL;
ALTER TABLE [dbo].[HRM_EMPLOYEE_MASTER] ALTER COLUMN [production_line] NVARCHAR(100) NULL;
ALTER TABLE [dbo].[HRM_EMPLOYEE_MASTER] ALTER COLUMN [emp_class] NVARCHAR(50) NULL;
ALTER TABLE [dbo].[HRM_EMPLOYEE_MASTER] ALTER COLUMN [team_group] NVARCHAR(100) NULL;
ALTER TABLE [dbo].[HRM_EMPLOYEE_MASTER] ALTER COLUMN [shift_name] NVARCHAR(100) NULL;
ALTER TABLE [dbo].[HRM_EMPLOYEE_MASTER] ALTER COLUMN [shift_duration] NVARCHAR(50) NULL;
