-- Create Session Monitoring Table
CREATE TABLE AD_USER_SESSION_AUDIT (
    ID BIGINT IDENTITY(1,1) PRIMARY KEY,
    USER_ID NVARCHAR(50),
    IP_ADDRESS NVARCHAR(50),
    LOGIN_TIME DATETIME,
    LOGOUT_TIME DATETIME,
    USER_AGENT NVARCHAR(255),
    SESSION_STATUS NVARCHAR(20)
);

-- Index for performance on searches
CREATE INDEX IDX_USER_SESSION_USER_ID ON AD_USER_SESSION_AUDIT(USER_ID);
CREATE INDEX IDX_USER_SESSION_LOGIN_TIME ON AD_USER_SESSION_AUDIT(LOGIN_TIME DESC);
