-- V004__Employee_Module.sql
-- Phase 4: Employee Core HR Schema Standardization
-- Renames and normalizes:
-- 1. HR_EMPLOYEE_MASTER -> HR_EMPLOYEE
-- 2. HR_EMPLOYEE_PERSONAL_DETAIL -> HR_EMPLOYEE_PERSONAL
-- 3. EMPLOYEE_MANAGER_MAPPING -> HR_EMPLOYEE_MANAGER_MAPPING
-- 4. Standardizes columns across all 14 employee tables to UPPERCASE
-- 5. Standardizes datatypes to NVARCHAR and sizes file paths to NVARCHAR(1000)
-- 6. Adds standard audit columns (CREATED_BY, CREATED_DATE, UPDATED_BY, UPDATED_DATE, IS_ACTIVE) where missing

-- ==========================================
-- Drop referencing Foreign Key constraints dynamically to avoid cascade/drop errors
-- ==========================================
DECLARE @sql NVARCHAR(MAX) = N'';
SELECT @sql += N'ALTER TABLE ' + QUOTENAME(OBJECT_SCHEMA_NAME(parent_object_id)) + '.' + QUOTENAME(OBJECT_NAME(parent_object_id)) + 
               ' DROP CONSTRAINT ' + QUOTENAME(name) + ';' + CHAR(13) + CHAR(10)
FROM sys.foreign_keys
WHERE referenced_object_id IN (
    OBJECT_ID('HR_EMPLOYEE_MASTER'),
    OBJECT_ID('hrm_employee_master'),
    OBJECT_ID('HR_EMPLOYEE_PERSONAL_DETAIL'),
    OBJECT_ID('hrm_employee_personal_detail'),
    OBJECT_ID('HR_EMPLOYEE_CONTACT'),
    OBJECT_ID('hrm_employee_contact'),
    OBJECT_ID('HR_EMPLOYEE_JOB_PROFILE'),
    OBJECT_ID('HR_EMPLOYEE_EDUCATION'),
    OBJECT_ID('HR_EMPLOYEE_EXPERIENCE'),
    OBJECT_ID('HR_EMPLOYEE_EMERGENCY_CONTACT'),
    OBJECT_ID('HR_EMPLOYEE_PASSPORT'),
    OBJECT_ID('HR_EMPLOYEE_DEPENDENT'),
    OBJECT_ID('HR_EMPLOYEE_ASSET'),
    OBJECT_ID('HR_EMPLOYEE_KYC'),
    OBJECT_ID('HR_EMPLOYEE_KYC_DOCUMENT'),
    OBJECT_ID('HR_EMPLOYEE_ACTIVITY'),
    OBJECT_ID('EMPLOYEE_MANAGER_MAPPING')
);
IF @sql <> N''
BEGIN
    EXEC sp_executesql @sql;
END
GO

-- ==========================================
-- 1. HR_EMPLOYEE (from HR_EMPLOYEE_MASTER / hrm_employee_master)
-- ==========================================
IF OBJECT_ID('dbo.sp_RenameTableCasingAndPrefix', 'P') IS NOT NULL
BEGIN
    EXEC dbo.sp_RenameTableCasingAndPrefix 'HR_EMPLOYEE_MASTER', 'HR_EMPLOYEE';
    EXEC dbo.sp_RenameTableCasingAndPrefix 'hrm_employee_master', 'HR_EMPLOYEE';
END
ELSE
BEGIN
    IF OBJECT_ID('HR_EMPLOYEE_MASTER', 'U') IS NOT NULL AND OBJECT_ID('HR_EMPLOYEE', 'U') IS NULL
        EXEC sp_rename 'HR_EMPLOYEE_MASTER', 'HR_EMPLOYEE';
    IF OBJECT_ID('hrm_employee_master', 'U') IS NOT NULL AND OBJECT_ID('HR_EMPLOYEE', 'U') IS NULL
        EXEC sp_rename 'hrm_employee_master', 'HR_EMPLOYEE';
END
GO

-- Rename columns to UPPERCASE
IF COL_LENGTH('HR_EMPLOYEE', 'emp_code') IS NOT NULL AND COL_LENGTH('HR_EMPLOYEE', 'EMP_CODE') IS NULL
IF COL_LENGTH('HR_EMPLOYEE', 'old_emp_code') IS NOT NULL AND COL_LENGTH('HR_EMPLOYEE', 'OLD_EMP_CODE') IS NULL
IF COL_LENGTH('HR_EMPLOYEE', 'title') IS NOT NULL AND COL_LENGTH('HR_EMPLOYEE', 'TITLE') IS NULL
IF COL_LENGTH('HR_EMPLOYEE', 'employee_name') IS NOT NULL AND COL_LENGTH('HR_EMPLOYEE', 'EMPLOYEE_NAME') IS NULL
IF COL_LENGTH('HR_EMPLOYEE', 'first_name') IS NOT NULL AND COL_LENGTH('HR_EMPLOYEE', 'FIRST_NAME') IS NULL
IF COL_LENGTH('HR_EMPLOYEE', 'last_name') IS NOT NULL AND COL_LENGTH('HR_EMPLOYEE', 'LAST_NAME') IS NULL
IF COL_LENGTH('HR_EMPLOYEE', 'father_husband_name') IS NOT NULL AND COL_LENGTH('HR_EMPLOYEE', 'FATHER_HUSBAND_NAME') IS NULL
IF COL_LENGTH('HR_EMPLOYEE', 'category_id') IS NOT NULL AND COL_LENGTH('HR_EMPLOYEE', 'CATEGORY_ID') IS NULL
IF COL_LENGTH('HR_EMPLOYEE', 'emp_level_id') IS NOT NULL AND COL_LENGTH('HR_EMPLOYEE', 'EMP_LEVEL_ID') IS NULL
IF COL_LENGTH('HR_EMPLOYEE', 'employee_type_id') IS NOT NULL AND COL_LENGTH('HR_EMPLOYEE', 'EMPLOYEE_TYPE_ID') IS NULL
IF COL_LENGTH('HR_EMPLOYEE', 'grade_code') IS NOT NULL AND COL_LENGTH('HR_EMPLOYEE', 'GRADE_CODE') IS NULL
IF COL_LENGTH('HR_EMPLOYEE', 'unit_id') IS NOT NULL AND COL_LENGTH('HR_EMPLOYEE', 'UNIT_ID') IS NULL
IF COL_LENGTH('HR_EMPLOYEE', 'department_id') IS NOT NULL AND COL_LENGTH('HR_EMPLOYEE', 'DEPARTMENT_ID') IS NULL
IF COL_LENGTH('HR_EMPLOYEE', 'designation_id') IS NOT NULL AND COL_LENGTH('HR_EMPLOYEE', 'DESIGNATION_ID') IS NULL
IF COL_LENGTH('HR_EMPLOYEE', 'employee_photo_upload') IS NOT NULL AND COL_LENGTH('HR_EMPLOYEE', 'EMPLOYEE_PHOTO_UPLOAD') IS NULL
IF COL_LENGTH('HR_EMPLOYEE', 'employee_signature_upload') IS NOT NULL AND COL_LENGTH('HR_EMPLOYEE', 'EMPLOYEE_SIGNATURE_UPLOAD') IS NULL
IF COL_LENGTH('HR_EMPLOYEE', 'nda_upload') IS NOT NULL AND COL_LENGTH('HR_EMPLOYEE', 'NDA_UPLOAD') IS NULL
IF COL_LENGTH('HR_EMPLOYEE', 'fitness_certificate_upload') IS NOT NULL AND COL_LENGTH('HR_EMPLOYEE', 'FITNESS_CERTIFICATE_UPLOAD') IS NULL
IF COL_LENGTH('HR_EMPLOYEE', 'vertical_head') IS NOT NULL AND COL_LENGTH('HR_EMPLOYEE', 'VERTICAL_HEAD') IS NULL
IF COL_LENGTH('HR_EMPLOYEE', 'hr_manager') IS NOT NULL AND COL_LENGTH('HR_EMPLOYEE', 'HR_MANAGER') IS NULL
IF COL_LENGTH('HR_EMPLOYEE', 'office_mail') IS NOT NULL AND COL_LENGTH('HR_EMPLOYEE', 'OFFICE_MAIL') IS NULL
IF COL_LENGTH('HR_EMPLOYEE', 'office_mail_password') IS NOT NULL AND COL_LENGTH('HR_EMPLOYEE', 'OFFICE_MAIL_PASSWORD') IS NULL
IF COL_LENGTH('HR_EMPLOYEE', 'pf_toggle') IS NOT NULL AND COL_LENGTH('HR_EMPLOYEE', 'PF_TOGGLE') IS NULL
IF COL_LENGTH('HR_EMPLOYEE', 'esi_toggle') IS NOT NULL AND COL_LENGTH('HR_EMPLOYEE', 'ESI_TOGGLE') IS NULL
IF COL_LENGTH('HR_EMPLOYEE', 'p_tax_toggle') IS NOT NULL AND COL_LENGTH('HR_EMPLOYEE', 'P_TAX_TOGGLE') IS NULL
IF COL_LENGTH('HR_EMPLOYEE', 'bonus_toggle') IS NOT NULL AND COL_LENGTH('HR_EMPLOYEE', 'BONUS_TOGGLE') IS NULL
IF COL_LENGTH('HR_EMPLOYEE', 'ot_toggle') IS NOT NULL AND COL_LENGTH('HR_EMPLOYEE', 'OT_TOGGLE') IS NULL
IF COL_LENGTH('HR_EMPLOYEE', 'ot_factorial') IS NOT NULL AND COL_LENGTH('HR_EMPLOYEE', 'OT_FACTORIAL') IS NULL
IF COL_LENGTH('HR_EMPLOYEE', 'lom_deduction') IS NOT NULL AND COL_LENGTH('HR_EMPLOYEE', 'LOM_DEDUCTION') IS NULL
IF COL_LENGTH('HR_EMPLOYEE', 'lom_allow') IS NOT NULL AND COL_LENGTH('HR_EMPLOYEE', 'LOM_ALLOW') IS NULL
IF COL_LENGTH('HR_EMPLOYEE', 'lta_eligible') IS NOT NULL AND COL_LENGTH('HR_EMPLOYEE', 'LTA_ELIGIBLE') IS NULL
IF COL_LENGTH('HR_EMPLOYEE', 'pf_restriction') IS NOT NULL AND COL_LENGTH('HR_EMPLOYEE', 'PF_RESTRICTION') IS NULL
IF COL_LENGTH('HR_EMPLOYEE', 'permission_toggle') IS NOT NULL AND COL_LENGTH('HR_EMPLOYEE', 'PERMISSION_TOGGLE') IS NULL
IF COL_LENGTH('HR_EMPLOYEE', 'permission_limit') IS NOT NULL AND COL_LENGTH('HR_EMPLOYEE', 'PERMISSION_LIMIT') IS NULL
IF COL_LENGTH('HR_EMPLOYEE', 'vendor_name') IS NOT NULL AND COL_LENGTH('HR_EMPLOYEE', 'VENDOR_NAME') IS NULL
IF COL_LENGTH('HR_EMPLOYEE', 'refer_mode') IS NOT NULL AND COL_LENGTH('HR_EMPLOYEE', 'REFER_MODE') IS NULL
IF COL_LENGTH('HR_EMPLOYEE', 'reference_comments') IS NOT NULL AND COL_LENGTH('HR_EMPLOYEE', 'REFERENCE_COMMENTS') IS NULL
IF COL_LENGTH('HR_EMPLOYEE', 'home_manager') IS NOT NULL AND COL_LENGTH('HR_EMPLOYEE', 'HOME_MANAGER') IS NULL
IF COL_LENGTH('HR_EMPLOYEE', 'business_manager') IS NOT NULL AND COL_LENGTH('HR_EMPLOYEE', 'BUSINESS_MANAGER') IS NULL
IF COL_LENGTH('HR_EMPLOYEE', 'supplier_name') IS NOT NULL AND COL_LENGTH('HR_EMPLOYEE', 'SUPPLIER_NAME') IS NULL
IF COL_LENGTH('HR_EMPLOYEE', 'date_of_joining') IS NOT NULL AND COL_LENGTH('HR_EMPLOYEE', 'DATE_OF_JOINING') IS NULL
IF COL_LENGTH('HR_EMPLOYEE', 'probation_period') IS NOT NULL AND COL_LENGTH('HR_EMPLOYEE', 'PROBATION_PERIOD') IS NULL
IF COL_LENGTH('HR_EMPLOYEE', 'confirmation_date') IS NOT NULL AND COL_LENGTH('HR_EMPLOYEE', 'CONFIRMATION_DATE') IS NULL
IF COL_LENGTH('HR_EMPLOYEE', 'induction_status') IS NOT NULL AND COL_LENGTH('HR_EMPLOYEE', 'INDUCTION_STATUS') IS NULL
IF COL_LENGTH('HR_EMPLOYEE', 'exit_date') IS NOT NULL AND COL_LENGTH('HR_EMPLOYEE', 'EXIT_DATE') IS NULL
IF COL_LENGTH('HR_EMPLOYEE', 'exit_reason') IS NOT NULL AND COL_LENGTH('HR_EMPLOYEE', 'EXIT_REASON') IS NULL
IF COL_LENGTH('HR_EMPLOYEE', 'exit_comments') IS NOT NULL AND COL_LENGTH('HR_EMPLOYEE', 'EXIT_COMMENTS') IS NULL
IF COL_LENGTH('HR_EMPLOYEE', 'rejoining_date') IS NOT NULL AND COL_LENGTH('HR_EMPLOYEE', 'REJOINING_DATE') IS NULL
IF COL_LENGTH('HR_EMPLOYEE', 'grace_minutes') IS NOT NULL AND COL_LENGTH('HR_EMPLOYEE', 'GRACE_MINUTES') IS NULL
IF COL_LENGTH('HR_EMPLOYEE', 'petrol_mode') IS NOT NULL AND COL_LENGTH('HR_EMPLOYEE', 'PETROL_MODE') IS NULL
IF COL_LENGTH('HR_EMPLOYEE', 'petrol_allowance') IS NOT NULL AND COL_LENGTH('HR_EMPLOYEE', 'PETROL_ALLOWANCE') IS NULL
IF COL_LENGTH('HR_EMPLOYEE', 'shift') IS NOT NULL AND COL_LENGTH('HR_EMPLOYEE', 'SHIFT') IS NULL
IF COL_LENGTH('HR_EMPLOYEE', 'shift_name') IS NOT NULL AND COL_LENGTH('HR_EMPLOYEE', 'SHIFT_NAME') IS NULL
IF COL_LENGTH('HR_EMPLOYEE', 'shift_duration') IS NOT NULL AND COL_LENGTH('HR_EMPLOYEE', 'SHIFT_DURATION') IS NULL
IF COL_LENGTH('HR_EMPLOYEE', 'is_auditor') IS NOT NULL AND COL_LENGTH('HR_EMPLOYEE', 'IS_AUDITOR') IS NULL
IF COL_LENGTH('HR_EMPLOYEE', 'auditor_type') IS NOT NULL AND COL_LENGTH('HR_EMPLOYEE', 'AUDITOR_TYPE') IS NULL
IF COL_LENGTH('HR_EMPLOYEE', 'auditor_file_info') IS NOT NULL AND COL_LENGTH('HR_EMPLOYEE', 'AUDITOR_FILE_INFO') IS NULL
IF COL_LENGTH('HR_EMPLOYEE', 'is_auditee') IS NOT NULL AND COL_LENGTH('HR_EMPLOYEE', 'IS_AUDITEE') IS NULL
IF COL_LENGTH('HR_EMPLOYEE', 'auditee_type') IS NOT NULL AND COL_LENGTH('HR_EMPLOYEE', 'AUDITEE_TYPE') IS NULL
IF COL_LENGTH('HR_EMPLOYEE', 'auditee_file_info') IS NOT NULL AND COL_LENGTH('HR_EMPLOYEE', 'AUDITEE_FILE_INFO') IS NULL
IF COL_LENGTH('HR_EMPLOYEE', 'is_ncr_approver') IS NOT NULL AND COL_LENGTH('HR_EMPLOYEE', 'IS_NCR_APPROVER') IS NULL
IF COL_LENGTH('HR_EMPLOYEE', 'ncr_approver_type') IS NOT NULL AND COL_LENGTH('HR_EMPLOYEE', 'NCR_APPROVER_TYPE') IS NULL
IF COL_LENGTH('HR_EMPLOYEE', 'ncr_approver_file_info') IS NOT NULL AND COL_LENGTH('HR_EMPLOYEE', 'NCR_APPROVER_FILE_INFO') IS NULL
IF COL_LENGTH('HR_EMPLOYEE', 'is_chaired') IS NOT NULL AND COL_LENGTH('HR_EMPLOYEE', 'IS_CHAIRED') IS NULL
IF COL_LENGTH('HR_EMPLOYEE', 'chaired_type') IS NOT NULL AND COL_LENGTH('HR_EMPLOYEE', 'CHAIRED_TYPE') IS NULL
IF COL_LENGTH('HR_EMPLOYEE', 'chaired_file_info') IS NOT NULL AND COL_LENGTH('HR_EMPLOYEE', 'CHAIRED_FILE_INFO') IS NULL
IF COL_LENGTH('HR_EMPLOYEE', 'is_host') IS NOT NULL AND COL_LENGTH('HR_EMPLOYEE', 'IS_HOST') IS NULL
IF COL_LENGTH('HR_EMPLOYEE', 'host_type') IS NOT NULL AND COL_LENGTH('HR_EMPLOYEE', 'HOST_TYPE') IS NULL
IF COL_LENGTH('HR_EMPLOYEE', 'host_file_info') IS NOT NULL AND COL_LENGTH('HR_EMPLOYEE', 'HOST_FILE_INFO') IS NULL
IF COL_LENGTH('HR_EMPLOYEE', 'is_participants') IS NOT NULL AND COL_LENGTH('HR_EMPLOYEE', 'IS_PARTICIPANTS') IS NULL
IF COL_LENGTH('HR_EMPLOYEE', 'participants_type') IS NOT NULL AND COL_LENGTH('HR_EMPLOYEE', 'PARTICIPANTS_TYPE') IS NULL
IF COL_LENGTH('HR_EMPLOYEE', 'participants_file_info') IS NOT NULL AND COL_LENGTH('HR_EMPLOYEE', 'PARTICIPANTS_FILE_INFO') IS NULL
IF COL_LENGTH('HR_EMPLOYEE', 'segment') IS NOT NULL AND COL_LENGTH('HR_EMPLOYEE', 'SEGMENT') IS NULL
IF COL_LENGTH('HR_EMPLOYEE', 'sub_segment') IS NOT NULL AND COL_LENGTH('HR_EMPLOYEE', 'SUB_SEGMENT') IS NULL
IF COL_LENGTH('HR_EMPLOYEE', 'is_first_aid') IS NOT NULL AND COL_LENGTH('HR_EMPLOYEE', 'IS_FIRST_AID') IS NULL
IF COL_LENGTH('HR_EMPLOYEE', 'first_aid_file_info') IS NOT NULL AND COL_LENGTH('HR_EMPLOYEE', 'FIRST_AID_FILE_INFO') IS NULL
IF COL_LENGTH('HR_EMPLOYEE', 'is_fire_fighter') IS NOT NULL AND COL_LENGTH('HR_EMPLOYEE', 'IS_FIRE_FIGHTER') IS NULL
IF COL_LENGTH('HR_EMPLOYEE', 'fire_fighter_file_info') IS NOT NULL AND COL_LENGTH('HR_EMPLOYEE', 'FIRE_FIGHTER_FILE_INFO') IS NULL
IF COL_LENGTH('HR_EMPLOYEE', 'is_two_wheeler') IS NOT NULL AND COL_LENGTH('HR_EMPLOYEE', 'IS_TWO_WHEELER') IS NULL
IF COL_LENGTH('HR_EMPLOYEE', 'two_wheeler_file_info') IS NOT NULL AND COL_LENGTH('HR_EMPLOYEE', 'TWO_WHEELER_FILE_INFO') IS NULL
IF COL_LENGTH('HR_EMPLOYEE', 'is_four_wheeler') IS NOT NULL AND COL_LENGTH('HR_EMPLOYEE', 'IS_FOUR_WHEELER') IS NULL
IF COL_LENGTH('HR_EMPLOYEE', 'four_wheeler_file_info') IS NOT NULL AND COL_LENGTH('HR_EMPLOYEE', 'FOUR_WHEELER_FILE_INFO') IS NULL
IF COL_LENGTH('HR_EMPLOYEE', 'is_induction_eligible') IS NOT NULL AND COL_LENGTH('HR_EMPLOYEE', 'IS_INDUCTION_ELIGIBLE') IS NULL
IF COL_LENGTH('HR_EMPLOYEE', 'is_interviewer') IS NOT NULL AND COL_LENGTH('HR_EMPLOYEE', 'IS_INTERVIEWER') IS NULL
IF COL_LENGTH('HR_EMPLOYEE', 'is_enquiry_assignee') IS NOT NULL AND COL_LENGTH('HR_EMPLOYEE', 'IS_ENQUIRY_ASSIGNEE') IS NULL
IF COL_LENGTH('HR_EMPLOYEE', 'is_pr_assignee') IS NOT NULL AND COL_LENGTH('HR_EMPLOYEE', 'IS_PR_ASSIGNEE') IS NULL
IF COL_LENGTH('HR_EMPLOYEE', 'applicant_date') IS NOT NULL AND COL_LENGTH('HR_EMPLOYEE', 'APPLICANT_DATE') IS NULL
IF COL_LENGTH('HR_EMPLOYEE', 'age') IS NOT NULL AND COL_LENGTH('HR_EMPLOYEE', 'AGE') IS NULL
IF COL_LENGTH('HR_EMPLOYEE', 'position_look_for') IS NOT NULL AND COL_LENGTH('HR_EMPLOYEE', 'POSITION_LOOK_FOR') IS NULL
IF COL_LENGTH('HR_EMPLOYEE', 'call_status') IS NOT NULL AND COL_LENGTH('HR_EMPLOYEE', 'CALL_STATUS') IS NULL
IF COL_LENGTH('HR_EMPLOYEE', 'interview_status') IS NOT NULL AND COL_LENGTH('HR_EMPLOYEE', 'INTERVIEW_STATUS') IS NULL
IF COL_LENGTH('HR_EMPLOYEE', 'offer_status') IS NOT NULL AND COL_LENGTH('HR_EMPLOYEE', 'OFFER_STATUS') IS NULL
IF COL_LENGTH('HR_EMPLOYEE', 'verification_status') IS NOT NULL AND COL_LENGTH('HR_EMPLOYEE', 'VERIFICATION_STATUS') IS NULL
IF COL_LENGTH('HR_EMPLOYEE', 'payslip_path') IS NOT NULL AND COL_LENGTH('HR_EMPLOYEE', 'PAYSLIP_PATH') IS NULL
IF COL_LENGTH('HR_EMPLOYEE', 'status') IS NOT NULL AND COL_LENGTH('HR_EMPLOYEE', 'STATUS') IS NULL
IF COL_LENGTH('HR_EMPLOYEE', 'created_by') IS NOT NULL AND COL_LENGTH('HR_EMPLOYEE', 'CREATED_BY') IS NULL
IF COL_LENGTH('HR_EMPLOYEE', 'created_at') IS NOT NULL AND COL_LENGTH('HR_EMPLOYEE', 'CREATED_DATE') IS NULL
IF COL_LENGTH('HR_EMPLOYEE', 'updated_by') IS NOT NULL AND COL_LENGTH('HR_EMPLOYEE', 'UPDATED_BY') IS NULL
IF COL_LENGTH('HR_EMPLOYEE', 'updated_at') IS NOT NULL AND COL_LENGTH('HR_EMPLOYEE', 'UPDATED_DATE') IS NULL

-- Self-assessment Q&A columns
IF COL_LENGTH('HR_EMPLOYEE', 'q1_native') IS NOT NULL AND COL_LENGTH('HR_EMPLOYEE', 'Q1_NATIVE') IS NULL
IF COL_LENGTH('HR_EMPLOYEE', 'q2_present_address') IS NOT NULL AND COL_LENGTH('HR_EMPLOYEE', 'Q2_PRESENT_ADDRESS') IS NULL
IF COL_LENGTH('HR_EMPLOYEE', 'q3_permanent_address') IS NOT NULL AND COL_LENGTH('HR_EMPLOYEE', 'Q3_PERMANENT_ADDRESS') IS NULL
IF COL_LENGTH('HR_EMPLOYEE', 'q4_father_occupation') IS NOT NULL AND COL_LENGTH('HR_EMPLOYEE', 'Q4_FATHER_OCCUPATION') IS NULL
IF COL_LENGTH('HR_EMPLOYEE', 'q5_mother_occupation') IS NOT NULL AND COL_LENGTH('HR_EMPLOYEE', 'Q5_MOTHER_OCCUPATION') IS NULL
IF COL_LENGTH('HR_EMPLOYEE', 'q6_marital_status') IS NOT NULL AND COL_LENGTH('HR_EMPLOYEE', 'Q6_MARITAL_STATUS') IS NULL
IF COL_LENGTH('HR_EMPLOYEE', 'q7_spouse_occupation') IS NOT NULL AND COL_LENGTH('HR_EMPLOYEE', 'Q7_SPOUSE_OCCUPATION') IS NULL
IF COL_LENGTH('HR_EMPLOYEE', 'q8_children') IS NOT NULL AND COL_LENGTH('HR_EMPLOYEE', 'Q8_CHILDREN') IS NULL
IF COL_LENGTH('HR_EMPLOYEE', 'q9_has_relatives') IS NOT NULL AND COL_LENGTH('HR_EMPLOYEE', 'Q9_HAS_RELATIVES') IS NULL
IF COL_LENGTH('HR_EMPLOYEE', 'q10_relatives_details') IS NOT NULL AND COL_LENGTH('HR_EMPLOYEE', 'Q10_RELATIVES_DETAILS') IS NULL
IF COL_LENGTH('HR_EMPLOYEE', 'q11_siblings_occupations') IS NOT NULL AND COL_LENGTH('HR_EMPLOYEE', 'Q11_SIBLINGS_OCCUPATIONS') IS NULL
IF COL_LENGTH('HR_EMPLOYEE', 'q12_has_two_wheeler') IS NOT NULL AND COL_LENGTH('HR_EMPLOYEE', 'Q12_HAS_TWO_WHEELER') IS NULL
IF COL_LENGTH('HR_EMPLOYEE', 'q13_has_android_phone') IS NOT NULL AND COL_LENGTH('HR_EMPLOYEE', 'Q13_HAS_ANDROID_PHONE') IS NULL
IF COL_LENGTH('HR_EMPLOYEE', 'q14_knows_car_driving') IS NOT NULL AND COL_LENGTH('HR_EMPLOYEE', 'Q14_KNOWS_CAR_DRIVING') IS NULL
IF COL_LENGTH('HR_EMPLOYEE', 'q15_willing_to_travel') IS NOT NULL AND COL_LENGTH('HR_EMPLOYEE', 'Q15_WILLING_TO_TRAVEL') IS NULL
IF COL_LENGTH('HR_EMPLOYEE', 'q16_covid_vaccination') IS NOT NULL AND COL_LENGTH('HR_EMPLOYEE', 'Q16_COVID_VACCINATION') IS NULL
IF COL_LENGTH('HR_EMPLOYEE', 'q17_positive_points') IS NOT NULL AND COL_LENGTH('HR_EMPLOYEE', 'Q17_POSITIVE_POINTS') IS NULL
IF COL_LENGTH('HR_EMPLOYEE', 'q18_negative_points') IS NOT NULL AND COL_LENGTH('HR_EMPLOYEE', 'Q18_NEGATIVE_POINTS') IS NULL
IF COL_LENGTH('HR_EMPLOYEE', 'q19_life_goals') IS NOT NULL AND COL_LENGTH('HR_EMPLOYEE', 'Q19_LIFE_GOALS') IS NULL
IF COL_LENGTH('HR_EMPLOYEE', 'q20_improvement_suggestions') IS NOT NULL AND COL_LENGTH('HR_EMPLOYEE', 'Q20_IMPROVEMENT_SUGGESTIONS') IS NULL
IF COL_LENGTH('HR_EMPLOYEE', 'q21_is_experienced') IS NOT NULL AND COL_LENGTH('HR_EMPLOYEE', 'Q21_IS_EXPERIENCED') IS NULL
IF COL_LENGTH('HR_EMPLOYEE', 'q22_total_experience') IS NOT NULL AND COL_LENGTH('HR_EMPLOYEE', 'Q22_TOTAL_EXPERIENCE') IS NULL
IF COL_LENGTH('HR_EMPLOYEE', 'q23_core_experience') IS NOT NULL AND COL_LENGTH('HR_EMPLOYEE', 'Q23_CORE_EXPERIENCE') IS NULL
IF COL_LENGTH('HR_EMPLOYEE', 'q24_prev_net_salary') IS NOT NULL AND COL_LENGTH('HR_EMPLOYEE', 'Q24_PREV_NET_SALARY') IS NULL
IF COL_LENGTH('HR_EMPLOYEE', 'q25_prev_gross_salary') IS NOT NULL AND COL_LENGTH('HR_EMPLOYEE', 'Q25_PREV_GROSS_SALARY') IS NULL
IF COL_LENGTH('HR_EMPLOYEE', 'q26_expected_net_salary') IS NOT NULL AND COL_LENGTH('HR_EMPLOYEE', 'Q26_EXPECTED_NET_SALARY') IS NULL
IF COL_LENGTH('HR_EMPLOYEE', 'q27_expected_gross_salary') IS NOT NULL AND COL_LENGTH('HR_EMPLOYEE', 'Q27_EXPECTED_GROSS_SALARY') IS NULL
IF COL_LENGTH('HR_EMPLOYEE', 'q28_pf_higher_pension') IS NOT NULL AND COL_LENGTH('HR_EMPLOYEE', 'Q28_PF_HIGHER_PENSION') IS NULL
IF COL_LENGTH('HR_EMPLOYEE', 'q29_pf_deduction_amount') IS NOT NULL AND COL_LENGTH('HR_EMPLOYEE', 'Q29_PF_DEDUCTION_AMOUNT') IS NULL
IF COL_LENGTH('HR_EMPLOYEE', 'q30_alternative_department') IS NOT NULL AND COL_LENGTH('HR_EMPLOYEE', 'Q30_ALTERNATIVE_DEPARTMENT') IS NULL
IF COL_LENGTH('HR_EMPLOYEE', 'q31_prev_location') IS NOT NULL AND COL_LENGTH('HR_EMPLOYEE', 'Q31_PREV_LOCATION') IS NULL
IF COL_LENGTH('HR_EMPLOYEE', 'q32_prev_shift') IS NOT NULL AND COL_LENGTH('HR_EMPLOYEE', 'Q32_PREV_SHIFT') IS NULL
IF COL_LENGTH('HR_EMPLOYEE', 'q33_reason_for_leaving') IS NOT NULL AND COL_LENGTH('HR_EMPLOYEE', 'Q33_REASON_FOR_LEAVING') IS NULL
IF COL_LENGTH('HR_EMPLOYEE', 'q34_notice_period') IS NOT NULL AND COL_LENGTH('HR_EMPLOYEE', 'Q34_NOTICE_PERIOD') IS NULL
IF COL_LENGTH('HR_EMPLOYEE', 'q35_prev_dept_position') IS NOT NULL AND COL_LENGTH('HR_EMPLOYEE', 'Q35_PREV_DEPT_POSITION') IS NULL
IF COL_LENGTH('HR_EMPLOYEE', 'q36_prev_dept_count') IS NOT NULL AND COL_LENGTH('HR_EMPLOYEE', 'Q36_PREV_DEPT_COUNT') IS NULL
IF COL_LENGTH('HR_EMPLOYEE', 'q37_prev_reporting_to') IS NOT NULL AND COL_LENGTH('HR_EMPLOYEE', 'Q37_PREV_REPORTING_TO') IS NULL
IF COL_LENGTH('HR_EMPLOYEE', 'q38_handle_mistake') IS NOT NULL AND COL_LENGTH('HR_EMPLOYEE', 'Q38_HANDLE_MISTAKE') IS NULL
IF COL_LENGTH('HR_EMPLOYEE', 'q39_handle_opinion_difference') IS NOT NULL AND COL_LENGTH('HR_EMPLOYEE', 'Q39_HANDLE_OPINION_DIFFERENCE') IS NULL
IF COL_LENGTH('HR_EMPLOYEE', 'q40_computer_self_rating') IS NOT NULL AND COL_LENGTH('HR_EMPLOYEE', 'Q40_COMPUTER_SELF_RATING') IS NULL
GO

IF OBJECT_ID('HR_EMPLOYEE', 'U') IS NOT NULL
BEGIN
    -- Drop unique constraint/index on EMP_CODE dynamically to allow type alteration
    DECLARE @drop_uq NVARCHAR(MAX) = N'';
    SELECT @drop_uq += N'ALTER TABLE [HR_EMPLOYEE] DROP CONSTRAINT ' + QUOTENAME(dc.name) + ';' + CHAR(13) + CHAR(10)
    FROM sys.key_constraints dc
    INNER JOIN sys.index_columns ic ON dc.parent_object_id = ic.object_id AND dc.unique_index_id = ic.index_id
    INNER JOIN sys.columns c ON ic.object_id = c.object_id AND ic.column_id = c.column_id
    WHERE dc.parent_object_id = OBJECT_ID('HR_EMPLOYEE')
      AND c.name = 'EMP_CODE';
    IF @drop_uq <> N'' EXEC sp_executesql @drop_uq;

    DECLARE @drop_idx NVARCHAR(MAX) = N'';
    SELECT @drop_idx += N'DROP INDEX ' + QUOTENAME(i.name) + ' ON [HR_EMPLOYEE];' + CHAR(13) + CHAR(10)
    FROM sys.indexes i
    INNER JOIN sys.index_columns ic ON i.object_id = ic.object_id AND i.index_id = ic.index_id
    INNER JOIN sys.columns c ON ic.object_id = c.object_id AND ic.column_id = c.column_id
    WHERE i.object_id = OBJECT_ID('HR_EMPLOYEE')
      AND c.name = 'EMP_CODE'
      AND i.is_primary_key = 0
      AND i.is_unique_constraint = 0;
    IF @drop_idx <> N'' EXEC sp_executesql @drop_idx;

    -- Size modification: Convert upload columns to standard NVARCHAR(1000) instead of MAX
    ALTER TABLE HR_EMPLOYEE ALTER COLUMN EMP_CODE NVARCHAR(50) NOT NULL;
    ALTER TABLE HR_EMPLOYEE ALTER COLUMN EMPLOYEE_NAME NVARCHAR(100);
    ALTER TABLE HR_EMPLOYEE ALTER COLUMN FIRST_NAME NVARCHAR(100);
    ALTER TABLE HR_EMPLOYEE ALTER COLUMN LAST_NAME NVARCHAR(100);
    ALTER TABLE HR_EMPLOYEE ALTER COLUMN EMPLOYEE_PHOTO_UPLOAD NVARCHAR(1000);
    ALTER TABLE HR_EMPLOYEE ALTER COLUMN EMPLOYEE_SIGNATURE_UPLOAD NVARCHAR(1000);
    ALTER TABLE HR_EMPLOYEE ALTER COLUMN NDA_UPLOAD NVARCHAR(1000);
    ALTER TABLE HR_EMPLOYEE ALTER COLUMN FITNESS_CERTIFICATE_UPLOAD NVARCHAR(1000);
    ALTER TABLE HR_EMPLOYEE ALTER COLUMN PAYSLIP_PATH NVARCHAR(1000);
    ALTER TABLE HR_EMPLOYEE ALTER COLUMN CREATED_BY NVARCHAR(100);
    ALTER TABLE HR_EMPLOYEE ALTER COLUMN CREATED_DATE DATETIME;
    ALTER TABLE HR_EMPLOYEE ALTER COLUMN UPDATED_BY NVARCHAR(100);
    ALTER TABLE HR_EMPLOYEE ALTER COLUMN UPDATED_DATE DATETIME;

    IF COL_LENGTH('HR_EMPLOYEE', 'IS_ACTIVE') IS NULL
    BEGIN
        ALTER TABLE HR_EMPLOYEE ADD IS_ACTIVE BIT DEFAULT 1;
    END
END
GO

-- Standardize PK for HR_EMPLOYEE
IF OBJECT_ID('HR_EMPLOYEE', 'U') IS NOT NULL
BEGIN
    DECLARE @emp_pk NVARCHAR(256);
    SELECT TOP 1 @emp_pk = name FROM sys.key_constraints WHERE parent_object_id = OBJECT_ID('HR_EMPLOYEE') AND type = 'PK';
    IF @emp_pk IS NOT NULL AND @emp_pk <> 'PK_HR_EMPLOYEE' AND NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE referenced_object_id = OBJECT_ID('HR_EMPLOYEE'))
    BEGIN
        DECLARE @drop_emp_pk NVARCHAR(MAX) = 'ALTER TABLE HR_EMPLOYEE DROP CONSTRAINT ' + @emp_pk;
        EXEC(@drop_emp_pk);
    END
    IF NOT EXISTS (SELECT 1 FROM sys.key_constraints WHERE parent_object_id = OBJECT_ID('HR_EMPLOYEE') AND type = 'PK')
    BEGIN
        ALTER TABLE HR_EMPLOYEE ADD CONSTRAINT PK_HR_EMPLOYEE PRIMARY KEY (id);
    END

    -- Re-create Standard Unique Constraint UQ_HR_EMPLOYEE_EMP_CODE on EMP_CODE column
    IF NOT EXISTS (SELECT 1 FROM sys.key_constraints WHERE parent_object_id = OBJECT_ID('HR_EMPLOYEE') AND name = 'UQ_HR_EMPLOYEE_EMP_CODE')
    BEGIN
        ALTER TABLE HR_EMPLOYEE ADD CONSTRAINT UQ_HR_EMPLOYEE_EMP_CODE UNIQUE (EMP_CODE);
    END
END
GO


-- ==========================================
-- 2. HR_EMPLOYEE_PERSONAL (from HR_EMPLOYEE_PERSONAL_DETAIL / hrm_employee_personal_detail)
-- ==========================================
IF OBJECT_ID('dbo.sp_RenameTableCasingAndPrefix', 'P') IS NOT NULL
BEGIN
    EXEC dbo.sp_RenameTableCasingAndPrefix 'HR_EMPLOYEE_PERSONAL_DETAIL', 'HR_EMPLOYEE_PERSONAL';
    EXEC dbo.sp_RenameTableCasingAndPrefix 'hrm_employee_personal_detail', 'HR_EMPLOYEE_PERSONAL';
END
ELSE
BEGIN
    IF OBJECT_ID('HR_EMPLOYEE_PERSONAL_DETAIL', 'U') IS NOT NULL AND OBJECT_ID('HR_EMPLOYEE_PERSONAL', 'U') IS NULL
        EXEC sp_rename 'HR_EMPLOYEE_PERSONAL_DETAIL', 'HR_EMPLOYEE_PERSONAL';
    IF OBJECT_ID('hrm_employee_personal_detail', 'U') IS NOT NULL AND OBJECT_ID('HR_EMPLOYEE_PERSONAL', 'U') IS NULL
        EXEC sp_rename 'hrm_employee_personal_detail', 'HR_EMPLOYEE_PERSONAL';
END
GO

IF OBJECT_ID('HR_EMPLOYEE_PERSONAL', 'U') IS NOT NULL
BEGIN
    IF COL_LENGTH('HR_EMPLOYEE_PERSONAL', 'employee_id') IS NOT NULL AND COL_LENGTH('HR_EMPLOYEE_PERSONAL', 'EMPLOYEE_ID') IS NULL
    IF COL_LENGTH('HR_EMPLOYEE_PERSONAL', 'gender') IS NOT NULL AND COL_LENGTH('HR_EMPLOYEE_PERSONAL', 'GENDER') IS NULL
    IF COL_LENGTH('HR_EMPLOYEE_PERSONAL', 'birth_date') IS NOT NULL AND COL_LENGTH('HR_EMPLOYEE_PERSONAL', 'BIRTH_DATE') IS NULL
    IF COL_LENGTH('HR_EMPLOYEE_PERSONAL', 'marital_status') IS NOT NULL AND COL_LENGTH('HR_EMPLOYEE_PERSONAL', 'MARITAL_STATUS') IS NULL
    IF COL_LENGTH('HR_EMPLOYEE_PERSONAL', 'marriage_date') IS NOT NULL AND COL_LENGTH('HR_EMPLOYEE_PERSONAL', 'MARRIAGE_DATE') IS NULL
    IF COL_LENGTH('HR_EMPLOYEE_PERSONAL', 'number_of_children') IS NOT NULL AND COL_LENGTH('HR_EMPLOYEE_PERSONAL', 'NUMBER_OF_CHILDREN') IS NULL
    IF COL_LENGTH('HR_EMPLOYEE_PERSONAL', 'email_id') IS NOT NULL AND COL_LENGTH('HR_EMPLOYEE_PERSONAL', 'PERSONAL_EMAIL') IS NULL
    IF COL_LENGTH('HR_EMPLOYEE_PERSONAL', 'passport_number') IS NOT NULL AND COL_LENGTH('HR_EMPLOYEE_PERSONAL', 'PASSPORT_NUMBER') IS NULL
    IF COL_LENGTH('HR_EMPLOYEE_PERSONAL', 'passport_issue_city') IS NOT NULL AND COL_LENGTH('HR_EMPLOYEE_PERSONAL', 'PASSPORT_ISSUE_CITY') IS NULL
    IF COL_LENGTH('HR_EMPLOYEE_PERSONAL', 'nationality') IS NOT NULL AND COL_LENGTH('HR_EMPLOYEE_PERSONAL', 'NATIONALITY') IS NULL
    IF COL_LENGTH('HR_EMPLOYEE_PERSONAL', 'blood_group') IS NOT NULL AND COL_LENGTH('HR_EMPLOYEE_PERSONAL', 'BLOOD_GROUP') IS NULL
    IF COL_LENGTH('HR_EMPLOYEE_PERSONAL', 'religion') IS NOT NULL AND COL_LENGTH('HR_EMPLOYEE_PERSONAL', 'RELIGION') IS NULL
    IF COL_LENGTH('HR_EMPLOYEE_PERSONAL', 'region') IS NOT NULL AND COL_LENGTH('HR_EMPLOYEE_PERSONAL', 'REGION') IS NULL
    IF COL_LENGTH('HR_EMPLOYEE_PERSONAL', 'height') IS NOT NULL AND COL_LENGTH('HR_EMPLOYEE_PERSONAL', 'HEIGHT') IS NULL
    IF COL_LENGTH('HR_EMPLOYEE_PERSONAL', 'weight') IS NOT NULL AND COL_LENGTH('HR_EMPLOYEE_PERSONAL', 'WEIGHT') IS NULL
    IF COL_LENGTH('HR_EMPLOYEE_PERSONAL', 'shirt_size') IS NOT NULL AND COL_LENGTH('HR_EMPLOYEE_PERSONAL', 'SHIRT_SIZE') IS NULL
    IF COL_LENGTH('HR_EMPLOYEE_PERSONAL', 'pant_size') IS NOT NULL AND COL_LENGTH('HR_EMPLOYEE_PERSONAL', 'PANT_SIZE') IS NULL
    IF COL_LENGTH('HR_EMPLOYEE_PERSONAL', 'shoe_size') IS NOT NULL AND COL_LENGTH('HR_EMPLOYEE_PERSONAL', 'SHOE_SIZE') IS NULL
    IF COL_LENGTH('HR_EMPLOYEE_PERSONAL', 'insurance_number') IS NOT NULL AND COL_LENGTH('HR_EMPLOYEE_PERSONAL', 'INSURANCE_NUMBER') IS NULL
    IF COL_LENGTH('HR_EMPLOYEE_PERSONAL', 'esic_number') IS NOT NULL AND COL_LENGTH('HR_EMPLOYEE_PERSONAL', 'ESIC_NUMBER') IS NULL
    IF COL_LENGTH('HR_EMPLOYEE_PERSONAL', 'pf_number') IS NOT NULL AND COL_LENGTH('HR_EMPLOYEE_PERSONAL', 'PF_NUMBER') IS NULL
    IF COL_LENGTH('HR_EMPLOYEE_PERSONAL', 'insurance_expiry_date') IS NOT NULL AND COL_LENGTH('HR_EMPLOYEE_PERSONAL', 'INSURANCE_EXPIRY_DATE') IS NULL
    IF COL_LENGTH('HR_EMPLOYEE_PERSONAL', 'uan_number') IS NOT NULL AND COL_LENGTH('HR_EMPLOYEE_PERSONAL', 'UAN_NUMBER') IS NULL
    IF COL_LENGTH('HR_EMPLOYEE_PERSONAL', 'pan_number') IS NOT NULL AND COL_LENGTH('HR_EMPLOYEE_PERSONAL', 'PAN_NUMBER') IS NULL
    IF COL_LENGTH('HR_EMPLOYEE_PERSONAL', 'aadhar_number') IS NOT NULL AND COL_LENGTH('HR_EMPLOYEE_PERSONAL', 'AADHAR_NUMBER') IS NULL
    IF COL_LENGTH('HR_EMPLOYEE_PERSONAL', 'driving_license_number') IS NOT NULL AND COL_LENGTH('HR_EMPLOYEE_PERSONAL', 'DRIVING_LICENSE_NUMBER') IS NULL
    IF COL_LENGTH('HR_EMPLOYEE_PERSONAL', 'license_expiry_date') IS NOT NULL AND COL_LENGTH('HR_EMPLOYEE_PERSONAL', 'LICENSE_EXPIRY_DATE') IS NULL
    IF COL_LENGTH('HR_EMPLOYEE_PERSONAL', 'election_card_number') IS NOT NULL AND COL_LENGTH('HR_EMPLOYEE_PERSONAL', 'ELECTION_CARD_NUMBER') IS NULL
    IF COL_LENGTH('HR_EMPLOYEE_PERSONAL', 'ration_card_number') IS NOT NULL AND COL_LENGTH('HR_EMPLOYEE_PERSONAL', 'RATION_CARD_NUMBER') IS NULL
    IF COL_LENGTH('HR_EMPLOYEE_PERSONAL', 'company_issued_mobile') IS NOT NULL AND COL_LENGTH('HR_EMPLOYEE_PERSONAL', 'COMPANY_ISSUED_MOBILE') IS NULL
    IF COL_LENGTH('HR_EMPLOYEE_PERSONAL', 'mobile_deduction') IS NOT NULL AND COL_LENGTH('HR_EMPLOYEE_PERSONAL', 'MOBILE_DEDUCTION') IS NULL
    IF COL_LENGTH('HR_EMPLOYEE_PERSONAL', 'canteen_allowance') IS NOT NULL AND COL_LENGTH('HR_EMPLOYEE_PERSONAL', 'CANTEEN_ALLOWANCE') IS NULL
    IF COL_LENGTH('HR_EMPLOYEE_PERSONAL', 'loan_installment_month') IS NOT NULL AND COL_LENGTH('HR_EMPLOYEE_PERSONAL', 'LOAN_INSTALLMENT_MONTH') IS NULL
    IF COL_LENGTH('HR_EMPLOYEE_PERSONAL', 'created_by') IS NOT NULL AND COL_LENGTH('HR_EMPLOYEE_PERSONAL', 'CREATED_BY') IS NULL
    IF COL_LENGTH('HR_EMPLOYEE_PERSONAL', 'created_at') IS NOT NULL AND COL_LENGTH('HR_EMPLOYEE_PERSONAL', 'CREATED_DATE') IS NULL
    IF COL_LENGTH('HR_EMPLOYEE_PERSONAL', 'updated_by') IS NOT NULL AND COL_LENGTH('HR_EMPLOYEE_PERSONAL', 'UPDATED_BY') IS NULL
    IF COL_LENGTH('HR_EMPLOYEE_PERSONAL', 'updated_at') IS NOT NULL AND COL_LENGTH('HR_EMPLOYEE_PERSONAL', 'UPDATED_DATE') IS NULL
END
GO

IF OBJECT_ID('HR_EMPLOYEE_PERSONAL', 'U') IS NOT NULL
BEGIN
    ALTER TABLE HR_EMPLOYEE_PERSONAL ALTER COLUMN GENDER NVARCHAR(20);
    ALTER TABLE HR_EMPLOYEE_PERSONAL ALTER COLUMN MARITAL_STATUS NVARCHAR(30);
    ALTER TABLE HR_EMPLOYEE_PERSONAL ALTER COLUMN PERSONAL_EMAIL NVARCHAR(255);
    ALTER TABLE HR_EMPLOYEE_PERSONAL ALTER COLUMN CREATED_BY NVARCHAR(100);
    ALTER TABLE HR_EMPLOYEE_PERSONAL ALTER COLUMN CREATED_DATE DATETIME;
    ALTER TABLE HR_EMPLOYEE_PERSONAL ALTER COLUMN UPDATED_BY NVARCHAR(100);
    ALTER TABLE HR_EMPLOYEE_PERSONAL ALTER COLUMN UPDATED_DATE DATETIME;

    IF COL_LENGTH('HR_EMPLOYEE_PERSONAL', 'IS_ACTIVE') IS NULL
        ALTER TABLE HR_EMPLOYEE_PERSONAL ADD IS_ACTIVE BIT DEFAULT 1;
END
GO

-- Standardize PK for HR_EMPLOYEE_PERSONAL
IF OBJECT_ID('HR_EMPLOYEE_PERSONAL', 'U') IS NOT NULL
BEGIN
    DECLARE @pers_pk NVARCHAR(256);
    SELECT TOP 1 @pers_pk = name FROM sys.key_constraints WHERE parent_object_id = OBJECT_ID('HR_EMPLOYEE_PERSONAL') AND type = 'PK';
    IF @pers_pk IS NOT NULL AND @pers_pk <> 'PK_HR_EMPLOYEE_PERSONAL' AND NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE referenced_object_id = OBJECT_ID('HR_EMPLOYEE_PERSONAL'))
    BEGIN
        DECLARE @drop_pers_pk NVARCHAR(MAX) = 'ALTER TABLE HR_EMPLOYEE_PERSONAL DROP CONSTRAINT ' + @pers_pk;
        EXEC(@drop_pers_pk);
    END
    IF NOT EXISTS (SELECT 1 FROM sys.key_constraints WHERE parent_object_id = OBJECT_ID('HR_EMPLOYEE_PERSONAL') AND type = 'PK')
    BEGIN
        ALTER TABLE HR_EMPLOYEE_PERSONAL ADD CONSTRAINT PK_HR_EMPLOYEE_PERSONAL PRIMARY KEY (id);
    END
END
GO


-- ==========================================
-- 3. HR_EMPLOYEE_CONTACT (from HR_EMPLOYEE_CONTACT / hrm_employee_contact)
-- ==========================================
IF OBJECT_ID('dbo.sp_RenameTableCasingAndPrefix', 'P') IS NOT NULL
BEGIN
    EXEC dbo.sp_RenameTableCasingAndPrefix 'hrm_employee_contact', 'HR_EMPLOYEE_CONTACT';
END
ELSE
BEGIN
    IF OBJECT_ID('hrm_employee_contact', 'U') IS NOT NULL AND OBJECT_ID('HR_EMPLOYEE_CONTACT', 'U') IS NULL
        EXEC sp_rename 'hrm_employee_contact', 'HR_EMPLOYEE_CONTACT';
END
GO

IF OBJECT_ID('HR_EMPLOYEE_CONTACT', 'U') IS NOT NULL
BEGIN
    IF COL_LENGTH('HR_EMPLOYEE_CONTACT', 'employee_id') IS NOT NULL AND COL_LENGTH('HR_EMPLOYEE_CONTACT', 'EMPLOYEE_ID') IS NULL
    IF COL_LENGTH('HR_EMPLOYEE_CONTACT', 'mobile') IS NOT NULL AND COL_LENGTH('HR_EMPLOYEE_CONTACT', 'MOBILE') IS NULL
    IF COL_LENGTH('HR_EMPLOYEE_CONTACT', 'alternate_mobile') IS NOT NULL AND COL_LENGTH('HR_EMPLOYEE_CONTACT', 'ALTERNATE_MOBILE') IS NULL
    IF COL_LENGTH('HR_EMPLOYEE_CONTACT', 'perm_address1') IS NOT NULL AND COL_LENGTH('HR_EMPLOYEE_CONTACT', 'PERM_ADDRESS1') IS NULL
    IF COL_LENGTH('HR_EMPLOYEE_CONTACT', 'perm_city') IS NOT NULL AND COL_LENGTH('HR_EMPLOYEE_CONTACT', 'PERM_CITY') IS NULL
    IF COL_LENGTH('HR_EMPLOYEE_CONTACT', 'perm_state') IS NOT NULL AND COL_LENGTH('HR_EMPLOYEE_CONTACT', 'PERM_STATE') IS NULL
    IF COL_LENGTH('HR_EMPLOYEE_CONTACT', 'perm_country') IS NOT NULL AND COL_LENGTH('HR_EMPLOYEE_CONTACT', 'PERM_COUNTRY') IS NULL
    IF COL_LENGTH('HR_EMPLOYEE_CONTACT', 'perm_pin_code') IS NOT NULL AND COL_LENGTH('HR_EMPLOYEE_CONTACT', 'PERM_PIN_CODE') IS NULL
    IF COL_LENGTH('HR_EMPLOYEE_CONTACT', 'comm_address1') IS NOT NULL AND COL_LENGTH('HR_EMPLOYEE_CONTACT', 'COMM_ADDRESS1') IS NULL
    IF COL_LENGTH('HR_EMPLOYEE_CONTACT', 'comm_city') IS NOT NULL AND COL_LENGTH('HR_EMPLOYEE_CONTACT', 'COMM_CITY') IS NULL
    IF COL_LENGTH('HR_EMPLOYEE_CONTACT', 'comm_state') IS NOT NULL AND COL_LENGTH('HR_EMPLOYEE_CONTACT', 'COMM_STATE') IS NULL
    IF COL_LENGTH('HR_EMPLOYEE_CONTACT', 'comm_country') IS NOT NULL AND COL_LENGTH('HR_EMPLOYEE_CONTACT', 'COMM_COUNTRY') IS NULL
    IF COL_LENGTH('HR_EMPLOYEE_CONTACT', 'comm_pin_code') IS NOT NULL AND COL_LENGTH('HR_EMPLOYEE_CONTACT', 'COMM_PIN_CODE') IS NULL
    IF COL_LENGTH('HR_EMPLOYEE_CONTACT', 'created_by') IS NOT NULL AND COL_LENGTH('HR_EMPLOYEE_CONTACT', 'CREATED_BY') IS NULL
    IF COL_LENGTH('HR_EMPLOYEE_CONTACT', 'created_at') IS NOT NULL AND COL_LENGTH('HR_EMPLOYEE_CONTACT', 'CREATED_DATE') IS NULL
    IF COL_LENGTH('HR_EMPLOYEE_CONTACT', 'updated_by') IS NOT NULL AND COL_LENGTH('HR_EMPLOYEE_CONTACT', 'UPDATED_BY') IS NULL
    IF COL_LENGTH('HR_EMPLOYEE_CONTACT', 'updated_at') IS NOT NULL AND COL_LENGTH('HR_EMPLOYEE_CONTACT', 'UPDATED_DATE') IS NULL
END
GO

IF OBJECT_ID('HR_EMPLOYEE_CONTACT', 'U') IS NOT NULL
BEGIN
    ALTER TABLE HR_EMPLOYEE_CONTACT ALTER COLUMN MOBILE NVARCHAR(20);
    ALTER TABLE HR_EMPLOYEE_CONTACT ALTER COLUMN ALTERNATE_MOBILE NVARCHAR(20);
    ALTER TABLE HR_EMPLOYEE_CONTACT ALTER COLUMN PERM_ADDRESS1 NVARCHAR(500);
    ALTER TABLE HR_EMPLOYEE_CONTACT ALTER COLUMN COMM_ADDRESS1 NVARCHAR(500);
    ALTER TABLE HR_EMPLOYEE_CONTACT ALTER COLUMN CREATED_BY NVARCHAR(100);
    ALTER TABLE HR_EMPLOYEE_CONTACT ALTER COLUMN CREATED_DATE DATETIME;
    ALTER TABLE HR_EMPLOYEE_CONTACT ALTER COLUMN UPDATED_BY NVARCHAR(100);
    ALTER TABLE HR_EMPLOYEE_CONTACT ALTER COLUMN UPDATED_DATE DATETIME;

    IF COL_LENGTH('HR_EMPLOYEE_CONTACT', 'IS_ACTIVE') IS NULL
        ALTER TABLE HR_EMPLOYEE_CONTACT ADD IS_ACTIVE BIT DEFAULT 1;
END
GO

-- Standardize PK for HR_EMPLOYEE_CONTACT
IF OBJECT_ID('HR_EMPLOYEE_CONTACT', 'U') IS NOT NULL
BEGIN
    DECLARE @cont_pk NVARCHAR(256);
    SELECT TOP 1 @cont_pk = name FROM sys.key_constraints WHERE parent_object_id = OBJECT_ID('HR_EMPLOYEE_CONTACT') AND type = 'PK';
    IF @cont_pk IS NOT NULL AND @cont_pk <> 'PK_HR_EMPLOYEE_CONTACT' AND NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE referenced_object_id = OBJECT_ID('HR_EMPLOYEE_CONTACT'))
    BEGIN
        DECLARE @drop_cont_pk NVARCHAR(MAX) = 'ALTER TABLE HR_EMPLOYEE_CONTACT DROP CONSTRAINT ' + @cont_pk;
        EXEC(@drop_cont_pk);
    END
    IF NOT EXISTS (SELECT 1 FROM sys.key_constraints WHERE parent_object_id = OBJECT_ID('HR_EMPLOYEE_CONTACT') AND type = 'PK')
    BEGIN
        ALTER TABLE HR_EMPLOYEE_CONTACT ADD CONSTRAINT PK_HR_EMPLOYEE_CONTACT PRIMARY KEY (id);
    END
END
GO


-- ==========================================
-- 4. HR_EMPLOYEE_JOB_PROFILE
-- ==========================================
IF OBJECT_ID('HR_EMPLOYEE_JOB_PROFILE', 'U') IS NOT NULL
BEGIN
    IF COL_LENGTH('HR_EMPLOYEE_JOB_PROFILE', 'employee_id') IS NOT NULL AND COL_LENGTH('HR_EMPLOYEE_JOB_PROFILE', 'EMPLOYEE_ID') IS NULL
    IF COL_LENGTH('HR_EMPLOYEE_JOB_PROFILE', 'wages_type') IS NOT NULL AND COL_LENGTH('HR_EMPLOYEE_JOB_PROFILE', 'WAGES_TYPE') IS NULL
    IF COL_LENGTH('HR_EMPLOYEE_JOB_PROFILE', 'payment_mode') IS NOT NULL AND COL_LENGTH('HR_EMPLOYEE_JOB_PROFILE', 'PAYMENT_MODE') IS NULL
    IF COL_LENGTH('HR_EMPLOYEE_JOB_PROFILE', 'salary_account_number') IS NOT NULL AND COL_LENGTH('HR_EMPLOYEE_JOB_PROFILE', 'SALARY_ACCOUNT_NUMBER') IS NULL
    IF COL_LENGTH('HR_EMPLOYEE_JOB_PROFILE', 'account_name') IS NOT NULL AND COL_LENGTH('HR_EMPLOYEE_JOB_PROFILE', 'ACCOUNT_NAME') IS NULL
    IF COL_LENGTH('HR_EMPLOYEE_JOB_PROFILE', 'bank_account_type') IS NOT NULL AND COL_LENGTH('HR_EMPLOYEE_JOB_PROFILE', 'BANK_ACCOUNT_TYPE') IS NULL
    IF COL_LENGTH('HR_EMPLOYEE_JOB_PROFILE', 'personal_account_number') IS NOT NULL AND COL_LENGTH('HR_EMPLOYEE_JOB_PROFILE', 'PERSONAL_ACCOUNT_NUMBER') IS NULL
    IF COL_LENGTH('HR_EMPLOYEE_JOB_PROFILE', 'bank_name') IS NOT NULL AND COL_LENGTH('HR_EMPLOYEE_JOB_PROFILE', 'BANK_NAME') IS NULL
    IF COL_LENGTH('HR_EMPLOYEE_JOB_PROFILE', 'ifsc_code') IS NOT NULL AND COL_LENGTH('HR_EMPLOYEE_JOB_PROFILE', 'IFSC_CODE') IS NULL
    IF COL_LENGTH('HR_EMPLOYEE_JOB_PROFILE', 'branch_name') IS NOT NULL AND COL_LENGTH('HR_EMPLOYEE_JOB_PROFILE', 'BRANCH_NAME') IS NULL
    IF COL_LENGTH('HR_EMPLOYEE_JOB_PROFILE', 'gross_salary') IS NOT NULL AND COL_LENGTH('HR_EMPLOYEE_JOB_PROFILE', 'GROSS_SALARY') IS NULL
    IF COL_LENGTH('HR_EMPLOYEE_JOB_PROFILE', 'net_salary') IS NOT NULL AND COL_LENGTH('HR_EMPLOYEE_JOB_PROFILE', 'NET_SALARY') IS NULL
    IF COL_LENGTH('HR_EMPLOYEE_JOB_PROFILE', 'basic_salary') IS NOT NULL AND COL_LENGTH('HR_EMPLOYEE_JOB_PROFILE', 'BASIC_SALARY') IS NULL
    IF COL_LENGTH('HR_EMPLOYEE_JOB_PROFILE', 'da') IS NOT NULL AND COL_LENGTH('HR_EMPLOYEE_JOB_PROFILE', 'DA') IS NULL
    IF COL_LENGTH('HR_EMPLOYEE_JOB_PROFILE', 'hra') IS NOT NULL AND COL_LENGTH('HR_EMPLOYEE_JOB_PROFILE', 'HRA') IS NULL
    IF COL_LENGTH('HR_EMPLOYEE_JOB_PROFILE', 'special_allowance') IS NOT NULL AND COL_LENGTH('HR_EMPLOYEE_JOB_PROFILE', 'SPECIAL_ALLOWANCE') IS NULL
    IF COL_LENGTH('HR_EMPLOYEE_JOB_PROFILE', 'performance_incentive') IS NOT NULL AND COL_LENGTH('HR_EMPLOYEE_JOB_PROFILE', 'PERFORMANCE_INCENTIVE') IS NULL
    IF COL_LENGTH('HR_EMPLOYEE_JOB_PROFILE', 'canteen_deduction') IS NOT NULL AND COL_LENGTH('HR_EMPLOYEE_JOB_PROFILE', 'CANTEEN_DEDUCTION') IS NULL
    IF COL_LENGTH('HR_EMPLOYEE_JOB_PROFILE', 'pf_type') IS NOT NULL AND COL_LENGTH('HR_EMPLOYEE_JOB_PROFILE', 'PF_TYPE') IS NULL
    IF COL_LENGTH('HR_EMPLOYEE_JOB_PROFILE', 'pf_employee') IS NOT NULL AND COL_LENGTH('HR_EMPLOYEE_JOB_PROFILE', 'PF_EMPLOYEE') IS NULL
    IF COL_LENGTH('HR_EMPLOYEE_JOB_PROFILE', 'esi_employee') IS NOT NULL AND COL_LENGTH('HR_EMPLOYEE_JOB_PROFILE', 'ESI_EMPLOYEE') IS NULL
    IF COL_LENGTH('HR_EMPLOYEE_JOB_PROFILE', 'professional_tax_amount') IS NOT NULL AND COL_LENGTH('HR_EMPLOYEE_JOB_PROFILE', 'PROFESSIONAL_TAX_AMOUNT') IS NULL
    IF COL_LENGTH('HR_EMPLOYEE_JOB_PROFILE', 'pf_document') IS NOT NULL AND COL_LENGTH('HR_EMPLOYEE_JOB_PROFILE', 'PF_DOCUMENT') IS NULL
    IF COL_LENGTH('HR_EMPLOYEE_JOB_PROFILE', 'monthly_ctc') IS NOT NULL AND COL_LENGTH('HR_EMPLOYEE_JOB_PROFILE', 'MONTHLY_CTC') IS NULL
    IF COL_LENGTH('HR_EMPLOYEE_JOB_PROFILE', 'basic_salary_ctc') IS NOT NULL AND COL_LENGTH('HR_EMPLOYEE_JOB_PROFILE', 'BASIC_SALARY_CTC') IS NULL
    IF COL_LENGTH('HR_EMPLOYEE_JOB_PROFILE', 'da_ctc') IS NOT NULL AND COL_LENGTH('HR_EMPLOYEE_JOB_PROFILE', 'DA_CTC') IS NULL
    IF COL_LENGTH('HR_EMPLOYEE_JOB_PROFILE', 'special_allowance_ctc') IS NOT NULL AND COL_LENGTH('HR_EMPLOYEE_JOB_PROFILE', 'SPECIAL_ALLOWANCE_CTC') IS NULL
    IF COL_LENGTH('HR_EMPLOYEE_JOB_PROFILE', 'canteen_allowance') IS NOT NULL AND COL_LENGTH('HR_EMPLOYEE_JOB_PROFILE', 'CANTEEN_ALLOWANCE') IS NULL
    IF COL_LENGTH('HR_EMPLOYEE_JOB_PROFILE', 'performance_incentive_ctc') IS NOT NULL AND COL_LENGTH('HR_EMPLOYEE_JOB_PROFILE', 'PERFORMANCE_INCENTIVE_CTC') IS NULL
    IF COL_LENGTH('HR_EMPLOYEE_JOB_PROFILE', 'esi_ctc') IS NOT NULL AND COL_LENGTH('HR_EMPLOYEE_JOB_PROFILE', 'ESI_CTC') IS NULL
    IF COL_LENGTH('HR_EMPLOYEE_JOB_PROFILE', 'pf_ctc') IS NOT NULL AND COL_LENGTH('HR_EMPLOYEE_JOB_PROFILE', 'PF_CTC') IS NULL
    IF COL_LENGTH('HR_EMPLOYEE_JOB_PROFILE', 'gross_ctc') IS NOT NULL AND COL_LENGTH('HR_EMPLOYEE_JOB_PROFILE', 'GROSS_CTC') IS NULL
    IF COL_LENGTH('HR_EMPLOYEE_JOB_PROFILE', 'employer_pf') IS NOT NULL AND COL_LENGTH('HR_EMPLOYEE_JOB_PROFILE', 'EMPLOYER_PF') IS NULL
    IF COL_LENGTH('HR_EMPLOYEE_JOB_PROFILE', 'employer_esi') IS NOT NULL AND COL_LENGTH('HR_EMPLOYEE_JOB_PROFILE', 'EMPLOYER_ESI') IS NULL
    IF COL_LENGTH('HR_EMPLOYEE_JOB_PROFILE', 'uniform_allowance') IS NOT NULL AND COL_LENGTH('HR_EMPLOYEE_JOB_PROFILE', 'UNIFORM_ALLOWANCE') IS NULL
    IF COL_LENGTH('HR_EMPLOYEE_JOB_PROFILE', 'shoe_allowance') IS NOT NULL AND COL_LENGTH('HR_EMPLOYEE_JOB_PROFILE', 'SHOE_ALLOWANCE') IS NULL
    IF COL_LENGTH('HR_EMPLOYEE_JOB_PROFILE', 'mobile_allowance_cug') IS NOT NULL AND COL_LENGTH('HR_EMPLOYEE_JOB_PROFILE', 'MOBILE_ALLOWANCE_CUG') IS NULL
    IF COL_LENGTH('HR_EMPLOYEE_JOB_PROFILE', 'annual_ctc') IS NOT NULL AND COL_LENGTH('HR_EMPLOYEE_JOB_PROFILE', 'ANNUAL_CTC') IS NULL
    IF COL_LENGTH('HR_EMPLOYEE_JOB_PROFILE', 'salary_ctc') IS NOT NULL AND COL_LENGTH('HR_EMPLOYEE_JOB_PROFILE', 'SALARY_CTC') IS NULL
    IF COL_LENGTH('HR_EMPLOYEE_JOB_PROFILE', 'gratuity') IS NOT NULL AND COL_LENGTH('HR_EMPLOYEE_JOB_PROFILE', 'GRATUITY') IS NULL
    IF COL_LENGTH('HR_EMPLOYEE_JOB_PROFILE', 'bonus') IS NOT NULL AND COL_LENGTH('HR_EMPLOYEE_JOB_PROFILE', 'BONUS') IS NULL
    IF COL_LENGTH('HR_EMPLOYEE_JOB_PROFILE', 'special_incentive') IS NOT NULL AND COL_LENGTH('HR_EMPLOYEE_JOB_PROFILE', 'SPECIAL_INCENTIVE') IS NULL
    IF COL_LENGTH('HR_EMPLOYEE_JOB_PROFILE', 'performance_linked_incentive') IS NOT NULL AND COL_LENGTH('HR_EMPLOYEE_JOB_PROFILE', 'PERFORMANCE_LINKED_INCENTIVE') IS NULL
    IF COL_LENGTH('HR_EMPLOYEE_JOB_PROFILE', 'health_insurance') IS NOT NULL AND COL_LENGTH('HR_EMPLOYEE_JOB_PROFILE', 'HEALTH_INSURANCE') IS NULL
    IF COL_LENGTH('HR_EMPLOYEE_JOB_PROFILE', 'created_by') IS NOT NULL AND COL_LENGTH('HR_EMPLOYEE_JOB_PROFILE', 'CREATED_BY') IS NULL
    IF COL_LENGTH('HR_EMPLOYEE_JOB_PROFILE', 'created_at') IS NOT NULL AND COL_LENGTH('HR_EMPLOYEE_JOB_PROFILE', 'CREATED_DATE') IS NULL
    IF COL_LENGTH('HR_EMPLOYEE_JOB_PROFILE', 'updated_by') IS NOT NULL AND COL_LENGTH('HR_EMPLOYEE_JOB_PROFILE', 'UPDATED_BY') IS NULL
    IF COL_LENGTH('HR_EMPLOYEE_JOB_PROFILE', 'updated_at') IS NOT NULL AND COL_LENGTH('HR_EMPLOYEE_JOB_PROFILE', 'UPDATED_DATE') IS NULL
END
GO

IF OBJECT_ID('HR_EMPLOYEE_JOB_PROFILE', 'U') IS NOT NULL
BEGIN
    ALTER TABLE HR_EMPLOYEE_JOB_PROFILE ALTER COLUMN WAGES_TYPE NVARCHAR(50);
    ALTER TABLE HR_EMPLOYEE_JOB_PROFILE ALTER COLUMN PAYMENT_MODE NVARCHAR(50);
    ALTER TABLE HR_EMPLOYEE_JOB_PROFILE ALTER COLUMN SALARY_ACCOUNT_NUMBER NVARCHAR(50);
    ALTER TABLE HR_EMPLOYEE_JOB_PROFILE ALTER COLUMN PF_DOCUMENT NVARCHAR(1000);
    ALTER TABLE HR_EMPLOYEE_JOB_PROFILE ALTER COLUMN CREATED_BY NVARCHAR(100);
    ALTER TABLE HR_EMPLOYEE_JOB_PROFILE ALTER COLUMN CREATED_DATE DATETIME;
    ALTER TABLE HR_EMPLOYEE_JOB_PROFILE ALTER COLUMN UPDATED_BY NVARCHAR(100);
    ALTER TABLE HR_EMPLOYEE_JOB_PROFILE ALTER COLUMN UPDATED_DATE DATETIME;

    IF COL_LENGTH('HR_EMPLOYEE_JOB_PROFILE', 'IS_ACTIVE') IS NULL
        ALTER TABLE HR_EMPLOYEE_JOB_PROFILE ADD IS_ACTIVE BIT DEFAULT 1;
END
GO

-- Standardize PK for HR_EMPLOYEE_JOB_PROFILE
IF OBJECT_ID('HR_EMPLOYEE_JOB_PROFILE', 'U') IS NOT NULL
BEGIN
    DECLARE @job_pk NVARCHAR(256);
    SELECT TOP 1 @job_pk = name FROM sys.key_constraints WHERE parent_object_id = OBJECT_ID('HR_EMPLOYEE_JOB_PROFILE') AND type = 'PK';
    IF @job_pk IS NOT NULL AND @job_pk <> 'PK_HR_EMPLOYEE_JOB_PROFILE' AND NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE referenced_object_id = OBJECT_ID('HR_EMPLOYEE_JOB_PROFILE'))
    BEGIN
        DECLARE @drop_job_pk NVARCHAR(MAX) = 'ALTER TABLE HR_EMPLOYEE_JOB_PROFILE DROP CONSTRAINT ' + @job_pk;
        EXEC(@drop_job_pk);
    END
    IF NOT EXISTS (SELECT 1 FROM sys.key_constraints WHERE parent_object_id = OBJECT_ID('HR_EMPLOYEE_JOB_PROFILE') AND type = 'PK')
    BEGIN
        ALTER TABLE HR_EMPLOYEE_JOB_PROFILE ADD CONSTRAINT PK_HR_EMPLOYEE_JOB_PROFILE PRIMARY KEY (id);
    END
END
GO


-- ==========================================
-- 5. HR_EMPLOYEE_EDUCATION
-- ==========================================
IF OBJECT_ID('HR_EMPLOYEE_EDUCATION', 'U') IS NOT NULL
BEGIN
    IF COL_LENGTH('HR_EMPLOYEE_EDUCATION', 'employee_id') IS NOT NULL AND COL_LENGTH('HR_EMPLOYEE_EDUCATION', 'EMPLOYEE_ID') IS NULL
    IF COL_LENGTH('HR_EMPLOYEE_EDUCATION', 'education') IS NOT NULL AND COL_LENGTH('HR_EMPLOYEE_EDUCATION', 'EDUCATION') IS NULL
    IF COL_LENGTH('HR_EMPLOYEE_EDUCATION', 'institution_name') IS NOT NULL AND COL_LENGTH('HR_EMPLOYEE_EDUCATION', 'INSTITUTION_NAME') IS NULL
    IF COL_LENGTH('HR_EMPLOYEE_EDUCATION', 'university') IS NOT NULL AND COL_LENGTH('HR_EMPLOYEE_EDUCATION', 'UNIVERSITY') IS NULL
    IF COL_LENGTH('HR_EMPLOYEE_EDUCATION', 'type') IS NOT NULL AND COL_LENGTH('HR_EMPLOYEE_EDUCATION', 'TYPE') IS NULL
    IF COL_LENGTH('HR_EMPLOYEE_EDUCATION', 'year_of_passing') IS NOT NULL AND COL_LENGTH('HR_EMPLOYEE_EDUCATION', 'YEAR_OF_PASSING') IS NULL
    IF COL_LENGTH('HR_EMPLOYEE_EDUCATION', 'percentage_grade') IS NOT NULL AND COL_LENGTH('HR_EMPLOYEE_EDUCATION', 'PERCENTAGE_GRADE') IS NULL
    IF COL_LENGTH('HR_EMPLOYEE_EDUCATION', 'documents') IS NOT NULL AND COL_LENGTH('HR_EMPLOYEE_EDUCATION', 'DOCUMENTS') IS NULL
    IF COL_LENGTH('HR_EMPLOYEE_EDUCATION', 'created_by') IS NOT NULL AND COL_LENGTH('HR_EMPLOYEE_EDUCATION', 'CREATED_BY') IS NULL
    IF COL_LENGTH('HR_EMPLOYEE_EDUCATION', 'created_at') IS NOT NULL AND COL_LENGTH('HR_EMPLOYEE_EDUCATION', 'CREATED_DATE') IS NULL
    IF COL_LENGTH('HR_EMPLOYEE_EDUCATION', 'updated_by') IS NOT NULL AND COL_LENGTH('HR_EMPLOYEE_EDUCATION', 'UPDATED_BY') IS NULL
    IF COL_LENGTH('HR_EMPLOYEE_EDUCATION', 'updated_at') IS NOT NULL AND COL_LENGTH('HR_EMPLOYEE_EDUCATION', 'UPDATED_DATE') IS NULL
END
GO

IF OBJECT_ID('HR_EMPLOYEE_EDUCATION', 'U') IS NOT NULL
BEGIN
    ALTER TABLE HR_EMPLOYEE_EDUCATION ALTER COLUMN EDUCATION NVARCHAR(100);
    ALTER TABLE HR_EMPLOYEE_EDUCATION ALTER COLUMN DOCUMENTS NVARCHAR(500);
    ALTER TABLE HR_EMPLOYEE_EDUCATION ALTER COLUMN CREATED_BY NVARCHAR(100);
    ALTER TABLE HR_EMPLOYEE_EDUCATION ALTER COLUMN CREATED_DATE DATETIME;
    ALTER TABLE HR_EMPLOYEE_EDUCATION ALTER COLUMN UPDATED_BY NVARCHAR(100);
    ALTER TABLE HR_EMPLOYEE_EDUCATION ALTER COLUMN UPDATED_DATE DATETIME;

    IF COL_LENGTH('HR_EMPLOYEE_EDUCATION', 'IS_ACTIVE') IS NULL
        ALTER TABLE HR_EMPLOYEE_EDUCATION ADD IS_ACTIVE BIT DEFAULT 1;
END
GO

-- PK
IF OBJECT_ID('HR_EMPLOYEE_EDUCATION', 'U') IS NOT NULL
BEGIN
    DECLARE @edu_pk NVARCHAR(256);
    SELECT TOP 1 @edu_pk = name FROM sys.key_constraints WHERE parent_object_id = OBJECT_ID('HR_EMPLOYEE_EDUCATION') AND type = 'PK';
    IF @edu_pk IS NOT NULL AND @edu_pk <> 'PK_HR_EMPLOYEE_EDUCATION' AND NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE referenced_object_id = OBJECT_ID('HR_EMPLOYEE_EDUCATION'))
    BEGIN
        DECLARE @drop_edu_pk NVARCHAR(MAX) = 'ALTER TABLE HR_EMPLOYEE_EDUCATION DROP CONSTRAINT ' + @edu_pk;
        EXEC(@drop_edu_pk);
    END
    IF NOT EXISTS (SELECT 1 FROM sys.key_constraints WHERE parent_object_id = OBJECT_ID('HR_EMPLOYEE_EDUCATION') AND type = 'PK')
    BEGIN
        ALTER TABLE HR_EMPLOYEE_EDUCATION ADD CONSTRAINT PK_HR_EMPLOYEE_EDUCATION PRIMARY KEY (id);
    END
END
GO


-- ==========================================
-- 6. HR_EMPLOYEE_EXPERIENCE
-- ==========================================
IF OBJECT_ID('HR_EMPLOYEE_EXPERIENCE', 'U') IS NOT NULL
BEGIN
    IF COL_LENGTH('HR_EMPLOYEE_EXPERIENCE', 'employee_id') IS NOT NULL AND COL_LENGTH('HR_EMPLOYEE_EXPERIENCE', 'EMPLOYEE_ID') IS NULL
    IF COL_LENGTH('HR_EMPLOYEE_EXPERIENCE', 'company_name') IS NOT NULL AND COL_LENGTH('HR_EMPLOYEE_EXPERIENCE', 'COMPANY_NAME') IS NULL
    IF COL_LENGTH('HR_EMPLOYEE_EXPERIENCE', 'location') IS NOT NULL AND COL_LENGTH('HR_EMPLOYEE_EXPERIENCE', 'LOCATION') IS NULL
    IF COL_LENGTH('HR_EMPLOYEE_EXPERIENCE', 'from_date') IS NOT NULL AND COL_LENGTH('HR_EMPLOYEE_EXPERIENCE', 'FROM_DATE') IS NULL
    IF COL_LENGTH('HR_EMPLOYEE_EXPERIENCE', 'to_date') IS NOT NULL AND COL_LENGTH('HR_EMPLOYEE_EXPERIENCE', 'TO_DATE') IS NULL
    IF COL_LENGTH('HR_EMPLOYEE_EXPERIENCE', 'total_experience_months') IS NOT NULL AND COL_LENGTH('HR_EMPLOYEE_EXPERIENCE', 'TOTAL_EXPERIENCE_MONTHS') IS NULL
    IF COL_LENGTH('HR_EMPLOYEE_EXPERIENCE', 'documents') IS NOT NULL AND COL_LENGTH('HR_EMPLOYEE_EXPERIENCE', 'DOCUMENTS') IS NULL
    IF COL_LENGTH('HR_EMPLOYEE_EXPERIENCE', 'created_by') IS NOT NULL AND COL_LENGTH('HR_EMPLOYEE_EXPERIENCE', 'CREATED_BY') IS NULL
    IF COL_LENGTH('HR_EMPLOYEE_EXPERIENCE', 'created_at') IS NOT NULL AND COL_LENGTH('HR_EMPLOYEE_EXPERIENCE', 'CREATED_DATE') IS NULL
    IF COL_LENGTH('HR_EMPLOYEE_EXPERIENCE', 'updated_by') IS NOT NULL AND COL_LENGTH('HR_EMPLOYEE_EXPERIENCE', 'UPDATED_BY') IS NULL
    IF COL_LENGTH('HR_EMPLOYEE_EXPERIENCE', 'updated_at') IS NOT NULL AND COL_LENGTH('HR_EMPLOYEE_EXPERIENCE', 'UPDATED_DATE') IS NULL
END
GO

IF OBJECT_ID('HR_EMPLOYEE_EXPERIENCE', 'U') IS NOT NULL
BEGIN
    ALTER TABLE HR_EMPLOYEE_EXPERIENCE ALTER COLUMN COMPANY_NAME NVARCHAR(255);
    ALTER TABLE HR_EMPLOYEE_EXPERIENCE ALTER COLUMN DOCUMENTS NVARCHAR(500);
    ALTER TABLE HR_EMPLOYEE_EXPERIENCE ALTER COLUMN CREATED_BY NVARCHAR(100);
    ALTER TABLE HR_EMPLOYEE_EXPERIENCE ALTER COLUMN CREATED_DATE DATETIME;
    ALTER TABLE HR_EMPLOYEE_EXPERIENCE ALTER COLUMN UPDATED_BY NVARCHAR(100);
    ALTER TABLE HR_EMPLOYEE_EXPERIENCE ALTER COLUMN UPDATED_DATE DATETIME;

    IF COL_LENGTH('HR_EMPLOYEE_EXPERIENCE', 'IS_ACTIVE') IS NULL
        ALTER TABLE HR_EMPLOYEE_EXPERIENCE ADD IS_ACTIVE BIT DEFAULT 1;
END
GO

-- PK
IF OBJECT_ID('HR_EMPLOYEE_EXPERIENCE', 'U') IS NOT NULL
BEGIN
    DECLARE @exp_pk NVARCHAR(256);
    SELECT TOP 1 @exp_pk = name FROM sys.key_constraints WHERE parent_object_id = OBJECT_ID('HR_EMPLOYEE_EXPERIENCE') AND type = 'PK';
    IF @exp_pk IS NOT NULL AND @exp_pk <> 'PK_HR_EMPLOYEE_EXPERIENCE' AND NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE referenced_object_id = OBJECT_ID('HR_EMPLOYEE_EXPERIENCE'))
    BEGIN
        DECLARE @drop_exp_pk NVARCHAR(MAX) = 'ALTER TABLE HR_EMPLOYEE_EXPERIENCE DROP CONSTRAINT ' + @exp_pk;
        EXEC(@drop_exp_pk);
    END
    IF NOT EXISTS (SELECT 1 FROM sys.key_constraints WHERE parent_object_id = OBJECT_ID('HR_EMPLOYEE_EXPERIENCE') AND type = 'PK')
    BEGIN
        ALTER TABLE HR_EMPLOYEE_EXPERIENCE ADD CONSTRAINT PK_HR_EMPLOYEE_EXPERIENCE PRIMARY KEY (id);
    END
END
GO


-- ==========================================
-- 7. HR_EMPLOYEE_EMERGENCY_CONTACT
-- ==========================================
IF OBJECT_ID('HR_EMPLOYEE_EMERGENCY_CONTACT', 'U') IS NOT NULL
BEGIN
    IF COL_LENGTH('HR_EMPLOYEE_EMERGENCY_CONTACT', 'employee_id') IS NOT NULL AND COL_LENGTH('HR_EMPLOYEE_EMERGENCY_CONTACT', 'EMPLOYEE_ID') IS NULL
    IF COL_LENGTH('HR_EMPLOYEE_EMERGENCY_CONTACT', 'contact_name') IS NOT NULL AND COL_LENGTH('HR_EMPLOYEE_EMERGENCY_CONTACT', 'CONTACT_NAME') IS NULL
    IF COL_LENGTH('HR_EMPLOYEE_EMERGENCY_CONTACT', 'relation') IS NOT NULL AND COL_LENGTH('HR_EMPLOYEE_EMERGENCY_CONTACT', 'RELATION') IS NULL
    IF COL_LENGTH('HR_EMPLOYEE_EMERGENCY_CONTACT', 'address1') IS NOT NULL AND COL_LENGTH('HR_EMPLOYEE_EMERGENCY_CONTACT', 'ADDRESS1') IS NULL
    IF COL_LENGTH('HR_EMPLOYEE_EMERGENCY_CONTACT', 'address2') IS NOT NULL AND COL_LENGTH('HR_EMPLOYEE_EMERGENCY_CONTACT', 'ADDRESS2') IS NULL
    IF COL_LENGTH('HR_EMPLOYEE_EMERGENCY_CONTACT', 'mobile_number') IS NOT NULL AND COL_LENGTH('HR_EMPLOYEE_EMERGENCY_CONTACT', 'MOBILE_NUMBER') IS NULL
    IF COL_LENGTH('HR_EMPLOYEE_EMERGENCY_CONTACT', 'home_phone_number') IS NOT NULL AND COL_LENGTH('HR_EMPLOYEE_EMERGENCY_CONTACT', 'HOME_PHONE_NUMBER') IS NULL
    IF COL_LENGTH('HR_EMPLOYEE_EMERGENCY_CONTACT', 'created_by') IS NOT NULL AND COL_LENGTH('HR_EMPLOYEE_EMERGENCY_CONTACT', 'CREATED_BY') IS NULL
    IF COL_LENGTH('HR_EMPLOYEE_EMERGENCY_CONTACT', 'created_at') IS NOT NULL AND COL_LENGTH('HR_EMPLOYEE_EMERGENCY_CONTACT', 'CREATED_DATE') IS NULL
    IF COL_LENGTH('HR_EMPLOYEE_EMERGENCY_CONTACT', 'updated_by') IS NOT NULL AND COL_LENGTH('HR_EMPLOYEE_EMERGENCY_CONTACT', 'UPDATED_BY') IS NULL
    IF COL_LENGTH('HR_EMPLOYEE_EMERGENCY_CONTACT', 'updated_at') IS NOT NULL AND COL_LENGTH('HR_EMPLOYEE_EMERGENCY_CONTACT', 'UPDATED_DATE') IS NULL
END
GO

IF OBJECT_ID('HR_EMPLOYEE_EMERGENCY_CONTACT', 'U') IS NOT NULL
BEGIN
    ALTER TABLE HR_EMPLOYEE_EMERGENCY_CONTACT ALTER COLUMN CONTACT_NAME NVARCHAR(100);
    ALTER TABLE HR_EMPLOYEE_EMERGENCY_CONTACT ALTER COLUMN RELATION NVARCHAR(50);
    ALTER TABLE HR_EMPLOYEE_EMERGENCY_CONTACT ALTER COLUMN MOBILE_NUMBER NVARCHAR(20);
    ALTER TABLE HR_EMPLOYEE_EMERGENCY_CONTACT ALTER COLUMN CREATED_BY NVARCHAR(100);
    ALTER TABLE HR_EMPLOYEE_EMERGENCY_CONTACT ALTER COLUMN CREATED_DATE DATETIME;
    ALTER TABLE HR_EMPLOYEE_EMERGENCY_CONTACT ALTER COLUMN UPDATED_BY NVARCHAR(100);
    ALTER TABLE HR_EMPLOYEE_EMERGENCY_CONTACT ALTER COLUMN UPDATED_DATE DATETIME;

    IF COL_LENGTH('HR_EMPLOYEE_EMERGENCY_CONTACT', 'IS_ACTIVE') IS NULL
        ALTER TABLE HR_EMPLOYEE_EMERGENCY_CONTACT ADD IS_ACTIVE BIT DEFAULT 1;
END
GO

-- PK
IF OBJECT_ID('HR_EMPLOYEE_EMERGENCY_CONTACT', 'U') IS NOT NULL
BEGIN
    DECLARE @emg_pk NVARCHAR(256);
    SELECT TOP 1 @emg_pk = name FROM sys.key_constraints WHERE parent_object_id = OBJECT_ID('HR_EMPLOYEE_EMERGENCY_CONTACT') AND type = 'PK';
    IF @emg_pk IS NOT NULL AND @emg_pk <> 'PK_HR_EMPLOYEE_EMERGENCY_CONTACT' AND NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE referenced_object_id = OBJECT_ID('HR_EMPLOYEE_EMERGENCY_CONTACT'))
    BEGIN
        DECLARE @drop_emg_pk NVARCHAR(MAX) = 'ALTER TABLE HR_EMPLOYEE_EMERGENCY_CONTACT DROP CONSTRAINT ' + @emg_pk;
        EXEC(@drop_emg_pk);
    END
    IF NOT EXISTS (SELECT 1 FROM sys.key_constraints WHERE parent_object_id = OBJECT_ID('HR_EMPLOYEE_EMERGENCY_CONTACT') AND type = 'PK')
    BEGIN
        ALTER TABLE HR_EMPLOYEE_EMERGENCY_CONTACT ADD CONSTRAINT PK_HR_EMPLOYEE_EMERGENCY_CONTACT PRIMARY KEY (id);
    END
END
GO


-- ==========================================
-- 8. HR_EMPLOYEE_PASSPORT
-- ==========================================
IF OBJECT_ID('HR_EMPLOYEE_PASSPORT', 'U') IS NOT NULL
BEGIN
    IF COL_LENGTH('HR_EMPLOYEE_PASSPORT', 'employee_id') IS NOT NULL AND COL_LENGTH('HR_EMPLOYEE_PASSPORT', 'EMPLOYEE_ID') IS NULL
    IF COL_LENGTH('HR_EMPLOYEE_PASSPORT', 'passport_number') IS NOT NULL AND COL_LENGTH('HR_EMPLOYEE_PASSPORT', 'PASSPORT_NUMBER') IS NULL
    IF COL_LENGTH('HR_EMPLOYEE_PASSPORT', 'passport_issue_city') IS NOT NULL AND COL_LENGTH('HR_EMPLOYEE_PASSPORT', 'PASSPORT_ISSUE_CITY') IS NULL
    IF COL_LENGTH('HR_EMPLOYEE_PASSPORT', 'issue_date') IS NOT NULL AND COL_LENGTH('HR_EMPLOYEE_PASSPORT', 'ISSUE_DATE') IS NULL
    IF COL_LENGTH('HR_EMPLOYEE_PASSPORT', 'expiry_date') IS NOT NULL AND COL_LENGTH('HR_EMPLOYEE_PASSPORT', 'EXPIRY_DATE') IS NULL
    IF COL_LENGTH('HR_EMPLOYEE_PASSPORT', 'comments') IS NOT NULL AND COL_LENGTH('HR_EMPLOYEE_PASSPORT', 'COMMENTS') IS NULL
    IF COL_LENGTH('HR_EMPLOYEE_PASSPORT', 'created_by') IS NOT NULL AND COL_LENGTH('HR_EMPLOYEE_PASSPORT', 'CREATED_BY') IS NULL
    IF COL_LENGTH('HR_EMPLOYEE_PASSPORT', 'created_at') IS NOT NULL AND COL_LENGTH('HR_EMPLOYEE_PASSPORT', 'CREATED_DATE') IS NULL
    IF COL_LENGTH('HR_EMPLOYEE_PASSPORT', 'updated_by') IS NOT NULL AND COL_LENGTH('HR_EMPLOYEE_PASSPORT', 'UPDATED_BY') IS NULL
    IF COL_LENGTH('HR_EMPLOYEE_PASSPORT', 'updated_at') IS NOT NULL AND COL_LENGTH('HR_EMPLOYEE_PASSPORT', 'UPDATED_DATE') IS NULL
END
GO

IF OBJECT_ID('HR_EMPLOYEE_PASSPORT', 'U') IS NOT NULL
BEGIN
    ALTER TABLE HR_EMPLOYEE_PASSPORT ALTER COLUMN PASSPORT_NUMBER NVARCHAR(50);
    ALTER TABLE HR_EMPLOYEE_PASSPORT ALTER COLUMN PASSPORT_ISSUE_CITY NVARCHAR(100);
    ALTER TABLE HR_EMPLOYEE_PASSPORT ALTER COLUMN COMMENTS NVARCHAR(1000);
    ALTER TABLE HR_EMPLOYEE_PASSPORT ALTER COLUMN CREATED_BY NVARCHAR(100);
    ALTER TABLE HR_EMPLOYEE_PASSPORT ALTER COLUMN CREATED_DATE DATETIME;
    ALTER TABLE HR_EMPLOYEE_PASSPORT ALTER COLUMN UPDATED_BY NVARCHAR(100);
    ALTER TABLE HR_EMPLOYEE_PASSPORT ALTER COLUMN UPDATED_DATE DATETIME;

    IF COL_LENGTH('HR_EMPLOYEE_PASSPORT', 'IS_ACTIVE') IS NULL
        ALTER TABLE HR_EMPLOYEE_PASSPORT ADD IS_ACTIVE BIT DEFAULT 1;
END
GO

-- PK
IF OBJECT_ID('HR_EMPLOYEE_PASSPORT', 'U') IS NOT NULL
BEGIN
    DECLARE @pass_pk NVARCHAR(256);
    SELECT TOP 1 @pass_pk = name FROM sys.key_constraints WHERE parent_object_id = OBJECT_ID('HR_EMPLOYEE_PASSPORT') AND type = 'PK';
    IF @pass_pk IS NOT NULL AND @pass_pk <> 'PK_HR_EMPLOYEE_PASSPORT' AND NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE referenced_object_id = OBJECT_ID('HR_EMPLOYEE_PASSPORT'))
    BEGIN
        DECLARE @drop_pass_pk NVARCHAR(MAX) = 'ALTER TABLE HR_EMPLOYEE_PASSPORT DROP CONSTRAINT ' + @pass_pk;
        EXEC(@drop_pass_pk);
    END
    IF NOT EXISTS (SELECT 1 FROM sys.key_constraints WHERE parent_object_id = OBJECT_ID('HR_EMPLOYEE_PASSPORT') AND type = 'PK')
    BEGIN
        ALTER TABLE HR_EMPLOYEE_PASSPORT ADD CONSTRAINT PK_HR_EMPLOYEE_PASSPORT PRIMARY KEY (id);
    END
END
GO


-- ==========================================
-- 9. HR_EMPLOYEE_DEPENDENT
-- ==========================================
IF OBJECT_ID('HR_EMPLOYEE_DEPENDENT', 'U') IS NOT NULL
BEGIN
    IF COL_LENGTH('HR_EMPLOYEE_DEPENDENT', 'employee_id') IS NOT NULL AND COL_LENGTH('HR_EMPLOYEE_DEPENDENT', 'EMPLOYEE_ID') IS NULL
    IF COL_LENGTH('HR_EMPLOYEE_DEPENDENT', 'relation_name') IS NOT NULL AND COL_LENGTH('HR_EMPLOYEE_DEPENDENT', 'RELATION_NAME') IS NULL
    IF COL_LENGTH('HR_EMPLOYEE_DEPENDENT', 'gender') IS NOT NULL AND COL_LENGTH('HR_EMPLOYEE_DEPENDENT', 'GENDER') IS NULL
    IF COL_LENGTH('HR_EMPLOYEE_DEPENDENT', 'date_of_birth') IS NOT NULL AND COL_LENGTH('HR_EMPLOYEE_DEPENDENT', 'DATE_OF_BIRTH') IS NULL
    IF COL_LENGTH('HR_EMPLOYEE_DEPENDENT', 'relationship') IS NOT NULL AND COL_LENGTH('HR_EMPLOYEE_DEPENDENT', 'RELATIONSHIP') IS NULL
    IF COL_LENGTH('HR_EMPLOYEE_DEPENDENT', 'occupation') IS NOT NULL AND COL_LENGTH('HR_EMPLOYEE_DEPENDENT', 'OCCUPATION') IS NULL
    IF COL_LENGTH('HR_EMPLOYEE_DEPENDENT', 'blood_group') IS NOT NULL AND COL_LENGTH('HR_EMPLOYEE_DEPENDENT', 'BLOOD_GROUP') IS NULL
    IF COL_LENGTH('HR_EMPLOYEE_DEPENDENT', 'contact_number1') IS NOT NULL AND COL_LENGTH('HR_EMPLOYEE_DEPENDENT', 'CONTACT_NUMBER1') IS NULL
    IF COL_LENGTH('HR_EMPLOYEE_DEPENDENT', 'created_by') IS NOT NULL AND COL_LENGTH('HR_EMPLOYEE_DEPENDENT', 'CREATED_BY') IS NULL
    IF COL_LENGTH('HR_EMPLOYEE_DEPENDENT', 'created_at') IS NOT NULL AND COL_LENGTH('HR_EMPLOYEE_DEPENDENT', 'CREATED_DATE') IS NULL
    IF COL_LENGTH('HR_EMPLOYEE_DEPENDENT', 'updated_by') IS NOT NULL AND COL_LENGTH('HR_EMPLOYEE_DEPENDENT', 'UPDATED_BY') IS NULL
    IF COL_LENGTH('HR_EMPLOYEE_DEPENDENT', 'updated_at') IS NOT NULL AND COL_LENGTH('HR_EMPLOYEE_DEPENDENT', 'UPDATED_DATE') IS NULL
END
GO

IF OBJECT_ID('HR_EMPLOYEE_DEPENDENT', 'U') IS NOT NULL
BEGIN
    ALTER TABLE HR_EMPLOYEE_DEPENDENT ALTER COLUMN RELATION_NAME NVARCHAR(100);
    ALTER TABLE HR_EMPLOYEE_DEPENDENT ALTER COLUMN GENDER NVARCHAR(20);
    ALTER TABLE HR_EMPLOYEE_DEPENDENT ALTER COLUMN RELATIONSHIP NVARCHAR(50);
    ALTER TABLE HR_EMPLOYEE_DEPENDENT ALTER COLUMN OCCUPATION NVARCHAR(100);
    ALTER TABLE HR_EMPLOYEE_DEPENDENT ALTER COLUMN CREATED_BY NVARCHAR(100);
    ALTER TABLE HR_EMPLOYEE_DEPENDENT ALTER COLUMN CREATED_DATE DATETIME;
    ALTER TABLE HR_EMPLOYEE_DEPENDENT ALTER COLUMN UPDATED_BY NVARCHAR(100);
    ALTER TABLE HR_EMPLOYEE_DEPENDENT ALTER COLUMN UPDATED_DATE DATETIME;

    IF COL_LENGTH('HR_EMPLOYEE_DEPENDENT', 'IS_ACTIVE') IS NULL
        ALTER TABLE HR_EMPLOYEE_DEPENDENT ADD IS_ACTIVE BIT DEFAULT 1;
END
GO

-- PK
IF OBJECT_ID('HR_EMPLOYEE_DEPENDENT', 'U') IS NOT NULL
BEGIN
    DECLARE @dep_pk NVARCHAR(256);
    SELECT TOP 1 @dep_pk = name FROM sys.key_constraints WHERE parent_object_id = OBJECT_ID('HR_EMPLOYEE_DEPENDENT') AND type = 'PK';
    IF @dep_pk IS NOT NULL AND @dep_pk <> 'PK_HR_EMPLOYEE_DEPENDENT' AND NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE referenced_object_id = OBJECT_ID('HR_EMPLOYEE_DEPENDENT'))
    BEGIN
        DECLARE @drop_dep_pk NVARCHAR(MAX) = 'ALTER TABLE HR_EMPLOYEE_DEPENDENT DROP CONSTRAINT ' + @dep_pk;
        EXEC(@drop_dep_pk);
    END
    IF NOT EXISTS (SELECT 1 FROM sys.key_constraints WHERE parent_object_id = OBJECT_ID('HR_EMPLOYEE_DEPENDENT') AND type = 'PK')
    BEGIN
        ALTER TABLE HR_EMPLOYEE_DEPENDENT ADD CONSTRAINT PK_HR_EMPLOYEE_DEPENDENT PRIMARY KEY (id);
    END
END
GO


-- ==========================================
-- 10. HR_EMPLOYEE_ASSET
-- ==========================================
IF OBJECT_ID('HR_EMPLOYEE_ASSET', 'U') IS NOT NULL
BEGIN
    IF COL_LENGTH('HR_EMPLOYEE_ASSET', 'employee_id') IS NOT NULL AND COL_LENGTH('HR_EMPLOYEE_ASSET', 'EMPLOYEE_ID') IS NULL
    IF COL_LENGTH('HR_EMPLOYEE_ASSET', 'asset_id') IS NOT NULL AND COL_LENGTH('HR_EMPLOYEE_ASSET', 'ASSET_ID') IS NULL
    IF COL_LENGTH('HR_EMPLOYEE_ASSET', 'asset_name') IS NOT NULL AND COL_LENGTH('HR_EMPLOYEE_ASSET', 'ASSET_NAME') IS NULL
    IF COL_LENGTH('HR_EMPLOYEE_ASSET', 'asset_value') IS NOT NULL AND COL_LENGTH('HR_EMPLOYEE_ASSET', 'ASSET_VALUE') IS NULL
    IF COL_LENGTH('HR_EMPLOYEE_ASSET', 'issue_date') IS NOT NULL AND COL_LENGTH('HR_EMPLOYEE_ASSET', 'ISSUE_DATE') IS NULL
    IF COL_LENGTH('HR_EMPLOYEE_ASSET', 'condition_of_asset') IS NOT NULL AND COL_LENGTH('HR_EMPLOYEE_ASSET', 'CONDITION_OF_ASSET') IS NULL
    IF COL_LENGTH('HR_EMPLOYEE_ASSET', 'qty') IS NOT NULL AND COL_LENGTH('HR_EMPLOYEE_ASSET', 'QTY') IS NULL
    IF COL_LENGTH('HR_EMPLOYEE_ASSET', 'serial_no') IS NOT NULL AND COL_LENGTH('HR_EMPLOYEE_ASSET', 'SERIAL_NO') IS NULL
    IF COL_LENGTH('HR_EMPLOYEE_ASSET', 'value') IS NOT NULL AND COL_LENGTH('HR_EMPLOYEE_ASSET', 'VALUE') IS NULL
    IF COL_LENGTH('HR_EMPLOYEE_ASSET', 'comments') IS NOT NULL AND COL_LENGTH('HR_EMPLOYEE_ASSET', 'COMMENTS') IS NULL
    IF COL_LENGTH('HR_EMPLOYEE_ASSET', 'created_by') IS NOT NULL AND COL_LENGTH('HR_EMPLOYEE_ASSET', 'CREATED_BY') IS NULL
    IF COL_LENGTH('HR_EMPLOYEE_ASSET', 'created_at') IS NOT NULL AND COL_LENGTH('HR_EMPLOYEE_ASSET', 'CREATED_DATE') IS NULL
    IF COL_LENGTH('HR_EMPLOYEE_ASSET', 'updated_by') IS NOT NULL AND COL_LENGTH('HR_EMPLOYEE_ASSET', 'UPDATED_BY') IS NULL
    IF COL_LENGTH('HR_EMPLOYEE_ASSET', 'updated_at') IS NOT NULL AND COL_LENGTH('HR_EMPLOYEE_ASSET', 'UPDATED_DATE') IS NULL
END
GO

IF OBJECT_ID('HR_EMPLOYEE_ASSET', 'U') IS NOT NULL
BEGIN
    ALTER TABLE HR_EMPLOYEE_ASSET ALTER COLUMN ASSET_ID NVARCHAR(50);
    ALTER TABLE HR_EMPLOYEE_ASSET ALTER COLUMN ASSET_NAME NVARCHAR(255);
    ALTER TABLE HR_EMPLOYEE_ASSET ALTER COLUMN CONDITION_OF_ASSET NVARCHAR(100);
    ALTER TABLE HR_EMPLOYEE_ASSET ALTER COLUMN SERIAL_NO NVARCHAR(100);
    ALTER TABLE HR_EMPLOYEE_ASSET ALTER COLUMN COMMENTS NVARCHAR(1000);
    ALTER TABLE HR_EMPLOYEE_ASSET ALTER COLUMN CREATED_BY NVARCHAR(100);
    ALTER TABLE HR_EMPLOYEE_ASSET ALTER COLUMN CREATED_DATE DATETIME;
    ALTER TABLE HR_EMPLOYEE_ASSET ALTER COLUMN UPDATED_BY NVARCHAR(100);
    ALTER TABLE HR_EMPLOYEE_ASSET ALTER COLUMN UPDATED_DATE DATETIME;

    IF COL_LENGTH('HR_EMPLOYEE_ASSET', 'IS_ACTIVE') IS NULL
        ALTER TABLE HR_EMPLOYEE_ASSET ADD IS_ACTIVE BIT DEFAULT 1;
END
GO

-- PK
IF OBJECT_ID('HR_EMPLOYEE_ASSET', 'U') IS NOT NULL
BEGIN
    DECLARE @ast_pk NVARCHAR(256);
    SELECT TOP 1 @ast_pk = name FROM sys.key_constraints WHERE parent_object_id = OBJECT_ID('HR_EMPLOYEE_ASSET') AND type = 'PK';
    IF @ast_pk IS NOT NULL AND @ast_pk <> 'PK_HR_EMPLOYEE_ASSET' AND NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE referenced_object_id = OBJECT_ID('HR_EMPLOYEE_ASSET'))
    BEGIN
        DECLARE @drop_ast_pk NVARCHAR(MAX) = 'ALTER TABLE HR_EMPLOYEE_ASSET DROP CONSTRAINT ' + @ast_pk;
        EXEC(@drop_ast_pk);
    END
    IF NOT EXISTS (SELECT 1 FROM sys.key_constraints WHERE parent_object_id = OBJECT_ID('HR_EMPLOYEE_ASSET') AND type = 'PK')
    BEGIN
        ALTER TABLE HR_EMPLOYEE_ASSET ADD CONSTRAINT PK_HR_EMPLOYEE_ASSET PRIMARY KEY (id);
    END
END
GO


-- ==========================================
-- 11. HR_EMPLOYEE_KYC
-- ==========================================
IF OBJECT_ID('HR_EMPLOYEE_KYC', 'U') IS NOT NULL
BEGIN
    IF COL_LENGTH('HR_EMPLOYEE_KYC', 'employee_id') IS NOT NULL AND COL_LENGTH('HR_EMPLOYEE_KYC', 'EMPLOYEE_ID') IS NULL
    IF COL_LENGTH('HR_EMPLOYEE_KYC', 'pf_number') IS NOT NULL AND COL_LENGTH('HR_EMPLOYEE_KYC', 'PF_NUMBER') IS NULL
    IF COL_LENGTH('HR_EMPLOYEE_KYC', 'uan_number') IS NOT NULL AND COL_LENGTH('HR_EMPLOYEE_KYC', 'UAN_NUMBER') IS NULL
    IF COL_LENGTH('HR_EMPLOYEE_KYC', 'pan_number') IS NOT NULL AND COL_LENGTH('HR_EMPLOYEE_KYC', 'PAN_NUMBER') IS NULL
    IF COL_LENGTH('HR_EMPLOYEE_KYC', 'aadhar_number') IS NOT NULL AND COL_LENGTH('HR_EMPLOYEE_KYC', 'AADHAR_NUMBER') IS NULL
    IF COL_LENGTH('HR_EMPLOYEE_KYC', 'driving_license_number') IS NOT NULL AND COL_LENGTH('HR_EMPLOYEE_KYC', 'DRIVING_LICENSE_NUMBER') IS NULL
    IF COL_LENGTH('HR_EMPLOYEE_KYC', 'license_expiry_date') IS NOT NULL AND COL_LENGTH('HR_EMPLOYEE_KYC', 'LICENSE_EXPIRY_DATE') IS NULL
    IF COL_LENGTH('HR_EMPLOYEE_KYC', 'election_card_number') IS NOT NULL AND COL_LENGTH('HR_EMPLOYEE_KYC', 'ELECTION_CARD_NUMBER') IS NULL
    IF COL_LENGTH('HR_EMPLOYEE_KYC', 'ration_card_number') IS NOT NULL AND COL_LENGTH('HR_EMPLOYEE_KYC', 'RATION_CARD_NUMBER') IS NULL
    IF COL_LENGTH('HR_EMPLOYEE_KYC', 'personal_account_number') IS NOT NULL AND COL_LENGTH('HR_EMPLOYEE_KYC', 'PERSONAL_ACCOUNT_NUMBER') IS NULL
    IF COL_LENGTH('HR_EMPLOYEE_KYC', 'bank_name') IS NOT NULL AND COL_LENGTH('HR_EMPLOYEE_KYC', 'BANK_NAME') IS NULL
    IF COL_LENGTH('HR_EMPLOYEE_KYC', 'ifsc_code') IS NOT NULL AND COL_LENGTH('HR_EMPLOYEE_KYC', 'IFSC_CODE') IS NULL
    IF COL_LENGTH('HR_EMPLOYEE_KYC', 'physically_challenged') IS NOT NULL AND COL_LENGTH('HR_EMPLOYEE_KYC', 'PHYSICALLY_CHALLENGED') IS NULL
    IF COL_LENGTH('HR_EMPLOYEE_KYC', 'physically_challenged_category') IS NOT NULL AND COL_LENGTH('HR_EMPLOYEE_KYC', 'PHYSICALLY_CHALLENGED_CATEGORY') IS NULL
    IF COL_LENGTH('HR_EMPLOYEE_KYC', 'international_worker') IS NOT NULL AND COL_LENGTH('HR_EMPLOYEE_KYC', 'INTERNATIONAL_WORKER') IS NULL
    IF COL_LENGTH('HR_EMPLOYEE_KYC', 'passport_number') IS NOT NULL AND COL_LENGTH('HR_EMPLOYEE_KYC', 'PASSPORT_NUMBER') IS NULL
    IF COL_LENGTH('HR_EMPLOYEE_KYC', 'passport_expiry_date') IS NOT NULL AND COL_LENGTH('HR_EMPLOYEE_KYC', 'PASSPORT_EXPIRY_DATE') IS NULL
    IF COL_LENGTH('HR_EMPLOYEE_KYC', 'created_by') IS NOT NULL AND COL_LENGTH('HR_EMPLOYEE_KYC', 'CREATED_BY') IS NULL
    IF COL_LENGTH('HR_EMPLOYEE_KYC', 'created_at') IS NOT NULL AND COL_LENGTH('HR_EMPLOYEE_KYC', 'CREATED_DATE') IS NULL
    IF COL_LENGTH('HR_EMPLOYEE_KYC', 'updated_by') IS NOT NULL AND COL_LENGTH('HR_EMPLOYEE_KYC', 'UPDATED_BY') IS NULL
    IF COL_LENGTH('HR_EMPLOYEE_KYC', 'updated_at') IS NOT NULL AND COL_LENGTH('HR_EMPLOYEE_KYC', 'UPDATED_DATE') IS NULL
END
GO

IF OBJECT_ID('HR_EMPLOYEE_KYC', 'U') IS NOT NULL
BEGIN
    ALTER TABLE HR_EMPLOYEE_KYC ALTER COLUMN PF_NUMBER NVARCHAR(100);
    ALTER TABLE HR_EMPLOYEE_KYC ALTER COLUMN UAN_NUMBER NVARCHAR(100);
    ALTER TABLE HR_EMPLOYEE_KYC ALTER COLUMN PAN_NUMBER NVARCHAR(20);
    ALTER TABLE HR_EMPLOYEE_KYC ALTER COLUMN AADHAR_NUMBER NVARCHAR(20);
    ALTER TABLE HR_EMPLOYEE_KYC ALTER COLUMN DRIVING_LICENSE_NUMBER NVARCHAR(50);
    ALTER TABLE HR_EMPLOYEE_KYC ALTER COLUMN ELECTION_CARD_NUMBER NVARCHAR(50);
    ALTER TABLE HR_EMPLOYEE_KYC ALTER COLUMN RATION_CARD_NUMBER NVARCHAR(50);
    ALTER TABLE HR_EMPLOYEE_KYC ALTER COLUMN PERSONAL_ACCOUNT_NUMBER NVARCHAR(50);
    ALTER TABLE HR_EMPLOYEE_KYC ALTER COLUMN BANK_NAME NVARCHAR(100);
    ALTER TABLE HR_EMPLOYEE_KYC ALTER COLUMN IFSC_CODE NVARCHAR(20);
    ALTER TABLE HR_EMPLOYEE_KYC ALTER COLUMN PHYSICALLY_CHALLENGED NVARCHAR(10);
    ALTER TABLE HR_EMPLOYEE_KYC ALTER COLUMN PHYSICALLY_CHALLENGED_CATEGORY NVARCHAR(50);
    ALTER TABLE HR_EMPLOYEE_KYC ALTER COLUMN INTERNATIONAL_WORKER NVARCHAR(10);
    ALTER TABLE HR_EMPLOYEE_KYC ALTER COLUMN PASSPORT_NUMBER NVARCHAR(50);
    ALTER TABLE HR_EMPLOYEE_KYC ALTER COLUMN CREATED_BY NVARCHAR(100);
    ALTER TABLE HR_EMPLOYEE_KYC ALTER COLUMN CREATED_DATE DATETIME;
    ALTER TABLE HR_EMPLOYEE_KYC ALTER COLUMN UPDATED_BY NVARCHAR(100);
    ALTER TABLE HR_EMPLOYEE_KYC ALTER COLUMN UPDATED_DATE DATETIME;

    IF COL_LENGTH('HR_EMPLOYEE_KYC', 'IS_ACTIVE') IS NULL
        ALTER TABLE HR_EMPLOYEE_KYC ADD IS_ACTIVE BIT DEFAULT 1;
END
GO

-- PK
IF OBJECT_ID('HR_EMPLOYEE_KYC', 'U') IS NOT NULL
BEGIN
    DECLARE @kyc_pk NVARCHAR(256);
    SELECT TOP 1 @kyc_pk = name FROM sys.key_constraints WHERE parent_object_id = OBJECT_ID('HR_EMPLOYEE_KYC') AND type = 'PK';
    IF @kyc_pk IS NOT NULL AND @kyc_pk <> 'PK_HR_EMPLOYEE_KYC' AND NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE referenced_object_id = OBJECT_ID('HR_EMPLOYEE_KYC'))
    BEGIN
        DECLARE @drop_kyc_pk NVARCHAR(MAX) = 'ALTER TABLE HR_EMPLOYEE_KYC DROP CONSTRAINT ' + @kyc_pk;
        EXEC(@drop_kyc_pk);
    END
    IF NOT EXISTS (SELECT 1 FROM sys.key_constraints WHERE parent_object_id = OBJECT_ID('HR_EMPLOYEE_KYC') AND type = 'PK')
    BEGIN
        ALTER TABLE HR_EMPLOYEE_KYC ADD CONSTRAINT PK_HR_EMPLOYEE_KYC PRIMARY KEY (id);
    END
END
GO


-- ==========================================
-- 12. HR_EMPLOYEE_KYC_DOCUMENT
-- ==========================================
IF OBJECT_ID('HR_EMPLOYEE_KYC_DOCUMENT', 'U') IS NOT NULL
BEGIN
    IF COL_LENGTH('HR_EMPLOYEE_KYC_DOCUMENT', 'employee_id') IS NOT NULL AND COL_LENGTH('HR_EMPLOYEE_KYC_DOCUMENT', 'EMPLOYEE_ID') IS NULL
    IF COL_LENGTH('HR_EMPLOYEE_KYC_DOCUMENT', 'seq_no') IS NOT NULL AND COL_LENGTH('HR_EMPLOYEE_KYC_DOCUMENT', 'SEQ_NO') IS NULL
    IF COL_LENGTH('HR_EMPLOYEE_KYC_DOCUMENT', 'document_name') IS NOT NULL AND COL_LENGTH('HR_EMPLOYEE_KYC_DOCUMENT', 'DOCUMENT_NAME') IS NULL
    IF COL_LENGTH('HR_EMPLOYEE_KYC_DOCUMENT', 'document_number') IS NOT NULL AND COL_LENGTH('HR_EMPLOYEE_KYC_DOCUMENT', 'DOCUMENT_NUMBER') IS NULL
    IF COL_LENGTH('HR_EMPLOYEE_KYC_DOCUMENT', 'attachment') IS NOT NULL AND COL_LENGTH('HR_EMPLOYEE_KYC_DOCUMENT', 'ATTACHMENT') IS NULL
    IF COL_LENGTH('HR_EMPLOYEE_KYC_DOCUMENT', 'file_name') IS NOT NULL AND COL_LENGTH('HR_EMPLOYEE_KYC_DOCUMENT', 'FILE_NAME') IS NULL
    IF COL_LENGTH('HR_EMPLOYEE_KYC_DOCUMENT', 'created_by') IS NOT NULL AND COL_LENGTH('HR_EMPLOYEE_KYC_DOCUMENT', 'CREATED_BY') IS NULL
    IF COL_LENGTH('HR_EMPLOYEE_KYC_DOCUMENT', 'created_at') IS NOT NULL AND COL_LENGTH('HR_EMPLOYEE_KYC_DOCUMENT', 'CREATED_DATE') IS NULL
    IF COL_LENGTH('HR_EMPLOYEE_KYC_DOCUMENT', 'updated_by') IS NOT NULL AND COL_LENGTH('HR_EMPLOYEE_KYC_DOCUMENT', 'UPDATED_BY') IS NULL
    IF COL_LENGTH('HR_EMPLOYEE_KYC_DOCUMENT', 'updated_at') IS NOT NULL AND COL_LENGTH('HR_EMPLOYEE_KYC_DOCUMENT', 'UPDATED_DATE') IS NULL
END
GO

IF OBJECT_ID('HR_EMPLOYEE_KYC_DOCUMENT', 'U') IS NOT NULL
BEGIN
    ALTER TABLE HR_EMPLOYEE_KYC_DOCUMENT ALTER COLUMN DOCUMENT_NAME NVARCHAR(255);
    ALTER TABLE HR_EMPLOYEE_KYC_DOCUMENT ALTER COLUMN DOCUMENT_NUMBER NVARCHAR(100);
    ALTER TABLE HR_EMPLOYEE_KYC_DOCUMENT ALTER COLUMN ATTACHMENT NVARCHAR(1000);
    ALTER TABLE HR_EMPLOYEE_KYC_DOCUMENT ALTER COLUMN FILE_NAME NVARCHAR(255);
    ALTER TABLE HR_EMPLOYEE_KYC_DOCUMENT ALTER COLUMN CREATED_BY NVARCHAR(100);
    ALTER TABLE HR_EMPLOYEE_KYC_DOCUMENT ALTER COLUMN CREATED_DATE DATETIME;
    ALTER TABLE HR_EMPLOYEE_KYC_DOCUMENT ALTER COLUMN UPDATED_BY NVARCHAR(100);
    ALTER TABLE HR_EMPLOYEE_KYC_DOCUMENT ALTER COLUMN UPDATED_DATE DATETIME;

    IF COL_LENGTH('HR_EMPLOYEE_KYC_DOCUMENT', 'IS_ACTIVE') IS NULL
        ALTER TABLE HR_EMPLOYEE_KYC_DOCUMENT ADD IS_ACTIVE BIT DEFAULT 1;
END
GO

-- PK
IF OBJECT_ID('HR_EMPLOYEE_KYC_DOCUMENT', 'U') IS NOT NULL
BEGIN
    DECLARE @kycd_pk NVARCHAR(256);
    SELECT TOP 1 @kycd_pk = name FROM sys.key_constraints WHERE parent_object_id = OBJECT_ID('HR_EMPLOYEE_KYC_DOCUMENT') AND type = 'PK';
    IF @kycd_pk IS NOT NULL AND @kycd_pk <> 'PK_HR_EMPLOYEE_KYC_DOCUMENT' AND NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE referenced_object_id = OBJECT_ID('HR_EMPLOYEE_KYC_DOCUMENT'))
    BEGIN
        DECLARE @drop_kycd_pk NVARCHAR(MAX) = 'ALTER TABLE HR_EMPLOYEE_KYC_DOCUMENT DROP CONSTRAINT ' + @kycd_pk;
        EXEC(@drop_kycd_pk);
    END
    IF NOT EXISTS (SELECT 1 FROM sys.key_constraints WHERE parent_object_id = OBJECT_ID('HR_EMPLOYEE_KYC_DOCUMENT') AND type = 'PK')
    BEGIN
        ALTER TABLE HR_EMPLOYEE_KYC_DOCUMENT ADD CONSTRAINT PK_HR_EMPLOYEE_KYC_DOCUMENT PRIMARY KEY (id);
    END
END
GO


-- ==========================================
-- 13. HR_EMPLOYEE_ACTIVITY
-- ==========================================
IF OBJECT_ID('HR_EMPLOYEE_ACTIVITY', 'U') IS NOT NULL
BEGIN
    IF COL_LENGTH('HR_EMPLOYEE_ACTIVITY', 'employee_id') IS NOT NULL AND COL_LENGTH('HR_EMPLOYEE_ACTIVITY', 'EMPLOYEE_ID') IS NULL
    IF COL_LENGTH('HR_EMPLOYEE_ACTIVITY', 'activity_details') IS NOT NULL AND COL_LENGTH('HR_EMPLOYEE_ACTIVITY', 'ACTIVITY_DETAILS') IS NULL
    IF COL_LENGTH('HR_EMPLOYEE_ACTIVITY', 'created_by') IS NOT NULL AND COL_LENGTH('HR_EMPLOYEE_ACTIVITY', 'CREATED_BY') IS NULL
    IF COL_LENGTH('HR_EMPLOYEE_ACTIVITY', 'created_at') IS NOT NULL AND COL_LENGTH('HR_EMPLOYEE_ACTIVITY', 'CREATED_DATE') IS NULL
    IF COL_LENGTH('HR_EMPLOYEE_ACTIVITY', 'updated_by') IS NOT NULL AND COL_LENGTH('HR_EMPLOYEE_ACTIVITY', 'UPDATED_BY') IS NULL
    IF COL_LENGTH('HR_EMPLOYEE_ACTIVITY', 'updated_at') IS NOT NULL AND COL_LENGTH('HR_EMPLOYEE_ACTIVITY', 'UPDATED_DATE') IS NULL
END
GO

IF OBJECT_ID('HR_EMPLOYEE_ACTIVITY', 'U') IS NOT NULL
BEGIN
    ALTER TABLE HR_EMPLOYEE_ACTIVITY ALTER COLUMN ACTIVITY_DETAILS NVARCHAR(MAX);
    ALTER TABLE HR_EMPLOYEE_ACTIVITY ALTER COLUMN CREATED_BY NVARCHAR(100);
    ALTER TABLE HR_EMPLOYEE_ACTIVITY ALTER COLUMN CREATED_DATE DATETIME;
    ALTER TABLE HR_EMPLOYEE_ACTIVITY ALTER COLUMN UPDATED_BY NVARCHAR(100);
    ALTER TABLE HR_EMPLOYEE_ACTIVITY ALTER COLUMN UPDATED_DATE DATETIME;

    IF COL_LENGTH('HR_EMPLOYEE_ACTIVITY', 'IS_ACTIVE') IS NULL
        ALTER TABLE HR_EMPLOYEE_ACTIVITY ADD IS_ACTIVE BIT DEFAULT 1;
END
GO

-- PK
IF OBJECT_ID('HR_EMPLOYEE_ACTIVITY', 'U') IS NOT NULL
BEGIN
    DECLARE @act_pk NVARCHAR(256);
    SELECT TOP 1 @act_pk = name FROM sys.key_constraints WHERE parent_object_id = OBJECT_ID('HR_EMPLOYEE_ACTIVITY') AND type = 'PK';
    IF @act_pk IS NOT NULL AND @act_pk <> 'PK_HR_EMPLOYEE_ACTIVITY' AND NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE referenced_object_id = OBJECT_ID('HR_EMPLOYEE_ACTIVITY'))
    BEGIN
        DECLARE @drop_act_pk NVARCHAR(MAX) = 'ALTER TABLE HR_EMPLOYEE_ACTIVITY DROP CONSTRAINT ' + @act_pk;
        EXEC(@drop_act_pk);
    END
    IF NOT EXISTS (SELECT 1 FROM sys.key_constraints WHERE parent_object_id = OBJECT_ID('HR_EMPLOYEE_ACTIVITY') AND type = 'PK')
    BEGIN
        ALTER TABLE HR_EMPLOYEE_ACTIVITY ADD CONSTRAINT PK_HR_EMPLOYEE_ACTIVITY PRIMARY KEY (id);
    END
END
GO


-- ==========================================
-- 14. HR_EMPLOYEE_MANAGER_MAPPING (from EMPLOYEE_MANAGER_MAPPING)
-- ==========================================
IF OBJECT_ID('dbo.sp_RenameTableCasingAndPrefix', 'P') IS NOT NULL
BEGIN
    EXEC dbo.sp_RenameTableCasingAndPrefix 'EMPLOYEE_MANAGER_MAPPING', 'HR_EMPLOYEE_MANAGER_MAPPING';
END
ELSE
BEGIN
    IF OBJECT_ID('EMPLOYEE_MANAGER_MAPPING', 'U') IS NOT NULL AND OBJECT_ID('HR_EMPLOYEE_MANAGER_MAPPING', 'U') IS NULL
        EXEC sp_rename 'EMPLOYEE_MANAGER_MAPPING', 'HR_EMPLOYEE_MANAGER_MAPPING';
END
GO

IF OBJECT_ID('HR_EMPLOYEE_MANAGER_MAPPING', 'U') IS NOT NULL
BEGIN
    IF COL_LENGTH('HR_EMPLOYEE_MANAGER_MAPPING', 'emp_id') IS NOT NULL AND COL_LENGTH('HR_EMPLOYEE_MANAGER_MAPPING', 'EMP_ID') IS NULL
    IF COL_LENGTH('HR_EMPLOYEE_MANAGER_MAPPING', 'home_manager_id') IS NOT NULL AND COL_LENGTH('HR_EMPLOYEE_MANAGER_MAPPING', 'HOME_MANAGER_ID') IS NULL
    IF COL_LENGTH('HR_EMPLOYEE_MANAGER_MAPPING', 'business_manager_id') IS NOT NULL AND COL_LENGTH('HR_EMPLOYEE_MANAGER_MAPPING', 'BUSINESS_MANAGER_ID') IS NULL
    IF COL_LENGTH('HR_EMPLOYEE_MANAGER_MAPPING', 'vertical_head_id') IS NOT NULL AND COL_LENGTH('HR_EMPLOYEE_MANAGER_MAPPING', 'VERTICAL_HEAD_ID') IS NULL
    IF COL_LENGTH('HR_EMPLOYEE_MANAGER_MAPPING', 'hr_id') IS NOT NULL AND COL_LENGTH('HR_EMPLOYEE_MANAGER_MAPPING', 'HR_ID') IS NULL
    IF COL_LENGTH('HR_EMPLOYEE_MANAGER_MAPPING', 'created_by') IS NOT NULL AND COL_LENGTH('HR_EMPLOYEE_MANAGER_MAPPING', 'CREATED_BY') IS NULL
    IF COL_LENGTH('HR_EMPLOYEE_MANAGER_MAPPING', 'created_at') IS NOT NULL AND COL_LENGTH('HR_EMPLOYEE_MANAGER_MAPPING', 'CREATED_DATE') IS NULL
    IF COL_LENGTH('HR_EMPLOYEE_MANAGER_MAPPING', 'updated_by') IS NOT NULL AND COL_LENGTH('HR_EMPLOYEE_MANAGER_MAPPING', 'UPDATED_BY') IS NULL
    IF COL_LENGTH('HR_EMPLOYEE_MANAGER_MAPPING', 'updated_at') IS NOT NULL AND COL_LENGTH('HR_EMPLOYEE_MANAGER_MAPPING', 'UPDATED_DATE') IS NULL
    IF COL_LENGTH('HR_EMPLOYEE_MANAGER_MAPPING', 'status') IS NOT NULL AND COL_LENGTH('HR_EMPLOYEE_MANAGER_MAPPING', 'STATUS') IS NULL
END
GO

IF OBJECT_ID('HR_EMPLOYEE_MANAGER_MAPPING', 'U') IS NOT NULL
BEGIN
    ALTER TABLE HR_EMPLOYEE_MANAGER_MAPPING ALTER COLUMN CREATED_BY NVARCHAR(100);
    ALTER TABLE HR_EMPLOYEE_MANAGER_MAPPING ALTER COLUMN CREATED_DATE DATETIME;
    ALTER TABLE HR_EMPLOYEE_MANAGER_MAPPING ALTER COLUMN UPDATED_BY NVARCHAR(100);
    ALTER TABLE HR_EMPLOYEE_MANAGER_MAPPING ALTER COLUMN UPDATED_DATE DATETIME;
    ALTER TABLE HR_EMPLOYEE_MANAGER_MAPPING ALTER COLUMN STATUS NVARCHAR(50);

    IF COL_LENGTH('HR_EMPLOYEE_MANAGER_MAPPING', 'IS_ACTIVE') IS NULL
        ALTER TABLE HR_EMPLOYEE_MANAGER_MAPPING ADD IS_ACTIVE BIT DEFAULT 1;
END
GO

-- PK
IF OBJECT_ID('HR_EMPLOYEE_MANAGER_MAPPING', 'U') IS NOT NULL
BEGIN
    DECLARE @map_pk NVARCHAR(256);
    SELECT TOP 1 @map_pk = name FROM sys.key_constraints WHERE parent_object_id = OBJECT_ID('HR_EMPLOYEE_MANAGER_MAPPING') AND type = 'PK';
    IF @map_pk IS NOT NULL AND @map_pk <> 'PK_HR_EMPLOYEE_MANAGER_MAPPING' AND NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE referenced_object_id = OBJECT_ID('HR_EMPLOYEE_MANAGER_MAPPING'))
    BEGIN
        DECLARE @drop_map_pk NVARCHAR(MAX) = 'ALTER TABLE HR_EMPLOYEE_MANAGER_MAPPING DROP CONSTRAINT ' + @map_pk;
        EXEC(@drop_map_pk);
    END
    IF NOT EXISTS (SELECT 1 FROM sys.key_constraints WHERE parent_object_id = OBJECT_ID('HR_EMPLOYEE_MANAGER_MAPPING') AND type = 'PK')
    BEGIN
        ALTER TABLE HR_EMPLOYEE_MANAGER_MAPPING ADD CONSTRAINT PK_HR_EMPLOYEE_MANAGER_MAPPING PRIMARY KEY (id);
    END
END
GO


-- ==========================================
-- Re-establish Foreign Keys where essential (Parent-Child relations)
-- ==========================================
IF OBJECT_ID('HR_EMPLOYEE_CONTACT', 'U') IS NOT NULL AND OBJECT_ID('HR_EMPLOYEE', 'U') IS NOT NULL
BEGIN
    ALTER TABLE HR_EMPLOYEE_CONTACT ADD CONSTRAINT FK_HR_EMPLOYEE_CONTACT_EMPLOYEE FOREIGN KEY (EMPLOYEE_ID) REFERENCES HR_EMPLOYEE(id);
END
GO

IF OBJECT_ID('HR_EMPLOYEE_PERSONAL', 'U') IS NOT NULL AND OBJECT_ID('HR_EMPLOYEE', 'U') IS NOT NULL
BEGIN
    ALTER TABLE HR_EMPLOYEE_PERSONAL ADD CONSTRAINT FK_HR_EMPLOYEE_PERSONAL_EMPLOYEE FOREIGN KEY (EMPLOYEE_ID) REFERENCES HR_EMPLOYEE(id);
END
GO

IF OBJECT_ID('HR_EMPLOYEE_JOB_PROFILE', 'U') IS NOT NULL AND OBJECT_ID('HR_EMPLOYEE', 'U') IS NOT NULL
BEGIN
    ALTER TABLE HR_EMPLOYEE_JOB_PROFILE ADD CONSTRAINT FK_HR_EMPLOYEE_JOB_PROFILE_EMPLOYEE FOREIGN KEY (EMPLOYEE_ID) REFERENCES HR_EMPLOYEE(id);
END
GO

IF OBJECT_ID('HR_EMPLOYEE_EDUCATION', 'U') IS NOT NULL AND OBJECT_ID('HR_EMPLOYEE', 'U') IS NOT NULL
BEGIN
    ALTER TABLE HR_EMPLOYEE_EDUCATION ADD CONSTRAINT FK_HR_EMPLOYEE_EDUCATION_EMPLOYEE FOREIGN KEY (EMPLOYEE_ID) REFERENCES HR_EMPLOYEE(id);
END
GO

IF OBJECT_ID('HR_EMPLOYEE_EXPERIENCE', 'U') IS NOT NULL AND OBJECT_ID('HR_EMPLOYEE', 'U') IS NOT NULL
BEGIN
    ALTER TABLE HR_EMPLOYEE_EXPERIENCE ADD CONSTRAINT FK_HR_EMPLOYEE_EXPERIENCE_EMPLOYEE FOREIGN KEY (EMPLOYEE_ID) REFERENCES HR_EMPLOYEE(id);
END
GO

IF OBJECT_ID('HR_EMPLOYEE_EMERGENCY_CONTACT', 'U') IS NOT NULL AND OBJECT_ID('HR_EMPLOYEE', 'U') IS NOT NULL
BEGIN
    ALTER TABLE HR_EMPLOYEE_EMERGENCY_CONTACT ADD CONSTRAINT FK_HR_EMPLOYEE_EMERGENCY_EMPLOYEE FOREIGN KEY (EMPLOYEE_ID) REFERENCES HR_EMPLOYEE(id);
END
GO

IF OBJECT_ID('HR_EMPLOYEE_PASSPORT', 'U') IS NOT NULL AND OBJECT_ID('HR_EMPLOYEE', 'U') IS NOT NULL
BEGIN
    ALTER TABLE HR_EMPLOYEE_PASSPORT ADD CONSTRAINT FK_HR_EMPLOYEE_PASSPORT_EMPLOYEE FOREIGN KEY (EMPLOYEE_ID) REFERENCES HR_EMPLOYEE(id);
END
GO

IF OBJECT_ID('HR_EMPLOYEE_DEPENDENT', 'U') IS NOT NULL AND OBJECT_ID('HR_EMPLOYEE', 'U') IS NOT NULL
BEGIN
    ALTER TABLE HR_EMPLOYEE_DEPENDENT ADD CONSTRAINT FK_HR_EMPLOYEE_DEPENDENT_EMPLOYEE FOREIGN KEY (EMPLOYEE_ID) REFERENCES HR_EMPLOYEE(id);
END
GO

IF OBJECT_ID('HR_EMPLOYEE_ASSET', 'U') IS NOT NULL AND OBJECT_ID('HR_EMPLOYEE', 'U') IS NOT NULL
BEGIN
    ALTER TABLE HR_EMPLOYEE_ASSET ADD CONSTRAINT FK_HR_EMPLOYEE_ASSET_EMPLOYEE FOREIGN KEY (EMPLOYEE_ID) REFERENCES HR_EMPLOYEE(id);
END
GO

IF OBJECT_ID('HR_EMPLOYEE_KYC', 'U') IS NOT NULL AND OBJECT_ID('HR_EMPLOYEE', 'U') IS NOT NULL
BEGIN
    ALTER TABLE HR_EMPLOYEE_KYC ADD CONSTRAINT FK_HR_EMPLOYEE_KYC_EMPLOYEE FOREIGN KEY (EMPLOYEE_ID) REFERENCES HR_EMPLOYEE(id);
END
GO

IF OBJECT_ID('HR_EMPLOYEE_KYC_DOCUMENT', 'U') IS NOT NULL AND OBJECT_ID('HR_EMPLOYEE', 'U') IS NOT NULL
BEGIN
    ALTER TABLE HR_EMPLOYEE_KYC_DOCUMENT ADD CONSTRAINT FK_HR_EMPLOYEE_KYC_DOC_EMPLOYEE FOREIGN KEY (EMPLOYEE_ID) REFERENCES HR_EMPLOYEE(id);
END
GO

IF OBJECT_ID('HR_EMPLOYEE_ACTIVITY', 'U') IS NOT NULL AND OBJECT_ID('HR_EMPLOYEE', 'U') IS NOT NULL
BEGIN
    ALTER TABLE HR_EMPLOYEE_ACTIVITY ADD CONSTRAINT FK_HR_EMPLOYEE_ACTIVITY_EMPLOYEE FOREIGN KEY (EMPLOYEE_ID) REFERENCES HR_EMPLOYEE(id);
END
GO

IF OBJECT_ID('HR_EMPLOYEE_MANAGER_MAPPING', 'U') IS NOT NULL AND OBJECT_ID('HR_EMPLOYEE', 'U') IS NOT NULL
BEGIN
    ALTER TABLE HR_EMPLOYEE_MANAGER_MAPPING ADD CONSTRAINT FK_HR_EMPLOYEE_MANAGER_EMPLOYEE FOREIGN KEY (EMP_ID) REFERENCES HR_EMPLOYEE(id);
END
GO
