-- V006__Sales_Vendor_Module.sql
-- Phase 6: Customer, Supplier & CRM Masters Schema Standardization
-- Renames and normalizes:
-- 1. SM_CUSTOMER_MASTER -> SLS_CUSTOMER
-- 2. SM_CUSTOMER_ADDRESS -> SLS_CUSTOMER_ADDRESS
-- 3. SM_SUPPLIER_MASTER -> VND_VENDOR
-- 4. SM_VENDOR_CUSTOMER_MASTER -> VND_CUSTOMER_MAPPING
-- 5. SM_CUSTOMER_POTENTIAL -> SLS_CUSTOMER_POTENTIAL

-- ==========================================
-- Drop referencing Foreign Key constraints dynamically to avoid cascade/drop errors
-- ==========================================
DECLARE @sql NVARCHAR(MAX) = N'';
SELECT @sql += N'ALTER TABLE ' + QUOTENAME(OBJECT_SCHEMA_NAME(parent_object_id)) + '.' + QUOTENAME(OBJECT_NAME(parent_object_id)) + 
               ' DROP CONSTRAINT ' + QUOTENAME(name) + ';' + CHAR(13) + CHAR(10)
FROM sys.foreign_keys
WHERE referenced_object_id IN (
    OBJECT_ID('SM_CUSTOMER_MASTER'),
    OBJECT_ID('SM_CUSTOMER_ADDRESS'),
    OBJECT_ID('SM_SUPPLIER_MASTER'),
    OBJECT_ID('SM_VENDOR_CUSTOMER_MASTER'),
    OBJECT_ID('SM_CUSTOMER_POTENTIAL')
);
IF @sql <> N''
BEGIN
    EXEC sp_executesql @sql;
END
GO

-- ==========================================
-- 1. SLS_CUSTOMER (from SM_CUSTOMER_MASTER)
-- ==========================================
IF OBJECT_ID('SM_CUSTOMER_MASTER', 'U') IS NOT NULL
BEGIN
    EXEC sp_rename 'SM_CUSTOMER_MASTER', 'SLS_CUSTOMER';
END
GO

IF OBJECT_ID('SLS_CUSTOMER', 'U') IS NOT NULL
BEGIN
    -- Handle duplicate created_at/CREATED_DATE columns
    IF COL_LENGTH('SLS_CUSTOMER', 'created_at') IS NOT NULL AND COL_LENGTH('SLS_CUSTOMER', 'created_date') IS NOT NULL
        ALTER TABLE SLS_CUSTOMER DROP COLUMN created_at;
    IF COL_LENGTH('SLS_CUSTOMER', 'updated_at') IS NOT NULL AND COL_LENGTH('SLS_CUSTOMER', 'updated_date') IS NOT NULL
        ALTER TABLE SLS_CUSTOMER DROP COLUMN updated_at;

    IF COL_LENGTH('SLS_CUSTOMER', 'customer_code') IS NOT NULL AND COL_LENGTH('SLS_CUSTOMER', 'CUSTOMER_CODE') IS NULL
    IF COL_LENGTH('SLS_CUSTOMER', 'customer_name') IS NOT NULL AND COL_LENGTH('SLS_CUSTOMER', 'CUSTOMER_NAME') IS NULL
    IF COL_LENGTH('SLS_CUSTOMER', 'customer_print_name') IS NOT NULL AND COL_LENGTH('SLS_CUSTOMER', 'CUSTOMER_PRINT_NAME') IS NULL
    IF COL_LENGTH('SLS_CUSTOMER', 'accounts_ledger') IS NOT NULL AND COL_LENGTH('SLS_CUSTOMER', 'ACCOUNTS_LEDGER') IS NULL
    IF COL_LENGTH('SLS_CUSTOMER', 'group_name') IS NOT NULL AND COL_LENGTH('SLS_CUSTOMER', 'GROUP_NAME') IS NULL
    IF COL_LENGTH('SLS_CUSTOMER', 'invoice_name') IS NOT NULL AND COL_LENGTH('SLS_CUSTOMER', 'INVOICE_NAME') IS NULL
    IF COL_LENGTH('SLS_CUSTOMER', 'short_name') IS NOT NULL AND COL_LENGTH('SLS_CUSTOMER', 'SHORT_NAME') IS NULL
    IF COL_LENGTH('SLS_CUSTOMER', 'segment') IS NOT NULL AND COL_LENGTH('SLS_CUSTOMER', 'SEGMENT') IS NULL
    IF COL_LENGTH('SLS_CUSTOMER', 'sub_segment') IS NOT NULL AND COL_LENGTH('SLS_CUSTOMER', 'SUB_SEGMENT') IS NULL
    IF COL_LENGTH('SLS_CUSTOMER', 'domain_name') IS NOT NULL AND COL_LENGTH('SLS_CUSTOMER', 'DOMAIN_NAME') IS NULL
    IF COL_LENGTH('SLS_CUSTOMER', 'address') IS NOT NULL AND COL_LENGTH('SLS_CUSTOMER', 'ADDRESS') IS NULL
    IF COL_LENGTH('SLS_CUSTOMER', 'pincode') IS NOT NULL AND COL_LENGTH('SLS_CUSTOMER', 'PINCODE') IS NULL
    IF COL_LENGTH('SLS_CUSTOMER', 'city') IS NOT NULL AND COL_LENGTH('SLS_CUSTOMER', 'CITY') IS NULL
    IF COL_LENGTH('SLS_CUSTOMER', 'state') IS NOT NULL AND COL_LENGTH('SLS_CUSTOMER', 'STATE') IS NULL
    IF COL_LENGTH('SLS_CUSTOMER', 'state_code') IS NOT NULL AND COL_LENGTH('SLS_CUSTOMER', 'STATE_CODE') IS NULL
    IF COL_LENGTH('SLS_CUSTOMER', 'country') IS NOT NULL AND COL_LENGTH('SLS_CUSTOMER', 'COUNTRY') IS NULL
    IF COL_LENGTH('SLS_CUSTOMER', 'prime_customer') IS NOT NULL AND COL_LENGTH('SLS_CUSTOMER', 'PRIME_CUSTOMER') IS NULL
    IF COL_LENGTH('SLS_CUSTOMER', 'pan_no') IS NOT NULL AND COL_LENGTH('SLS_CUSTOMER', 'PAN_NO') IS NULL
    IF COL_LENGTH('SLS_CUSTOMER', 'pan_file_info') IS NOT NULL AND COL_LENGTH('SLS_CUSTOMER', 'PAN_FILE_INFO') IS NULL
    IF COL_LENGTH('SLS_CUSTOMER', 'website') IS NOT NULL AND COL_LENGTH('SLS_CUSTOMER', 'WEBSITE') IS NULL
    IF COL_LENGTH('SLS_CUSTOMER', 'register_no') IS NOT NULL AND COL_LENGTH('SLS_CUSTOMER', 'REGISTER_NO') IS NULL
    IF COL_LENGTH('SLS_CUSTOMER', 'cin_no') IS NOT NULL AND COL_LENGTH('SLS_CUSTOMER', 'CIN_NO') IS NULL
    IF COL_LENGTH('SLS_CUSTOMER', 'distance') IS NOT NULL AND COL_LENGTH('SLS_CUSTOMER', 'DISTANCE') IS NULL
    IF COL_LENGTH('SLS_CUSTOMER', 'gstin') IS NOT NULL AND COL_LENGTH('SLS_CUSTOMER', 'GSTIN') IS NULL
    IF COL_LENGTH('SLS_CUSTOMER', 'vendor_code') IS NOT NULL AND COL_LENGTH('SLS_CUSTOMER', 'VENDOR_CODE') IS NULL
    IF COL_LENGTH('SLS_CUSTOMER', 'iso_number') IS NOT NULL AND COL_LENGTH('SLS_CUSTOMER', 'ISO_NUMBER') IS NULL
    IF COL_LENGTH('SLS_CUSTOMER', 'iso_expiry') IS NOT NULL AND COL_LENGTH('SLS_CUSTOMER', 'ISO_EXPIRY') IS NULL
    IF COL_LENGTH('SLS_CUSTOMER', 'nda_required') IS NOT NULL AND COL_LENGTH('SLS_CUSTOMER', 'NDA_REQUIRED') IS NULL
    IF COL_LENGTH('SLS_CUSTOMER', 'dispatch_mode') IS NOT NULL AND COL_LENGTH('SLS_CUSTOMER', 'DISPATCH_MODE') IS NULL
    IF COL_LENGTH('SLS_CUSTOMER', 'currency') IS NOT NULL AND COL_LENGTH('SLS_CUSTOMER', 'CURRENCY') IS NULL
    IF COL_LENGTH('SLS_CUSTOMER', 'payment_terms') IS NOT NULL AND COL_LENGTH('SLS_CUSTOMER', 'PAYMENT_TERMS') IS NULL
    IF COL_LENGTH('SLS_CUSTOMER', 'delivery_terms') IS NOT NULL AND COL_LENGTH('SLS_CUSTOMER', 'DELIVERY_TERMS') IS NULL
    IF COL_LENGTH('SLS_CUSTOMER', 'freight') IS NOT NULL AND COL_LENGTH('SLS_CUSTOMER', 'FREIGHT') IS NULL
    IF COL_LENGTH('SLS_CUSTOMER', 'negotiate_customer') IS NOT NULL AND COL_LENGTH('SLS_CUSTOMER', 'NEGOTIATE_CUSTOMER') IS NULL
    IF COL_LENGTH('SLS_CUSTOMER', 'daily_dispatch_mail') IS NOT NULL AND COL_LENGTH('SLS_CUSTOMER', 'DAILY_DISPATCH_MAIL') IS NULL
    IF COL_LENGTH('SLS_CUSTOMER', 'file_upload') IS NOT NULL AND COL_LENGTH('SLS_CUSTOMER', 'FILE_UPLOAD') IS NULL
    IF COL_LENGTH('SLS_CUSTOMER', 'location') IS NOT NULL AND COL_LENGTH('SLS_CUSTOMER', 'LOCATION') IS NULL
    IF COL_LENGTH('SLS_CUSTOMER', 'ld_applicable') IS NOT NULL AND COL_LENGTH('SLS_CUSTOMER', 'LD_APPLICABLE') IS NULL
    IF COL_LENGTH('SLS_CUSTOMER', 'status') IS NOT NULL AND COL_LENGTH('SLS_CUSTOMER', 'STATUS') IS NULL
    IF COL_LENGTH('SLS_CUSTOMER', 'created_by') IS NOT NULL AND COL_LENGTH('SLS_CUSTOMER', 'CREATED_BY') IS NULL
    IF COL_LENGTH('SLS_CUSTOMER', 'updated_by') IS NOT NULL AND COL_LENGTH('SLS_CUSTOMER', 'UPDATED_BY') IS NULL

    IF COL_LENGTH('SLS_CUSTOMER', 'created_at') IS NOT NULL AND COL_LENGTH('SLS_CUSTOMER', 'CREATED_DATE') IS NULL 
        EXEC sp_rename 'SLS_CUSTOMER.created_at', 'CREATED_DATE', 'COLUMN';
    IF COL_LENGTH('SLS_CUSTOMER', 'updated_at') IS NOT NULL AND COL_LENGTH('SLS_CUSTOMER', 'UPDATED_DATE') IS NULL 
        EXEC sp_rename 'SLS_CUSTOMER.updated_at', 'UPDATED_DATE', 'COLUMN';
    IF COL_LENGTH('SLS_CUSTOMER', 'created_date') IS NOT NULL AND COL_LENGTH('SLS_CUSTOMER', 'CREATED_DATE') IS NULL 
        EXEC sp_rename 'SLS_CUSTOMER.created_date', 'CREATED_DATE', 'COLUMN';
    IF COL_LENGTH('SLS_CUSTOMER', 'updated_date') IS NOT NULL AND COL_LENGTH('SLS_CUSTOMER', 'UPDATED_DATE') IS NULL 
        EXEC sp_rename 'SLS_CUSTOMER.updated_date', 'UPDATED_DATE', 'COLUMN';
END
GO

IF OBJECT_ID('SLS_CUSTOMER', 'U') IS NOT NULL
BEGIN
    -- Drop unique constraint/index on CUSTOMER_CODE dynamically to allow type alteration
    DECLARE @drop_uq NVARCHAR(MAX) = N'';
    SELECT @drop_uq += N'ALTER TABLE [SLS_CUSTOMER] DROP CONSTRAINT ' + QUOTENAME(dc.name) + ';' + CHAR(13) + CHAR(10)
    FROM sys.key_constraints dc
    INNER JOIN sys.index_columns ic ON dc.parent_object_id = ic.object_id AND dc.unique_index_id = ic.index_id
    INNER JOIN sys.columns c ON ic.object_id = c.object_id AND ic.column_id = c.column_id
    WHERE dc.parent_object_id = OBJECT_ID('SLS_CUSTOMER')
      AND c.name = 'CUSTOMER_CODE';
    IF @drop_uq <> N'' EXEC sp_executesql @drop_uq;

    DECLARE @drop_idx NVARCHAR(MAX) = N'';
    SELECT @drop_idx += N'DROP INDEX ' + QUOTENAME(i.name) + ' ON [SLS_CUSTOMER];' + CHAR(13) + CHAR(10)
    FROM sys.indexes i
    INNER JOIN sys.index_columns ic ON i.object_id = ic.object_id AND i.index_id = ic.index_id
    INNER JOIN sys.columns c ON ic.object_id = c.object_id AND ic.column_id = c.column_id
    WHERE i.object_id = OBJECT_ID('SLS_CUSTOMER')
      AND c.name = 'CUSTOMER_CODE'
      AND i.is_primary_key = 0
      AND i.is_unique_constraint = 0;
    IF @drop_idx <> N'' EXEC sp_executesql @drop_idx;

    -- Alter types and lengths to NVARCHAR
    ALTER TABLE SLS_CUSTOMER ALTER COLUMN CUSTOMER_CODE NVARCHAR(50) NOT NULL;
    ALTER TABLE SLS_CUSTOMER ALTER COLUMN CUSTOMER_NAME NVARCHAR(200) NOT NULL;
    ALTER TABLE SLS_CUSTOMER ALTER COLUMN CUSTOMER_PRINT_NAME NVARCHAR(200);
    ALTER TABLE SLS_CUSTOMER ALTER COLUMN ACCOUNTS_LEDGER NVARCHAR(200);
    ALTER TABLE SLS_CUSTOMER ALTER COLUMN GROUP_NAME NVARCHAR(200);
    ALTER TABLE SLS_CUSTOMER ALTER COLUMN INVOICE_NAME NVARCHAR(200);
    ALTER TABLE SLS_CUSTOMER ALTER COLUMN SHORT_NAME NVARCHAR(50);
    ALTER TABLE SLS_CUSTOMER ALTER COLUMN SEGMENT NVARCHAR(100);
    ALTER TABLE SLS_CUSTOMER ALTER COLUMN SUB_SEGMENT NVARCHAR(100);
    ALTER TABLE SLS_CUSTOMER ALTER COLUMN DOMAIN_NAME NVARCHAR(150);
    ALTER TABLE SLS_CUSTOMER ALTER COLUMN ADDRESS NVARCHAR(MAX);
    ALTER TABLE SLS_CUSTOMER ALTER COLUMN PINCODE NVARCHAR(20);
    ALTER TABLE SLS_CUSTOMER ALTER COLUMN CITY NVARCHAR(100);
    ALTER TABLE SLS_CUSTOMER ALTER COLUMN STATE NVARCHAR(100);
    ALTER TABLE SLS_CUSTOMER ALTER COLUMN STATE_CODE NVARCHAR(20);
    ALTER TABLE SLS_CUSTOMER ALTER COLUMN COUNTRY NVARCHAR(100);
    ALTER TABLE SLS_CUSTOMER ALTER COLUMN PRIME_CUSTOMER NVARCHAR(10);
    ALTER TABLE SLS_CUSTOMER ALTER COLUMN PAN_NO NVARCHAR(50);
    ALTER TABLE SLS_CUSTOMER ALTER COLUMN PAN_FILE_INFO NVARCHAR(1000);
    ALTER TABLE SLS_CUSTOMER ALTER COLUMN WEBSITE NVARCHAR(150);
    ALTER TABLE SLS_CUSTOMER ALTER COLUMN REGISTER_NO NVARCHAR(100);
    ALTER TABLE SLS_CUSTOMER ALTER COLUMN CIN_NO NVARCHAR(100);
    ALTER TABLE SLS_CUSTOMER ALTER COLUMN DISTANCE NVARCHAR(50);
    ALTER TABLE SLS_CUSTOMER ALTER COLUMN GSTIN NVARCHAR(50);
    ALTER TABLE SLS_CUSTOMER ALTER COLUMN VENDOR_CODE NVARCHAR(50);
    ALTER TABLE SLS_CUSTOMER ALTER COLUMN ISO_NUMBER NVARCHAR(50);
    ALTER TABLE SLS_CUSTOMER ALTER COLUMN ISO_EXPIRY NVARCHAR(50);
    ALTER TABLE SLS_CUSTOMER ALTER COLUMN NDA_REQUIRED NVARCHAR(10);
    ALTER TABLE SLS_CUSTOMER ALTER COLUMN DISPATCH_MODE NVARCHAR(50);
    ALTER TABLE SLS_CUSTOMER ALTER COLUMN CURRENCY NVARCHAR(20);
    ALTER TABLE SLS_CUSTOMER ALTER COLUMN PAYMENT_TERMS NVARCHAR(100);
    ALTER TABLE SLS_CUSTOMER ALTER COLUMN DELIVERY_TERMS NVARCHAR(100);
    ALTER TABLE SLS_CUSTOMER ALTER COLUMN FREIGHT NVARCHAR(100);
    ALTER TABLE SLS_CUSTOMER ALTER COLUMN NEGOTIATE_CUSTOMER NVARCHAR(10);
    ALTER TABLE SLS_CUSTOMER ALTER COLUMN DAILY_DISPATCH_MAIL NVARCHAR(10);
    ALTER TABLE SLS_CUSTOMER ALTER COLUMN FILE_UPLOAD NVARCHAR(1000);
    ALTER TABLE SLS_CUSTOMER ALTER COLUMN LOCATION NVARCHAR(200);
    ALTER TABLE SLS_CUSTOMER ALTER COLUMN LD_APPLICABLE NVARCHAR(10);
    ALTER TABLE SLS_CUSTOMER ALTER COLUMN STATUS NVARCHAR(20);
    ALTER TABLE SLS_CUSTOMER ALTER COLUMN CREATED_BY NVARCHAR(100);
    ALTER TABLE SLS_CUSTOMER ALTER COLUMN CREATED_DATE DATETIME;
    ALTER TABLE SLS_CUSTOMER ALTER COLUMN UPDATED_BY NVARCHAR(100);
    ALTER TABLE SLS_CUSTOMER ALTER COLUMN UPDATED_DATE DATETIME;

    IF COL_LENGTH('SLS_CUSTOMER', 'IS_ACTIVE') IS NULL
        ALTER TABLE SLS_CUSTOMER ADD IS_ACTIVE BIT DEFAULT 1;
END
GO

-- Recreate unique constraints & indexes for customer_code
IF OBJECT_ID('SLS_CUSTOMER', 'U') IS NOT NULL
BEGIN
    -- Drop old PK
    DECLARE @cust_pk NVARCHAR(256);
    SELECT TOP 1 @cust_pk = name FROM sys.key_constraints WHERE parent_object_id = OBJECT_ID('SLS_CUSTOMER') AND type = 'PK';
    IF @cust_pk IS NOT NULL AND @cust_pk <> 'PK_SLS_CUSTOMER'
    BEGIN
        DECLARE @drop_cust_pk NVARCHAR(MAX) = 'ALTER TABLE SLS_CUSTOMER DROP CONSTRAINT ' + @cust_pk;
        EXEC(@drop_cust_pk);
    END
    IF NOT EXISTS (SELECT 1 FROM sys.key_constraints WHERE parent_object_id = OBJECT_ID('SLS_CUSTOMER') AND name = 'PK_SLS_CUSTOMER')
    BEGIN
        ALTER TABLE SLS_CUSTOMER ADD CONSTRAINT PK_SLS_CUSTOMER PRIMARY KEY (id);
    END

    -- Re-create clean unique constraint
    IF NOT EXISTS (SELECT 1 FROM sys.key_constraints WHERE parent_object_id = OBJECT_ID('SLS_CUSTOMER') AND name = 'UQ_SLS_CUSTOMER_CODE')
    BEGIN
        ALTER TABLE SLS_CUSTOMER ADD CONSTRAINT UQ_SLS_CUSTOMER_CODE UNIQUE (CUSTOMER_CODE);
    END
END
GO


-- ==========================================
-- 2. SLS_CUSTOMER_ADDRESS (from SM_CUSTOMER_ADDRESS)
-- ==========================================
IF OBJECT_ID('SM_CUSTOMER_ADDRESS', 'U') IS NOT NULL
BEGIN
    EXEC sp_rename 'SM_CUSTOMER_ADDRESS', 'SLS_CUSTOMER_ADDRESS';
END
GO

IF OBJECT_ID('SLS_CUSTOMER_ADDRESS', 'U') IS NOT NULL
BEGIN
    IF COL_LENGTH('SLS_CUSTOMER_ADDRESS', 'customer_id') IS NOT NULL AND COL_LENGTH('SLS_CUSTOMER_ADDRESS', 'CUSTOMER_ID') IS NULL
    IF COL_LENGTH('SLS_CUSTOMER_ADDRESS', 'customer_name') IS NOT NULL AND COL_LENGTH('SLS_CUSTOMER_ADDRESS', 'CUSTOMER_NAME') IS NULL
    IF COL_LENGTH('SLS_CUSTOMER_ADDRESS', 'invoice_name') IS NOT NULL AND COL_LENGTH('SLS_CUSTOMER_ADDRESS', 'INVOICE_NAME') IS NULL
    IF COL_LENGTH('SLS_CUSTOMER_ADDRESS', 'shipment') IS NOT NULL AND COL_LENGTH('SLS_CUSTOMER_ADDRESS', 'SHIPMENT') IS NULL
    IF COL_LENGTH('SLS_CUSTOMER_ADDRESS', 'address') IS NOT NULL AND COL_LENGTH('SLS_CUSTOMER_ADDRESS', 'ADDRESS') IS NULL
    IF COL_LENGTH('SLS_CUSTOMER_ADDRESS', 'city') IS NOT NULL AND COL_LENGTH('SLS_CUSTOMER_ADDRESS', 'CITY') IS NULL
    IF COL_LENGTH('SLS_CUSTOMER_ADDRESS', 'district') IS NOT NULL AND COL_LENGTH('SLS_CUSTOMER_ADDRESS', 'DISTRICT') IS NULL
    IF COL_LENGTH('SLS_CUSTOMER_ADDRESS', 'state') IS NOT NULL AND COL_LENGTH('SLS_CUSTOMER_ADDRESS', 'STATE') IS NULL
    IF COL_LENGTH('SLS_CUSTOMER_ADDRESS', 'country') IS NOT NULL AND COL_LENGTH('SLS_CUSTOMER_ADDRESS', 'COUNTRY') IS NULL
    IF COL_LENGTH('SLS_CUSTOMER_ADDRESS', 'pincode') IS NOT NULL AND COL_LENGTH('SLS_CUSTOMER_ADDRESS', 'PINCODE') IS NULL
    IF COL_LENGTH('SLS_CUSTOMER_ADDRESS', 'distance') IS NOT NULL AND COL_LENGTH('SLS_CUSTOMER_ADDRESS', 'DISTANCE') IS NULL
    IF COL_LENGTH('SLS_CUSTOMER_ADDRESS', 'contact_name') IS NOT NULL AND COL_LENGTH('SLS_CUSTOMER_ADDRESS', 'CONTACT_NAME') IS NULL
    IF COL_LENGTH('SLS_CUSTOMER_ADDRESS', 'contact_no') IS NOT NULL AND COL_LENGTH('SLS_CUSTOMER_ADDRESS', 'CONTACT_NO') IS NULL
    IF COL_LENGTH('SLS_CUSTOMER_ADDRESS', 'status') IS NOT NULL AND COL_LENGTH('SLS_CUSTOMER_ADDRESS', 'STATUS') IS NULL
    IF COL_LENGTH('SLS_CUSTOMER_ADDRESS', 'created_by') IS NOT NULL AND COL_LENGTH('SLS_CUSTOMER_ADDRESS', 'CREATED_BY') IS NULL
    IF COL_LENGTH('SLS_CUSTOMER_ADDRESS', 'created_date') IS NOT NULL AND COL_LENGTH('SLS_CUSTOMER_ADDRESS', 'CREATED_DATE') IS NULL
    IF COL_LENGTH('SLS_CUSTOMER_ADDRESS', 'updated_by') IS NOT NULL AND COL_LENGTH('SLS_CUSTOMER_ADDRESS', 'UPDATED_BY') IS NULL
    IF COL_LENGTH('SLS_CUSTOMER_ADDRESS', 'updated_date') IS NOT NULL AND COL_LENGTH('SLS_CUSTOMER_ADDRESS', 'UPDATED_DATE') IS NULL
END
GO

IF OBJECT_ID('SLS_CUSTOMER_ADDRESS', 'U') IS NOT NULL
BEGIN
    ALTER TABLE SLS_CUSTOMER_ADDRESS ALTER COLUMN CUSTOMER_ID BIGINT NOT NULL;
    ALTER TABLE SLS_CUSTOMER_ADDRESS ALTER COLUMN CUSTOMER_NAME NVARCHAR(200);
    ALTER TABLE SLS_CUSTOMER_ADDRESS ALTER COLUMN INVOICE_NAME NVARCHAR(200);
    ALTER TABLE SLS_CUSTOMER_ADDRESS ALTER COLUMN SHIPMENT NVARCHAR(100);
    ALTER TABLE SLS_CUSTOMER_ADDRESS ALTER COLUMN ADDRESS NVARCHAR(MAX);
    ALTER TABLE SLS_CUSTOMER_ADDRESS ALTER COLUMN CITY NVARCHAR(100);
    ALTER TABLE SLS_CUSTOMER_ADDRESS ALTER COLUMN DISTRICT NVARCHAR(100);
    ALTER TABLE SLS_CUSTOMER_ADDRESS ALTER COLUMN STATE NVARCHAR(100);
    ALTER TABLE SLS_CUSTOMER_ADDRESS ALTER COLUMN COUNTRY NVARCHAR(100);
    ALTER TABLE SLS_CUSTOMER_ADDRESS ALTER COLUMN PINCODE NVARCHAR(20);
    ALTER TABLE SLS_CUSTOMER_ADDRESS ALTER COLUMN DISTANCE FLOAT;
    ALTER TABLE SLS_CUSTOMER_ADDRESS ALTER COLUMN CONTACT_NAME NVARCHAR(200);
    ALTER TABLE SLS_CUSTOMER_ADDRESS ALTER COLUMN CONTACT_NO NVARCHAR(50);
    ALTER TABLE SLS_CUSTOMER_ADDRESS ALTER COLUMN STATUS NVARCHAR(20);
    ALTER TABLE SLS_CUSTOMER_ADDRESS ALTER COLUMN CREATED_BY NVARCHAR(100);
    ALTER TABLE SLS_CUSTOMER_ADDRESS ALTER COLUMN CREATED_DATE DATETIME;
    ALTER TABLE SLS_CUSTOMER_ADDRESS ALTER COLUMN UPDATED_BY NVARCHAR(100);
    ALTER TABLE SLS_CUSTOMER_ADDRESS ALTER COLUMN UPDATED_DATE DATETIME;

    IF COL_LENGTH('SLS_CUSTOMER_ADDRESS', 'IS_ACTIVE') IS NULL
        ALTER TABLE SLS_CUSTOMER_ADDRESS ADD IS_ACTIVE BIT DEFAULT 1;
END
GO

IF OBJECT_ID('SLS_CUSTOMER_ADDRESS', 'U') IS NOT NULL
BEGIN
    DECLARE @addr_pk NVARCHAR(256);
    SELECT TOP 1 @addr_pk = name FROM sys.key_constraints WHERE parent_object_id = OBJECT_ID('SLS_CUSTOMER_ADDRESS') AND type = 'PK';
    IF @addr_pk IS NOT NULL AND @addr_pk <> 'PK_SLS_CUSTOMER_ADDR'
    BEGIN
        DECLARE @drop_addr_pk NVARCHAR(MAX) = 'ALTER TABLE SLS_CUSTOMER_ADDRESS DROP CONSTRAINT ' + @addr_pk;
        EXEC(@drop_addr_pk);
    END
    IF NOT EXISTS (SELECT 1 FROM sys.key_constraints WHERE parent_object_id = OBJECT_ID('SLS_CUSTOMER_ADDRESS') AND name = 'PK_SLS_CUSTOMER_ADDR')
    BEGIN
        ALTER TABLE SLS_CUSTOMER_ADDRESS ADD CONSTRAINT PK_SLS_CUSTOMER_ADDR PRIMARY KEY (id);
    END
END
GO


-- ==========================================
-- 3. VND_VENDOR (from SM_SUPPLIER_MASTER)
-- ==========================================
IF OBJECT_ID('SM_SUPPLIER_MASTER', 'U') IS NOT NULL
BEGIN
    EXEC sp_rename 'SM_SUPPLIER_MASTER', 'VND_VENDOR';
END
GO

IF OBJECT_ID('VND_VENDOR', 'U') IS NOT NULL
BEGIN
    -- Handle duplicate created_at/CREATED_DATE columns
    IF COL_LENGTH('VND_VENDOR', 'created_at') IS NOT NULL AND COL_LENGTH('VND_VENDOR', 'created_date') IS NOT NULL
        ALTER TABLE VND_VENDOR DROP COLUMN created_at;
    IF COL_LENGTH('VND_VENDOR', 'updated_at') IS NOT NULL AND COL_LENGTH('VND_VENDOR', 'updated_date') IS NOT NULL
        ALTER TABLE VND_VENDOR DROP COLUMN updated_at;

    IF COL_LENGTH('VND_VENDOR', 'SUPPLIER_CODE') IS NOT NULL AND COL_LENGTH('VND_VENDOR', 'SUPPLIER_CODE') IS NULL
    IF COL_LENGTH('VND_VENDOR', 'GST_NO') IS NOT NULL AND COL_LENGTH('VND_VENDOR', 'GST_NO') IS NULL
    IF COL_LENGTH('VND_VENDOR', 'SUPPLIER_NAME') IS NOT NULL AND COL_LENGTH('VND_VENDOR', 'SUPPLIER_NAME') IS NULL
    IF COL_LENGTH('VND_VENDOR', 'LEDGER_NAME') IS NOT NULL AND COL_LENGTH('VND_VENDOR', 'LEDGER_NAME') IS NULL
    IF COL_LENGTH('VND_VENDOR', 'SHORT_NAME') IS NOT NULL AND COL_LENGTH('VND_VENDOR', 'SHORT_NAME') IS NULL
    IF COL_LENGTH('VND_VENDOR', 'SUPPLIER_PRINT_NAME') IS NOT NULL AND COL_LENGTH('VND_VENDOR', 'SUPPLIER_PRINT_NAME') IS NULL
    IF COL_LENGTH('VND_VENDOR', 'ADDRESS') IS NOT NULL AND COL_LENGTH('VND_VENDOR', 'ADDRESS') IS NULL
    IF COL_LENGTH('VND_VENDOR', 'CITY') IS NOT NULL AND COL_LENGTH('VND_VENDOR', 'CITY') IS NULL
    IF COL_LENGTH('VND_VENDOR', 'STATE') IS NOT NULL AND COL_LENGTH('VND_VENDOR', 'STATE') IS NULL
    IF COL_LENGTH('VND_VENDOR', 'COUNTRY') IS NOT NULL AND COL_LENGTH('VND_VENDOR', 'COUNTRY') IS NULL
    IF COL_LENGTH('VND_VENDOR', 'PINCODE') IS NOT NULL AND COL_LENGTH('VND_VENDOR', 'PINCODE') IS NULL
    IF COL_LENGTH('VND_VENDOR', 'MOBILE_NO') IS NOT NULL AND COL_LENGTH('VND_VENDOR', 'MOBILE_NO') IS NULL
    IF COL_LENGTH('VND_VENDOR', 'CONTACT_PERSON') IS NOT NULL AND COL_LENGTH('VND_VENDOR', 'CONTACT_PERSON') IS NULL
    IF COL_LENGTH('VND_VENDOR', 'EMAIL_ID') IS NOT NULL AND COL_LENGTH('VND_VENDOR', 'EMAIL_ID') IS NULL
    IF COL_LENGTH('VND_VENDOR', 'WEBSITE') IS NOT NULL AND COL_LENGTH('VND_VENDOR', 'WEBSITE') IS NULL
    IF COL_LENGTH('VND_VENDOR', 'PAN_NO') IS NOT NULL AND COL_LENGTH('VND_VENDOR', 'PAN_NO') IS NULL
    IF COL_LENGTH('VND_VENDOR', 'pan_file_info') IS NOT NULL AND COL_LENGTH('VND_VENDOR', 'PAN_FILE_INFO') IS NULL
    IF COL_LENGTH('VND_VENDOR', 'MSME_NO') IS NOT NULL AND COL_LENGTH('VND_VENDOR', 'MSME_NO') IS NULL
    IF COL_LENGTH('VND_VENDOR', 'msme_file_info') IS NOT NULL AND COL_LENGTH('VND_VENDOR', 'MSME_FILE_INFO') IS NULL
    IF COL_LENGTH('VND_VENDOR', 'ISO_NO') IS NOT NULL AND COL_LENGTH('VND_VENDOR', 'ISO_NO') IS NULL
    IF COL_LENGTH('VND_VENDOR', 'iso_file_info') IS NOT NULL AND COL_LENGTH('VND_VENDOR', 'ISO_FILE_INFO') IS NULL
    IF COL_LENGTH('VND_VENDOR', 'ISO_EXPIRY_DATE') IS NOT NULL AND COL_LENGTH('VND_VENDOR', 'ISO_EXPIRY_DATE') IS NULL
    IF COL_LENGTH('VND_VENDOR', 'APPROVED_SUPPLIER') IS NOT NULL AND COL_LENGTH('VND_VENDOR', 'APPROVED_SUPPLIER') IS NULL
    IF COL_LENGTH('VND_VENDOR', 'NDA_REQUIRED') IS NOT NULL AND COL_LENGTH('VND_VENDOR', 'NDA_REQUIRED') IS NULL
    IF COL_LENGTH('VND_VENDOR', 'DELIVERY_TERMS') IS NOT NULL AND COL_LENGTH('VND_VENDOR', 'DELIVERY_TERMS') IS NULL
    IF COL_LENGTH('VND_VENDOR', 'TYPE_OF_SERVICE') IS NOT NULL AND COL_LENGTH('VND_VENDOR', 'TYPE_OF_SERVICE') IS NULL
    IF COL_LENGTH('VND_VENDOR', 'PAYMENT_TERMS') IS NOT NULL AND COL_LENGTH('VND_VENDOR', 'PAYMENT_TERMS') IS NULL
    IF COL_LENGTH('VND_VENDOR', 'PRIME_SUPPLIER') IS NOT NULL AND COL_LENGTH('VND_VENDOR', 'PRIME_SUPPLIER') IS NULL
    IF COL_LENGTH('VND_VENDOR', 'FREIGHT_REQUIRED') IS NOT NULL AND COL_LENGTH('VND_VENDOR', 'FREIGHT_REQUIRED') IS NULL
    IF COL_LENGTH('VND_VENDOR', 'CURRENCY') IS NOT NULL AND COL_LENGTH('VND_VENDOR', 'CURRENCY') IS NULL
    IF COL_LENGTH('VND_VENDOR', 'DUE_DAYS') IS NOT NULL AND COL_LENGTH('VND_VENDOR', 'DUE_DAYS') IS NULL
    IF COL_LENGTH('VND_VENDOR', 'IS_AUDITOR_CONSULTANT') IS NOT NULL AND COL_LENGTH('VND_VENDOR', 'IS_AUDITOR_CONSULTANT') IS NULL
    IF COL_LENGTH('VND_VENDOR', 'ACCOUNT_NO') IS NOT NULL AND COL_LENGTH('VND_VENDOR', 'ACCOUNT_NO') IS NULL
    IF COL_LENGTH('VND_VENDOR', 'ACCOUNT_NAME') IS NOT NULL AND COL_LENGTH('VND_VENDOR', 'ACCOUNT_NAME') IS NULL
    IF COL_LENGTH('VND_VENDOR', 'BANK_NAME') IS NOT NULL AND COL_LENGTH('VND_VENDOR', 'BANK_NAME') IS NULL
    IF COL_LENGTH('VND_VENDOR', 'BRANCH_NAME') IS NOT NULL AND COL_LENGTH('VND_VENDOR', 'BRANCH_NAME') IS NULL
    IF COL_LENGTH('VND_VENDOR', 'IFSC_CODE') IS NOT NULL AND COL_LENGTH('VND_VENDOR', 'IFSC_CODE') IS NULL
    IF COL_LENGTH('VND_VENDOR', 'SWIFT_CODE') IS NOT NULL AND COL_LENGTH('VND_VENDOR', 'SWIFT_CODE') IS NULL
    IF COL_LENGTH('VND_VENDOR', 'ACCOUNT_TYPE') IS NOT NULL AND COL_LENGTH('VND_VENDOR', 'ACCOUNT_TYPE') IS NULL
    IF COL_LENGTH('VND_VENDOR', 'STATUS') IS NOT NULL AND COL_LENGTH('VND_VENDOR', 'STATUS') IS NULL
    IF COL_LENGTH('VND_VENDOR', 'UPLOAD_FILES') IS NOT NULL AND COL_LENGTH('VND_VENDOR', 'UPLOAD_FILES') IS NULL
    IF COL_LENGTH('VND_VENDOR', 'created_by') IS NOT NULL AND COL_LENGTH('VND_VENDOR', 'CREATED_BY') IS NULL
    IF COL_LENGTH('VND_VENDOR', 'updated_by') IS NOT NULL AND COL_LENGTH('VND_VENDOR', 'UPDATED_BY') IS NULL

    IF COL_LENGTH('VND_VENDOR', 'created_at') IS NOT NULL AND COL_LENGTH('VND_VENDOR', 'CREATED_DATE') IS NULL 
        EXEC sp_rename 'VND_VENDOR.created_at', 'CREATED_DATE', 'COLUMN';
    IF COL_LENGTH('VND_VENDOR', 'updated_at') IS NOT NULL AND COL_LENGTH('VND_VENDOR', 'UPDATED_DATE') IS NULL 
        EXEC sp_rename 'VND_VENDOR.updated_at', 'UPDATED_DATE', 'COLUMN';
    IF COL_LENGTH('VND_VENDOR', 'created_date') IS NOT NULL AND COL_LENGTH('VND_VENDOR', 'CREATED_DATE') IS NULL 
        EXEC sp_rename 'VND_VENDOR.created_date', 'CREATED_DATE', 'COLUMN';
    IF COL_LENGTH('VND_VENDOR', 'updated_date') IS NOT NULL AND COL_LENGTH('VND_VENDOR', 'UPDATED_DATE') IS NULL 
        EXEC sp_rename 'VND_VENDOR.updated_date', 'UPDATED_DATE', 'COLUMN';
END
GO

IF OBJECT_ID('VND_VENDOR', 'U') IS NOT NULL
BEGIN
    -- Drop unique constraint/index on SUPPLIER_CODE dynamically to allow type alteration
    DECLARE @drop_uq_vend NVARCHAR(MAX) = N'';
    SELECT @drop_uq_vend += N'ALTER TABLE [VND_VENDOR] DROP CONSTRAINT ' + QUOTENAME(dc.name) + ';' + CHAR(13) + CHAR(10)
    FROM sys.key_constraints dc
    INNER JOIN sys.index_columns ic ON dc.parent_object_id = ic.object_id AND dc.unique_index_id = ic.index_id
    INNER JOIN sys.columns c ON ic.object_id = c.object_id AND ic.column_id = c.column_id
    WHERE dc.parent_object_id = OBJECT_ID('VND_VENDOR')
      AND c.name = 'SUPPLIER_CODE';
    IF @drop_uq_vend <> N'' EXEC sp_executesql @drop_uq_vend;

    DECLARE @drop_idx_vend NVARCHAR(MAX) = N'';
    SELECT @drop_idx_vend += N'DROP INDEX ' + QUOTENAME(i.name) + ' ON [VND_VENDOR];' + CHAR(13) + CHAR(10)
    FROM sys.indexes i
    INNER JOIN sys.index_columns ic ON i.object_id = ic.object_id AND i.index_id = ic.index_id
    INNER JOIN sys.columns c ON ic.object_id = c.object_id AND ic.column_id = c.column_id
    WHERE i.object_id = OBJECT_ID('VND_VENDOR')
      AND c.name = 'SUPPLIER_CODE'
      AND i.is_primary_key = 0
      AND i.is_unique_constraint = 0;
    IF @drop_idx_vend <> N'' EXEC sp_executesql @drop_idx_vend;

    -- Alter types and lengths to NVARCHAR
    ALTER TABLE VND_VENDOR ALTER COLUMN SUPPLIER_CODE NVARCHAR(50) NOT NULL;
    ALTER TABLE VND_VENDOR ALTER COLUMN GST_NO NVARCHAR(50);
    ALTER TABLE VND_VENDOR ALTER COLUMN SUPPLIER_NAME NVARCHAR(200);
    ALTER TABLE VND_VENDOR ALTER COLUMN LEDGER_NAME NVARCHAR(200);
    ALTER TABLE VND_VENDOR ALTER COLUMN SHORT_NAME NVARCHAR(50);
    ALTER TABLE VND_VENDOR ALTER COLUMN SUPPLIER_PRINT_NAME NVARCHAR(200);
    ALTER TABLE VND_VENDOR ALTER COLUMN ADDRESS NVARCHAR(500);
    ALTER TABLE VND_VENDOR ALTER COLUMN CITY NVARCHAR(100);
    ALTER TABLE VND_VENDOR ALTER COLUMN STATE NVARCHAR(100);
    ALTER TABLE VND_VENDOR ALTER COLUMN COUNTRY NVARCHAR(100);
    ALTER TABLE VND_VENDOR ALTER COLUMN PINCODE NVARCHAR(20);
    ALTER TABLE VND_VENDOR ALTER COLUMN MOBILE_NO NVARCHAR(20);
    ALTER TABLE VND_VENDOR ALTER COLUMN CONTACT_PERSON NVARCHAR(100);
    ALTER TABLE VND_VENDOR ALTER COLUMN EMAIL_ID NVARCHAR(100);
    ALTER TABLE VND_VENDOR ALTER COLUMN WEBSITE NVARCHAR(100);
    ALTER TABLE VND_VENDOR ALTER COLUMN PAN_NO NVARCHAR(50);
    ALTER TABLE VND_VENDOR ALTER COLUMN PAN_FILE_INFO NVARCHAR(1000);
    ALTER TABLE VND_VENDOR ALTER COLUMN MSME_NO NVARCHAR(50);
    ALTER TABLE VND_VENDOR ALTER COLUMN MSME_FILE_INFO NVARCHAR(1000);
    ALTER TABLE VND_VENDOR ALTER COLUMN ISO_NO NVARCHAR(50);
    ALTER TABLE VND_VENDOR ALTER COLUMN ISO_FILE_INFO NVARCHAR(1000);
    ALTER TABLE VND_VENDOR ALTER COLUMN ISO_EXPIRY_DATE NVARCHAR(50);
    ALTER TABLE VND_VENDOR ALTER COLUMN APPROVED_SUPPLIER NVARCHAR(10);
    ALTER TABLE VND_VENDOR ALTER COLUMN NDA_REQUIRED NVARCHAR(10);
    ALTER TABLE VND_VENDOR ALTER COLUMN DELIVERY_TERMS NVARCHAR(100);
    ALTER TABLE VND_VENDOR ALTER COLUMN TYPE_OF_SERVICE NVARCHAR(100);
    ALTER TABLE VND_VENDOR ALTER COLUMN PAYMENT_TERMS NVARCHAR(100);
    ALTER TABLE VND_VENDOR ALTER COLUMN PRIME_SUPPLIER NVARCHAR(10);
    ALTER TABLE VND_VENDOR ALTER COLUMN FREIGHT_REQUIRED NVARCHAR(10);
    ALTER TABLE VND_VENDOR ALTER COLUMN CURRENCY NVARCHAR(20);
    ALTER TABLE VND_VENDOR ALTER COLUMN DUE_DAYS NVARCHAR(20);
    ALTER TABLE VND_VENDOR ALTER COLUMN IS_AUDITOR_CONSULTANT NVARCHAR(10);
    ALTER TABLE VND_VENDOR ALTER COLUMN ACCOUNT_NO NVARCHAR(50);
    ALTER TABLE VND_VENDOR ALTER COLUMN ACCOUNT_NAME NVARCHAR(100);
    ALTER TABLE VND_VENDOR ALTER COLUMN BANK_NAME NVARCHAR(100);
    ALTER TABLE VND_VENDOR ALTER COLUMN BRANCH_NAME NVARCHAR(100);
    ALTER TABLE VND_VENDOR ALTER COLUMN IFSC_CODE NVARCHAR(50);
    ALTER TABLE VND_VENDOR ALTER COLUMN SWIFT_CODE NVARCHAR(50);
    ALTER TABLE VND_VENDOR ALTER COLUMN ACCOUNT_TYPE NVARCHAR(50);
    ALTER TABLE VND_VENDOR ALTER COLUMN STATUS NVARCHAR(20);
    ALTER TABLE VND_VENDOR ALTER COLUMN UPLOAD_FILES NVARCHAR(1000);
    ALTER TABLE VND_VENDOR ALTER COLUMN CREATED_BY NVARCHAR(100);
    ALTER TABLE VND_VENDOR ALTER COLUMN CREATED_DATE DATETIME;
    ALTER TABLE VND_VENDOR ALTER COLUMN UPDATED_BY NVARCHAR(100);
    ALTER TABLE VND_VENDOR ALTER COLUMN UPDATED_DATE DATETIME;

    IF COL_LENGTH('VND_VENDOR', 'IS_ACTIVE') IS NULL
        ALTER TABLE VND_VENDOR ADD IS_ACTIVE BIT DEFAULT 1;
END
GO

IF OBJECT_ID('VND_VENDOR', 'U') IS NOT NULL
BEGIN
    -- PK
    DECLARE @vend_pk NVARCHAR(256);
    SELECT TOP 1 @vend_pk = name FROM sys.key_constraints WHERE parent_object_id = OBJECT_ID('VND_VENDOR') AND type = 'PK';
    IF @vend_pk IS NOT NULL AND @vend_pk <> 'PK_VND_VENDOR'
    BEGIN
        DECLARE @drop_vend_pk NVARCHAR(MAX) = 'ALTER TABLE VND_VENDOR DROP CONSTRAINT ' + @vend_pk;
        EXEC(@drop_vend_pk);
    END
    IF NOT EXISTS (SELECT 1 FROM sys.key_constraints WHERE parent_object_id = OBJECT_ID('VND_VENDOR') AND name = 'PK_VND_VENDOR')
    BEGIN
        ALTER TABLE VND_VENDOR ADD CONSTRAINT PK_VND_VENDOR PRIMARY KEY (id);
    END

    -- Re-create unique constraint
    IF NOT EXISTS (SELECT 1 FROM sys.key_constraints WHERE parent_object_id = OBJECT_ID('VND_VENDOR') AND name = 'UQ_VND_VENDOR_CODE')
    BEGIN
        ALTER TABLE VND_VENDOR ADD CONSTRAINT UQ_VND_VENDOR_CODE UNIQUE (SUPPLIER_CODE);
    END
END
GO


-- ==========================================
-- 4. VND_CUSTOMER_MAPPING (from SM_VENDOR_CUSTOMER_MASTER)
-- ==========================================
IF OBJECT_ID('SM_VENDOR_CUSTOMER_MASTER', 'U') IS NOT NULL
BEGIN
    EXEC sp_rename 'SM_VENDOR_CUSTOMER_MASTER', 'VND_CUSTOMER_MAPPING';
END
GO

IF OBJECT_ID('VND_CUSTOMER_MAPPING', 'U') IS NOT NULL
BEGIN
    -- Handle duplicate created_at/CREATED_DATE columns
    IF COL_LENGTH('VND_CUSTOMER_MAPPING', 'created_at') IS NOT NULL AND COL_LENGTH('VND_CUSTOMER_MAPPING', 'created_date') IS NOT NULL
        ALTER TABLE VND_CUSTOMER_MAPPING DROP COLUMN created_at;
    IF COL_LENGTH('VND_CUSTOMER_MAPPING', 'updated_at') IS NOT NULL AND COL_LENGTH('VND_CUSTOMER_MAPPING', 'updated_date') IS NOT NULL
        ALTER TABLE VND_CUSTOMER_MAPPING DROP COLUMN updated_at;

    IF COL_LENGTH('VND_CUSTOMER_MAPPING', 'record_type') IS NOT NULL AND COL_LENGTH('VND_CUSTOMER_MAPPING', 'RECORD_TYPE') IS NULL
    IF COL_LENGTH('VND_CUSTOMER_MAPPING', 'code') IS NOT NULL AND COL_LENGTH('VND_CUSTOMER_MAPPING', 'CODE') IS NULL
    IF COL_LENGTH('VND_CUSTOMER_MAPPING', 'name') IS NOT NULL AND COL_LENGTH('VND_CUSTOMER_MAPPING', 'NAME') IS NULL
    IF COL_LENGTH('VND_CUSTOMER_MAPPING', 'print_name') IS NOT NULL AND COL_LENGTH('VND_CUSTOMER_MAPPING', 'PRINT_NAME') IS NULL
    IF COL_LENGTH('VND_CUSTOMER_MAPPING', 'short_name') IS NOT NULL AND COL_LENGTH('VND_CUSTOMER_MAPPING', 'SHORT_NAME') IS NULL
    IF COL_LENGTH('VND_CUSTOMER_MAPPING', 'ledger_name') IS NOT NULL AND COL_LENGTH('VND_CUSTOMER_MAPPING', 'LEDGER_NAME') IS NULL
    IF COL_LENGTH('VND_CUSTOMER_MAPPING', 'invoice_name') IS NOT NULL AND COL_LENGTH('VND_CUSTOMER_MAPPING', 'INVOICE_NAME') IS NULL
    IF COL_LENGTH('VND_CUSTOMER_MAPPING', 'group_name') IS NOT NULL AND COL_LENGTH('VND_CUSTOMER_MAPPING', 'GROUP_NAME') IS NULL
    IF COL_LENGTH('VND_CUSTOMER_MAPPING', 'address') IS NOT NULL AND COL_LENGTH('VND_CUSTOMER_MAPPING', 'ADDRESS') IS NULL
    IF COL_LENGTH('VND_CUSTOMER_MAPPING', 'pincode') IS NOT NULL AND COL_LENGTH('VND_CUSTOMER_MAPPING', 'PINCODE') IS NULL
    IF COL_LENGTH('VND_CUSTOMER_MAPPING', 'city') IS NOT NULL AND COL_LENGTH('VND_CUSTOMER_MAPPING', 'CITY') IS NULL
    IF COL_LENGTH('VND_CUSTOMER_MAPPING', 'state') IS NOT NULL AND COL_LENGTH('VND_CUSTOMER_MAPPING', 'STATE') IS NULL
    IF COL_LENGTH('VND_CUSTOMER_MAPPING', 'state_code') IS NOT NULL AND COL_LENGTH('VND_CUSTOMER_MAPPING', 'STATE_CODE') IS NULL
    IF COL_LENGTH('VND_CUSTOMER_MAPPING', 'country') IS NOT NULL AND COL_LENGTH('VND_CUSTOMER_MAPPING', 'COUNTRY') IS NULL
    IF COL_LENGTH('VND_CUSTOMER_MAPPING', 'location') IS NOT NULL AND COL_LENGTH('VND_CUSTOMER_MAPPING', 'LOCATION') IS NULL
    IF COL_LENGTH('VND_CUSTOMER_MAPPING', 'distance') IS NOT NULL AND COL_LENGTH('VND_CUSTOMER_MAPPING', 'DISTANCE') IS NULL
    IF COL_LENGTH('VND_CUSTOMER_MAPPING', 'contact_person') IS NOT NULL AND COL_LENGTH('VND_CUSTOMER_MAPPING', 'CONTACT_PERSON') IS NULL
    IF COL_LENGTH('VND_CUSTOMER_MAPPING', 'mobile_no') IS NOT NULL AND COL_LENGTH('VND_CUSTOMER_MAPPING', 'MOBILE_NO') IS NULL
    IF COL_LENGTH('VND_CUSTOMER_MAPPING', 'email_id') IS NOT NULL AND COL_LENGTH('VND_CUSTOMER_MAPPING', 'EMAIL_ID') IS NULL
    IF COL_LENGTH('VND_CUSTOMER_MAPPING', 'website') IS NOT NULL AND COL_LENGTH('VND_CUSTOMER_MAPPING', 'WEBSITE') IS NULL
    IF COL_LENGTH('VND_CUSTOMER_MAPPING', 'gst_no') IS NOT NULL AND COL_LENGTH('VND_CUSTOMER_MAPPING', 'GST_NO') IS NULL
    IF COL_LENGTH('VND_CUSTOMER_MAPPING', 'pan_no') IS NOT NULL AND COL_LENGTH('VND_CUSTOMER_MAPPING', 'PAN_NO') IS NULL
    IF COL_LENGTH('VND_CUSTOMER_MAPPING', 'pan_file_info') IS NOT NULL AND COL_LENGTH('VND_CUSTOMER_MAPPING', 'PAN_FILE_INFO') IS NULL
    IF COL_LENGTH('VND_CUSTOMER_MAPPING', 'register_no') IS NOT NULL AND COL_LENGTH('VND_CUSTOMER_MAPPING', 'REGISTER_NO') IS NULL
    IF COL_LENGTH('VND_CUSTOMER_MAPPING', 'cin_no') IS NOT NULL AND COL_LENGTH('VND_CUSTOMER_MAPPING', 'CIN_NO') IS NULL
    IF COL_LENGTH('VND_CUSTOMER_MAPPING', 'vendor_code') IS NOT NULL AND COL_LENGTH('VND_CUSTOMER_MAPPING', 'VENDOR_CODE') IS NULL
    IF COL_LENGTH('VND_CUSTOMER_MAPPING', 'msme_no') IS NOT NULL AND COL_LENGTH('VND_CUSTOMER_MAPPING', 'MSME_NO') IS NULL
    IF COL_LENGTH('VND_CUSTOMER_MAPPING', 'msme_file_info') IS NOT NULL AND COL_LENGTH('VND_CUSTOMER_MAPPING', 'MSME_FILE_INFO') IS NULL
    IF COL_LENGTH('VND_CUSTOMER_MAPPING', 'iso_no') IS NOT NULL AND COL_LENGTH('VND_CUSTOMER_MAPPING', 'ISO_NO') IS NULL
    IF COL_LENGTH('VND_CUSTOMER_MAPPING', 'iso_file_info') IS NOT NULL AND COL_LENGTH('VND_CUSTOMER_MAPPING', 'ISO_FILE_INFO') IS NULL
    IF COL_LENGTH('VND_CUSTOMER_MAPPING', 'iso_expiry_date') IS NOT NULL AND COL_LENGTH('VND_CUSTOMER_MAPPING', 'ISO_EXPIRY_DATE') IS NULL
    IF COL_LENGTH('VND_CUSTOMER_MAPPING', 'prime_flag') IS NOT NULL AND COL_LENGTH('VND_CUSTOMER_MAPPING', 'PRIME_FLAG') IS NULL
    IF COL_LENGTH('VND_CUSTOMER_MAPPING', 'approved_supplier') IS NOT NULL AND COL_LENGTH('VND_CUSTOMER_MAPPING', 'APPROVED_SUPPLIER') IS NULL
    IF COL_LENGTH('VND_CUSTOMER_MAPPING', 'nda_required') IS NOT NULL AND COL_LENGTH('VND_CUSTOMER_MAPPING', 'NDA_REQUIRED') IS NULL
    IF COL_LENGTH('VND_CUSTOMER_MAPPING', 'is_auditor_consultant') IS NOT NULL AND COL_LENGTH('VND_CUSTOMER_MAPPING', 'IS_AUDITOR_CONSULTANT') IS NULL
    IF COL_LENGTH('VND_CUSTOMER_MAPPING', 'segment') IS NOT NULL AND COL_LENGTH('VND_CUSTOMER_MAPPING', 'SEGMENT') IS NULL
    IF COL_LENGTH('VND_CUSTOMER_MAPPING', 'sub_segment') IS NOT NULL AND COL_LENGTH('VND_CUSTOMER_MAPPING', 'SUB_SEGMENT') IS NULL
    IF COL_LENGTH('VND_CUSTOMER_MAPPING', 'domain_name') IS NOT NULL AND COL_LENGTH('VND_CUSTOMER_MAPPING', 'DOMAIN_NAME') IS NULL
    IF COL_LENGTH('VND_CUSTOMER_MAPPING', 'negotiate_customer') IS NOT NULL AND COL_LENGTH('VND_CUSTOMER_MAPPING', 'NEGOTIATE_CUSTOMER') IS NULL
    IF COL_LENGTH('VND_CUSTOMER_MAPPING', 'daily_dispatch_mail') IS NOT NULL AND COL_LENGTH('VND_CUSTOMER_MAPPING', 'DAILY_DISPATCH_MAIL') IS NULL
    IF COL_LENGTH('VND_CUSTOMER_MAPPING', 'ld_applicable') IS NOT NULL AND COL_LENGTH('VND_CUSTOMER_MAPPING', 'LD_APPLICABLE') IS NULL
    IF COL_LENGTH('VND_CUSTOMER_MAPPING', 'currency') IS NOT NULL AND COL_LENGTH('VND_CUSTOMER_MAPPING', 'CURRENCY') IS NULL
    IF COL_LENGTH('VND_CUSTOMER_MAPPING', 'payment_terms') IS NOT NULL AND COL_LENGTH('VND_CUSTOMER_MAPPING', 'PAYMENT_TERMS') IS NULL
    IF COL_LENGTH('VND_CUSTOMER_MAPPING', 'delivery_terms') IS NOT NULL AND COL_LENGTH('VND_CUSTOMER_MAPPING', 'DELIVERY_TERMS') IS NULL
    IF COL_LENGTH('VND_CUSTOMER_MAPPING', 'freight') IS NOT NULL AND COL_LENGTH('VND_CUSTOMER_MAPPING', 'FREIGHT') IS NULL
    IF COL_LENGTH('VND_CUSTOMER_MAPPING', 'dispatch_mode') IS NOT NULL AND COL_LENGTH('VND_CUSTOMER_MAPPING', 'DISPATCH_MODE') IS NULL
    IF COL_LENGTH('VND_CUSTOMER_MAPPING', 'type_of_service') IS NOT NULL AND COL_LENGTH('VND_CUSTOMER_MAPPING', 'TYPE_OF_SERVICE') IS NULL
    IF COL_LENGTH('VND_CUSTOMER_MAPPING', 'due_days') IS NOT NULL AND COL_LENGTH('VND_CUSTOMER_MAPPING', 'DUE_DAYS') IS NULL
    IF COL_LENGTH('VND_CUSTOMER_MAPPING', 'account_no') IS NOT NULL AND COL_LENGTH('VND_CUSTOMER_MAPPING', 'ACCOUNT_NO') IS NULL
    IF COL_LENGTH('VND_CUSTOMER_MAPPING', 'account_name') IS NOT NULL AND COL_LENGTH('VND_CUSTOMER_MAPPING', 'ACCOUNT_NAME') IS NULL
    IF COL_LENGTH('VND_CUSTOMER_MAPPING', 'bank_name') IS NOT NULL AND COL_LENGTH('VND_CUSTOMER_MAPPING', 'BANK_NAME') IS NULL
    IF COL_LENGTH('VND_CUSTOMER_MAPPING', 'branch_name') IS NOT NULL AND COL_LENGTH('VND_CUSTOMER_MAPPING', 'BRANCH_NAME') IS NULL
    IF COL_LENGTH('VND_CUSTOMER_MAPPING', 'ifsc_code') IS NOT NULL AND COL_LENGTH('VND_CUSTOMER_MAPPING', 'IFSC_CODE') IS NULL
    IF COL_LENGTH('VND_CUSTOMER_MAPPING', 'swift_code') IS NOT NULL AND COL_LENGTH('VND_CUSTOMER_MAPPING', 'SWIFT_CODE') IS NULL
    IF COL_LENGTH('VND_CUSTOMER_MAPPING', 'account_type') IS NOT NULL AND COL_LENGTH('VND_CUSTOMER_MAPPING', 'ACCOUNT_TYPE') IS NULL
    IF COL_LENGTH('VND_CUSTOMER_MAPPING', 'upload_files') IS NOT NULL AND COL_LENGTH('VND_CUSTOMER_MAPPING', 'UPLOAD_FILES') IS NULL
    IF COL_LENGTH('VND_CUSTOMER_MAPPING', 'status') IS NOT NULL AND COL_LENGTH('VND_CUSTOMER_MAPPING', 'STATUS') IS NULL
    IF COL_LENGTH('VND_CUSTOMER_MAPPING', 'created_by') IS NOT NULL AND COL_LENGTH('VND_CUSTOMER_MAPPING', 'CREATED_BY') IS NULL
    IF COL_LENGTH('VND_CUSTOMER_MAPPING', 'updated_by') IS NOT NULL AND COL_LENGTH('VND_CUSTOMER_MAPPING', 'UPDATED_BY') IS NULL

    IF COL_LENGTH('VND_CUSTOMER_MAPPING', 'created_at') IS NOT NULL AND COL_LENGTH('VND_CUSTOMER_MAPPING', 'CREATED_DATE') IS NULL 
        EXEC sp_rename 'VND_CUSTOMER_MAPPING.created_at', 'CREATED_DATE', 'COLUMN';
    IF COL_LENGTH('VND_CUSTOMER_MAPPING', 'updated_at') IS NOT NULL AND COL_LENGTH('VND_CUSTOMER_MAPPING', 'UPDATED_DATE') IS NULL 
        EXEC sp_rename 'VND_CUSTOMER_MAPPING.updated_at', 'UPDATED_DATE', 'COLUMN';
    IF COL_LENGTH('VND_CUSTOMER_MAPPING', 'created_date') IS NOT NULL AND COL_LENGTH('VND_CUSTOMER_MAPPING', 'CREATED_DATE') IS NULL 
        EXEC sp_rename 'VND_CUSTOMER_MAPPING.created_date', 'CREATED_DATE', 'COLUMN';
    IF COL_LENGTH('VND_CUSTOMER_MAPPING', 'updated_date') IS NOT NULL AND COL_LENGTH('VND_CUSTOMER_MAPPING', 'UPDATED_DATE') IS NULL 
        EXEC sp_rename 'VND_CUSTOMER_MAPPING.updated_date', 'UPDATED_DATE', 'COLUMN';
END
GO

IF OBJECT_ID('VND_CUSTOMER_MAPPING', 'U') IS NOT NULL
BEGIN
    ALTER TABLE VND_CUSTOMER_MAPPING ALTER COLUMN RECORD_TYPE NVARCHAR(20) NOT NULL;
    ALTER TABLE VND_CUSTOMER_MAPPING ALTER COLUMN CODE NVARCHAR(50);
    ALTER TABLE VND_CUSTOMER_MAPPING ALTER COLUMN NAME NVARCHAR(200);
    ALTER TABLE VND_CUSTOMER_MAPPING ALTER COLUMN PRINT_NAME NVARCHAR(200);
    ALTER TABLE VND_CUSTOMER_MAPPING ALTER COLUMN SHORT_NAME NVARCHAR(50);
    ALTER TABLE VND_CUSTOMER_MAPPING ALTER COLUMN LEDGER_NAME NVARCHAR(200);
    ALTER TABLE VND_CUSTOMER_MAPPING ALTER COLUMN INVOICE_NAME NVARCHAR(200);
    ALTER TABLE VND_CUSTOMER_MAPPING ALTER COLUMN GROUP_NAME NVARCHAR(200);
    ALTER TABLE VND_CUSTOMER_MAPPING ALTER COLUMN ADDRESS NVARCHAR(MAX);
    ALTER TABLE VND_CUSTOMER_MAPPING ALTER COLUMN PINCODE NVARCHAR(20);
    ALTER TABLE VND_CUSTOMER_MAPPING ALTER COLUMN CITY NVARCHAR(100);
    ALTER TABLE VND_CUSTOMER_MAPPING ALTER COLUMN STATE NVARCHAR(100);
    ALTER TABLE VND_CUSTOMER_MAPPING ALTER COLUMN STATE_CODE NVARCHAR(20);
    ALTER TABLE VND_CUSTOMER_MAPPING ALTER COLUMN COUNTRY NVARCHAR(100);
    ALTER TABLE VND_CUSTOMER_MAPPING ALTER COLUMN LOCATION NVARCHAR(200);
    ALTER TABLE VND_CUSTOMER_MAPPING ALTER COLUMN DISTANCE NVARCHAR(50);
    ALTER TABLE VND_CUSTOMER_MAPPING ALTER COLUMN CONTACT_PERSON NVARCHAR(100);
    ALTER TABLE VND_CUSTOMER_MAPPING ALTER COLUMN MOBILE_NO NVARCHAR(20);
    ALTER TABLE VND_CUSTOMER_MAPPING ALTER COLUMN EMAIL_ID NVARCHAR(100);
    ALTER TABLE VND_CUSTOMER_MAPPING ALTER COLUMN WEBSITE NVARCHAR(150);
    ALTER TABLE VND_CUSTOMER_MAPPING ALTER COLUMN GST_NO NVARCHAR(50);
    ALTER TABLE VND_CUSTOMER_MAPPING ALTER COLUMN PAN_NO NVARCHAR(50);
    ALTER TABLE VND_CUSTOMER_MAPPING ALTER COLUMN PAN_FILE_INFO NVARCHAR(1000);
    ALTER TABLE VND_CUSTOMER_MAPPING ALTER COLUMN REGISTER_NO NVARCHAR(100);
    ALTER TABLE VND_CUSTOMER_MAPPING ALTER COLUMN CIN_NO NVARCHAR(100);
    ALTER TABLE VND_CUSTOMER_MAPPING ALTER COLUMN VENDOR_CODE NVARCHAR(50);
    ALTER TABLE VND_CUSTOMER_MAPPING ALTER COLUMN MSME_NO NVARCHAR(50);
    ALTER TABLE VND_CUSTOMER_MAPPING ALTER COLUMN MSME_FILE_INFO NVARCHAR(1000);
    ALTER TABLE VND_CUSTOMER_MAPPING ALTER COLUMN ISO_NO NVARCHAR(50);
    ALTER TABLE VND_CUSTOMER_MAPPING ALTER COLUMN ISO_FILE_INFO NVARCHAR(1000);
    ALTER TABLE VND_CUSTOMER_MAPPING ALTER COLUMN ISO_EXPIRY_DATE NVARCHAR(50);
    ALTER TABLE VND_CUSTOMER_MAPPING ALTER COLUMN PRIME_FLAG NVARCHAR(10);
    ALTER TABLE VND_CUSTOMER_MAPPING ALTER COLUMN APPROVED_SUPPLIER NVARCHAR(10);
    ALTER TABLE VND_CUSTOMER_MAPPING ALTER COLUMN NDA_REQUIRED NVARCHAR(10);
    ALTER TABLE VND_CUSTOMER_MAPPING ALTER COLUMN IS_AUDITOR_CONSULTANT NVARCHAR(10);
    ALTER TABLE VND_CUSTOMER_MAPPING ALTER COLUMN SEGMENT NVARCHAR(100);
    ALTER TABLE VND_CUSTOMER_MAPPING ALTER COLUMN SUB_SEGMENT NVARCHAR(100);
    ALTER TABLE VND_CUSTOMER_MAPPING ALTER COLUMN DOMAIN_NAME NVARCHAR(150);
    ALTER TABLE VND_CUSTOMER_MAPPING ALTER COLUMN NEGOTIATE_CUSTOMER NVARCHAR(10);
    ALTER TABLE VND_CUSTOMER_MAPPING ALTER COLUMN DAILY_DISPATCH_MAIL NVARCHAR(10);
    ALTER TABLE VND_CUSTOMER_MAPPING ALTER COLUMN LD_APPLICABLE NVARCHAR(10);
    ALTER TABLE VND_CUSTOMER_MAPPING ALTER COLUMN CURRENCY NVARCHAR(20);
    ALTER TABLE VND_CUSTOMER_MAPPING ALTER COLUMN PAYMENT_TERMS NVARCHAR(100);
    ALTER TABLE VND_CUSTOMER_MAPPING ALTER COLUMN DELIVERY_TERMS NVARCHAR(100);
    ALTER TABLE VND_CUSTOMER_MAPPING ALTER COLUMN FREIGHT NVARCHAR(100);
    ALTER TABLE VND_CUSTOMER_MAPPING ALTER COLUMN DISPATCH_MODE NVARCHAR(50);
    ALTER TABLE VND_CUSTOMER_MAPPING ALTER COLUMN TYPE_OF_SERVICE NVARCHAR(100);
    ALTER TABLE VND_CUSTOMER_MAPPING ALTER COLUMN DUE_DAYS NVARCHAR(20);
    ALTER TABLE VND_CUSTOMER_MAPPING ALTER COLUMN ACCOUNT_NO NVARCHAR(50);
    ALTER TABLE VND_CUSTOMER_MAPPING ALTER COLUMN ACCOUNT_NAME NVARCHAR(100);
    ALTER TABLE VND_CUSTOMER_MAPPING ALTER COLUMN BANK_NAME NVARCHAR(100);
    ALTER TABLE VND_CUSTOMER_MAPPING ALTER COLUMN BRANCH_NAME NVARCHAR(100);
    ALTER TABLE VND_CUSTOMER_MAPPING ALTER COLUMN IFSC_CODE NVARCHAR(50);
    ALTER TABLE VND_CUSTOMER_MAPPING ALTER COLUMN SWIFT_CODE NVARCHAR(50);
    ALTER TABLE VND_CUSTOMER_MAPPING ALTER COLUMN ACCOUNT_TYPE NVARCHAR(50);
    ALTER TABLE VND_CUSTOMER_MAPPING ALTER COLUMN UPLOAD_FILES NVARCHAR(1000);
    ALTER TABLE VND_CUSTOMER_MAPPING ALTER COLUMN STATUS NVARCHAR(20);
    ALTER TABLE VND_CUSTOMER_MAPPING ALTER COLUMN CREATED_BY NVARCHAR(100);
    ALTER TABLE VND_CUSTOMER_MAPPING ALTER COLUMN CREATED_DATE DATETIME;
    ALTER TABLE VND_CUSTOMER_MAPPING ALTER COLUMN UPDATED_BY NVARCHAR(100);
    ALTER TABLE VND_CUSTOMER_MAPPING ALTER COLUMN UPDATED_DATE DATETIME;

    IF COL_LENGTH('VND_CUSTOMER_MAPPING', 'IS_ACTIVE') IS NULL
        ALTER TABLE VND_CUSTOMER_MAPPING ADD IS_ACTIVE BIT DEFAULT 1;
END
GO

IF OBJECT_ID('VND_CUSTOMER_MAPPING', 'U') IS NOT NULL
BEGIN
    DECLARE @map_pk NVARCHAR(256);
    SELECT TOP 1 @map_pk = name FROM sys.key_constraints WHERE parent_object_id = OBJECT_ID('VND_CUSTOMER_MAPPING') AND type = 'PK';
    IF @map_pk IS NOT NULL AND @map_pk <> 'PK_VND_CUSTOMER_MAPPING'
    BEGIN
        DECLARE @drop_map_pk NVARCHAR(MAX) = 'ALTER TABLE VND_CUSTOMER_MAPPING DROP CONSTRAINT ' + @map_pk;
        EXEC(@drop_map_pk);
    END
    IF NOT EXISTS (SELECT 1 FROM sys.key_constraints WHERE parent_object_id = OBJECT_ID('VND_CUSTOMER_MAPPING') AND name = 'PK_VND_CUSTOMER_MAPPING')
    BEGIN
        ALTER TABLE VND_CUSTOMER_MAPPING ADD CONSTRAINT PK_VND_CUSTOMER_MAPPING PRIMARY KEY (id);
    END
END
GO


-- ==========================================
-- 5. SLS_CUSTOMER_POTENTIAL (from SM_CUSTOMER_POTENTIAL)
-- ==========================================
IF OBJECT_ID('SM_CUSTOMER_POTENTIAL', 'U') IS NOT NULL
BEGIN
    EXEC sp_rename 'SM_CUSTOMER_POTENTIAL', 'SLS_CUSTOMER_POTENTIAL';
END
GO

IF OBJECT_ID('SLS_CUSTOMER_POTENTIAL', 'U') IS NOT NULL
BEGIN
    -- Handle duplicate created_at/CREATED_DATE columns
    IF COL_LENGTH('SLS_CUSTOMER_POTENTIAL', 'created_at') IS NOT NULL AND COL_LENGTH('SLS_CUSTOMER_POTENTIAL', 'created_date') IS NOT NULL
        ALTER TABLE SLS_CUSTOMER_POTENTIAL DROP COLUMN created_at;
    IF COL_LENGTH('SLS_CUSTOMER_POTENTIAL', 'updated_at') IS NOT NULL AND COL_LENGTH('SLS_CUSTOMER_POTENTIAL', 'updated_date') IS NOT NULL
        ALTER TABLE SLS_CUSTOMER_POTENTIAL DROP COLUMN updated_at;

    IF COL_LENGTH('SLS_CUSTOMER_POTENTIAL', 'customer_group_name') IS NOT NULL AND COL_LENGTH('SLS_CUSTOMER_POTENTIAL', 'CUSTOMER_GROUP_NAME') IS NULL
    IF COL_LENGTH('SLS_CUSTOMER_POTENTIAL', 'customer_code') IS NOT NULL AND COL_LENGTH('SLS_CUSTOMER_POTENTIAL', 'CUSTOMER_CODE') IS NULL
    IF COL_LENGTH('SLS_CUSTOMER_POTENTIAL', 'customer_type') IS NOT NULL AND COL_LENGTH('SLS_CUSTOMER_POTENTIAL', 'CUSTOMER_TYPE') IS NULL
    IF COL_LENGTH('SLS_CUSTOMER_POTENTIAL', 'manufacturer_oem') IS NOT NULL AND COL_LENGTH('SLS_CUSTOMER_POTENTIAL', 'MANUFACTURER_OEM') IS NULL
    IF COL_LENGTH('SLS_CUSTOMER_POTENTIAL', 'wtg_model') IS NOT NULL AND COL_LENGTH('SLS_CUSTOMER_POTENTIAL', 'WTG_MODEL') IS NULL
    IF COL_LENGTH('SLS_CUSTOMER_POTENTIAL', 'wind_turbine_power') IS NOT NULL AND COL_LENGTH('SLS_CUSTOMER_POTENTIAL', 'WIND_TURBINE_POWER') IS NULL
    IF COL_LENGTH('SLS_CUSTOMER_POTENTIAL', 'wind_farm_name') IS NOT NULL AND COL_LENGTH('SLS_CUSTOMER_POTENTIAL', 'WIND_FARM_NAME') IS NULL
    IF COL_LENGTH('SLS_CUSTOMER_POTENTIAL', 'area') IS NOT NULL AND COL_LENGTH('SLS_CUSTOMER_POTENTIAL', 'AREA') IS NULL
    IF COL_LENGTH('SLS_CUSTOMER_POTENTIAL', 'pincode') IS NOT NULL AND COL_LENGTH('SLS_CUSTOMER_POTENTIAL', 'PINCODE') IS NULL
    IF COL_LENGTH('SLS_CUSTOMER_POTENTIAL', 'state') IS NOT NULL AND COL_LENGTH('SLS_CUSTOMER_POTENTIAL', 'STATE') IS NULL
    IF COL_LENGTH('SLS_CUSTOMER_POTENTIAL', 'country') IS NOT NULL AND COL_LENGTH('SLS_CUSTOMER_POTENTIAL', 'COUNTRY') IS NULL
    IF COL_LENGTH('SLS_CUSTOMER_POTENTIAL', 'developer') IS NOT NULL AND COL_LENGTH('SLS_CUSTOMER_POTENTIAL', 'DEVELOPER') IS NULL
    IF COL_LENGTH('SLS_CUSTOMER_POTENTIAL', 'plant_mw') IS NOT NULL AND COL_LENGTH('SLS_CUSTOMER_POTENTIAL', 'PLANT_MW') IS NULL
    IF COL_LENGTH('SLS_CUSTOMER_POTENTIAL', 'turbine_count') IS NOT NULL AND COL_LENGTH('SLS_CUSTOMER_POTENTIAL', 'TURBINE_COUNT') IS NULL
    IF COL_LENGTH('SLS_CUSTOMER_POTENTIAL', 'hub') IS NOT NULL AND COL_LENGTH('SLS_CUSTOMER_POTENTIAL', 'HUB') IS NULL
    IF COL_LENGTH('SLS_CUSTOMER_POTENTIAL', 'operational_status') IS NOT NULL AND COL_LENGTH('SLS_CUSTOMER_POTENTIAL', 'OPERATIONAL_STATUS') IS NULL
    IF COL_LENGTH('SLS_CUSTOMER_POTENTIAL', 'commissioning_year') IS NOT NULL AND COL_LENGTH('SLS_CUSTOMER_POTENTIAL', 'COMMISSIONING_YEAR') IS NULL
    IF COL_LENGTH('SLS_CUSTOMER_POTENTIAL', 'commissioning_month') IS NOT NULL AND COL_LENGTH('SLS_CUSTOMER_POTENTIAL', 'COMMISSIONING_MONTH') IS NULL
    IF COL_LENGTH('SLS_CUSTOMER_POTENTIAL', 'latitude') IS NOT NULL AND COL_LENGTH('SLS_CUSTOMER_POTENTIAL', 'LATITUDE') IS NULL
    IF COL_LENGTH('SLS_CUSTOMER_POTENTIAL', 'longitude') IS NOT NULL AND COL_LENGTH('SLS_CUSTOMER_POTENTIAL', 'LONGITUDE') IS NULL
    IF COL_LENGTH('SLS_CUSTOMER_POTENTIAL', 'status') IS NOT NULL AND COL_LENGTH('SLS_CUSTOMER_POTENTIAL', 'STATUS') IS NULL
    IF COL_LENGTH('SLS_CUSTOMER_POTENTIAL', 'created_by') IS NOT NULL AND COL_LENGTH('SLS_CUSTOMER_POTENTIAL', 'CREATED_BY') IS NULL
    IF COL_LENGTH('SLS_CUSTOMER_POTENTIAL', 'updated_by') IS NOT NULL AND COL_LENGTH('SLS_CUSTOMER_POTENTIAL', 'UPDATED_BY') IS NULL

    IF COL_LENGTH('SLS_CUSTOMER_POTENTIAL', 'created_at') IS NOT NULL AND COL_LENGTH('SLS_CUSTOMER_POTENTIAL', 'CREATED_DATE') IS NULL 
        EXEC sp_rename 'SLS_CUSTOMER_POTENTIAL.created_at', 'CREATED_DATE', 'COLUMN';
    IF COL_LENGTH('SLS_CUSTOMER_POTENTIAL', 'updated_at') IS NOT NULL AND COL_LENGTH('SLS_CUSTOMER_POTENTIAL', 'UPDATED_DATE') IS NULL 
        EXEC sp_rename 'SLS_CUSTOMER_POTENTIAL.updated_at', 'UPDATED_DATE', 'COLUMN';
    IF COL_LENGTH('SLS_CUSTOMER_POTENTIAL', 'created_date') IS NOT NULL AND COL_LENGTH('SLS_CUSTOMER_POTENTIAL', 'CREATED_DATE') IS NULL 
        EXEC sp_rename 'SLS_CUSTOMER_POTENTIAL.created_date', 'CREATED_DATE', 'COLUMN';
    IF COL_LENGTH('SLS_CUSTOMER_POTENTIAL', 'updated_date') IS NOT NULL AND COL_LENGTH('SLS_CUSTOMER_POTENTIAL', 'UPDATED_DATE') IS NULL 
        EXEC sp_rename 'SLS_CUSTOMER_POTENTIAL.updated_date', 'UPDATED_DATE', 'COLUMN';
END
GO

IF OBJECT_ID('SLS_CUSTOMER_POTENTIAL', 'U') IS NOT NULL
BEGIN
    ALTER TABLE SLS_CUSTOMER_POTENTIAL ALTER COLUMN CUSTOMER_GROUP_NAME NVARCHAR(200);
    ALTER TABLE SLS_CUSTOMER_POTENTIAL ALTER COLUMN CUSTOMER_CODE NVARCHAR(50) NOT NULL;
    ALTER TABLE SLS_CUSTOMER_POTENTIAL ALTER COLUMN CUSTOMER_TYPE NVARCHAR(50);
    ALTER TABLE SLS_CUSTOMER_POTENTIAL ALTER COLUMN MANUFACTURER_OEM NVARCHAR(100);
    ALTER TABLE SLS_CUSTOMER_POTENTIAL ALTER COLUMN WTG_MODEL NVARCHAR(100);
    ALTER TABLE SLS_CUSTOMER_POTENTIAL ALTER COLUMN WIND_TURBINE_POWER NVARCHAR(100);
    ALTER TABLE SLS_CUSTOMER_POTENTIAL ALTER COLUMN WIND_FARM_NAME NVARCHAR(100);
    ALTER TABLE SLS_CUSTOMER_POTENTIAL ALTER COLUMN AREA NVARCHAR(200);
    ALTER TABLE SLS_CUSTOMER_POTENTIAL ALTER COLUMN PINCODE NVARCHAR(20);
    ALTER TABLE SLS_CUSTOMER_POTENTIAL ALTER COLUMN STATE NVARCHAR(100);
    ALTER TABLE SLS_CUSTOMER_POTENTIAL ALTER COLUMN COUNTRY NVARCHAR(100);
    ALTER TABLE SLS_CUSTOMER_POTENTIAL ALTER COLUMN DEVELOPER NVARCHAR(200);
    ALTER TABLE SLS_CUSTOMER_POTENTIAL ALTER COLUMN PLANT_MW FLOAT;
    ALTER TABLE SLS_CUSTOMER_POTENTIAL ALTER COLUMN TURBINE_COUNT INT;
    ALTER TABLE SLS_CUSTOMER_POTENTIAL ALTER COLUMN HUB NVARCHAR(100);
    ALTER TABLE SLS_CUSTOMER_POTENTIAL ALTER COLUMN OPERATIONAL_STATUS NVARCHAR(100);
    ALTER TABLE SLS_CUSTOMER_POTENTIAL ALTER COLUMN COMMISSIONING_YEAR NVARCHAR(20);
    ALTER TABLE SLS_CUSTOMER_POTENTIAL ALTER COLUMN COMMISSIONING_MONTH NVARCHAR(20);
    ALTER TABLE SLS_CUSTOMER_POTENTIAL ALTER COLUMN LATITUDE FLOAT;
    ALTER TABLE SLS_CUSTOMER_POTENTIAL ALTER COLUMN LONGITUDE FLOAT;
    ALTER TABLE SLS_CUSTOMER_POTENTIAL ALTER COLUMN STATUS NVARCHAR(20);
    ALTER TABLE SLS_CUSTOMER_POTENTIAL ALTER COLUMN CREATED_BY NVARCHAR(100);
    ALTER TABLE SLS_CUSTOMER_POTENTIAL ALTER COLUMN CREATED_DATE DATETIME;
    ALTER TABLE SLS_CUSTOMER_POTENTIAL ALTER COLUMN UPDATED_BY NVARCHAR(100);
    ALTER TABLE SLS_CUSTOMER_POTENTIAL ALTER COLUMN UPDATED_DATE DATETIME;

    IF COL_LENGTH('SLS_CUSTOMER_POTENTIAL', 'IS_ACTIVE') IS NULL
        ALTER TABLE SLS_CUSTOMER_POTENTIAL ADD IS_ACTIVE BIT DEFAULT 1;
END
GO

IF OBJECT_ID('SLS_CUSTOMER_POTENTIAL', 'U') IS NOT NULL
BEGIN
    DECLARE @pot_pk NVARCHAR(256);
    SELECT TOP 1 @pot_pk = name FROM sys.key_constraints WHERE parent_object_id = OBJECT_ID('SLS_CUSTOMER_POTENTIAL') AND type = 'PK';
    IF @pot_pk IS NOT NULL AND @pot_pk <> 'PK_SLS_CUSTOMER_POTENTIAL'
    BEGIN
        DECLARE @drop_pot_pk NVARCHAR(MAX) = 'ALTER TABLE SLS_CUSTOMER_POTENTIAL DROP CONSTRAINT ' + @pot_pk;
        EXEC(@drop_pot_pk);
    END
    IF NOT EXISTS (SELECT 1 FROM sys.key_constraints WHERE parent_object_id = OBJECT_ID('SLS_CUSTOMER_POTENTIAL') AND name = 'PK_SLS_CUSTOMER_POTENTIAL')
    BEGIN
        ALTER TABLE SLS_CUSTOMER_POTENTIAL ADD CONSTRAINT PK_SLS_CUSTOMER_POTENTIAL PRIMARY KEY (id);
    END
END
GO


-- ==========================================
-- Re-establish Foreign Keys
-- ==========================================
IF OBJECT_ID('SLS_CUSTOMER_ADDRESS', 'U') IS NOT NULL AND OBJECT_ID('SLS_CUSTOMER', 'U') IS NOT NULL
BEGIN
    IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = 'FK_SLS_CUSTOMER_ADDR_CUSTOMER')
    BEGIN
        ALTER TABLE SLS_CUSTOMER_ADDRESS ADD CONSTRAINT FK_SLS_CUSTOMER_ADDR_CUSTOMER FOREIGN KEY (CUSTOMER_ID) REFERENCES SLS_CUSTOMER(id);
    END
END
GO
