-- V006__Sales_Vendor_Module.sql
-- Phase 6: Customer, Supplier & CRM Masters Schema Standardization
-- Renames and normalizes:
-- 1. SM_CUSTOMER_MASTER -> SLS_CUSTOMER
-- 2. SM_CUSTOMER_ADDRESS -> SLS_CUSTOMER_ADDRESS
-- 3. SM_SUPPLIER_MASTER -> VND_VENDOR
-- 4. SM_VENDOR_CUSTOMER_MASTER -> VND_CUSTOMER_MAPPING
-- 5. SM_CUSTOMER_POTENTIAL -> SLS_CUSTOMER_POTENTIAL

-- ==========================================
-- Drop referencing Foreign Key constraints dynamically to avoid cascade/drop errors
-- ==========================================
DECLARE @sql NVARCHAR(MAX) = N'';
SELECT @sql += N'ALTER TABLE ' + QUOTENAME(OBJECT_SCHEMA_NAME(parent_object_id)) + '.' + QUOTENAME(OBJECT_NAME(parent_object_id)) + 
               ' DROP CONSTRAINT ' + QUOTENAME(name) + ';' + CHAR(13) + CHAR(10)
FROM sys.foreign_keys
WHERE referenced_object_id IN (
    OBJECT_ID('SM_CUSTOMER_MASTER'),
    OBJECT_ID('SM_CUSTOMER_ADDRESS'),
    OBJECT_ID('SM_SUPPLIER_MASTER'),
    OBJECT_ID('SM_VENDOR_CUSTOMER_MASTER'),
    OBJECT_ID('SM_CUSTOMER_POTENTIAL')
);
IF @sql <> N''
BEGIN
    EXEC sp_executesql @sql;
END
GO

-- ==========================================
-- 1. SLS_CUSTOMER (from SM_CUSTOMER_MASTER)
-- ==========================================
IF OBJECT_ID('dbo.sp_RenameTableCasingAndPrefix', 'P') IS NOT NULL
BEGIN
    EXEC dbo.sp_RenameTableCasingAndPrefix 'SM_CUSTOMER_MASTER', 'SLS_CUSTOMER';
END
ELSE
BEGIN
    IF OBJECT_ID('SM_CUSTOMER_MASTER', 'U') IS NOT NULL AND OBJECT_ID('SLS_CUSTOMER', 'U') IS NULL
        EXEC sp_rename 'SM_CUSTOMER_MASTER', 'SLS_CUSTOMER';
END
GO

IF OBJECT_ID('SLS_CUSTOMER', 'U') IS NOT NULL
BEGIN
    -- Drop unique constraint/index on CUSTOMER_CODE dynamically BEFORE column renames to avoid filtered index rename errors
    DECLARE @cust_idx NVARCHAR(256);
    DECLARE @cust_is_uq BIT;
    
    SELECT TOP 1 @cust_idx = i.name, @cust_is_uq = i.is_unique_constraint
    FROM sys.indexes i
    JOIN sys.index_columns ic ON i.object_id = ic.object_id AND i.index_id = ic.index_id
    JOIN sys.columns c ON ic.object_id = c.object_id AND ic.column_id = c.column_id
    WHERE i.object_id = OBJECT_ID('SLS_CUSTOMER')
      AND c.name = 'CUSTOMER_CODE'
      AND i.is_primary_key = 0 AND i.is_unique = 1;

    IF @cust_idx IS NOT NULL
    BEGIN
        DECLARE @drop_cust_sql NVARCHAR(MAX);
        IF @cust_is_uq = 1 OR EXISTS (SELECT 1 FROM sys.objects WHERE parent_object_id = OBJECT_ID('SLS_CUSTOMER') AND name = @cust_idx AND type = 'UQ')
            SET @drop_cust_sql = 'ALTER TABLE SLS_CUSTOMER DROP CONSTRAINT ' + QUOTENAME(@cust_idx);
        ELSE
            SET @drop_cust_sql = 'DROP INDEX ' + QUOTENAME(@cust_idx) + ' ON SLS_CUSTOMER';
        EXEC(@drop_cust_sql);
    END
END
GO

IF OBJECT_ID('SLS_CUSTOMER', 'U') IS NOT NULL
BEGIN
    -- Handle duplicate created_at/CREATED_DATE columns
    IF COL_LENGTH('SLS_CUSTOMER', 'created_at') IS NOT NULL AND COL_LENGTH('SLS_CUSTOMER', 'created_date') IS NOT NULL
        ALTER TABLE SLS_CUSTOMER DROP COLUMN created_at;
    IF COL_LENGTH('SLS_CUSTOMER', 'updated_at') IS NOT NULL AND COL_LENGTH('SLS_CUSTOMER', 'updated_date') IS NOT NULL
        ALTER TABLE SLS_CUSTOMER DROP COLUMN updated_at;

    IF COL_LENGTH('SLS_CUSTOMER', 'customer_code') IS NOT NULL EXEC sp_rename 'SLS_CUSTOMER.customer_code', 'CUSTOMER_CODE', 'COLUMN';
    IF COL_LENGTH('SLS_CUSTOMER', 'customer_name') IS NOT NULL EXEC sp_rename 'SLS_CUSTOMER.customer_name', 'CUSTOMER_NAME', 'COLUMN';
    IF COL_LENGTH('SLS_CUSTOMER', 'customer_print_name') IS NOT NULL EXEC sp_rename 'SLS_CUSTOMER.customer_print_name', 'CUSTOMER_PRINT_NAME', 'COLUMN';
    IF COL_LENGTH('SLS_CUSTOMER', 'accounts_ledger') IS NOT NULL EXEC sp_rename 'SLS_CUSTOMER.accounts_ledger', 'ACCOUNTS_LEDGER', 'COLUMN';
    IF COL_LENGTH('SLS_CUSTOMER', 'group_name') IS NOT NULL EXEC sp_rename 'SLS_CUSTOMER.group_name', 'GROUP_NAME', 'COLUMN';
    IF COL_LENGTH('SLS_CUSTOMER', 'invoice_name') IS NOT NULL EXEC sp_rename 'SLS_CUSTOMER.invoice_name', 'INVOICE_NAME', 'COLUMN';
    IF COL_LENGTH('SLS_CUSTOMER', 'short_name') IS NOT NULL EXEC sp_rename 'SLS_CUSTOMER.short_name', 'SHORT_NAME', 'COLUMN';
    IF COL_LENGTH('SLS_CUSTOMER', 'segment') IS NOT NULL EXEC sp_rename 'SLS_CUSTOMER.segment', 'SEGMENT', 'COLUMN';
    IF COL_LENGTH('SLS_CUSTOMER', 'sub_segment') IS NOT NULL EXEC sp_rename 'SLS_CUSTOMER.sub_segment', 'SUB_SEGMENT', 'COLUMN';
    IF COL_LENGTH('SLS_CUSTOMER', 'domain_name') IS NOT NULL EXEC sp_rename 'SLS_CUSTOMER.domain_name', 'DOMAIN_NAME', 'COLUMN';
    IF COL_LENGTH('SLS_CUSTOMER', 'address') IS NOT NULL EXEC sp_rename 'SLS_CUSTOMER.address', 'ADDRESS', 'COLUMN';
    IF COL_LENGTH('SLS_CUSTOMER', 'pincode') IS NOT NULL EXEC sp_rename 'SLS_CUSTOMER.pincode', 'PINCODE', 'COLUMN';
    IF COL_LENGTH('SLS_CUSTOMER', 'city') IS NOT NULL EXEC sp_rename 'SLS_CUSTOMER.city', 'CITY', 'COLUMN';
    IF COL_LENGTH('SLS_CUSTOMER', 'state') IS NOT NULL EXEC sp_rename 'SLS_CUSTOMER.state', 'STATE', 'COLUMN';
    IF COL_LENGTH('SLS_CUSTOMER', 'state_code') IS NOT NULL EXEC sp_rename 'SLS_CUSTOMER.state_code', 'STATE_CODE', 'COLUMN';
    IF COL_LENGTH('SLS_CUSTOMER', 'country') IS NOT NULL EXEC sp_rename 'SLS_CUSTOMER.country', 'COUNTRY', 'COLUMN';
    IF COL_LENGTH('SLS_CUSTOMER', 'prime_customer') IS NOT NULL EXEC sp_rename 'SLS_CUSTOMER.prime_customer', 'PRIME_CUSTOMER', 'COLUMN';
    IF COL_LENGTH('SLS_CUSTOMER', 'pan_no') IS NOT NULL EXEC sp_rename 'SLS_CUSTOMER.pan_no', 'PAN_NO', 'COLUMN';
    IF COL_LENGTH('SLS_CUSTOMER', 'pan_file_info') IS NOT NULL EXEC sp_rename 'SLS_CUSTOMER.pan_file_info', 'PAN_FILE_INFO', 'COLUMN';
    IF COL_LENGTH('SLS_CUSTOMER', 'website') IS NOT NULL EXEC sp_rename 'SLS_CUSTOMER.website', 'WEBSITE', 'COLUMN';
    IF COL_LENGTH('SLS_CUSTOMER', 'register_no') IS NOT NULL EXEC sp_rename 'SLS_CUSTOMER.register_no', 'REGISTER_NO', 'COLUMN';
    IF COL_LENGTH('SLS_CUSTOMER', 'cin_no') IS NOT NULL EXEC sp_rename 'SLS_CUSTOMER.cin_no', 'CIN_NO', 'COLUMN';
    IF COL_LENGTH('SLS_CUSTOMER', 'distance') IS NOT NULL EXEC sp_rename 'SLS_CUSTOMER.distance', 'DISTANCE', 'COLUMN';
    IF COL_LENGTH('SLS_CUSTOMER', 'gstin') IS NOT NULL EXEC sp_rename 'SLS_CUSTOMER.gstin', 'GSTIN', 'COLUMN';
    IF COL_LENGTH('SLS_CUSTOMER', 'vendor_code') IS NOT NULL EXEC sp_rename 'SLS_CUSTOMER.vendor_code', 'VENDOR_CODE', 'COLUMN';
    IF COL_LENGTH('SLS_CUSTOMER', 'iso_number') IS NOT NULL EXEC sp_rename 'SLS_CUSTOMER.iso_number', 'ISO_NUMBER', 'COLUMN';
    IF COL_LENGTH('SLS_CUSTOMER', 'iso_expiry') IS NOT NULL EXEC sp_rename 'SLS_CUSTOMER.iso_expiry', 'ISO_EXPIRY', 'COLUMN';
    IF COL_LENGTH('SLS_CUSTOMER', 'nda_required') IS NOT NULL EXEC sp_rename 'SLS_CUSTOMER.nda_required', 'NDA_REQUIRED', 'COLUMN';
    IF COL_LENGTH('SLS_CUSTOMER', 'dispatch_mode') IS NOT NULL EXEC sp_rename 'SLS_CUSTOMER.dispatch_mode', 'DISPATCH_MODE', 'COLUMN';
    IF COL_LENGTH('SLS_CUSTOMER', 'currency') IS NOT NULL EXEC sp_rename 'SLS_CUSTOMER.currency', 'CURRENCY', 'COLUMN';
    IF COL_LENGTH('SLS_CUSTOMER', 'payment_terms') IS NOT NULL EXEC sp_rename 'SLS_CUSTOMER.payment_terms', 'PAYMENT_TERMS', 'COLUMN';
    IF COL_LENGTH('SLS_CUSTOMER', 'delivery_terms') IS NOT NULL EXEC sp_rename 'SLS_CUSTOMER.delivery_terms', 'DELIVERY_TERMS', 'COLUMN';
    IF COL_LENGTH('SLS_CUSTOMER', 'freight') IS NOT NULL EXEC sp_rename 'SLS_CUSTOMER.freight', 'FREIGHT', 'COLUMN';
    IF COL_LENGTH('SLS_CUSTOMER', 'negotiate_customer') IS NOT NULL EXEC sp_rename 'SLS_CUSTOMER.negotiate_customer', 'NEGOTIATE_CUSTOMER', 'COLUMN';
    IF COL_LENGTH('SLS_CUSTOMER', 'daily_dispatch_mail') IS NOT NULL EXEC sp_rename 'SLS_CUSTOMER.daily_dispatch_mail', 'DAILY_DISPATCH_MAIL', 'COLUMN';
    IF COL_LENGTH('SLS_CUSTOMER', 'file_upload') IS NOT NULL EXEC sp_rename 'SLS_CUSTOMER.file_upload', 'FILE_UPLOAD', 'COLUMN';
    IF COL_LENGTH('SLS_CUSTOMER', 'location') IS NOT NULL EXEC sp_rename 'SLS_CUSTOMER.location', 'LOCATION', 'COLUMN';
    IF COL_LENGTH('SLS_CUSTOMER', 'ld_applicable') IS NOT NULL EXEC sp_rename 'SLS_CUSTOMER.ld_applicable', 'LD_APPLICABLE', 'COLUMN';
    IF COL_LENGTH('SLS_CUSTOMER', 'status') IS NOT NULL EXEC sp_rename 'SLS_CUSTOMER.status', 'STATUS', 'COLUMN';
    IF COL_LENGTH('SLS_CUSTOMER', 'created_by') IS NOT NULL EXEC sp_rename 'SLS_CUSTOMER.created_by', 'CREATED_BY', 'COLUMN';
    IF COL_LENGTH('SLS_CUSTOMER', 'updated_by') IS NOT NULL EXEC sp_rename 'SLS_CUSTOMER.updated_by', 'UPDATED_BY', 'COLUMN';

    IF COL_LENGTH('SLS_CUSTOMER', 'created_at') IS NOT NULL AND COL_LENGTH('SLS_CUSTOMER', 'CREATED_DATE') IS NULL 
        EXEC sp_rename 'SLS_CUSTOMER.created_at', 'CREATED_DATE', 'COLUMN';
    IF COL_LENGTH('SLS_CUSTOMER', 'updated_at') IS NOT NULL AND COL_LENGTH('SLS_CUSTOMER', 'UPDATED_DATE') IS NULL 
        EXEC sp_rename 'SLS_CUSTOMER.updated_at', 'UPDATED_DATE', 'COLUMN';
    IF COL_LENGTH('SLS_CUSTOMER', 'created_date') IS NOT NULL AND COL_LENGTH('SLS_CUSTOMER', 'CREATED_DATE') IS NULL 
        EXEC sp_rename 'SLS_CUSTOMER.created_date', 'CREATED_DATE', 'COLUMN';
    IF COL_LENGTH('SLS_CUSTOMER', 'updated_date') IS NOT NULL AND COL_LENGTH('SLS_CUSTOMER', 'UPDATED_DATE') IS NULL 
        EXEC sp_rename 'SLS_CUSTOMER.updated_date', 'UPDATED_DATE', 'COLUMN';
END
GO

IF OBJECT_ID('SLS_CUSTOMER', 'U') IS NOT NULL
BEGIN
    -- Alter types and lengths to NVARCHAR
    ALTER TABLE SLS_CUSTOMER ALTER COLUMN CUSTOMER_CODE NVARCHAR(50) NOT NULL;
    ALTER TABLE SLS_CUSTOMER ALTER COLUMN CUSTOMER_NAME NVARCHAR(200) NOT NULL;
    ALTER TABLE SLS_CUSTOMER ALTER COLUMN CUSTOMER_PRINT_NAME NVARCHAR(200);
    ALTER TABLE SLS_CUSTOMER ALTER COLUMN ACCOUNTS_LEDGER NVARCHAR(200);
    ALTER TABLE SLS_CUSTOMER ALTER COLUMN GROUP_NAME NVARCHAR(200);
    ALTER TABLE SLS_CUSTOMER ALTER COLUMN INVOICE_NAME NVARCHAR(200);
    ALTER TABLE SLS_CUSTOMER ALTER COLUMN SHORT_NAME NVARCHAR(50);
    ALTER TABLE SLS_CUSTOMER ALTER COLUMN SEGMENT NVARCHAR(100);
    ALTER TABLE SLS_CUSTOMER ALTER COLUMN SUB_SEGMENT NVARCHAR(100);
    ALTER TABLE SLS_CUSTOMER ALTER COLUMN DOMAIN_NAME NVARCHAR(150);
    ALTER TABLE SLS_CUSTOMER ALTER COLUMN ADDRESS NVARCHAR(MAX);
    ALTER TABLE SLS_CUSTOMER ALTER COLUMN PINCODE NVARCHAR(20);
    ALTER TABLE SLS_CUSTOMER ALTER COLUMN CITY NVARCHAR(100);
    ALTER TABLE SLS_CUSTOMER ALTER COLUMN STATE NVARCHAR(100);
    ALTER TABLE SLS_CUSTOMER ALTER COLUMN STATE_CODE NVARCHAR(20);
    ALTER TABLE SLS_CUSTOMER ALTER COLUMN COUNTRY NVARCHAR(100);
    ALTER TABLE SLS_CUSTOMER ALTER COLUMN PRIME_CUSTOMER NVARCHAR(10);
    ALTER TABLE SLS_CUSTOMER ALTER COLUMN PAN_NO NVARCHAR(50);
    ALTER TABLE SLS_CUSTOMER ALTER COLUMN PAN_FILE_INFO NVARCHAR(1000);
    ALTER TABLE SLS_CUSTOMER ALTER COLUMN WEBSITE NVARCHAR(150);
    ALTER TABLE SLS_CUSTOMER ALTER COLUMN REGISTER_NO NVARCHAR(100);
    ALTER TABLE SLS_CUSTOMER ALTER COLUMN CIN_NO NVARCHAR(100);
    ALTER TABLE SLS_CUSTOMER ALTER COLUMN DISTANCE NVARCHAR(50);
    ALTER TABLE SLS_CUSTOMER ALTER COLUMN GSTIN NVARCHAR(50);
    ALTER TABLE SLS_CUSTOMER ALTER COLUMN VENDOR_CODE NVARCHAR(50);
    ALTER TABLE SLS_CUSTOMER ALTER COLUMN ISO_NUMBER NVARCHAR(50);
    ALTER TABLE SLS_CUSTOMER ALTER COLUMN ISO_EXPIRY NVARCHAR(50);
    ALTER TABLE SLS_CUSTOMER ALTER COLUMN NDA_REQUIRED NVARCHAR(10);
    ALTER TABLE SLS_CUSTOMER ALTER COLUMN DISPATCH_MODE NVARCHAR(50);
    ALTER TABLE SLS_CUSTOMER ALTER COLUMN CURRENCY NVARCHAR(20);
    ALTER TABLE SLS_CUSTOMER ALTER COLUMN PAYMENT_TERMS NVARCHAR(100);
    ALTER TABLE SLS_CUSTOMER ALTER COLUMN DELIVERY_TERMS NVARCHAR(100);
    ALTER TABLE SLS_CUSTOMER ALTER COLUMN FREIGHT NVARCHAR(100);
    ALTER TABLE SLS_CUSTOMER ALTER COLUMN NEGOTIATE_CUSTOMER NVARCHAR(10);
    ALTER TABLE SLS_CUSTOMER ALTER COLUMN DAILY_DISPATCH_MAIL NVARCHAR(10);
    ALTER TABLE SLS_CUSTOMER ALTER COLUMN FILE_UPLOAD NVARCHAR(1000);
    ALTER TABLE SLS_CUSTOMER ALTER COLUMN LOCATION NVARCHAR(200);
    ALTER TABLE SLS_CUSTOMER ALTER COLUMN LD_APPLICABLE NVARCHAR(10);
    ALTER TABLE SLS_CUSTOMER ALTER COLUMN STATUS NVARCHAR(20);
    ALTER TABLE SLS_CUSTOMER ALTER COLUMN CREATED_BY NVARCHAR(100);
    ALTER TABLE SLS_CUSTOMER ALTER COLUMN CREATED_DATE DATETIME;
    ALTER TABLE SLS_CUSTOMER ALTER COLUMN UPDATED_BY NVARCHAR(100);
    ALTER TABLE SLS_CUSTOMER ALTER COLUMN UPDATED_DATE DATETIME;

    IF COL_LENGTH('SLS_CUSTOMER', 'IS_ACTIVE') IS NULL
        ALTER TABLE SLS_CUSTOMER ADD IS_ACTIVE BIT DEFAULT 1;
END
GO

-- Recreate unique constraints & indexes for customer_code
IF OBJECT_ID('SLS_CUSTOMER', 'U') IS NOT NULL
BEGIN
    -- Drop old PK
    DECLARE @cust_pk NVARCHAR(256);
    SELECT TOP 1 @cust_pk = name FROM sys.key_constraints WHERE parent_object_id = OBJECT_ID('SLS_CUSTOMER') AND type = 'PK';
    IF @cust_pk IS NOT NULL AND @cust_pk <> 'PK_SLS_CUSTOMER' AND NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE referenced_object_id = OBJECT_ID('SLS_CUSTOMER'))
    BEGIN
        DECLARE @drop_cust_pk NVARCHAR(MAX) = 'ALTER TABLE SLS_CUSTOMER DROP CONSTRAINT ' + @cust_pk;
        EXEC(@drop_cust_pk);
    END
    IF NOT EXISTS (SELECT 1 FROM sys.key_constraints WHERE parent_object_id = OBJECT_ID('SLS_CUSTOMER') AND type = 'PK')
    BEGIN
        ALTER TABLE SLS_CUSTOMER ADD CONSTRAINT PK_SLS_CUSTOMER PRIMARY KEY (id);
    END

    -- Re-create clean unique constraint
    IF NOT EXISTS (SELECT 1 FROM sys.key_constraints WHERE parent_object_id = OBJECT_ID('SLS_CUSTOMER') AND name = 'UQ_SLS_CUSTOMER_CODE')
    BEGIN
        ALTER TABLE SLS_CUSTOMER ADD CONSTRAINT UQ_SLS_CUSTOMER_CODE UNIQUE (CUSTOMER_CODE);
    END
END
GO


-- ==========================================
-- 2. SLS_CUSTOMER_ADDRESS (from SM_CUSTOMER_ADDRESS)
-- ==========================================
IF OBJECT_ID('dbo.sp_RenameTableCasingAndPrefix', 'P') IS NOT NULL
BEGIN
    EXEC dbo.sp_RenameTableCasingAndPrefix 'SM_CUSTOMER_ADDRESS', 'SLS_CUSTOMER_ADDRESS';
END
ELSE
BEGIN
    IF OBJECT_ID('SM_CUSTOMER_ADDRESS', 'U') IS NOT NULL AND OBJECT_ID('SLS_CUSTOMER_ADDRESS', 'U') IS NULL
        EXEC sp_rename 'SM_CUSTOMER_ADDRESS', 'SLS_CUSTOMER_ADDRESS';
END
GO

IF OBJECT_ID('SLS_CUSTOMER_ADDRESS', 'U') IS NOT NULL
BEGIN
    IF COL_LENGTH('SLS_CUSTOMER_ADDRESS', 'customer_id') IS NOT NULL EXEC sp_rename 'SLS_CUSTOMER_ADDRESS.customer_id', 'CUSTOMER_ID', 'COLUMN';
    IF COL_LENGTH('SLS_CUSTOMER_ADDRESS', 'customer_name') IS NOT NULL EXEC sp_rename 'SLS_CUSTOMER_ADDRESS.customer_name', 'CUSTOMER_NAME', 'COLUMN';
    IF COL_LENGTH('SLS_CUSTOMER_ADDRESS', 'invoice_name') IS NOT NULL EXEC sp_rename 'SLS_CUSTOMER_ADDRESS.invoice_name', 'INVOICE_NAME', 'COLUMN';
    IF COL_LENGTH('SLS_CUSTOMER_ADDRESS', 'shipment') IS NOT NULL EXEC sp_rename 'SLS_CUSTOMER_ADDRESS.shipment', 'SHIPMENT', 'COLUMN';
    IF COL_LENGTH('SLS_CUSTOMER_ADDRESS', 'address') IS NOT NULL EXEC sp_rename 'SLS_CUSTOMER_ADDRESS.address', 'ADDRESS', 'COLUMN';
    IF COL_LENGTH('SLS_CUSTOMER_ADDRESS', 'city') IS NOT NULL EXEC sp_rename 'SLS_CUSTOMER_ADDRESS.city', 'CITY', 'COLUMN';
    IF COL_LENGTH('SLS_CUSTOMER_ADDRESS', 'district') IS NOT NULL EXEC sp_rename 'SLS_CUSTOMER_ADDRESS.district', 'DISTRICT', 'COLUMN';
    IF COL_LENGTH('SLS_CUSTOMER_ADDRESS', 'state') IS NOT NULL EXEC sp_rename 'SLS_CUSTOMER_ADDRESS.state', 'STATE', 'COLUMN';
    IF COL_LENGTH('SLS_CUSTOMER_ADDRESS', 'country') IS NOT NULL EXEC sp_rename 'SLS_CUSTOMER_ADDRESS.country', 'COUNTRY', 'COLUMN';
    IF COL_LENGTH('SLS_CUSTOMER_ADDRESS', 'pincode') IS NOT NULL EXEC sp_rename 'SLS_CUSTOMER_ADDRESS.pincode', 'PINCODE', 'COLUMN';
    IF COL_LENGTH('SLS_CUSTOMER_ADDRESS', 'distance') IS NOT NULL EXEC sp_rename 'SLS_CUSTOMER_ADDRESS.distance', 'DISTANCE', 'COLUMN';
    IF COL_LENGTH('SLS_CUSTOMER_ADDRESS', 'contact_name') IS NOT NULL EXEC sp_rename 'SLS_CUSTOMER_ADDRESS.contact_name', 'CONTACT_NAME', 'COLUMN';
    IF COL_LENGTH('SLS_CUSTOMER_ADDRESS', 'contact_no') IS NOT NULL EXEC sp_rename 'SLS_CUSTOMER_ADDRESS.contact_no', 'CONTACT_NO', 'COLUMN';
    IF COL_LENGTH('SLS_CUSTOMER_ADDRESS', 'status') IS NOT NULL EXEC sp_rename 'SLS_CUSTOMER_ADDRESS.status', 'STATUS', 'COLUMN';
    IF COL_LENGTH('SLS_CUSTOMER_ADDRESS', 'created_by') IS NOT NULL EXEC sp_rename 'SLS_CUSTOMER_ADDRESS.created_by', 'CREATED_BY', 'COLUMN';
    IF COL_LENGTH('SLS_CUSTOMER_ADDRESS', 'created_date') IS NOT NULL EXEC sp_rename 'SLS_CUSTOMER_ADDRESS.created_date', 'CREATED_DATE', 'COLUMN';
    IF COL_LENGTH('SLS_CUSTOMER_ADDRESS', 'updated_by') IS NOT NULL EXEC sp_rename 'SLS_CUSTOMER_ADDRESS.updated_by', 'UPDATED_BY', 'COLUMN';
    IF COL_LENGTH('SLS_CUSTOMER_ADDRESS', 'updated_date') IS NOT NULL EXEC sp_rename 'SLS_CUSTOMER_ADDRESS.updated_date', 'UPDATED_DATE', 'COLUMN';
END
GO

IF OBJECT_ID('SLS_CUSTOMER_ADDRESS', 'U') IS NOT NULL
BEGIN
    ALTER TABLE SLS_CUSTOMER_ADDRESS ALTER COLUMN CUSTOMER_ID BIGINT NOT NULL;
    ALTER TABLE SLS_CUSTOMER_ADDRESS ALTER COLUMN CUSTOMER_NAME NVARCHAR(200);
    ALTER TABLE SLS_CUSTOMER_ADDRESS ALTER COLUMN INVOICE_NAME NVARCHAR(200);
    ALTER TABLE SLS_CUSTOMER_ADDRESS ALTER COLUMN SHIPMENT NVARCHAR(100);
    ALTER TABLE SLS_CUSTOMER_ADDRESS ALTER COLUMN ADDRESS NVARCHAR(MAX);
    ALTER TABLE SLS_CUSTOMER_ADDRESS ALTER COLUMN CITY NVARCHAR(100);
    ALTER TABLE SLS_CUSTOMER_ADDRESS ALTER COLUMN DISTRICT NVARCHAR(100);
    ALTER TABLE SLS_CUSTOMER_ADDRESS ALTER COLUMN STATE NVARCHAR(100);
    ALTER TABLE SLS_CUSTOMER_ADDRESS ALTER COLUMN COUNTRY NVARCHAR(100);
    ALTER TABLE SLS_CUSTOMER_ADDRESS ALTER COLUMN PINCODE NVARCHAR(20);
    ALTER TABLE SLS_CUSTOMER_ADDRESS ALTER COLUMN DISTANCE FLOAT;
    ALTER TABLE SLS_CUSTOMER_ADDRESS ALTER COLUMN CONTACT_NAME NVARCHAR(200);
    ALTER TABLE SLS_CUSTOMER_ADDRESS ALTER COLUMN CONTACT_NO NVARCHAR(50);
    ALTER TABLE SLS_CUSTOMER_ADDRESS ALTER COLUMN STATUS NVARCHAR(20);
    ALTER TABLE SLS_CUSTOMER_ADDRESS ALTER COLUMN CREATED_BY NVARCHAR(100);
    ALTER TABLE SLS_CUSTOMER_ADDRESS ALTER COLUMN CREATED_DATE DATETIME;
    ALTER TABLE SLS_CUSTOMER_ADDRESS ALTER COLUMN UPDATED_BY NVARCHAR(100);
    ALTER TABLE SLS_CUSTOMER_ADDRESS ALTER COLUMN UPDATED_DATE DATETIME;

    IF COL_LENGTH('SLS_CUSTOMER_ADDRESS', 'IS_ACTIVE') IS NULL
        ALTER TABLE SLS_CUSTOMER_ADDRESS ADD IS_ACTIVE BIT DEFAULT 1;
END
GO

IF OBJECT_ID('SLS_CUSTOMER_ADDRESS', 'U') IS NOT NULL
BEGIN
    DECLARE @addr_pk NVARCHAR(256);
    SELECT TOP 1 @addr_pk = name FROM sys.key_constraints WHERE parent_object_id = OBJECT_ID('SLS_CUSTOMER_ADDRESS') AND type = 'PK';
    IF @addr_pk IS NOT NULL AND @addr_pk <> 'PK_SLS_CUSTOMER_ADDR'
    BEGIN
        DECLARE @drop_addr_pk NVARCHAR(MAX) = 'ALTER TABLE SLS_CUSTOMER_ADDRESS DROP CONSTRAINT ' + @addr_pk;
        EXEC(@drop_addr_pk);
    END
    IF NOT EXISTS (SELECT 1 FROM sys.key_constraints WHERE parent_object_id = OBJECT_ID('SLS_CUSTOMER_ADDRESS') AND name = 'PK_SLS_CUSTOMER_ADDR')
    BEGIN
        ALTER TABLE SLS_CUSTOMER_ADDRESS ADD CONSTRAINT PK_SLS_CUSTOMER_ADDR PRIMARY KEY (id);
    END
END
GO


-- ==========================================
-- 3. VND_VENDOR (from SM_SUPPLIER_MASTER)
-- ==========================================
IF OBJECT_ID('dbo.sp_RenameTableCasingAndPrefix', 'P') IS NOT NULL
BEGIN
    EXEC dbo.sp_RenameTableCasingAndPrefix 'SM_SUPPLIER_MASTER', 'VND_VENDOR';
END
ELSE
BEGIN
    IF OBJECT_ID('SM_SUPPLIER_MASTER', 'U') IS NOT NULL AND OBJECT_ID('VND_VENDOR', 'U') IS NULL
        EXEC sp_rename 'SM_SUPPLIER_MASTER', 'VND_VENDOR';
END
GO

IF OBJECT_ID('VND_VENDOR', 'U') IS NOT NULL
BEGIN
    -- Drop unique constraint/index on SUPPLIER_CODE dynamically BEFORE column renames to avoid filtered index rename errors
    DECLARE @vend_idx NVARCHAR(256);
    DECLARE @vend_is_uq BIT;
    
    SELECT TOP 1 @vend_idx = i.name, @vend_is_uq = i.is_unique_constraint
    FROM sys.indexes i
    JOIN sys.index_columns ic ON i.object_id = ic.object_id AND i.index_id = ic.index_id
    JOIN sys.columns c ON ic.object_id = c.object_id AND ic.column_id = c.column_id
    WHERE i.object_id = OBJECT_ID('VND_VENDOR')
      AND c.name = 'SUPPLIER_CODE'
      AND i.is_primary_key = 0 AND i.is_unique = 1;

    IF @vend_idx IS NOT NULL
    BEGIN
        DECLARE @drop_vend_sql NVARCHAR(MAX);
        IF @vend_is_uq = 1 OR EXISTS (SELECT 1 FROM sys.objects WHERE parent_object_id = OBJECT_ID('VND_VENDOR') AND name = @vend_idx AND type = 'UQ')
            SET @drop_vend_sql = 'ALTER TABLE VND_VENDOR DROP CONSTRAINT ' + QUOTENAME(@vend_idx);
        ELSE
            SET @drop_vend_sql = 'DROP INDEX ' + QUOTENAME(@vend_idx) + ' ON VND_VENDOR';
        EXEC(@drop_vend_sql);
    END
END
GO

IF OBJECT_ID('VND_VENDOR', 'U') IS NOT NULL
BEGIN
    -- Handle duplicate created_at/CREATED_DATE columns
    IF COL_LENGTH('VND_VENDOR', 'created_at') IS NOT NULL AND COL_LENGTH('VND_VENDOR', 'created_date') IS NOT NULL
        ALTER TABLE VND_VENDOR DROP COLUMN created_at;
    IF COL_LENGTH('VND_VENDOR', 'updated_at') IS NOT NULL AND COL_LENGTH('VND_VENDOR', 'updated_date') IS NOT NULL
        ALTER TABLE VND_VENDOR DROP COLUMN updated_at;

    IF COL_LENGTH('VND_VENDOR', 'SUPPLIER_CODE') IS NOT NULL EXEC sp_rename 'VND_VENDOR.SUPPLIER_CODE', 'SUPPLIER_CODE', 'COLUMN';
    IF COL_LENGTH('VND_VENDOR', 'GST_NO') IS NOT NULL EXEC sp_rename 'VND_VENDOR.GST_NO', 'GST_NO', 'COLUMN';
    IF COL_LENGTH('VND_VENDOR', 'SUPPLIER_NAME') IS NOT NULL EXEC sp_rename 'VND_VENDOR.SUPPLIER_NAME', 'SUPPLIER_NAME', 'COLUMN';
    IF COL_LENGTH('VND_VENDOR', 'LEDGER_NAME') IS NOT NULL EXEC sp_rename 'VND_VENDOR.LEDGER_NAME', 'LEDGER_NAME', 'COLUMN';
    IF COL_LENGTH('VND_VENDOR', 'SHORT_NAME') IS NOT NULL EXEC sp_rename 'VND_VENDOR.SHORT_NAME', 'SHORT_NAME', 'COLUMN';
    IF COL_LENGTH('VND_VENDOR', 'SUPPLIER_PRINT_NAME') IS NOT NULL EXEC sp_rename 'VND_VENDOR.SUPPLIER_PRINT_NAME', 'SUPPLIER_PRINT_NAME', 'COLUMN';
    IF COL_LENGTH('VND_VENDOR', 'ADDRESS') IS NOT NULL EXEC sp_rename 'VND_VENDOR.ADDRESS', 'ADDRESS', 'COLUMN';
    IF COL_LENGTH('VND_VENDOR', 'CITY') IS NOT NULL EXEC sp_rename 'VND_VENDOR.CITY', 'CITY', 'COLUMN';
    IF COL_LENGTH('VND_VENDOR', 'STATE') IS NOT NULL EXEC sp_rename 'VND_VENDOR.STATE', 'STATE', 'COLUMN';
    IF COL_LENGTH('VND_VENDOR', 'COUNTRY') IS NOT NULL EXEC sp_rename 'VND_VENDOR.COUNTRY', 'COUNTRY', 'COLUMN';
    IF COL_LENGTH('VND_VENDOR', 'PINCODE') IS NOT NULL EXEC sp_rename 'VND_VENDOR.PINCODE', 'PINCODE', 'COLUMN';
    IF COL_LENGTH('VND_VENDOR', 'MOBILE_NO') IS NOT NULL EXEC sp_rename 'VND_VENDOR.MOBILE_NO', 'MOBILE_NO', 'COLUMN';
    IF COL_LENGTH('VND_VENDOR', 'CONTACT_PERSON') IS NOT NULL EXEC sp_rename 'VND_VENDOR.CONTACT_PERSON', 'CONTACT_PERSON', 'COLUMN';
    IF COL_LENGTH('VND_VENDOR', 'EMAIL_ID') IS NOT NULL EXEC sp_rename 'VND_VENDOR.EMAIL_ID', 'EMAIL_ID', 'COLUMN';
    IF COL_LENGTH('VND_VENDOR', 'WEBSITE') IS NOT NULL EXEC sp_rename 'VND_VENDOR.WEBSITE', 'WEBSITE', 'COLUMN';
    IF COL_LENGTH('VND_VENDOR', 'PAN_NO') IS NOT NULL EXEC sp_rename 'VND_VENDOR.PAN_NO', 'PAN_NO', 'COLUMN';
    IF COL_LENGTH('VND_VENDOR', 'pan_file_info') IS NOT NULL EXEC sp_rename 'VND_VENDOR.pan_file_info', 'PAN_FILE_INFO', 'COLUMN';
    IF COL_LENGTH('VND_VENDOR', 'MSME_NO') IS NOT NULL EXEC sp_rename 'VND_VENDOR.MSME_NO', 'MSME_NO', 'COLUMN';
    IF COL_LENGTH('VND_VENDOR', 'msme_file_info') IS NOT NULL EXEC sp_rename 'VND_VENDOR.msme_file_info', 'MSME_FILE_INFO', 'COLUMN';
    IF COL_LENGTH('VND_VENDOR', 'ISO_NO') IS NOT NULL EXEC sp_rename 'VND_VENDOR.ISO_NO', 'ISO_NO', 'COLUMN';
    IF COL_LENGTH('VND_VENDOR', 'iso_file_info') IS NOT NULL EXEC sp_rename 'VND_VENDOR.iso_file_info', 'ISO_FILE_INFO', 'COLUMN';
    IF COL_LENGTH('VND_VENDOR', 'ISO_EXPIRY_DATE') IS NOT NULL EXEC sp_rename 'VND_VENDOR.ISO_EXPIRY_DATE', 'ISO_EXPIRY_DATE', 'COLUMN';
    IF COL_LENGTH('VND_VENDOR', 'APPROVED_SUPPLIER') IS NOT NULL EXEC sp_rename 'VND_VENDOR.APPROVED_SUPPLIER', 'APPROVED_SUPPLIER', 'COLUMN';
    IF COL_LENGTH('VND_VENDOR', 'NDA_REQUIRED') IS NOT NULL EXEC sp_rename 'VND_VENDOR.NDA_REQUIRED', 'NDA_REQUIRED', 'COLUMN';
    IF COL_LENGTH('VND_VENDOR', 'DELIVERY_TERMS') IS NOT NULL EXEC sp_rename 'VND_VENDOR.DELIVERY_TERMS', 'DELIVERY_TERMS', 'COLUMN';
    IF COL_LENGTH('VND_VENDOR', 'TYPE_OF_SERVICE') IS NOT NULL EXEC sp_rename 'VND_VENDOR.TYPE_OF_SERVICE', 'TYPE_OF_SERVICE', 'COLUMN';
    IF COL_LENGTH('VND_VENDOR', 'PAYMENT_TERMS') IS NOT NULL EXEC sp_rename 'VND_VENDOR.PAYMENT_TERMS', 'PAYMENT_TERMS', 'COLUMN';
    IF COL_LENGTH('VND_VENDOR', 'PRIME_SUPPLIER') IS NOT NULL EXEC sp_rename 'VND_VENDOR.PRIME_SUPPLIER', 'PRIME_SUPPLIER', 'COLUMN';
    IF COL_LENGTH('VND_VENDOR', 'FREIGHT_REQUIRED') IS NOT NULL EXEC sp_rename 'VND_VENDOR.FREIGHT_REQUIRED', 'FREIGHT_REQUIRED', 'COLUMN';
    IF COL_LENGTH('VND_VENDOR', 'CURRENCY') IS NOT NULL EXEC sp_rename 'VND_VENDOR.CURRENCY', 'CURRENCY', 'COLUMN';
    IF COL_LENGTH('VND_VENDOR', 'DUE_DAYS') IS NOT NULL EXEC sp_rename 'VND_VENDOR.DUE_DAYS', 'DUE_DAYS', 'COLUMN';
    IF COL_LENGTH('VND_VENDOR', 'IS_AUDITOR_CONSULTANT') IS NOT NULL EXEC sp_rename 'VND_VENDOR.IS_AUDITOR_CONSULTANT', 'IS_AUDITOR_CONSULTANT', 'COLUMN';
    IF COL_LENGTH('VND_VENDOR', 'ACCOUNT_NO') IS NOT NULL EXEC sp_rename 'VND_VENDOR.ACCOUNT_NO', 'ACCOUNT_NO', 'COLUMN';
    IF COL_LENGTH('VND_VENDOR', 'ACCOUNT_NAME') IS NOT NULL EXEC sp_rename 'VND_VENDOR.ACCOUNT_NAME', 'ACCOUNT_NAME', 'COLUMN';
    IF COL_LENGTH('VND_VENDOR', 'BANK_NAME') IS NOT NULL EXEC sp_rename 'VND_VENDOR.BANK_NAME', 'BANK_NAME', 'COLUMN';
    IF COL_LENGTH('VND_VENDOR', 'BRANCH_NAME') IS NOT NULL EXEC sp_rename 'VND_VENDOR.BRANCH_NAME', 'BRANCH_NAME', 'COLUMN';
    IF COL_LENGTH('VND_VENDOR', 'IFSC_CODE') IS NOT NULL EXEC sp_rename 'VND_VENDOR.IFSC_CODE', 'IFSC_CODE', 'COLUMN';
    IF COL_LENGTH('VND_VENDOR', 'SWIFT_CODE') IS NOT NULL EXEC sp_rename 'VND_VENDOR.SWIFT_CODE', 'SWIFT_CODE', 'COLUMN';
    IF COL_LENGTH('VND_VENDOR', 'ACCOUNT_TYPE') IS NOT NULL EXEC sp_rename 'VND_VENDOR.ACCOUNT_TYPE', 'ACCOUNT_TYPE', 'COLUMN';
    IF COL_LENGTH('VND_VENDOR', 'STATUS') IS NOT NULL EXEC sp_rename 'VND_VENDOR.STATUS', 'STATUS', 'COLUMN';
    IF COL_LENGTH('VND_VENDOR', 'UPLOAD_FILES') IS NOT NULL EXEC sp_rename 'VND_VENDOR.UPLOAD_FILES', 'UPLOAD_FILES', 'COLUMN';
    IF COL_LENGTH('VND_VENDOR', 'created_by') IS NOT NULL EXEC sp_rename 'VND_VENDOR.created_by', 'CREATED_BY', 'COLUMN';
    IF COL_LENGTH('VND_VENDOR', 'updated_by') IS NOT NULL EXEC sp_rename 'VND_VENDOR.updated_by', 'UPDATED_BY', 'COLUMN';

    IF COL_LENGTH('VND_VENDOR', 'created_at') IS NOT NULL AND COL_LENGTH('VND_VENDOR', 'CREATED_DATE') IS NULL 
        EXEC sp_rename 'VND_VENDOR.created_at', 'CREATED_DATE', 'COLUMN';
    IF COL_LENGTH('VND_VENDOR', 'updated_at') IS NOT NULL AND COL_LENGTH('VND_VENDOR', 'UPDATED_DATE') IS NULL 
        EXEC sp_rename 'VND_VENDOR.updated_at', 'UPDATED_DATE', 'COLUMN';
    IF COL_LENGTH('VND_VENDOR', 'created_date') IS NOT NULL AND COL_LENGTH('VND_VENDOR', 'CREATED_DATE') IS NULL 
        EXEC sp_rename 'VND_VENDOR.created_date', 'CREATED_DATE', 'COLUMN';
    IF COL_LENGTH('VND_VENDOR', 'updated_date') IS NOT NULL AND COL_LENGTH('VND_VENDOR', 'UPDATED_DATE') IS NULL 
        EXEC sp_rename 'VND_VENDOR.updated_date', 'UPDATED_DATE', 'COLUMN';
END
GO

IF OBJECT_ID('VND_VENDOR', 'U') IS NOT NULL
BEGIN
    -- Drop unique constraint/index on SUPPLIER_CODE dynamically to allow type alteration
    DECLARE @vend_idx NVARCHAR(256);
    DECLARE @vend_is_uq BIT;
    
    SELECT TOP 1 @vend_idx = i.name, @vend_is_uq = i.is_unique_constraint
    FROM sys.indexes i
    JOIN sys.index_columns ic ON i.object_id = ic.object_id AND i.index_id = ic.index_id
    JOIN sys.columns c ON ic.object_id = c.object_id AND ic.column_id = c.column_id
    WHERE i.object_id = OBJECT_ID('VND_VENDOR')
      AND c.name = 'SUPPLIER_CODE'
      AND i.is_primary_key = 0 AND i.is_unique = 1;

    IF @vend_idx IS NOT NULL
    BEGIN
        DECLARE @drop_vend_sql NVARCHAR(MAX);
        IF @vend_is_uq = 1 OR EXISTS (SELECT 1 FROM sys.objects WHERE parent_object_id = OBJECT_ID('VND_VENDOR') AND name = @vend_idx AND type = 'UQ')
            SET @drop_vend_sql = 'ALTER TABLE VND_VENDOR DROP CONSTRAINT ' + QUOTENAME(@vend_idx);
        ELSE
            SET @drop_vend_sql = 'DROP INDEX ' + QUOTENAME(@vend_idx) + ' ON VND_VENDOR';
        EXEC(@drop_vend_sql);
    END
END
GO

IF OBJECT_ID('VND_VENDOR', 'U') IS NOT NULL
BEGIN
    -- Alter types and lengths to NVARCHAR
    ALTER TABLE VND_VENDOR ALTER COLUMN SUPPLIER_CODE NVARCHAR(50) NOT NULL;
    ALTER TABLE VND_VENDOR ALTER COLUMN GST_NO NVARCHAR(50);
    ALTER TABLE VND_VENDOR ALTER COLUMN SUPPLIER_NAME NVARCHAR(200);
    ALTER TABLE VND_VENDOR ALTER COLUMN LEDGER_NAME NVARCHAR(200);
    ALTER TABLE VND_VENDOR ALTER COLUMN SHORT_NAME NVARCHAR(50);
    ALTER TABLE VND_VENDOR ALTER COLUMN SUPPLIER_PRINT_NAME NVARCHAR(200);
    ALTER TABLE VND_VENDOR ALTER COLUMN ADDRESS NVARCHAR(500);
    ALTER TABLE VND_VENDOR ALTER COLUMN CITY NVARCHAR(100);
    ALTER TABLE VND_VENDOR ALTER COLUMN STATE NVARCHAR(100);
    ALTER TABLE VND_VENDOR ALTER COLUMN COUNTRY NVARCHAR(100);
    ALTER TABLE VND_VENDOR ALTER COLUMN PINCODE NVARCHAR(20);
    ALTER TABLE VND_VENDOR ALTER COLUMN MOBILE_NO NVARCHAR(20);
    ALTER TABLE VND_VENDOR ALTER COLUMN CONTACT_PERSON NVARCHAR(100);
    ALTER TABLE VND_VENDOR ALTER COLUMN EMAIL_ID NVARCHAR(100);
    ALTER TABLE VND_VENDOR ALTER COLUMN WEBSITE NVARCHAR(100);
    ALTER TABLE VND_VENDOR ALTER COLUMN PAN_NO NVARCHAR(50);
    ALTER TABLE VND_VENDOR ALTER COLUMN PAN_FILE_INFO NVARCHAR(1000);
    ALTER TABLE VND_VENDOR ALTER COLUMN MSME_NO NVARCHAR(50);
    ALTER TABLE VND_VENDOR ALTER COLUMN MSME_FILE_INFO NVARCHAR(1000);
    ALTER TABLE VND_VENDOR ALTER COLUMN ISO_NO NVARCHAR(50);
    ALTER TABLE VND_VENDOR ALTER COLUMN ISO_FILE_INFO NVARCHAR(1000);
    ALTER TABLE VND_VENDOR ALTER COLUMN ISO_EXPIRY_DATE NVARCHAR(50);
    ALTER TABLE VND_VENDOR ALTER COLUMN APPROVED_SUPPLIER NVARCHAR(10);
    ALTER TABLE VND_VENDOR ALTER COLUMN NDA_REQUIRED NVARCHAR(10);
    ALTER TABLE VND_VENDOR ALTER COLUMN DELIVERY_TERMS NVARCHAR(100);
    ALTER TABLE VND_VENDOR ALTER COLUMN TYPE_OF_SERVICE NVARCHAR(100);
    ALTER TABLE VND_VENDOR ALTER COLUMN PAYMENT_TERMS NVARCHAR(100);
    ALTER TABLE VND_VENDOR ALTER COLUMN PRIME_SUPPLIER NVARCHAR(10);
    ALTER TABLE VND_VENDOR ALTER COLUMN FREIGHT_REQUIRED NVARCHAR(10);
    ALTER TABLE VND_VENDOR ALTER COLUMN CURRENCY NVARCHAR(20);
    ALTER TABLE VND_VENDOR ALTER COLUMN DUE_DAYS NVARCHAR(20);
    ALTER TABLE VND_VENDOR ALTER COLUMN IS_AUDITOR_CONSULTANT NVARCHAR(10);
    ALTER TABLE VND_VENDOR ALTER COLUMN ACCOUNT_NO NVARCHAR(50);
    ALTER TABLE VND_VENDOR ALTER COLUMN ACCOUNT_NAME NVARCHAR(100);
    ALTER TABLE VND_VENDOR ALTER COLUMN BANK_NAME NVARCHAR(100);
    ALTER TABLE VND_VENDOR ALTER COLUMN BRANCH_NAME NVARCHAR(100);
    ALTER TABLE VND_VENDOR ALTER COLUMN IFSC_CODE NVARCHAR(50);
    ALTER TABLE VND_VENDOR ALTER COLUMN SWIFT_CODE NVARCHAR(50);
    ALTER TABLE VND_VENDOR ALTER COLUMN ACCOUNT_TYPE NVARCHAR(50);
    ALTER TABLE VND_VENDOR ALTER COLUMN STATUS NVARCHAR(20);
    ALTER TABLE VND_VENDOR ALTER COLUMN UPLOAD_FILES NVARCHAR(1000);
    ALTER TABLE VND_VENDOR ALTER COLUMN CREATED_BY NVARCHAR(100);
    ALTER TABLE VND_VENDOR ALTER COLUMN CREATED_DATE DATETIME;
    ALTER TABLE VND_VENDOR ALTER COLUMN UPDATED_BY NVARCHAR(100);
    ALTER TABLE VND_VENDOR ALTER COLUMN UPDATED_DATE DATETIME;

    IF COL_LENGTH('VND_VENDOR', 'IS_ACTIVE') IS NULL
        ALTER TABLE VND_VENDOR ADD IS_ACTIVE BIT DEFAULT 1;
END
GO

IF OBJECT_ID('VND_VENDOR', 'U') IS NOT NULL
BEGIN
    -- PK
    DECLARE @vend_pk NVARCHAR(256);
    SELECT TOP 1 @vend_pk = name FROM sys.key_constraints WHERE parent_object_id = OBJECT_ID('VND_VENDOR') AND type = 'PK';
    IF @vend_pk IS NOT NULL AND @vend_pk <> 'PK_VND_VENDOR' AND NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE referenced_object_id = OBJECT_ID('VND_VENDOR'))
    BEGIN
        DECLARE @drop_vend_pk NVARCHAR(MAX) = 'ALTER TABLE VND_VENDOR DROP CONSTRAINT ' + @vend_pk;
        EXEC(@drop_vend_pk);
    END
    IF NOT EXISTS (SELECT 1 FROM sys.key_constraints WHERE parent_object_id = OBJECT_ID('VND_VENDOR') AND type = 'PK')
    BEGIN
        ALTER TABLE VND_VENDOR ADD CONSTRAINT PK_VND_VENDOR PRIMARY KEY (id);
    END

    -- Re-create unique constraint
    IF NOT EXISTS (SELECT 1 FROM sys.key_constraints WHERE parent_object_id = OBJECT_ID('VND_VENDOR') AND name = 'UQ_VND_VENDOR_CODE')
    BEGIN
        ALTER TABLE VND_VENDOR ADD CONSTRAINT UQ_VND_VENDOR_CODE UNIQUE (SUPPLIER_CODE);
    END
END
GO


-- ==========================================
-- 4. VND_CUSTOMER_MAPPING (from SM_VENDOR_CUSTOMER_MASTER)
-- ==========================================
IF OBJECT_ID('dbo.sp_RenameTableCasingAndPrefix', 'P') IS NOT NULL
BEGIN
    EXEC dbo.sp_RenameTableCasingAndPrefix 'SM_VENDOR_CUSTOMER_MASTER', 'VND_CUSTOMER_MAPPING';
END
ELSE
BEGIN
    IF OBJECT_ID('SM_VENDOR_CUSTOMER_MASTER', 'U') IS NOT NULL AND OBJECT_ID('VND_CUSTOMER_MAPPING', 'U') IS NULL
        EXEC sp_rename 'SM_VENDOR_CUSTOMER_MASTER', 'VND_CUSTOMER_MAPPING';
END
GO

IF OBJECT_ID('VND_CUSTOMER_MAPPING', 'U') IS NOT NULL
BEGIN
    -- Handle duplicate created_at/CREATED_DATE columns
    IF COL_LENGTH('VND_CUSTOMER_MAPPING', 'created_at') IS NOT NULL AND COL_LENGTH('VND_CUSTOMER_MAPPING', 'created_date') IS NOT NULL
        ALTER TABLE VND_CUSTOMER_MAPPING DROP COLUMN created_at;
    IF COL_LENGTH('VND_CUSTOMER_MAPPING', 'updated_at') IS NOT NULL AND COL_LENGTH('VND_CUSTOMER_MAPPING', 'updated_date') IS NOT NULL
        ALTER TABLE VND_CUSTOMER_MAPPING DROP COLUMN updated_at;

    IF COL_LENGTH('VND_CUSTOMER_MAPPING', 'record_type') IS NOT NULL EXEC sp_rename 'VND_CUSTOMER_MAPPING.record_type', 'RECORD_TYPE', 'COLUMN';
    IF COL_LENGTH('VND_CUSTOMER_MAPPING', 'code') IS NOT NULL EXEC sp_rename 'VND_CUSTOMER_MAPPING.code', 'CODE', 'COLUMN';
    IF COL_LENGTH('VND_CUSTOMER_MAPPING', 'name') IS NOT NULL EXEC sp_rename 'VND_CUSTOMER_MAPPING.name', 'NAME', 'COLUMN';
    IF COL_LENGTH('VND_CUSTOMER_MAPPING', 'print_name') IS NOT NULL EXEC sp_rename 'VND_CUSTOMER_MAPPING.print_name', 'PRINT_NAME', 'COLUMN';
    IF COL_LENGTH('VND_CUSTOMER_MAPPING', 'short_name') IS NOT NULL EXEC sp_rename 'VND_CUSTOMER_MAPPING.short_name', 'SHORT_NAME', 'COLUMN';
    IF COL_LENGTH('VND_CUSTOMER_MAPPING', 'ledger_name') IS NOT NULL EXEC sp_rename 'VND_CUSTOMER_MAPPING.ledger_name', 'LEDGER_NAME', 'COLUMN';
    IF COL_LENGTH('VND_CUSTOMER_MAPPING', 'invoice_name') IS NOT NULL EXEC sp_rename 'VND_CUSTOMER_MAPPING.invoice_name', 'INVOICE_NAME', 'COLUMN';
    IF COL_LENGTH('VND_CUSTOMER_MAPPING', 'group_name') IS NOT NULL EXEC sp_rename 'VND_CUSTOMER_MAPPING.group_name', 'GROUP_NAME', 'COLUMN';
    IF COL_LENGTH('VND_CUSTOMER_MAPPING', 'address') IS NOT NULL EXEC sp_rename 'VND_CUSTOMER_MAPPING.address', 'ADDRESS', 'COLUMN';
    IF COL_LENGTH('VND_CUSTOMER_MAPPING', 'pincode') IS NOT NULL EXEC sp_rename 'VND_CUSTOMER_MAPPING.pincode', 'PINCODE', 'COLUMN';
    IF COL_LENGTH('VND_CUSTOMER_MAPPING', 'city') IS NOT NULL EXEC sp_rename 'VND_CUSTOMER_MAPPING.city', 'CITY', 'COLUMN';
    IF COL_LENGTH('VND_CUSTOMER_MAPPING', 'state') IS NOT NULL EXEC sp_rename 'VND_CUSTOMER_MAPPING.state', 'STATE', 'COLUMN';
    IF COL_LENGTH('VND_CUSTOMER_MAPPING', 'state_code') IS NOT NULL EXEC sp_rename 'VND_CUSTOMER_MAPPING.state_code', 'STATE_CODE', 'COLUMN';
    IF COL_LENGTH('VND_CUSTOMER_MAPPING', 'country') IS NOT NULL EXEC sp_rename 'VND_CUSTOMER_MAPPING.country', 'COUNTRY', 'COLUMN';
    IF COL_LENGTH('VND_CUSTOMER_MAPPING', 'location') IS NOT NULL EXEC sp_rename 'VND_CUSTOMER_MAPPING.location', 'LOCATION', 'COLUMN';
    IF COL_LENGTH('VND_CUSTOMER_MAPPING', 'distance') IS NOT NULL EXEC sp_rename 'VND_CUSTOMER_MAPPING.distance', 'DISTANCE', 'COLUMN';
    IF COL_LENGTH('VND_CUSTOMER_MAPPING', 'contact_person') IS NOT NULL EXEC sp_rename 'VND_CUSTOMER_MAPPING.contact_person', 'CONTACT_PERSON', 'COLUMN';
    IF COL_LENGTH('VND_CUSTOMER_MAPPING', 'mobile_no') IS NOT NULL EXEC sp_rename 'VND_CUSTOMER_MAPPING.mobile_no', 'MOBILE_NO', 'COLUMN';
    IF COL_LENGTH('VND_CUSTOMER_MAPPING', 'email_id') IS NOT NULL EXEC sp_rename 'VND_CUSTOMER_MAPPING.email_id', 'EMAIL_ID', 'COLUMN';
    IF COL_LENGTH('VND_CUSTOMER_MAPPING', 'website') IS NOT NULL EXEC sp_rename 'VND_CUSTOMER_MAPPING.website', 'WEBSITE', 'COLUMN';
    IF COL_LENGTH('VND_CUSTOMER_MAPPING', 'gst_no') IS NOT NULL EXEC sp_rename 'VND_CUSTOMER_MAPPING.gst_no', 'GST_NO', 'COLUMN';
    IF COL_LENGTH('VND_CUSTOMER_MAPPING', 'pan_no') IS NOT NULL EXEC sp_rename 'VND_CUSTOMER_MAPPING.pan_no', 'PAN_NO', 'COLUMN';
    IF COL_LENGTH('VND_CUSTOMER_MAPPING', 'pan_file_info') IS NOT NULL EXEC sp_rename 'VND_CUSTOMER_MAPPING.pan_file_info', 'PAN_FILE_INFO', 'COLUMN';
    IF COL_LENGTH('VND_CUSTOMER_MAPPING', 'register_no') IS NOT NULL EXEC sp_rename 'VND_CUSTOMER_MAPPING.register_no', 'REGISTER_NO', 'COLUMN';
    IF COL_LENGTH('VND_CUSTOMER_MAPPING', 'cin_no') IS NOT NULL EXEC sp_rename 'VND_CUSTOMER_MAPPING.cin_no', 'CIN_NO', 'COLUMN';
    IF COL_LENGTH('VND_CUSTOMER_MAPPING', 'vendor_code') IS NOT NULL EXEC sp_rename 'VND_CUSTOMER_MAPPING.vendor_code', 'VENDOR_CODE', 'COLUMN';
    IF COL_LENGTH('VND_CUSTOMER_MAPPING', 'msme_no') IS NOT NULL EXEC sp_rename 'VND_CUSTOMER_MAPPING.msme_no', 'MSME_NO', 'COLUMN';
    IF COL_LENGTH('VND_CUSTOMER_MAPPING', 'msme_file_info') IS NOT NULL EXEC sp_rename 'VND_CUSTOMER_MAPPING.msme_file_info', 'MSME_FILE_INFO', 'COLUMN';
    IF COL_LENGTH('VND_CUSTOMER_MAPPING', 'iso_no') IS NOT NULL EXEC sp_rename 'VND_CUSTOMER_MAPPING.iso_no', 'ISO_NO', 'COLUMN';
    IF COL_LENGTH('VND_CUSTOMER_MAPPING', 'iso_file_info') IS NOT NULL EXEC sp_rename 'VND_CUSTOMER_MAPPING.iso_file_info', 'ISO_FILE_INFO', 'COLUMN';
    IF COL_LENGTH('VND_CUSTOMER_MAPPING', 'iso_expiry_date') IS NOT NULL EXEC sp_rename 'VND_CUSTOMER_MAPPING.iso_expiry_date', 'ISO_EXPIRY_DATE', 'COLUMN';
    IF COL_LENGTH('VND_CUSTOMER_MAPPING', 'prime_flag') IS NOT NULL EXEC sp_rename 'VND_CUSTOMER_MAPPING.prime_flag', 'PRIME_FLAG', 'COLUMN';
    IF COL_LENGTH('VND_CUSTOMER_MAPPING', 'approved_supplier') IS NOT NULL EXEC sp_rename 'VND_CUSTOMER_MAPPING.approved_supplier', 'APPROVED_SUPPLIER', 'COLUMN';
    IF COL_LENGTH('VND_CUSTOMER_MAPPING', 'nda_required') IS NOT NULL EXEC sp_rename 'VND_CUSTOMER_MAPPING.nda_required', 'NDA_REQUIRED', 'COLUMN';
    IF COL_LENGTH('VND_CUSTOMER_MAPPING', 'is_auditor_consultant') IS NOT NULL EXEC sp_rename 'VND_CUSTOMER_MAPPING.is_auditor_consultant', 'IS_AUDITOR_CONSULTANT', 'COLUMN';
    IF COL_LENGTH('VND_CUSTOMER_MAPPING', 'segment') IS NOT NULL EXEC sp_rename 'VND_CUSTOMER_MAPPING.segment', 'SEGMENT', 'COLUMN';
    IF COL_LENGTH('VND_CUSTOMER_MAPPING', 'sub_segment') IS NOT NULL EXEC sp_rename 'VND_CUSTOMER_MAPPING.sub_segment', 'SUB_SEGMENT', 'COLUMN';
    IF COL_LENGTH('VND_CUSTOMER_MAPPING', 'domain_name') IS NOT NULL EXEC sp_rename 'VND_CUSTOMER_MAPPING.domain_name', 'DOMAIN_NAME', 'COLUMN';
    IF COL_LENGTH('VND_CUSTOMER_MAPPING', 'negotiate_customer') IS NOT NULL EXEC sp_rename 'VND_CUSTOMER_MAPPING.negotiate_customer', 'NEGOTIATE_CUSTOMER', 'COLUMN';
    IF COL_LENGTH('VND_CUSTOMER_MAPPING', 'daily_dispatch_mail') IS NOT NULL EXEC sp_rename 'VND_CUSTOMER_MAPPING.daily_dispatch_mail', 'DAILY_DISPATCH_MAIL', 'COLUMN';
    IF COL_LENGTH('VND_CUSTOMER_MAPPING', 'ld_applicable') IS NOT NULL EXEC sp_rename 'VND_CUSTOMER_MAPPING.ld_applicable', 'LD_APPLICABLE', 'COLUMN';
    IF COL_LENGTH('VND_CUSTOMER_MAPPING', 'currency') IS NOT NULL EXEC sp_rename 'VND_CUSTOMER_MAPPING.currency', 'CURRENCY', 'COLUMN';
    IF COL_LENGTH('VND_CUSTOMER_MAPPING', 'payment_terms') IS NOT NULL EXEC sp_rename 'VND_CUSTOMER_MAPPING.payment_terms', 'PAYMENT_TERMS', 'COLUMN';
    IF COL_LENGTH('VND_CUSTOMER_MAPPING', 'delivery_terms') IS NOT NULL EXEC sp_rename 'VND_CUSTOMER_MAPPING.delivery_terms', 'DELIVERY_TERMS', 'COLUMN';
    IF COL_LENGTH('VND_CUSTOMER_MAPPING', 'freight') IS NOT NULL EXEC sp_rename 'VND_CUSTOMER_MAPPING.freight', 'FREIGHT', 'COLUMN';
    IF COL_LENGTH('VND_CUSTOMER_MAPPING', 'dispatch_mode') IS NOT NULL EXEC sp_rename 'VND_CUSTOMER_MAPPING.dispatch_mode', 'DISPATCH_MODE', 'COLUMN';
    IF COL_LENGTH('VND_CUSTOMER_MAPPING', 'type_of_service') IS NOT NULL EXEC sp_rename 'VND_CUSTOMER_MAPPING.type_of_service', 'TYPE_OF_SERVICE', 'COLUMN';
    IF COL_LENGTH('VND_CUSTOMER_MAPPING', 'due_days') IS NOT NULL EXEC sp_rename 'VND_CUSTOMER_MAPPING.due_days', 'DUE_DAYS', 'COLUMN';
    IF COL_LENGTH('VND_CUSTOMER_MAPPING', 'account_no') IS NOT NULL EXEC sp_rename 'VND_CUSTOMER_MAPPING.account_no', 'ACCOUNT_NO', 'COLUMN';
    IF COL_LENGTH('VND_CUSTOMER_MAPPING', 'account_name') IS NOT NULL EXEC sp_rename 'VND_CUSTOMER_MAPPING.account_name', 'ACCOUNT_NAME', 'COLUMN';
    IF COL_LENGTH('VND_CUSTOMER_MAPPING', 'bank_name') IS NOT NULL EXEC sp_rename 'VND_CUSTOMER_MAPPING.bank_name', 'BANK_NAME', 'COLUMN';
    IF COL_LENGTH('VND_CUSTOMER_MAPPING', 'branch_name') IS NOT NULL EXEC sp_rename 'VND_CUSTOMER_MAPPING.branch_name', 'BRANCH_NAME', 'COLUMN';
    IF COL_LENGTH('VND_CUSTOMER_MAPPING', 'ifsc_code') IS NOT NULL EXEC sp_rename 'VND_CUSTOMER_MAPPING.ifsc_code', 'IFSC_CODE', 'COLUMN';
    IF COL_LENGTH('VND_CUSTOMER_MAPPING', 'swift_code') IS NOT NULL EXEC sp_rename 'VND_CUSTOMER_MAPPING.swift_code', 'SWIFT_CODE', 'COLUMN';
    IF COL_LENGTH('VND_CUSTOMER_MAPPING', 'account_type') IS NOT NULL EXEC sp_rename 'VND_CUSTOMER_MAPPING.account_type', 'ACCOUNT_TYPE', 'COLUMN';
    IF COL_LENGTH('VND_CUSTOMER_MAPPING', 'upload_files') IS NOT NULL EXEC sp_rename 'VND_CUSTOMER_MAPPING.upload_files', 'UPLOAD_FILES', 'COLUMN';
    IF COL_LENGTH('VND_CUSTOMER_MAPPING', 'status') IS NOT NULL EXEC sp_rename 'VND_CUSTOMER_MAPPING.status', 'STATUS', 'COLUMN';
    IF COL_LENGTH('VND_CUSTOMER_MAPPING', 'created_by') IS NOT NULL EXEC sp_rename 'VND_CUSTOMER_MAPPING.created_by', 'CREATED_BY', 'COLUMN';
    IF COL_LENGTH('VND_CUSTOMER_MAPPING', 'updated_by') IS NOT NULL EXEC sp_rename 'VND_CUSTOMER_MAPPING.updated_by', 'UPDATED_BY', 'COLUMN';

    IF COL_LENGTH('VND_CUSTOMER_MAPPING', 'created_at') IS NOT NULL AND COL_LENGTH('VND_CUSTOMER_MAPPING', 'CREATED_DATE') IS NULL 
        EXEC sp_rename 'VND_CUSTOMER_MAPPING.created_at', 'CREATED_DATE', 'COLUMN';
    IF COL_LENGTH('VND_CUSTOMER_MAPPING', 'updated_at') IS NOT NULL AND COL_LENGTH('VND_CUSTOMER_MAPPING', 'UPDATED_DATE') IS NULL 
        EXEC sp_rename 'VND_CUSTOMER_MAPPING.updated_at', 'UPDATED_DATE', 'COLUMN';
    IF COL_LENGTH('VND_CUSTOMER_MAPPING', 'created_date') IS NOT NULL AND COL_LENGTH('VND_CUSTOMER_MAPPING', 'CREATED_DATE') IS NULL 
        EXEC sp_rename 'VND_CUSTOMER_MAPPING.created_date', 'CREATED_DATE', 'COLUMN';
    IF COL_LENGTH('VND_CUSTOMER_MAPPING', 'updated_date') IS NOT NULL AND COL_LENGTH('VND_CUSTOMER_MAPPING', 'UPDATED_DATE') IS NULL 
        EXEC sp_rename 'VND_CUSTOMER_MAPPING.updated_date', 'UPDATED_DATE', 'COLUMN';
END
GO

IF OBJECT_ID('VND_CUSTOMER_MAPPING', 'U') IS NOT NULL
BEGIN
    ALTER TABLE VND_CUSTOMER_MAPPING ALTER COLUMN RECORD_TYPE NVARCHAR(20) NOT NULL;
    ALTER TABLE VND_CUSTOMER_MAPPING ALTER COLUMN CODE NVARCHAR(50);
    ALTER TABLE VND_CUSTOMER_MAPPING ALTER COLUMN NAME NVARCHAR(200);
    ALTER TABLE VND_CUSTOMER_MAPPING ALTER COLUMN PRINT_NAME NVARCHAR(200);
    ALTER TABLE VND_CUSTOMER_MAPPING ALTER COLUMN SHORT_NAME NVARCHAR(50);
    ALTER TABLE VND_CUSTOMER_MAPPING ALTER COLUMN LEDGER_NAME NVARCHAR(200);
    ALTER TABLE VND_CUSTOMER_MAPPING ALTER COLUMN INVOICE_NAME NVARCHAR(200);
    ALTER TABLE VND_CUSTOMER_MAPPING ALTER COLUMN GROUP_NAME NVARCHAR(200);
    ALTER TABLE VND_CUSTOMER_MAPPING ALTER COLUMN ADDRESS NVARCHAR(MAX);
    ALTER TABLE VND_CUSTOMER_MAPPING ALTER COLUMN PINCODE NVARCHAR(20);
    ALTER TABLE VND_CUSTOMER_MAPPING ALTER COLUMN CITY NVARCHAR(100);
    ALTER TABLE VND_CUSTOMER_MAPPING ALTER COLUMN STATE NVARCHAR(100);
    ALTER TABLE VND_CUSTOMER_MAPPING ALTER COLUMN STATE_CODE NVARCHAR(20);
    ALTER TABLE VND_CUSTOMER_MAPPING ALTER COLUMN COUNTRY NVARCHAR(100);
    ALTER TABLE VND_CUSTOMER_MAPPING ALTER COLUMN LOCATION NVARCHAR(200);
    ALTER TABLE VND_CUSTOMER_MAPPING ALTER COLUMN DISTANCE NVARCHAR(50);
    ALTER TABLE VND_CUSTOMER_MAPPING ALTER COLUMN CONTACT_PERSON NVARCHAR(100);
    ALTER TABLE VND_CUSTOMER_MAPPING ALTER COLUMN MOBILE_NO NVARCHAR(20);
    ALTER TABLE VND_CUSTOMER_MAPPING ALTER COLUMN EMAIL_ID NVARCHAR(100);
    ALTER TABLE VND_CUSTOMER_MAPPING ALTER COLUMN WEBSITE NVARCHAR(150);
    ALTER TABLE VND_CUSTOMER_MAPPING ALTER COLUMN GST_NO NVARCHAR(50);
    ALTER TABLE VND_CUSTOMER_MAPPING ALTER COLUMN PAN_NO NVARCHAR(50);
    ALTER TABLE VND_CUSTOMER_MAPPING ALTER COLUMN PAN_FILE_INFO NVARCHAR(1000);
    ALTER TABLE VND_CUSTOMER_MAPPING ALTER COLUMN REGISTER_NO NVARCHAR(100);
    ALTER TABLE VND_CUSTOMER_MAPPING ALTER COLUMN CIN_NO NVARCHAR(100);
    ALTER TABLE VND_CUSTOMER_MAPPING ALTER COLUMN VENDOR_CODE NVARCHAR(50);
    ALTER TABLE VND_CUSTOMER_MAPPING ALTER COLUMN MSME_NO NVARCHAR(50);
    ALTER TABLE VND_CUSTOMER_MAPPING ALTER COLUMN MSME_FILE_INFO NVARCHAR(1000);
    ALTER TABLE VND_CUSTOMER_MAPPING ALTER COLUMN ISO_NO NVARCHAR(50);
    ALTER TABLE VND_CUSTOMER_MAPPING ALTER COLUMN ISO_FILE_INFO NVARCHAR(1000);
    ALTER TABLE VND_CUSTOMER_MAPPING ALTER COLUMN ISO_EXPIRY_DATE NVARCHAR(50);
    ALTER TABLE VND_CUSTOMER_MAPPING ALTER COLUMN PRIME_FLAG NVARCHAR(10);
    ALTER TABLE VND_CUSTOMER_MAPPING ALTER COLUMN APPROVED_SUPPLIER NVARCHAR(10);
    ALTER TABLE VND_CUSTOMER_MAPPING ALTER COLUMN NDA_REQUIRED NVARCHAR(10);
    ALTER TABLE VND_CUSTOMER_MAPPING ALTER COLUMN IS_AUDITOR_CONSULTANT NVARCHAR(10);
    ALTER TABLE VND_CUSTOMER_MAPPING ALTER COLUMN SEGMENT NVARCHAR(100);
    ALTER TABLE VND_CUSTOMER_MAPPING ALTER COLUMN SUB_SEGMENT NVARCHAR(100);
    ALTER TABLE VND_CUSTOMER_MAPPING ALTER COLUMN DOMAIN_NAME NVARCHAR(150);
    ALTER TABLE VND_CUSTOMER_MAPPING ALTER COLUMN NEGOTIATE_CUSTOMER NVARCHAR(10);
    ALTER TABLE VND_CUSTOMER_MAPPING ALTER COLUMN DAILY_DISPATCH_MAIL NVARCHAR(10);
    ALTER TABLE VND_CUSTOMER_MAPPING ALTER COLUMN LD_APPLICABLE NVARCHAR(10);
    ALTER TABLE VND_CUSTOMER_MAPPING ALTER COLUMN CURRENCY NVARCHAR(20);
    ALTER TABLE VND_CUSTOMER_MAPPING ALTER COLUMN PAYMENT_TERMS NVARCHAR(100);
    ALTER TABLE VND_CUSTOMER_MAPPING ALTER COLUMN DELIVERY_TERMS NVARCHAR(100);
    ALTER TABLE VND_CUSTOMER_MAPPING ALTER COLUMN FREIGHT NVARCHAR(100);
    ALTER TABLE VND_CUSTOMER_MAPPING ALTER COLUMN DISPATCH_MODE NVARCHAR(50);
    ALTER TABLE VND_CUSTOMER_MAPPING ALTER COLUMN TYPE_OF_SERVICE NVARCHAR(100);
    ALTER TABLE VND_CUSTOMER_MAPPING ALTER COLUMN DUE_DAYS NVARCHAR(20);
    ALTER TABLE VND_CUSTOMER_MAPPING ALTER COLUMN ACCOUNT_NO NVARCHAR(50);
    ALTER TABLE VND_CUSTOMER_MAPPING ALTER COLUMN ACCOUNT_NAME NVARCHAR(100);
    ALTER TABLE VND_CUSTOMER_MAPPING ALTER COLUMN BANK_NAME NVARCHAR(100);
    ALTER TABLE VND_CUSTOMER_MAPPING ALTER COLUMN BRANCH_NAME NVARCHAR(100);
    ALTER TABLE VND_CUSTOMER_MAPPING ALTER COLUMN IFSC_CODE NVARCHAR(50);
    ALTER TABLE VND_CUSTOMER_MAPPING ALTER COLUMN SWIFT_CODE NVARCHAR(50);
    ALTER TABLE VND_CUSTOMER_MAPPING ALTER COLUMN ACCOUNT_TYPE NVARCHAR(50);
    ALTER TABLE VND_CUSTOMER_MAPPING ALTER COLUMN UPLOAD_FILES NVARCHAR(1000);
    ALTER TABLE VND_CUSTOMER_MAPPING ALTER COLUMN STATUS NVARCHAR(20);
    ALTER TABLE VND_CUSTOMER_MAPPING ALTER COLUMN CREATED_BY NVARCHAR(100);
    ALTER TABLE VND_CUSTOMER_MAPPING ALTER COLUMN CREATED_DATE DATETIME;
    ALTER TABLE VND_CUSTOMER_MAPPING ALTER COLUMN UPDATED_BY NVARCHAR(100);
    ALTER TABLE VND_CUSTOMER_MAPPING ALTER COLUMN UPDATED_DATE DATETIME;

    IF COL_LENGTH('VND_CUSTOMER_MAPPING', 'IS_ACTIVE') IS NULL
        ALTER TABLE VND_CUSTOMER_MAPPING ADD IS_ACTIVE BIT DEFAULT 1;
END
GO

IF OBJECT_ID('VND_CUSTOMER_MAPPING', 'U') IS NOT NULL
BEGIN
    DECLARE @map_pk NVARCHAR(256);
    SELECT TOP 1 @map_pk = name FROM sys.key_constraints WHERE parent_object_id = OBJECT_ID('VND_CUSTOMER_MAPPING') AND type = 'PK';
    IF @map_pk IS NOT NULL AND @map_pk <> 'PK_VND_CUSTOMER_MAPPING' AND NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE referenced_object_id = OBJECT_ID('VND_CUSTOMER_MAPPING'))
    BEGIN
        DECLARE @drop_map_pk NVARCHAR(MAX) = 'ALTER TABLE VND_CUSTOMER_MAPPING DROP CONSTRAINT ' + @map_pk;
        EXEC(@drop_map_pk);
    END
    IF NOT EXISTS (SELECT 1 FROM sys.key_constraints WHERE parent_object_id = OBJECT_ID('VND_CUSTOMER_MAPPING') AND type = 'PK')
    BEGIN
        ALTER TABLE VND_CUSTOMER_MAPPING ADD CONSTRAINT PK_VND_CUSTOMER_MAPPING PRIMARY KEY (id);
    END
END
GO


-- ==========================================
-- 5. SLS_CUSTOMER_POTENTIAL (from SM_CUSTOMER_POTENTIAL)
-- ==========================================
IF OBJECT_ID('dbo.sp_RenameTableCasingAndPrefix', 'P') IS NOT NULL
BEGIN
    EXEC dbo.sp_RenameTableCasingAndPrefix 'SM_CUSTOMER_POTENTIAL', 'SLS_CUSTOMER_POTENTIAL';
END
ELSE
BEGIN
    IF OBJECT_ID('SM_CUSTOMER_POTENTIAL', 'U') IS NOT NULL AND OBJECT_ID('SLS_CUSTOMER_POTENTIAL', 'U') IS NULL
        EXEC sp_rename 'SM_CUSTOMER_POTENTIAL', 'SLS_CUSTOMER_POTENTIAL';
END
GO

IF OBJECT_ID('SLS_CUSTOMER_POTENTIAL', 'U') IS NOT NULL
BEGIN
    -- Handle duplicate created_at/CREATED_DATE columns
    IF COL_LENGTH('SLS_CUSTOMER_POTENTIAL', 'created_at') IS NOT NULL AND COL_LENGTH('SLS_CUSTOMER_POTENTIAL', 'created_date') IS NOT NULL
        ALTER TABLE SLS_CUSTOMER_POTENTIAL DROP COLUMN created_at;
    IF COL_LENGTH('SLS_CUSTOMER_POTENTIAL', 'updated_at') IS NOT NULL AND COL_LENGTH('SLS_CUSTOMER_POTENTIAL', 'updated_date') IS NOT NULL
        ALTER TABLE SLS_CUSTOMER_POTENTIAL DROP COLUMN updated_at;

    IF COL_LENGTH('SLS_CUSTOMER_POTENTIAL', 'customer_group_name') IS NOT NULL EXEC sp_rename 'SLS_CUSTOMER_POTENTIAL.customer_group_name', 'CUSTOMER_GROUP_NAME', 'COLUMN';
    IF COL_LENGTH('SLS_CUSTOMER_POTENTIAL', 'customer_code') IS NOT NULL EXEC sp_rename 'SLS_CUSTOMER_POTENTIAL.customer_code', 'CUSTOMER_CODE', 'COLUMN';
    IF COL_LENGTH('SLS_CUSTOMER_POTENTIAL', 'customer_type') IS NOT NULL EXEC sp_rename 'SLS_CUSTOMER_POTENTIAL.customer_type', 'CUSTOMER_TYPE', 'COLUMN';
    IF COL_LENGTH('SLS_CUSTOMER_POTENTIAL', 'manufacturer_oem') IS NOT NULL EXEC sp_rename 'SLS_CUSTOMER_POTENTIAL.manufacturer_oem', 'MANUFACTURER_OEM', 'COLUMN';
    IF COL_LENGTH('SLS_CUSTOMER_POTENTIAL', 'wtg_model') IS NOT NULL EXEC sp_rename 'SLS_CUSTOMER_POTENTIAL.wtg_model', 'WTG_MODEL', 'COLUMN';
    IF COL_LENGTH('SLS_CUSTOMER_POTENTIAL', 'wind_turbine_power') IS NOT NULL EXEC sp_rename 'SLS_CUSTOMER_POTENTIAL.wind_turbine_power', 'WIND_TURBINE_POWER', 'COLUMN';
    IF COL_LENGTH('SLS_CUSTOMER_POTENTIAL', 'wind_farm_name') IS NOT NULL EXEC sp_rename 'SLS_CUSTOMER_POTENTIAL.wind_farm_name', 'WIND_FARM_NAME', 'COLUMN';
    IF COL_LENGTH('SLS_CUSTOMER_POTENTIAL', 'area') IS NOT NULL EXEC sp_rename 'SLS_CUSTOMER_POTENTIAL.area', 'AREA', 'COLUMN';
    IF COL_LENGTH('SLS_CUSTOMER_POTENTIAL', 'pincode') IS NOT NULL EXEC sp_rename 'SLS_CUSTOMER_POTENTIAL.pincode', 'PINCODE', 'COLUMN';
    IF COL_LENGTH('SLS_CUSTOMER_POTENTIAL', 'state') IS NOT NULL EXEC sp_rename 'SLS_CUSTOMER_POTENTIAL.state', 'STATE', 'COLUMN';
    IF COL_LENGTH('SLS_CUSTOMER_POTENTIAL', 'country') IS NOT NULL EXEC sp_rename 'SLS_CUSTOMER_POTENTIAL.country', 'COUNTRY', 'COLUMN';
    IF COL_LENGTH('SLS_CUSTOMER_POTENTIAL', 'developer') IS NOT NULL EXEC sp_rename 'SLS_CUSTOMER_POTENTIAL.developer', 'DEVELOPER', 'COLUMN';
    IF COL_LENGTH('SLS_CUSTOMER_POTENTIAL', 'plant_mw') IS NOT NULL EXEC sp_rename 'SLS_CUSTOMER_POTENTIAL.plant_mw', 'PLANT_MW', 'COLUMN';
    IF COL_LENGTH('SLS_CUSTOMER_POTENTIAL', 'turbine_count') IS NOT NULL EXEC sp_rename 'SLS_CUSTOMER_POTENTIAL.turbine_count', 'TURBINE_COUNT', 'COLUMN';
    IF COL_LENGTH('SLS_CUSTOMER_POTENTIAL', 'hub') IS NOT NULL EXEC sp_rename 'SLS_CUSTOMER_POTENTIAL.hub', 'HUB', 'COLUMN';
    IF COL_LENGTH('SLS_CUSTOMER_POTENTIAL', 'operational_status') IS NOT NULL EXEC sp_rename 'SLS_CUSTOMER_POTENTIAL.operational_status', 'OPERATIONAL_STATUS', 'COLUMN';
    IF COL_LENGTH('SLS_CUSTOMER_POTENTIAL', 'commissioning_year') IS NOT NULL EXEC sp_rename 'SLS_CUSTOMER_POTENTIAL.commissioning_year', 'COMMISSIONING_YEAR', 'COLUMN';
    IF COL_LENGTH('SLS_CUSTOMER_POTENTIAL', 'commissioning_month') IS NOT NULL EXEC sp_rename 'SLS_CUSTOMER_POTENTIAL.commissioning_month', 'COMMISSIONING_MONTH', 'COLUMN';
    IF COL_LENGTH('SLS_CUSTOMER_POTENTIAL', 'latitude') IS NOT NULL EXEC sp_rename 'SLS_CUSTOMER_POTENTIAL.latitude', 'LATITUDE', 'COLUMN';
    IF COL_LENGTH('SLS_CUSTOMER_POTENTIAL', 'longitude') IS NOT NULL EXEC sp_rename 'SLS_CUSTOMER_POTENTIAL.longitude', 'LONGITUDE', 'COLUMN';
    IF COL_LENGTH('SLS_CUSTOMER_POTENTIAL', 'status') IS NOT NULL EXEC sp_rename 'SLS_CUSTOMER_POTENTIAL.status', 'STATUS', 'COLUMN';
    IF COL_LENGTH('SLS_CUSTOMER_POTENTIAL', 'created_by') IS NOT NULL EXEC sp_rename 'SLS_CUSTOMER_POTENTIAL.created_by', 'CREATED_BY', 'COLUMN';
    IF COL_LENGTH('SLS_CUSTOMER_POTENTIAL', 'updated_by') IS NOT NULL EXEC sp_rename 'SLS_CUSTOMER_POTENTIAL.updated_by', 'UPDATED_BY', 'COLUMN';

    IF COL_LENGTH('SLS_CUSTOMER_POTENTIAL', 'created_at') IS NOT NULL AND COL_LENGTH('SLS_CUSTOMER_POTENTIAL', 'CREATED_DATE') IS NULL 
        EXEC sp_rename 'SLS_CUSTOMER_POTENTIAL.created_at', 'CREATED_DATE', 'COLUMN';
    IF COL_LENGTH('SLS_CUSTOMER_POTENTIAL', 'updated_at') IS NOT NULL AND COL_LENGTH('SLS_CUSTOMER_POTENTIAL', 'UPDATED_DATE') IS NULL 
        EXEC sp_rename 'SLS_CUSTOMER_POTENTIAL.updated_at', 'UPDATED_DATE', 'COLUMN';
    IF COL_LENGTH('SLS_CUSTOMER_POTENTIAL', 'created_date') IS NOT NULL AND COL_LENGTH('SLS_CUSTOMER_POTENTIAL', 'CREATED_DATE') IS NULL 
        EXEC sp_rename 'SLS_CUSTOMER_POTENTIAL.created_date', 'CREATED_DATE', 'COLUMN';
    IF COL_LENGTH('SLS_CUSTOMER_POTENTIAL', 'updated_date') IS NOT NULL AND COL_LENGTH('SLS_CUSTOMER_POTENTIAL', 'UPDATED_DATE') IS NULL 
        EXEC sp_rename 'SLS_CUSTOMER_POTENTIAL.updated_date', 'UPDATED_DATE', 'COLUMN';
END
GO

IF OBJECT_ID('SLS_CUSTOMER_POTENTIAL', 'U') IS NOT NULL
BEGIN
    ALTER TABLE SLS_CUSTOMER_POTENTIAL ALTER COLUMN CUSTOMER_GROUP_NAME NVARCHAR(200);
    ALTER TABLE SLS_CUSTOMER_POTENTIAL ALTER COLUMN CUSTOMER_CODE NVARCHAR(50) NOT NULL;
    ALTER TABLE SLS_CUSTOMER_POTENTIAL ALTER COLUMN CUSTOMER_TYPE NVARCHAR(50);
    ALTER TABLE SLS_CUSTOMER_POTENTIAL ALTER COLUMN MANUFACTURER_OEM NVARCHAR(100);
    ALTER TABLE SLS_CUSTOMER_POTENTIAL ALTER COLUMN WTG_MODEL NVARCHAR(100);
    ALTER TABLE SLS_CUSTOMER_POTENTIAL ALTER COLUMN WIND_TURBINE_POWER NVARCHAR(100);
    ALTER TABLE SLS_CUSTOMER_POTENTIAL ALTER COLUMN WIND_FARM_NAME NVARCHAR(100);
    ALTER TABLE SLS_CUSTOMER_POTENTIAL ALTER COLUMN AREA NVARCHAR(200);
    ALTER TABLE SLS_CUSTOMER_POTENTIAL ALTER COLUMN PINCODE NVARCHAR(20);
    ALTER TABLE SLS_CUSTOMER_POTENTIAL ALTER COLUMN STATE NVARCHAR(100);
    ALTER TABLE SLS_CUSTOMER_POTENTIAL ALTER COLUMN COUNTRY NVARCHAR(100);
    ALTER TABLE SLS_CUSTOMER_POTENTIAL ALTER COLUMN DEVELOPER NVARCHAR(200);
    ALTER TABLE SLS_CUSTOMER_POTENTIAL ALTER COLUMN PLANT_MW FLOAT;
    ALTER TABLE SLS_CUSTOMER_POTENTIAL ALTER COLUMN TURBINE_COUNT INT;
    ALTER TABLE SLS_CUSTOMER_POTENTIAL ALTER COLUMN HUB NVARCHAR(100);
    ALTER TABLE SLS_CUSTOMER_POTENTIAL ALTER COLUMN OPERATIONAL_STATUS NVARCHAR(100);
    ALTER TABLE SLS_CUSTOMER_POTENTIAL ALTER COLUMN COMMISSIONING_YEAR NVARCHAR(20);
    ALTER TABLE SLS_CUSTOMER_POTENTIAL ALTER COLUMN COMMISSIONING_MONTH NVARCHAR(20);
    ALTER TABLE SLS_CUSTOMER_POTENTIAL ALTER COLUMN LATITUDE FLOAT;
    ALTER TABLE SLS_CUSTOMER_POTENTIAL ALTER COLUMN LONGITUDE FLOAT;
    ALTER TABLE SLS_CUSTOMER_POTENTIAL ALTER COLUMN STATUS NVARCHAR(20);
    ALTER TABLE SLS_CUSTOMER_POTENTIAL ALTER COLUMN CREATED_BY NVARCHAR(100);
    ALTER TABLE SLS_CUSTOMER_POTENTIAL ALTER COLUMN CREATED_DATE DATETIME;
    ALTER TABLE SLS_CUSTOMER_POTENTIAL ALTER COLUMN UPDATED_BY NVARCHAR(100);
    ALTER TABLE SLS_CUSTOMER_POTENTIAL ALTER COLUMN UPDATED_DATE DATETIME;

    IF COL_LENGTH('SLS_CUSTOMER_POTENTIAL', 'IS_ACTIVE') IS NULL
        ALTER TABLE SLS_CUSTOMER_POTENTIAL ADD IS_ACTIVE BIT DEFAULT 1;
END
GO

IF OBJECT_ID('SLS_CUSTOMER_POTENTIAL', 'U') IS NOT NULL
BEGIN
    DECLARE @pot_pk NVARCHAR(256);
    SELECT TOP 1 @pot_pk = name FROM sys.key_constraints WHERE parent_object_id = OBJECT_ID('SLS_CUSTOMER_POTENTIAL') AND type = 'PK';
    IF @pot_pk IS NOT NULL AND @pot_pk <> 'PK_SLS_CUSTOMER_POTENTIAL' AND NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE referenced_object_id = OBJECT_ID('SLS_CUSTOMER_POTENTIAL'))
    BEGIN
        DECLARE @drop_pot_pk NVARCHAR(MAX) = 'ALTER TABLE SLS_CUSTOMER_POTENTIAL DROP CONSTRAINT ' + @pot_pk;
        EXEC(@drop_pot_pk);
    END
    IF NOT EXISTS (SELECT 1 FROM sys.key_constraints WHERE parent_object_id = OBJECT_ID('SLS_CUSTOMER_POTENTIAL') AND type = 'PK')
    BEGIN
        ALTER TABLE SLS_CUSTOMER_POTENTIAL ADD CONSTRAINT PK_SLS_CUSTOMER_POTENTIAL PRIMARY KEY (id);
    END
END
GO


-- ==========================================
-- Re-establish Foreign Keys
-- ==========================================
IF OBJECT_ID('SLS_CUSTOMER_ADDRESS', 'U') IS NOT NULL AND OBJECT_ID('SLS_CUSTOMER', 'U') IS NOT NULL
BEGIN
    IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = 'FK_SLS_CUSTOMER_ADDR_CUSTOMER')
    BEGIN
        ALTER TABLE SLS_CUSTOMER_ADDRESS ADD CONSTRAINT FK_SLS_CUSTOMER_ADDR_CUSTOMER FOREIGN KEY (CUSTOMER_ID) REFERENCES SLS_CUSTOMER(id);
    END
END
GO
