-- Add TYPE and CONTACT_TYPE columns to SM_CONTACT_MASTER table if they do not exist
IF OBJECT_ID('SM_CONTACT_MASTER', 'U') IS NOT NULL
BEGIN
    IF NOT EXISTS (SELECT 1 FROM sys.columns WHERE object_id = OBJECT_ID('SM_CONTACT_MASTER') AND name = 'TYPE')
    BEGIN
        ALTER TABLE SM_CONTACT_MASTER ADD [TYPE] NVARCHAR(100);
    END

    IF NOT EXISTS (SELECT 1 FROM sys.columns WHERE object_id = OBJECT_ID('SM_CONTACT_MASTER') AND name = 'CONTACT_TYPE')
    BEGIN
        ALTER TABLE SM_CONTACT_MASTER ADD [CONTACT_TYPE] NVARCHAR(100);
    END
END
