-- V002__User_Module.sql
-- Phase 2: User & Auth Module Schema Standardization
-- Renames and normalizes:
-- 1. AD_USER_CREDENTIAL
-- 2. AD_COMPANY_CREDENTIAL
-- 3. AD_DIVISION_MASTER -> AD_DIVISION
-- 4. AD_USER_COMPANY_MAPPING, AD_USER_DIVISION_MAPPING
-- 5. AD_USER_SESSION_AUDIT, AD_USER_SESSION_ACTIVITY

-- ==========================================
-- Drop referencing Foreign Key constraints dynamically to avoid cascade/drop errors
-- ==========================================
DECLARE @sql NVARCHAR(MAX) = N'';
SELECT @sql += N'ALTER TABLE ' + QUOTENAME(OBJECT_SCHEMA_NAME(parent_object_id)) + '.' + QUOTENAME(OBJECT_NAME(parent_object_id)) + 
               ' DROP CONSTRAINT ' + QUOTENAME(name) + ';' + CHAR(13) + CHAR(10)
FROM sys.foreign_keys
WHERE referenced_object_id IN (
    OBJECT_ID('ad_user_credential'),
    OBJECT_ID('AD_USER_CREDENTIAL'),
    OBJECT_ID('AD_USER_CREDENTIALS'),
    OBJECT_ID('ad_company_credential'),
    OBJECT_ID('AD_COMPANY_CREDENTIAL'),
    OBJECT_ID('ad_division_master'),
    OBJECT_ID('AD_DIVISION_MASTER'),
    OBJECT_ID('ad_division'),
    OBJECT_ID('AD_DIVISION')
);
IF @sql <> N''
BEGIN
    EXEC sp_executesql @sql;
END
GO

-- 1. AD_USER_CREDENTIAL
-- ==========================================
IF COL_LENGTH('AD_USER_CREDENTIAL', 'user_id') IS NOT NULL AND COL_LENGTH('AD_USER_CREDENTIAL', 'USER_ID') IS NULL
    EXEC sp_rename 'AD_USER_CREDENTIAL.user_id', 'USER_ID', 'COLUMN';
GO
IF COL_LENGTH('AD_USER_CREDENTIAL', 'emp_id') IS NOT NULL AND COL_LENGTH('AD_USER_CREDENTIAL', 'EMP_ID') IS NULL
    EXEC sp_rename 'AD_USER_CREDENTIAL.emp_id', 'EMP_ID', 'COLUMN';
GO
IF COL_LENGTH('AD_USER_CREDENTIAL', 'password') IS NOT NULL AND COL_LENGTH('AD_USER_CREDENTIAL', 'PASSWORD') IS NULL
    EXEC sp_rename 'AD_USER_CREDENTIAL.password', 'PASSWORD', 'COLUMN';
GO
IF COL_LENGTH('AD_USER_CREDENTIAL', 'created_by') IS NOT NULL AND COL_LENGTH('AD_USER_CREDENTIAL', 'CREATED_BY') IS NULL
    EXEC sp_rename 'AD_USER_CREDENTIAL.created_by', 'CREATED_BY', 'COLUMN';
GO
IF COL_LENGTH('AD_USER_CREDENTIAL', 'created_at') IS NOT NULL
BEGIN
    IF COL_LENGTH('AD_USER_CREDENTIAL', 'CREATED_DATE') IS NOT NULL AND LOWER('created_at') <> LOWER('CREATED_DATE')
    BEGIN
        EXEC('UPDATE AD_USER_CREDENTIAL SET CREATED_DATE = created_at WHERE CREATED_DATE IS NULL AND created_at IS NOT NULL');
        ALTER TABLE AD_USER_CREDENTIAL DROP COLUMN created_at;
    END
    ELSE
    BEGIN
        EXEC sp_rename 'AD_USER_CREDENTIAL.created_at', 'CREATED_DATE', 'COLUMN';
    END
END
GO
IF COL_LENGTH('AD_USER_CREDENTIAL', 'updated_by') IS NOT NULL AND COL_LENGTH('AD_USER_CREDENTIAL', 'UPDATED_BY') IS NULL
    EXEC sp_rename 'AD_USER_CREDENTIAL.updated_by', 'UPDATED_BY', 'COLUMN';
GO
IF COL_LENGTH('AD_USER_CREDENTIAL', 'updated_at') IS NOT NULL
BEGIN
    IF COL_LENGTH('AD_USER_CREDENTIAL', 'UPDATED_DATE') IS NOT NULL AND LOWER('updated_at') <> LOWER('UPDATED_DATE')
    BEGIN
        EXEC('UPDATE AD_USER_CREDENTIAL SET UPDATED_DATE = updated_at WHERE UPDATED_DATE IS NULL AND updated_at IS NOT NULL');
        ALTER TABLE AD_USER_CREDENTIAL DROP COLUMN updated_at;
    END
    ELSE
    BEGIN
        EXEC sp_rename 'AD_USER_CREDENTIAL.updated_at', 'UPDATED_DATE', 'COLUMN';
    END
END
GO
IF COL_LENGTH('AD_USER_CREDENTIAL', 'status') IS NOT NULL AND COL_LENGTH('AD_USER_CREDENTIAL', 'STATUS') IS NULL
    EXEC sp_rename 'AD_USER_CREDENTIAL.status', 'STATUS', 'COLUMN';
GO
IF COL_LENGTH('AD_USER_CREDENTIAL', 'img_name') IS NOT NULL AND COL_LENGTH('AD_USER_CREDENTIAL', 'IMG_NAME') IS NULL
    EXEC sp_rename 'AD_USER_CREDENTIAL.img_name', 'IMG_NAME', 'COLUMN';
GO
IF COL_LENGTH('AD_USER_CREDENTIAL', 'face_image') IS NOT NULL AND COL_LENGTH('AD_USER_CREDENTIAL', 'FACE_IMAGE') IS NULL
    EXEC sp_rename 'AD_USER_CREDENTIAL.face_image', 'FACE_IMAGE', 'COLUMN';
GO
IF COL_LENGTH('AD_USER_CREDENTIAL', 'auth_method') IS NOT NULL AND COL_LENGTH('AD_USER_CREDENTIAL', 'AUTH_METHOD') IS NULL
    EXEC sp_rename 'AD_USER_CREDENTIAL.auth_method', 'AUTH_METHOD', 'COLUMN';
GO
IF COL_LENGTH('AD_USER_CREDENTIAL', 'face_descriptor') IS NOT NULL AND COL_LENGTH('AD_USER_CREDENTIAL', 'FACE_DESCRIPTOR') IS NULL
    EXEC sp_rename 'AD_USER_CREDENTIAL.face_descriptor', 'FACE_DESCRIPTOR', 'COLUMN';
GO
IF COL_LENGTH('AD_USER_CREDENTIAL', 'auto_logout_on_face_absence') IS NOT NULL AND COL_LENGTH('AD_USER_CREDENTIAL', 'AUTO_LOGOUT_ON_FACE_ABSENCE') IS NULL
    EXEC sp_rename 'AD_USER_CREDENTIAL.auto_logout_on_face_absence', 'AUTO_LOGOUT_ON_FACE_ABSENCE', 'COLUMN';
GO

IF OBJECT_ID('AD_USER_CREDENTIAL', 'U') IS NOT NULL
BEGIN
    ALTER TABLE AD_USER_CREDENTIAL ALTER COLUMN USER_ID NVARCHAR(50) NOT NULL;
    ALTER TABLE AD_USER_CREDENTIAL ALTER COLUMN EMP_ID BIGINT NOT NULL;
    ALTER TABLE AD_USER_CREDENTIAL ALTER COLUMN PASSWORD NVARCHAR(255) NOT NULL;
    ALTER TABLE AD_USER_CREDENTIAL ALTER COLUMN CREATED_BY NVARCHAR(100);
    ALTER TABLE AD_USER_CREDENTIAL ALTER COLUMN CREATED_DATE DATETIME;
    ALTER TABLE AD_USER_CREDENTIAL ALTER COLUMN UPDATED_BY NVARCHAR(100);
    ALTER TABLE AD_USER_CREDENTIAL ALTER COLUMN UPDATED_DATE DATETIME;
    ALTER TABLE AD_USER_CREDENTIAL ALTER COLUMN IMG_NAME NVARCHAR(255);
    ALTER TABLE AD_USER_CREDENTIAL ALTER COLUMN AUTH_METHOD NVARCHAR(50);
END
GO

IF OBJECT_ID('AD_USER_CREDENTIAL', 'U') IS NOT NULL
BEGIN
    IF COL_LENGTH('AD_USER_CREDENTIAL', 'IS_ACTIVE') IS NULL
    BEGIN
        ALTER TABLE AD_USER_CREDENTIAL ADD IS_ACTIVE BIT DEFAULT 1;
    END
END
GO

IF OBJECT_ID('AD_USER_CREDENTIAL', 'U') IS NOT NULL
BEGIN
    DECLARE @user_pk NVARCHAR(256);
    SELECT TOP 1 @user_pk = name FROM sys.key_constraints WHERE parent_object_id = OBJECT_ID('AD_USER_CREDENTIAL') AND type = 'PK';
    IF @user_pk IS NOT NULL AND @user_pk <> 'PK_AD_USER_CREDENTIAL' AND NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE referenced_object_id = OBJECT_ID('AD_USER_CREDENTIAL'))
    BEGIN
        DECLARE @drop_user_pk NVARCHAR(MAX) = 'ALTER TABLE AD_USER_CREDENTIAL DROP CONSTRAINT ' + @user_pk;
        EXEC(@drop_user_pk);
    END
    IF NOT EXISTS (SELECT 1 FROM sys.key_constraints WHERE parent_object_id = OBJECT_ID('AD_USER_CREDENTIAL') AND type = 'PK')
    BEGIN
        ALTER TABLE AD_USER_CREDENTIAL ADD CONSTRAINT PK_AD_USER_CREDENTIAL PRIMARY KEY (USER_ID);
    END
END
GO


-- ==========================================
-- 2. AD_COMPANY_CREDENTIAL
-- ==========================================
IF COL_LENGTH('AD_COMPANY_CREDENTIAL', 'company_name') IS NOT NULL AND COL_LENGTH('AD_COMPANY_CREDENTIAL', 'COMPANY_NAME') IS NULL
    EXEC sp_rename 'AD_COMPANY_CREDENTIAL.company_name', 'COMPANY_NAME', 'COLUMN';
GO
IF COL_LENGTH('AD_COMPANY_CREDENTIAL', 'short_name') IS NOT NULL AND COL_LENGTH('AD_COMPANY_CREDENTIAL', 'SHORT_NAME') IS NULL
    EXEC sp_rename 'AD_COMPANY_CREDENTIAL.short_name', 'SHORT_NAME', 'COLUMN';
GO
IF COL_LENGTH('AD_COMPANY_CREDENTIAL', 'address') IS NOT NULL AND COL_LENGTH('AD_COMPANY_CREDENTIAL', 'ADDRESS') IS NULL
    EXEC sp_rename 'AD_COMPANY_CREDENTIAL.address', 'ADDRESS', 'COLUMN';
GO
IF COL_LENGTH('AD_COMPANY_CREDENTIAL', 'city') IS NOT NULL AND COL_LENGTH('AD_COMPANY_CREDENTIAL', 'CITY') IS NULL
    EXEC sp_rename 'AD_COMPANY_CREDENTIAL.city', 'CITY', 'COLUMN';
GO
IF COL_LENGTH('AD_COMPANY_CREDENTIAL', 'state') IS NOT NULL AND COL_LENGTH('AD_COMPANY_CREDENTIAL', 'STATE') IS NULL
    EXEC sp_rename 'AD_COMPANY_CREDENTIAL.state', 'STATE', 'COLUMN';
GO
IF COL_LENGTH('AD_COMPANY_CREDENTIAL', 'state_cd') IS NOT NULL
BEGIN
    IF COL_LENGTH('AD_COMPANY_CREDENTIAL', 'STATE_CODE') IS NOT NULL AND LOWER('state_cd') <> LOWER('STATE_CODE')
    BEGIN
        EXEC('UPDATE AD_COMPANY_CREDENTIAL SET STATE_CODE = state_cd WHERE STATE_CODE IS NULL AND state_cd IS NOT NULL');
        ALTER TABLE AD_COMPANY_CREDENTIAL DROP COLUMN state_cd;
    END
    ELSE
    BEGIN
        EXEC sp_rename 'AD_COMPANY_CREDENTIAL.state_cd', 'STATE_CODE', 'COLUMN';
    END
END
GO
IF COL_LENGTH('AD_COMPANY_CREDENTIAL', 'country') IS NOT NULL AND COL_LENGTH('AD_COMPANY_CREDENTIAL', 'COUNTRY') IS NULL
    EXEC sp_rename 'AD_COMPANY_CREDENTIAL.country', 'COUNTRY', 'COLUMN';
GO
IF COL_LENGTH('AD_COMPANY_CREDENTIAL', 'pincode') IS NOT NULL AND COL_LENGTH('AD_COMPANY_CREDENTIAL', 'PINCODE') IS NULL
    EXEC sp_rename 'AD_COMPANY_CREDENTIAL.pincode', 'PINCODE', 'COLUMN';
GO
IF COL_LENGTH('AD_COMPANY_CREDENTIAL', 'gst_in') IS NOT NULL AND COL_LENGTH('AD_COMPANY_CREDENTIAL', 'GST_IN') IS NULL
    EXEC sp_rename 'AD_COMPANY_CREDENTIAL.gst_in', 'GST_IN', 'COLUMN';
GO
IF COL_LENGTH('AD_COMPANY_CREDENTIAL', 'db_source_name') IS NOT NULL AND COL_LENGTH('AD_COMPANY_CREDENTIAL', 'DB_SOURCE_NAME') IS NULL
    EXEC sp_rename 'AD_COMPANY_CREDENTIAL.db_source_name', 'DB_SOURCE_NAME', 'COLUMN';
GO
IF COL_LENGTH('AD_COMPANY_CREDENTIAL', 'lic_renewal_date') IS NOT NULL AND COL_LENGTH('AD_COMPANY_CREDENTIAL', 'LIC_RENEWAL_DATE') IS NULL
    EXEC sp_rename 'AD_COMPANY_CREDENTIAL.lic_renewal_date', 'LIC_RENEWAL_DATE', 'COLUMN';
GO
IF COL_LENGTH('AD_COMPANY_CREDENTIAL', 'lic_expiry_date') IS NOT NULL AND COL_LENGTH('AD_COMPANY_CREDENTIAL', 'LIC_EXPIRY_DATE') IS NULL
    EXEC sp_rename 'AD_COMPANY_CREDENTIAL.lic_expiry_date', 'LIC_EXPIRY_DATE', 'COLUMN';
GO
IF COL_LENGTH('AD_COMPANY_CREDENTIAL', 'logo_file_name') IS NOT NULL AND COL_LENGTH('AD_COMPANY_CREDENTIAL', 'LOGO_FILE_NAME') IS NULL
    EXEC sp_rename 'AD_COMPANY_CREDENTIAL.logo_file_name', 'LOGO_FILE_NAME', 'COLUMN';
GO
IF COL_LENGTH('AD_COMPANY_CREDENTIAL', 'login_bg_file_name') IS NOT NULL AND COL_LENGTH('AD_COMPANY_CREDENTIAL', 'LOGIN_BG_FILE_NAME') IS NULL
    EXEC sp_rename 'AD_COMPANY_CREDENTIAL.login_bg_file_name', 'LOGIN_BG_FILE_NAME', 'COLUMN';
GO
IF COL_LENGTH('AD_COMPANY_CREDENTIAL', 'dir_path') IS NOT NULL
BEGIN
    IF COL_LENGTH('AD_COMPANY_CREDENTIAL', 'DIRECTORY_PATH') IS NOT NULL AND LOWER('dir_path') <> LOWER('DIRECTORY_PATH')
    BEGIN
        EXEC('UPDATE AD_COMPANY_CREDENTIAL SET DIRECTORY_PATH = dir_path WHERE DIRECTORY_PATH IS NULL AND dir_path IS NOT NULL');
        ALTER TABLE AD_COMPANY_CREDENTIAL DROP COLUMN dir_path;
    END
    ELSE
    BEGIN
        EXEC sp_rename 'AD_COMPANY_CREDENTIAL.dir_path', 'DIRECTORY_PATH', 'COLUMN';
    END
END
GO
IF COL_LENGTH('AD_COMPANY_CREDENTIAL', 'created_by') IS NOT NULL AND COL_LENGTH('AD_COMPANY_CREDENTIAL', 'CREATED_BY') IS NULL
    EXEC sp_rename 'AD_COMPANY_CREDENTIAL.created_by', 'CREATED_BY', 'COLUMN';
GO
IF COL_LENGTH('AD_COMPANY_CREDENTIAL', 'created_at') IS NOT NULL
BEGIN
    IF COL_LENGTH('AD_COMPANY_CREDENTIAL', 'CREATED_DATE') IS NOT NULL AND LOWER('created_at') <> LOWER('CREATED_DATE')
    BEGIN
        EXEC('UPDATE AD_COMPANY_CREDENTIAL SET CREATED_DATE = created_at WHERE CREATED_DATE IS NULL AND created_at IS NOT NULL');
        ALTER TABLE AD_COMPANY_CREDENTIAL DROP COLUMN created_at;
    END
    ELSE
    BEGIN
        EXEC sp_rename 'AD_COMPANY_CREDENTIAL.created_at', 'CREATED_DATE', 'COLUMN';
    END
END
GO
IF COL_LENGTH('AD_COMPANY_CREDENTIAL', 'updated_by') IS NOT NULL AND COL_LENGTH('AD_COMPANY_CREDENTIAL', 'UPDATED_BY') IS NULL
    EXEC sp_rename 'AD_COMPANY_CREDENTIAL.updated_by', 'UPDATED_BY', 'COLUMN';
GO
IF COL_LENGTH('AD_COMPANY_CREDENTIAL', 'updated_at') IS NOT NULL
BEGIN
    IF COL_LENGTH('AD_COMPANY_CREDENTIAL', 'UPDATED_DATE') IS NOT NULL AND LOWER('updated_at') <> LOWER('UPDATED_DATE')
    BEGIN
        EXEC('UPDATE AD_COMPANY_CREDENTIAL SET UPDATED_DATE = updated_at WHERE UPDATED_DATE IS NULL AND updated_at IS NOT NULL');
        ALTER TABLE AD_COMPANY_CREDENTIAL DROP COLUMN updated_at;
    END
    ELSE
    BEGIN
        EXEC sp_rename 'AD_COMPANY_CREDENTIAL.updated_at', 'UPDATED_DATE', 'COLUMN';
    END
END
GO

IF OBJECT_ID('AD_COMPANY_CREDENTIAL', 'U') IS NOT NULL
BEGIN
    ALTER TABLE AD_COMPANY_CREDENTIAL ALTER COLUMN COMPANY_NAME NVARCHAR(100) NOT NULL;
    ALTER TABLE AD_COMPANY_CREDENTIAL ALTER COLUMN SHORT_NAME NVARCHAR(50);
    ALTER TABLE AD_COMPANY_CREDENTIAL ALTER COLUMN ADDRESS NVARCHAR(500);
    ALTER TABLE AD_COMPANY_CREDENTIAL ALTER COLUMN CITY NVARCHAR(50);
    ALTER TABLE AD_COMPANY_CREDENTIAL ALTER COLUMN STATE NVARCHAR(50);
    ALTER TABLE AD_COMPANY_CREDENTIAL ALTER COLUMN COUNTRY NVARCHAR(50);
    ALTER TABLE AD_COMPANY_CREDENTIAL ALTER COLUMN PINCODE NVARCHAR(10);
    ALTER TABLE AD_COMPANY_CREDENTIAL ALTER COLUMN GST_IN NVARCHAR(15);
    ALTER TABLE AD_COMPANY_CREDENTIAL ALTER COLUMN DB_SOURCE_NAME NVARCHAR(50);
    ALTER TABLE AD_COMPANY_CREDENTIAL ALTER COLUMN LOGO_FILE_NAME NVARCHAR(100);
    ALTER TABLE AD_COMPANY_CREDENTIAL ALTER COLUMN LOGIN_BG_FILE_NAME NVARCHAR(100);
    ALTER TABLE AD_COMPANY_CREDENTIAL ALTER COLUMN DIRECTORY_PATH NVARCHAR(1000);
    ALTER TABLE AD_COMPANY_CREDENTIAL ALTER COLUMN CREATED_BY NVARCHAR(100);
    ALTER TABLE AD_COMPANY_CREDENTIAL ALTER COLUMN CREATED_DATE DATETIME;
    ALTER TABLE AD_COMPANY_CREDENTIAL ALTER COLUMN UPDATED_BY NVARCHAR(100);
    ALTER TABLE AD_COMPANY_CREDENTIAL ALTER COLUMN UPDATED_DATE DATETIME;
END
GO

IF OBJECT_ID('AD_COMPANY_CREDENTIAL', 'U') IS NOT NULL
BEGIN
    IF COL_LENGTH('AD_COMPANY_CREDENTIAL', 'IS_ACTIVE') IS NULL
    BEGIN
        ALTER TABLE AD_COMPANY_CREDENTIAL ADD IS_ACTIVE BIT DEFAULT 1;
    END
END
GO

IF OBJECT_ID('AD_COMPANY_CREDENTIAL', 'U') IS NOT NULL
BEGIN
    DECLARE @comp_pk NVARCHAR(256);
    SELECT TOP 1 @comp_pk = name FROM sys.key_constraints WHERE parent_object_id = OBJECT_ID('AD_COMPANY_CREDENTIAL') AND type = 'PK';
    IF @comp_pk IS NOT NULL AND @comp_pk <> 'PK_AD_COMPANY_CREDENTIAL' AND NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE referenced_object_id = OBJECT_ID('AD_COMPANY_CREDENTIAL'))
    BEGIN
        DECLARE @drop_comp_pk NVARCHAR(MAX) = 'ALTER TABLE AD_COMPANY_CREDENTIAL DROP CONSTRAINT ' + @comp_pk;
        EXEC(@drop_comp_pk);
    END
    IF NOT EXISTS (SELECT 1 FROM sys.key_constraints WHERE parent_object_id = OBJECT_ID('AD_COMPANY_CREDENTIAL') AND type = 'PK')
    BEGIN
        ALTER TABLE AD_COMPANY_CREDENTIAL ADD CONSTRAINT PK_AD_COMPANY_CREDENTIAL PRIMARY KEY (id);
    END
END
GO


-- ==========================================
-- 3. AD_DIVISION_MASTER -> AD_DIVISION
-- ==========================================
IF OBJECT_ID('dbo.sp_RenameTableCasingAndPrefix', 'P') IS NOT NULL
BEGIN
    EXEC dbo.sp_RenameTableCasingAndPrefix 'AD_DIVISION_MASTER', 'AD_DIVISION';
END
ELSE
BEGIN
    IF OBJECT_ID('AD_DIVISION_MASTER', 'U') IS NOT NULL AND OBJECT_ID('AD_DIVISION', 'U') IS NULL
        EXEC sp_rename 'AD_DIVISION_MASTER', 'AD_DIVISION';
END
GO

IF COL_LENGTH('AD_DIVISION', 'company_id') IS NOT NULL AND COL_LENGTH('AD_DIVISION', 'COMPANY_ID') IS NULL
    EXEC sp_rename 'AD_DIVISION.company_id', 'COMPANY_ID', 'COLUMN';
GO
IF COL_LENGTH('AD_DIVISION', 'division_name') IS NOT NULL AND COL_LENGTH('AD_DIVISION', 'DIVISION_NAME') IS NULL
    EXEC sp_rename 'AD_DIVISION.division_name', 'DIVISION_NAME', 'COLUMN';
GO
IF COL_LENGTH('AD_DIVISION', 'description') IS NOT NULL AND COL_LENGTH('AD_DIVISION', 'DESCRIPTION') IS NULL
    EXEC sp_rename 'AD_DIVISION.description', 'DESCRIPTION', 'COLUMN';
GO
IF COL_LENGTH('AD_DIVISION', 'address') IS NOT NULL AND COL_LENGTH('AD_DIVISION', 'ADDRESS') IS NULL
    EXEC sp_rename 'AD_DIVISION.address', 'ADDRESS', 'COLUMN';
GO
IF COL_LENGTH('AD_DIVISION', 'city') IS NOT NULL AND COL_LENGTH('AD_DIVISION', 'CITY') IS NULL
    EXEC sp_rename 'AD_DIVISION.city', 'CITY', 'COLUMN';
GO
IF COL_LENGTH('AD_DIVISION', 'state') IS NOT NULL AND COL_LENGTH('AD_DIVISION', 'STATE') IS NULL
    EXEC sp_rename 'AD_DIVISION.state', 'STATE', 'COLUMN';
GO
IF COL_LENGTH('AD_DIVISION', 'country') IS NOT NULL AND COL_LENGTH('AD_DIVISION', 'COUNTRY') IS NULL
    EXEC sp_rename 'AD_DIVISION.country', 'COUNTRY', 'COLUMN';
GO
IF COL_LENGTH('AD_DIVISION', 'pincode') IS NOT NULL AND COL_LENGTH('AD_DIVISION', 'PINCODE') IS NULL
    EXEC sp_rename 'AD_DIVISION.pincode', 'PINCODE', 'COLUMN';
GO
IF COL_LENGTH('AD_DIVISION', 'gst_in') IS NOT NULL AND COL_LENGTH('AD_DIVISION', 'GST_IN') IS NULL
    EXEC sp_rename 'AD_DIVISION.gst_in', 'GST_IN', 'COLUMN';
GO
IF COL_LENGTH('AD_DIVISION', 'state_cd') IS NOT NULL
BEGIN
    IF COL_LENGTH('AD_DIVISION', 'STATE_CODE') IS NOT NULL AND LOWER('state_cd') <> LOWER('STATE_CODE')
    BEGIN
        EXEC('UPDATE AD_DIVISION SET STATE_CODE = state_cd WHERE STATE_CODE IS NULL AND state_cd IS NOT NULL');
        ALTER TABLE AD_DIVISION DROP COLUMN state_cd;
    END
    ELSE
    BEGIN
        EXEC sp_rename 'AD_DIVISION.state_cd', 'STATE_CODE', 'COLUMN';
    END
END
GO
IF COL_LENGTH('AD_DIVISION', 'seq_no') IS NOT NULL
BEGIN
    IF COL_LENGTH('AD_DIVISION', 'SEQUENCE_NO') IS NOT NULL AND LOWER('seq_no') <> LOWER('SEQUENCE_NO')
    BEGIN
        EXEC('UPDATE AD_DIVISION SET SEQUENCE_NO = seq_no WHERE SEQUENCE_NO IS NULL AND seq_no IS NOT NULL');
        ALTER TABLE AD_DIVISION DROP COLUMN seq_no;
    END
    ELSE
    BEGIN
        EXEC sp_rename 'AD_DIVISION.seq_no', 'SEQUENCE_NO', 'COLUMN';
    END
END
GO
IF COL_LENGTH('AD_DIVISION', 'status') IS NOT NULL AND COL_LENGTH('AD_DIVISION', 'STATUS') IS NULL
    EXEC sp_rename 'AD_DIVISION.status', 'STATUS', 'COLUMN';
GO
IF COL_LENGTH('AD_DIVISION', 'created_by') IS NOT NULL AND COL_LENGTH('AD_DIVISION', 'CREATED_BY') IS NULL
    EXEC sp_rename 'AD_DIVISION.created_by', 'CREATED_BY', 'COLUMN';
GO
IF COL_LENGTH('AD_DIVISION', 'created_at') IS NOT NULL
BEGIN
    IF COL_LENGTH('AD_DIVISION', 'CREATED_DATE') IS NOT NULL AND LOWER('created_at') <> LOWER('CREATED_DATE')
    BEGIN
        EXEC('UPDATE AD_DIVISION SET CREATED_DATE = created_at WHERE CREATED_DATE IS NULL AND created_at IS NOT NULL');
        ALTER TABLE AD_DIVISION DROP COLUMN created_at;
    END
    ELSE
    BEGIN
        EXEC sp_rename 'AD_DIVISION.created_at', 'CREATED_DATE', 'COLUMN';
    END
END
GO
IF COL_LENGTH('AD_DIVISION', 'updated_by') IS NOT NULL AND COL_LENGTH('AD_DIVISION', 'UPDATED_BY') IS NULL
    EXEC sp_rename 'AD_DIVISION.updated_by', 'UPDATED_BY', 'COLUMN';
GO
IF COL_LENGTH('AD_DIVISION', 'updated_at') IS NOT NULL
BEGIN
    IF COL_LENGTH('AD_DIVISION', 'UPDATED_DATE') IS NOT NULL AND LOWER('updated_at') <> LOWER('UPDATED_DATE')
    BEGIN
        EXEC('UPDATE AD_DIVISION SET UPDATED_DATE = updated_at WHERE UPDATED_DATE IS NULL AND updated_at IS NOT NULL');
        ALTER TABLE AD_DIVISION DROP COLUMN updated_at;
    END
    ELSE
    BEGIN
        EXEC sp_rename 'AD_DIVISION.updated_at', 'UPDATED_DATE', 'COLUMN';
    END
END
GO

IF OBJECT_ID('AD_DIVISION', 'U') IS NOT NULL
BEGIN
    ALTER TABLE AD_DIVISION ALTER COLUMN COMPANY_ID BIGINT NOT NULL;
    ALTER TABLE AD_DIVISION ALTER COLUMN DIVISION_NAME NVARCHAR(100) NOT NULL;
    ALTER TABLE AD_DIVISION ALTER COLUMN DESCRIPTION NVARCHAR(250);
    ALTER TABLE AD_DIVISION ALTER COLUMN ADDRESS NVARCHAR(500);
    ALTER TABLE AD_DIVISION ALTER COLUMN CITY NVARCHAR(50);
    ALTER TABLE AD_DIVISION ALTER COLUMN STATE NVARCHAR(50);
    ALTER TABLE AD_DIVISION ALTER COLUMN COUNTRY NVARCHAR(50);
    ALTER TABLE AD_DIVISION ALTER COLUMN PINCODE NVARCHAR(10);
    ALTER TABLE AD_DIVISION ALTER COLUMN GST_IN NVARCHAR(15);
    ALTER TABLE AD_DIVISION ALTER COLUMN CREATED_BY NVARCHAR(100);
    ALTER TABLE AD_DIVISION ALTER COLUMN CREATED_DATE DATETIME;
    ALTER TABLE AD_DIVISION ALTER COLUMN UPDATED_BY NVARCHAR(100);
    ALTER TABLE AD_DIVISION ALTER COLUMN UPDATED_DATE DATETIME;
END
GO

IF OBJECT_ID('AD_DIVISION', 'U') IS NOT NULL
BEGIN
    IF COL_LENGTH('AD_DIVISION', 'IS_ACTIVE') IS NULL
    BEGIN
        ALTER TABLE AD_DIVISION ADD IS_ACTIVE BIT DEFAULT 1;
    END
END
GO

IF OBJECT_ID('AD_DIVISION', 'U') IS NOT NULL
BEGIN
    DECLARE @div_pk NVARCHAR(256);
    SELECT TOP 1 @div_pk = name FROM sys.key_constraints WHERE parent_object_id = OBJECT_ID('AD_DIVISION') AND type = 'PK';
    IF @div_pk IS NOT NULL AND @div_pk <> 'PK_AD_DIVISION' AND NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE referenced_object_id = OBJECT_ID('AD_DIVISION'))
    BEGIN
        DECLARE @drop_div_pk NVARCHAR(MAX) = 'ALTER TABLE AD_DIVISION DROP CONSTRAINT ' + @div_pk;
        EXEC(@drop_div_pk);
    END
    IF NOT EXISTS (SELECT 1 FROM sys.key_constraints WHERE parent_object_id = OBJECT_ID('AD_DIVISION') AND type = 'PK')
    BEGIN
        ALTER TABLE AD_DIVISION ADD CONSTRAINT PK_AD_DIVISION PRIMARY KEY (id);
    END
END
GO


-- ==========================================
-- 4. AD_USER_COMPANY_MAPPING, AD_USER_DIVISION_MAPPING
-- ==========================================
IF COL_LENGTH('AD_USER_COMPANY_MAPPING', 'user_id') IS NOT NULL AND COL_LENGTH('AD_USER_COMPANY_MAPPING', 'USER_ID') IS NULL
    EXEC sp_rename 'AD_USER_COMPANY_MAPPING.user_id', 'USER_ID', 'COLUMN';
GO
IF COL_LENGTH('AD_USER_COMPANY_MAPPING', 'company_id') IS NOT NULL AND COL_LENGTH('AD_USER_COMPANY_MAPPING', 'COMPANY_ID') IS NULL
    EXEC sp_rename 'AD_USER_COMPANY_MAPPING.company_id', 'COMPANY_ID', 'COLUMN';
GO
IF COL_LENGTH('AD_USER_COMPANY_MAPPING', 'created_by') IS NOT NULL AND COL_LENGTH('AD_USER_COMPANY_MAPPING', 'CREATED_BY') IS NULL
    EXEC sp_rename 'AD_USER_COMPANY_MAPPING.created_by', 'CREATED_BY', 'COLUMN';
GO
IF COL_LENGTH('AD_USER_COMPANY_MAPPING', 'created_at') IS NOT NULL AND COL_LENGTH('AD_USER_COMPANY_MAPPING', 'CREATED_DATE') IS NULL
    EXEC sp_rename 'AD_USER_COMPANY_MAPPING.created_at', 'CREATED_DATE', 'COLUMN';
GO

IF OBJECT_ID('AD_USER_COMPANY_MAPPING', 'U') IS NOT NULL
BEGIN
    ALTER TABLE AD_USER_COMPANY_MAPPING ALTER COLUMN USER_ID NVARCHAR(50) NOT NULL;
    ALTER TABLE AD_USER_COMPANY_MAPPING ALTER COLUMN COMPANY_ID BIGINT NOT NULL;
    ALTER TABLE AD_USER_COMPANY_MAPPING ALTER COLUMN CREATED_BY NVARCHAR(100);
    ALTER TABLE AD_USER_COMPANY_MAPPING ALTER COLUMN CREATED_DATE DATETIME;
END
GO

IF OBJECT_ID('AD_USER_COMPANY_MAPPING', 'U') IS NOT NULL
BEGIN
    DECLARE @uc_pk NVARCHAR(256);
    SELECT TOP 1 @uc_pk = name FROM sys.key_constraints WHERE parent_object_id = OBJECT_ID('AD_USER_COMPANY_MAPPING') AND type = 'PK';
    IF @uc_pk IS NOT NULL AND @uc_pk <> 'PK_AD_USER_COMPANY_MAPPING' AND NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE referenced_object_id = OBJECT_ID('AD_USER_COMPANY_MAPPING'))
    BEGIN
        DECLARE @drop_uc_pk NVARCHAR(MAX) = 'ALTER TABLE AD_USER_COMPANY_MAPPING DROP CONSTRAINT ' + @uc_pk;
        EXEC(@drop_uc_pk);
    END
    IF NOT EXISTS (SELECT 1 FROM sys.key_constraints WHERE parent_object_id = OBJECT_ID('AD_USER_COMPANY_MAPPING') AND type = 'PK')
    BEGIN
        ALTER TABLE AD_USER_COMPANY_MAPPING ADD CONSTRAINT PK_AD_USER_COMPANY_MAPPING PRIMARY KEY (id);
    END
END
GO

IF COL_LENGTH('AD_USER_DIVISION_MAPPING', 'user_id') IS NOT NULL AND COL_LENGTH('AD_USER_DIVISION_MAPPING', 'USER_ID') IS NULL
    EXEC sp_rename 'AD_USER_DIVISION_MAPPING.user_id', 'USER_ID', 'COLUMN';
GO
IF COL_LENGTH('AD_USER_DIVISION_MAPPING', 'division_id') IS NOT NULL AND COL_LENGTH('AD_USER_DIVISION_MAPPING', 'DIVISION_ID') IS NULL
    EXEC sp_rename 'AD_USER_DIVISION_MAPPING.division_id', 'DIVISION_ID', 'COLUMN';
GO
IF COL_LENGTH('AD_USER_DIVISION_MAPPING', 'created_by') IS NOT NULL AND COL_LENGTH('AD_USER_DIVISION_MAPPING', 'CREATED_BY') IS NULL
    EXEC sp_rename 'AD_USER_DIVISION_MAPPING.created_by', 'CREATED_BY', 'COLUMN';
GO
IF COL_LENGTH('AD_USER_DIVISION_MAPPING', 'created_at') IS NOT NULL AND COL_LENGTH('AD_USER_DIVISION_MAPPING', 'CREATED_DATE') IS NULL
    EXEC sp_rename 'AD_USER_DIVISION_MAPPING.created_at', 'CREATED_DATE', 'COLUMN';
GO

IF OBJECT_ID('AD_USER_DIVISION_MAPPING', 'U') IS NOT NULL
BEGIN
    ALTER TABLE AD_USER_DIVISION_MAPPING ALTER COLUMN USER_ID NVARCHAR(50) NOT NULL;
    ALTER TABLE AD_USER_DIVISION_MAPPING ALTER COLUMN DIVISION_ID BIGINT NOT NULL;
    ALTER TABLE AD_USER_DIVISION_MAPPING ALTER COLUMN CREATED_BY NVARCHAR(100);
    ALTER TABLE AD_USER_DIVISION_MAPPING ALTER COLUMN CREATED_DATE DATETIME;
END
GO

IF OBJECT_ID('AD_USER_DIVISION_MAPPING', 'U') IS NOT NULL
BEGIN
    DECLARE @ud_pk NVARCHAR(256);
    SELECT TOP 1 @ud_pk = name FROM sys.key_constraints WHERE parent_object_id = OBJECT_ID('AD_USER_DIVISION_MAPPING') AND type = 'PK';
    IF @ud_pk IS NOT NULL AND @ud_pk <> 'PK_AD_USER_DIVISION_MAPPING' AND NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE referenced_object_id = OBJECT_ID('AD_USER_DIVISION_MAPPING'))
    BEGIN
        DECLARE @drop_ud_pk NVARCHAR(MAX) = 'ALTER TABLE AD_USER_DIVISION_MAPPING DROP CONSTRAINT ' + @ud_pk;
        EXEC(@drop_ud_pk);
    END
    IF NOT EXISTS (SELECT 1 FROM sys.key_constraints WHERE parent_object_id = OBJECT_ID('AD_USER_DIVISION_MAPPING') AND type = 'PK')
    BEGIN
        ALTER TABLE AD_USER_DIVISION_MAPPING ADD CONSTRAINT PK_AD_USER_DIVISION_MAPPING PRIMARY KEY (id);
    END
END
GO


-- ==========================================
-- 5. AD_USER_SESSION_AUDIT, AD_USER_SESSION_ACTIVITY
-- ==========================================
IF OBJECT_ID('AD_USER_SESSION_AUDIT', 'U') IS NOT NULL
BEGIN
    DECLARE @usa_pk NVARCHAR(256);
    SELECT TOP 1 @usa_pk = name FROM sys.key_constraints WHERE parent_object_id = OBJECT_ID('AD_USER_SESSION_AUDIT') AND type = 'PK';
    IF @usa_pk IS NOT NULL AND @usa_pk <> 'PK_AD_USER_SESSION_AUDIT' AND NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE referenced_object_id = OBJECT_ID('AD_USER_SESSION_AUDIT'))
    BEGIN
        DECLARE @drop_usa_pk NVARCHAR(MAX) = 'ALTER TABLE AD_USER_SESSION_AUDIT DROP CONSTRAINT ' + @usa_pk;
        EXEC(@drop_usa_pk);
    END
    IF NOT EXISTS (SELECT 1 FROM sys.key_constraints WHERE parent_object_id = OBJECT_ID('AD_USER_SESSION_AUDIT') AND type = 'PK')
    BEGIN
        ALTER TABLE AD_USER_SESSION_AUDIT ADD CONSTRAINT PK_AD_USER_SESSION_AUDIT PRIMARY KEY (id);
    END
END
GO

IF OBJECT_ID('AD_USER_SESSION_ACTIVITY', 'U') IS NOT NULL
BEGIN
    DECLARE @usact_pk NVARCHAR(256);
    SELECT TOP 1 @usact_pk = name FROM sys.key_constraints WHERE parent_object_id = OBJECT_ID('AD_USER_SESSION_ACTIVITY') AND type = 'PK';
    IF @usact_pk IS NOT NULL AND @usact_pk <> 'PK_AD_USER_SESSION_ACTIVITY' AND NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE referenced_object_id = OBJECT_ID('AD_USER_SESSION_ACTIVITY'))
    BEGIN
        DECLARE @drop_usact_pk NVARCHAR(MAX) = 'ALTER TABLE AD_USER_SESSION_ACTIVITY DROP CONSTRAINT ' + @usact_pk;
        EXEC(@drop_usact_pk);
    END
    IF NOT EXISTS (SELECT 1 FROM sys.key_constraints WHERE parent_object_id = OBJECT_ID('AD_USER_SESSION_ACTIVITY') AND type = 'PK')
    BEGIN
        ALTER TABLE AD_USER_SESSION_ACTIVITY ADD CONSTRAINT PK_AD_USER_SESSION_ACTIVITY PRIMARY KEY (id);
    END
END
GO
