-- V005__Induction_Module.sql
-- Phase 5: Induction & Interview Modules Schema Standardization
-- Renames and normalizes:
-- 1. IND_INDUCTION_MASTER -> HR_INDUCTION
-- 2. IND_INDUCTION_ASSIGNMENT -> HR_INDUCTION_ASSIGNMENT
-- 3. IND_INDUCTION_TRAINING_DETAIL -> HR_INDUCTION_TRAINING
-- 4. IND_INTERVIEW_MASTER -> HR_INTERVIEW
-- 5. hr_induction_round_master -> HR_INDUCTION_ROUND
-- 6. IND_VERIFICATION_CRITERIA -> HR_VERIFICATION_CRITERIA
-- 7. IND_EMAIL_CONTENT -> HR_EMAIL_CONTENT

-- ==========================================
-- Drop referencing Foreign Key constraints dynamically to avoid cascade/drop errors
-- ==========================================
DECLARE @sql NVARCHAR(MAX) = N'';
SELECT @sql += N'ALTER TABLE ' + QUOTENAME(OBJECT_SCHEMA_NAME(parent_object_id)) + '.' + QUOTENAME(OBJECT_NAME(parent_object_id)) + 
               ' DROP CONSTRAINT ' + QUOTENAME(name) + ';' + CHAR(13) + CHAR(10)
FROM sys.foreign_keys
WHERE referenced_object_id IN (
    OBJECT_ID('IND_INDUCTION_MASTER'),
    OBJECT_ID('IND_INDUCTION_ASSIGNMENT'),
    OBJECT_ID('IND_INDUCTION_TRAINING_DETAIL'),
    OBJECT_ID('IND_INTERVIEW_MASTER'),
    OBJECT_ID('hr_induction_round_master'),
    OBJECT_ID('IND_VERIFICATION_CRITERIA'),
    OBJECT_ID('IND_EMAIL_CONTENT')
);
IF @sql <> N''
BEGIN
    EXEC sp_executesql @sql;
END
GO

-- ==========================================
-- 1. HR_INDUCTION (from IND_INDUCTION_MASTER)
-- ==========================================
IF OBJECT_ID('dbo.sp_RenameTableCasingAndPrefix', 'P') IS NOT NULL
BEGIN
    EXEC dbo.sp_RenameTableCasingAndPrefix 'IND_INDUCTION_MASTER', 'HR_INDUCTION';
END
ELSE
BEGIN
    IF OBJECT_ID('IND_INDUCTION_MASTER', 'U') IS NOT NULL AND OBJECT_ID('HR_INDUCTION', 'U') IS NULL
        EXEC sp_rename 'IND_INDUCTION_MASTER', 'HR_INDUCTION';
END
GO

IF OBJECT_ID('HR_INDUCTION', 'U') IS NOT NULL
BEGIN
    IF COL_LENGTH('HR_INDUCTION', 'induction_details') IS NOT NULL AND COL_LENGTH('HR_INDUCTION', 'INDUCTION_DETAILS') IS NULL EXEC sp_rename 'HR_INDUCTION.induction_details', 'INDUCTION_DETAILS', 'COLUMN';
    IF COL_LENGTH('HR_INDUCTION', 'answer') IS NOT NULL AND COL_LENGTH('HR_INDUCTION', 'ANSWER') IS NULL EXEC sp_rename 'HR_INDUCTION.answer', 'ANSWER', 'COLUMN';
    IF COL_LENGTH('HR_INDUCTION', 'department_codes') IS NOT NULL AND COL_LENGTH('HR_INDUCTION', 'DEPARTMENT_CODES') IS NULL EXEC sp_rename 'HR_INDUCTION.department_codes', 'DEPARTMENT_CODES', 'COLUMN';
    IF COL_LENGTH('HR_INDUCTION', 'level_codes') IS NOT NULL AND COL_LENGTH('HR_INDUCTION', 'LEVEL_CODES') IS NULL EXEC sp_rename 'HR_INDUCTION.level_codes', 'LEVEL_CODES', 'COLUMN';
    IF COL_LENGTH('HR_INDUCTION', 'induction_round') IS NOT NULL AND COL_LENGTH('HR_INDUCTION', 'INDUCTION_ROUND') IS NULL EXEC sp_rename 'HR_INDUCTION.induction_round', 'INDUCTION_ROUND', 'COLUMN';
    IF COL_LENGTH('HR_INDUCTION', 'attachment_required') IS NOT NULL AND COL_LENGTH('HR_INDUCTION', 'ATTACHMENT_REQUIRED') IS NULL EXEC sp_rename 'HR_INDUCTION.attachment_required', 'ATTACHMENT_REQUIRED', 'COLUMN';
    IF COL_LENGTH('HR_INDUCTION', 'induction_attachment') IS NOT NULL AND COL_LENGTH('HR_INDUCTION', 'INDUCTION_ATTACHMENT') IS NULL EXEC sp_rename 'HR_INDUCTION.induction_attachment', 'INDUCTION_ATTACHMENT', 'COLUMN';
    IF COL_LENGTH('HR_INDUCTION', 'status') IS NOT NULL AND COL_LENGTH('HR_INDUCTION', 'STATUS') IS NULL EXEC sp_rename 'HR_INDUCTION.status', 'STATUS', 'COLUMN';
    IF COL_LENGTH('HR_INDUCTION', 'created_by') IS NOT NULL AND COL_LENGTH('HR_INDUCTION', 'CREATED_USER') IS NULL EXEC sp_rename 'HR_INDUCTION.created_by', 'CREATED_USER', 'COLUMN';
    IF COL_LENGTH('HR_INDUCTION', 'created_at') IS NOT NULL AND COL_LENGTH('HR_INDUCTION', 'CREATED_DATE') IS NULL EXEC sp_rename 'HR_INDUCTION.created_at', 'CREATED_DATE', 'COLUMN';
    IF COL_LENGTH('HR_INDUCTION', 'updated_by') IS NOT NULL AND COL_LENGTH('HR_INDUCTION', 'UPDATED_USER') IS NULL EXEC sp_rename 'HR_INDUCTION.updated_by', 'UPDATED_USER', 'COLUMN';
    IF COL_LENGTH('HR_INDUCTION', 'updated_at') IS NOT NULL AND COL_LENGTH('HR_INDUCTION', 'UPDATED_DATE') IS NULL EXEC sp_rename 'HR_INDUCTION.updated_at', 'UPDATED_DATE', 'COLUMN';
END
GO

IF OBJECT_ID('HR_INDUCTION', 'U') IS NOT NULL
BEGIN
    ALTER TABLE HR_INDUCTION ALTER COLUMN INDUCTION_ATTACHMENT NVARCHAR(1000);
    ALTER TABLE HR_INDUCTION ALTER COLUMN DEPARTMENT_CODES NVARCHAR(100);
    ALTER TABLE HR_INDUCTION ALTER COLUMN LEVEL_CODES NVARCHAR(100);
    ALTER TABLE HR_INDUCTION ALTER COLUMN STATUS NVARCHAR(20);
    ALTER TABLE HR_INDUCTION ALTER COLUMN CREATED_USER NVARCHAR(100);
    ALTER TABLE HR_INDUCTION ALTER COLUMN CREATED_DATE DATETIME;
    ALTER TABLE HR_INDUCTION ALTER COLUMN UPDATED_USER NVARCHAR(100);
    ALTER TABLE HR_INDUCTION ALTER COLUMN UPDATED_DATE DATETIME;

    IF COL_LENGTH('HR_INDUCTION', 'IS_ACTIVE') IS NULL
        ALTER TABLE HR_INDUCTION ADD IS_ACTIVE BIT DEFAULT 1;
END
GO

-- PK
IF OBJECT_ID('HR_INDUCTION', 'U') IS NOT NULL
BEGIN
    DECLARE @ind_pk NVARCHAR(256);
    SELECT TOP 1 @ind_pk = name FROM sys.key_constraints WHERE parent_object_id = OBJECT_ID('HR_INDUCTION') AND type = 'PK';
    IF @ind_pk IS NOT NULL AND @ind_pk <> 'PK_HR_INDUCTION' AND NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE referenced_object_id = OBJECT_ID('HR_INDUCTION'))
    BEGIN
        DECLARE @drop_ind_pk NVARCHAR(MAX) = 'ALTER TABLE HR_INDUCTION DROP CONSTRAINT ' + @ind_pk;
        EXEC(@drop_ind_pk);
    END
    IF NOT EXISTS (SELECT 1 FROM sys.key_constraints WHERE parent_object_id = OBJECT_ID('HR_INDUCTION') AND type = 'PK')
    BEGIN
        ALTER TABLE HR_INDUCTION ADD CONSTRAINT PK_HR_INDUCTION PRIMARY KEY (id);
    END
END
GO


-- ==========================================
-- 2. HR_INDUCTION_ASSIGNMENT (from IND_INDUCTION_ASSIGNMENT)
-- ==========================================
IF OBJECT_ID('dbo.sp_RenameTableCasingAndPrefix', 'P') IS NOT NULL
BEGIN
    EXEC dbo.sp_RenameTableCasingAndPrefix 'IND_INDUCTION_ASSIGNMENT', 'HR_INDUCTION_ASSIGNMENT';
END
ELSE
BEGIN
    IF OBJECT_ID('IND_INDUCTION_ASSIGNMENT', 'U') IS NOT NULL AND OBJECT_ID('HR_INDUCTION_ASSIGNMENT', 'U') IS NULL
        EXEC sp_rename 'IND_INDUCTION_ASSIGNMENT', 'HR_INDUCTION_ASSIGNMENT';
END
GO

IF OBJECT_ID('HR_INDUCTION_ASSIGNMENT', 'U') IS NOT NULL
BEGIN
    IF COL_LENGTH('HR_INDUCTION_ASSIGNMENT', 'emp_code') IS NOT NULL AND COL_LENGTH('HR_INDUCTION_ASSIGNMENT', 'EMP_CODE') IS NULL EXEC sp_rename 'HR_INDUCTION_ASSIGNMENT.emp_code', 'EMP_CODE', 'COLUMN';
    IF COL_LENGTH('HR_INDUCTION_ASSIGNMENT', 'emp_name') IS NOT NULL AND COL_LENGTH('HR_INDUCTION_ASSIGNMENT', 'EMP_NAME') IS NULL EXEC sp_rename 'HR_INDUCTION_ASSIGNMENT.emp_name', 'EMP_NAME', 'COLUMN';
    IF COL_LENGTH('HR_INDUCTION_ASSIGNMENT', 'old_emp_code') IS NOT NULL AND COL_LENGTH('HR_INDUCTION_ASSIGNMENT', 'OLD_EMP_CODE') IS NULL EXEC sp_rename 'HR_INDUCTION_ASSIGNMENT.old_emp_code', 'OLD_EMP_CODE', 'COLUMN';
    IF COL_LENGTH('HR_INDUCTION_ASSIGNMENT', 'department') IS NOT NULL AND COL_LENGTH('HR_INDUCTION_ASSIGNMENT', 'DEPARTMENT') IS NULL EXEC sp_rename 'HR_INDUCTION_ASSIGNMENT.department', 'DEPARTMENT', 'COLUMN';
    IF COL_LENGTH('HR_INDUCTION_ASSIGNMENT', 'designation') IS NOT NULL AND COL_LENGTH('HR_INDUCTION_ASSIGNMENT', 'DESIGNATION') IS NULL EXEC sp_rename 'HR_INDUCTION_ASSIGNMENT.designation', 'DESIGNATION', 'COLUMN';
    IF COL_LENGTH('HR_INDUCTION_ASSIGNMENT', 'induction_round') IS NOT NULL AND COL_LENGTH('HR_INDUCTION_ASSIGNMENT', 'INDUCTION_ROUND') IS NULL EXEC sp_rename 'HR_INDUCTION_ASSIGNMENT.induction_round', 'INDUCTION_ROUND', 'COLUMN';
    IF COL_LENGTH('HR_INDUCTION_ASSIGNMENT', 'screening_level') IS NOT NULL AND COL_LENGTH('HR_INDUCTION_ASSIGNMENT', 'SCREENING_LEVEL') IS NULL EXEC sp_rename 'HR_INDUCTION_ASSIGNMENT.screening_level', 'SCREENING_LEVEL', 'COLUMN';
    IF COL_LENGTH('HR_INDUCTION_ASSIGNMENT', 'induction_date') IS NOT NULL AND COL_LENGTH('HR_INDUCTION_ASSIGNMENT', 'INDUCTION_DATE') IS NULL EXEC sp_rename 'HR_INDUCTION_ASSIGNMENT.induction_date', 'INDUCTION_DATE', 'COLUMN';
    IF COL_LENGTH('HR_INDUCTION_ASSIGNMENT', 'induction_time') IS NOT NULL AND COL_LENGTH('HR_INDUCTION_ASSIGNMENT', 'INDUCTION_TIME') IS NULL EXEC sp_rename 'HR_INDUCTION_ASSIGNMENT.induction_time', 'INDUCTION_TIME', 'COLUMN';
    IF COL_LENGTH('HR_INDUCTION_ASSIGNMENT', 'trainer_name') IS NOT NULL AND COL_LENGTH('HR_INDUCTION_ASSIGNMENT', 'TRAINER_NAME') IS NULL EXEC sp_rename 'HR_INDUCTION_ASSIGNMENT.trainer_name', 'TRAINER_NAME', 'COLUMN';
    IF COL_LENGTH('HR_INDUCTION_ASSIGNMENT', 'current_status') IS NOT NULL AND COL_LENGTH('HR_INDUCTION_ASSIGNMENT', 'CURRENT_STATUS') IS NULL EXEC sp_rename 'HR_INDUCTION_ASSIGNMENT.current_status', 'CURRENT_STATUS', 'COLUMN';
    IF COL_LENGTH('HR_INDUCTION_ASSIGNMENT', 'induction_status') IS NOT NULL AND COL_LENGTH('HR_INDUCTION_ASSIGNMENT', 'INDUCTION_STATUS') IS NULL EXEC sp_rename 'HR_INDUCTION_ASSIGNMENT.induction_status', 'INDUCTION_STATUS', 'COLUMN';
    IF COL_LENGTH('HR_INDUCTION_ASSIGNMENT', 'remarks') IS NOT NULL AND COL_LENGTH('HR_INDUCTION_ASSIGNMENT', 'REMARKS') IS NULL EXEC sp_rename 'HR_INDUCTION_ASSIGNMENT.remarks', 'REMARKS', 'COLUMN';
    IF COL_LENGTH('HR_INDUCTION_ASSIGNMENT', 'trainer_emp_code') IS NOT NULL AND COL_LENGTH('HR_INDUCTION_ASSIGNMENT', 'TRAINER_EMP_CODE') IS NULL EXEC sp_rename 'HR_INDUCTION_ASSIGNMENT.trainer_emp_code', 'TRAINER_EMP_CODE', 'COLUMN';
    IF COL_LENGTH('HR_INDUCTION_ASSIGNMENT', 'average_rating') IS NOT NULL AND COL_LENGTH('HR_INDUCTION_ASSIGNMENT', 'AVERAGE_RATING') IS NULL EXEC sp_rename 'HR_INDUCTION_ASSIGNMENT.average_rating', 'AVERAGE_RATING', 'COLUMN';
    IF COL_LENGTH('HR_INDUCTION_ASSIGNMENT', 'training_started_at') IS NOT NULL AND COL_LENGTH('HR_INDUCTION_ASSIGNMENT', 'TRAINING_STARTED_AT') IS NULL EXEC sp_rename 'HR_INDUCTION_ASSIGNMENT.training_started_at', 'TRAINING_STARTED_AT', 'COLUMN';
    IF COL_LENGTH('HR_INDUCTION_ASSIGNMENT', 'training_completed_at') IS NOT NULL AND COL_LENGTH('HR_INDUCTION_ASSIGNMENT', 'TRAINING_COMPLETED_AT') IS NULL EXEC sp_rename 'HR_INDUCTION_ASSIGNMENT.training_completed_at', 'TRAINING_COMPLETED_AT', 'COLUMN';
    IF COL_LENGTH('HR_INDUCTION_ASSIGNMENT', 'created_by') IS NOT NULL AND COL_LENGTH('HR_INDUCTION_ASSIGNMENT', 'CREATED_USER') IS NULL EXEC sp_rename 'HR_INDUCTION_ASSIGNMENT.created_by', 'CREATED_USER', 'COLUMN';
    IF COL_LENGTH('HR_INDUCTION_ASSIGNMENT', 'created_at') IS NOT NULL AND COL_LENGTH('HR_INDUCTION_ASSIGNMENT', 'CREATED_DATE') IS NULL EXEC sp_rename 'HR_INDUCTION_ASSIGNMENT.created_at', 'CREATED_DATE', 'COLUMN';
    IF COL_LENGTH('HR_INDUCTION_ASSIGNMENT', 'updated_by') IS NOT NULL AND COL_LENGTH('HR_INDUCTION_ASSIGNMENT', 'UPDATED_USER') IS NULL EXEC sp_rename 'HR_INDUCTION_ASSIGNMENT.updated_by', 'UPDATED_USER', 'COLUMN';
    IF COL_LENGTH('HR_INDUCTION_ASSIGNMENT', 'updated_at') IS NOT NULL AND COL_LENGTH('HR_INDUCTION_ASSIGNMENT', 'UPDATED_DATE') IS NULL EXEC sp_rename 'HR_INDUCTION_ASSIGNMENT.updated_at', 'UPDATED_DATE', 'COLUMN';
END
GO

IF OBJECT_ID('HR_INDUCTION_ASSIGNMENT', 'U') IS NOT NULL
BEGIN
    ALTER TABLE HR_INDUCTION_ASSIGNMENT ALTER COLUMN EMP_CODE NVARCHAR(50) NOT NULL;
    ALTER TABLE HR_INDUCTION_ASSIGNMENT ALTER COLUMN EMP_NAME NVARCHAR(100);
    ALTER TABLE HR_INDUCTION_ASSIGNMENT ALTER COLUMN REMARKS NVARCHAR(MAX);
    ALTER TABLE HR_INDUCTION_ASSIGNMENT ALTER COLUMN CREATED_USER NVARCHAR(100);
    ALTER TABLE HR_INDUCTION_ASSIGNMENT ALTER COLUMN CREATED_DATE DATETIME;
    ALTER TABLE HR_INDUCTION_ASSIGNMENT ALTER COLUMN UPDATED_USER NVARCHAR(100);
    ALTER TABLE HR_INDUCTION_ASSIGNMENT ALTER COLUMN UPDATED_DATE DATETIME;

    IF COL_LENGTH('HR_INDUCTION_ASSIGNMENT', 'IS_ACTIVE') IS NULL
        ALTER TABLE HR_INDUCTION_ASSIGNMENT ADD IS_ACTIVE BIT DEFAULT 1;
END
GO

-- PK
IF OBJECT_ID('HR_INDUCTION_ASSIGNMENT', 'U') IS NOT NULL
BEGIN
    DECLARE @asg_pk NVARCHAR(256);
    SELECT TOP 1 @asg_pk = name FROM sys.key_constraints WHERE parent_object_id = OBJECT_ID('HR_INDUCTION_ASSIGNMENT') AND type = 'PK';
    IF @asg_pk IS NOT NULL AND @asg_pk <> 'PK_HR_INDUCTION_ASSIGNMENT' AND NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE referenced_object_id = OBJECT_ID('HR_INDUCTION_ASSIGNMENT'))
    BEGIN
        DECLARE @drop_asg_pk NVARCHAR(MAX) = 'ALTER TABLE HR_INDUCTION_ASSIGNMENT DROP CONSTRAINT ' + @asg_pk;
        EXEC(@drop_asg_pk);
    END
    IF NOT EXISTS (SELECT 1 FROM sys.key_constraints WHERE parent_object_id = OBJECT_ID('HR_INDUCTION_ASSIGNMENT') AND type = 'PK')
    BEGIN
        ALTER TABLE HR_INDUCTION_ASSIGNMENT ADD CONSTRAINT PK_HR_INDUCTION_ASSIGNMENT PRIMARY KEY (id);
    END
END
GO


-- ==========================================
-- 3. HR_INDUCTION_TRAINING (from IND_INDUCTION_TRAINING_DETAIL)
-- ==========================================
IF OBJECT_ID('dbo.sp_RenameTableCasingAndPrefix', 'P') IS NOT NULL
BEGIN
    EXEC dbo.sp_RenameTableCasingAndPrefix 'IND_INDUCTION_TRAINING_DETAIL', 'HR_INDUCTION_TRAINING';
END
ELSE
BEGIN
    IF OBJECT_ID('IND_INDUCTION_TRAINING_DETAIL', 'U') IS NOT NULL AND OBJECT_ID('HR_INDUCTION_TRAINING', 'U') IS NULL
        EXEC sp_rename 'IND_INDUCTION_TRAINING_DETAIL', 'HR_INDUCTION_TRAINING';
END
GO

IF OBJECT_ID('HR_INDUCTION_TRAINING', 'U') IS NOT NULL
BEGIN
    IF COL_LENGTH('HR_INDUCTION_TRAINING', 'assignment_id') IS NOT NULL AND COL_LENGTH('HR_INDUCTION_TRAINING', 'ASSIGNMENT_ID') IS NULL EXEC sp_rename 'HR_INDUCTION_TRAINING.assignment_id', 'ASSIGNMENT_ID', 'COLUMN';
    IF COL_LENGTH('HR_INDUCTION_TRAINING', 'induction_master_id') IS NOT NULL AND COL_LENGTH('HR_INDUCTION_TRAINING', 'INDUCTION_MASTER_ID') IS NULL EXEC sp_rename 'HR_INDUCTION_TRAINING.induction_master_id', 'INDUCTION_MASTER_ID', 'COLUMN';
    IF COL_LENGTH('HR_INDUCTION_TRAINING', 'trainer_status') IS NOT NULL AND COL_LENGTH('HR_INDUCTION_TRAINING', 'TRAINER_STATUS') IS NULL EXEC sp_rename 'HR_INDUCTION_TRAINING.trainer_status', 'TRAINER_STATUS', 'COLUMN';
    IF COL_LENGTH('HR_INDUCTION_TRAINING', 'trainer_comments') IS NOT NULL AND COL_LENGTH('HR_INDUCTION_TRAINING', 'TRAINER_COMMENTS') IS NULL EXEC sp_rename 'HR_INDUCTION_TRAINING.trainer_comments', 'TRAINER_COMMENTS', 'COLUMN';
    IF COL_LENGTH('HR_INDUCTION_TRAINING', 'skill_rating') IS NOT NULL AND COL_LENGTH('HR_INDUCTION_TRAINING', 'SKILL_RATING') IS NULL EXEC sp_rename 'HR_INDUCTION_TRAINING.skill_rating', 'SKILL_RATING', 'COLUMN';
    IF COL_LENGTH('HR_INDUCTION_TRAINING', 'trainee_status') IS NOT NULL AND COL_LENGTH('HR_INDUCTION_TRAINING', 'TRAINEE_STATUS') IS NULL EXEC sp_rename 'HR_INDUCTION_TRAINING.trainee_status', 'TRAINEE_STATUS', 'COLUMN';
    IF COL_LENGTH('HR_INDUCTION_TRAINING', 'trainee_comments') IS NOT NULL AND COL_LENGTH('HR_INDUCTION_TRAINING', 'TRAINEE_COMMENTS') IS NULL EXEC sp_rename 'HR_INDUCTION_TRAINING.trainee_comments', 'TRAINEE_COMMENTS', 'COLUMN';
    IF COL_LENGTH('HR_INDUCTION_TRAINING', 'attachment_path') IS NOT NULL AND COL_LENGTH('HR_INDUCTION_TRAINING', 'ATTACHMENT_PATH') IS NULL EXEC sp_rename 'HR_INDUCTION_TRAINING.attachment_path', 'ATTACHMENT_PATH', 'COLUMN';
    IF COL_LENGTH('HR_INDUCTION_TRAINING', 'created_by') IS NOT NULL AND COL_LENGTH('HR_INDUCTION_TRAINING', 'CREATED_USER') IS NULL EXEC sp_rename 'HR_INDUCTION_TRAINING.created_by', 'CREATED_USER', 'COLUMN';
    IF COL_LENGTH('HR_INDUCTION_TRAINING', 'created_at') IS NOT NULL AND COL_LENGTH('HR_INDUCTION_TRAINING', 'CREATED_DATE') IS NULL EXEC sp_rename 'HR_INDUCTION_TRAINING.created_at', 'CREATED_DATE', 'COLUMN';
    IF COL_LENGTH('HR_INDUCTION_TRAINING', 'updated_by') IS NOT NULL AND COL_LENGTH('HR_INDUCTION_TRAINING', 'UPDATED_USER') IS NULL EXEC sp_rename 'HR_INDUCTION_TRAINING.updated_by', 'UPDATED_USER', 'COLUMN';
    IF COL_LENGTH('HR_INDUCTION_TRAINING', 'updated_at') IS NOT NULL AND COL_LENGTH('HR_INDUCTION_TRAINING', 'UPDATED_DATE') IS NULL EXEC sp_rename 'HR_INDUCTION_TRAINING.updated_at', 'UPDATED_DATE', 'COLUMN';
END
GO

IF OBJECT_ID('HR_INDUCTION_TRAINING', 'U') IS NOT NULL
BEGIN
    ALTER TABLE HR_INDUCTION_TRAINING ALTER COLUMN ATTACHMENT_PATH NVARCHAR(1000);
    ALTER TABLE HR_INDUCTION_TRAINING ALTER COLUMN TRAINER_STATUS NVARCHAR(20);
    ALTER TABLE HR_INDUCTION_TRAINING ALTER COLUMN TRAINEE_STATUS NVARCHAR(20);
    ALTER TABLE HR_INDUCTION_TRAINING ALTER COLUMN CREATED_USER NVARCHAR(100);
    ALTER TABLE HR_INDUCTION_TRAINING ALTER COLUMN CREATED_DATE DATETIME;
    ALTER TABLE HR_INDUCTION_TRAINING ALTER COLUMN UPDATED_USER NVARCHAR(100);
    ALTER TABLE HR_INDUCTION_TRAINING ALTER COLUMN UPDATED_DATE DATETIME;

    IF COL_LENGTH('HR_INDUCTION_TRAINING', 'IS_ACTIVE') IS NULL
        ALTER TABLE HR_INDUCTION_TRAINING ADD IS_ACTIVE BIT DEFAULT 1;
END
GO

-- PK
IF OBJECT_ID('HR_INDUCTION_TRAINING', 'U') IS NOT NULL
BEGIN
    DECLARE @trn_pk NVARCHAR(256);
    SELECT TOP 1 @trn_pk = name FROM sys.key_constraints WHERE parent_object_id = OBJECT_ID('HR_INDUCTION_TRAINING') AND type = 'PK';
    IF @trn_pk IS NOT NULL AND @trn_pk <> 'PK_HR_INDUCTION_TRAINING' AND NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE referenced_object_id = OBJECT_ID('HR_INDUCTION_TRAINING'))
    BEGIN
        DECLARE @drop_trn_pk NVARCHAR(MAX) = 'ALTER TABLE HR_INDUCTION_TRAINING DROP CONSTRAINT ' + @trn_pk;
        EXEC(@drop_trn_pk);
    END
    IF NOT EXISTS (SELECT 1 FROM sys.key_constraints WHERE parent_object_id = OBJECT_ID('HR_INDUCTION_TRAINING') AND type = 'PK')
    BEGIN
        ALTER TABLE HR_INDUCTION_TRAINING ADD CONSTRAINT PK_HR_INDUCTION_TRAINING PRIMARY KEY (id);
    END
END
GO


-- ==========================================
-- 4. HR_INTERVIEW (from IND_INTERVIEW_MASTER)
-- ==========================================
IF OBJECT_ID('dbo.sp_RenameTableCasingAndPrefix', 'P') IS NOT NULL
BEGIN
    EXEC dbo.sp_RenameTableCasingAndPrefix 'IND_INTERVIEW_MASTER', 'HR_INTERVIEW';
END
ELSE
BEGIN
    IF OBJECT_ID('IND_INTERVIEW_MASTER', 'U') IS NOT NULL AND OBJECT_ID('HR_INTERVIEW', 'U') IS NULL
        EXEC sp_rename 'IND_INTERVIEW_MASTER', 'HR_INTERVIEW';
END
GO

IF OBJECT_ID('HR_INTERVIEW', 'U') IS NOT NULL
BEGIN
    IF COL_LENGTH('HR_INTERVIEW', 'criteria_details') IS NOT NULL AND COL_LENGTH('HR_INTERVIEW', 'CRITERIA_DETAILS') IS NULL EXEC sp_rename 'HR_INTERVIEW.criteria_details', 'CRITERIA_DETAILS', 'COLUMN';
    IF COL_LENGTH('HR_INTERVIEW', 'answer') IS NOT NULL AND COL_LENGTH('HR_INTERVIEW', 'ANSWER') IS NULL EXEC sp_rename 'HR_INTERVIEW.answer', 'ANSWER', 'COLUMN';
    IF COL_LENGTH('HR_INTERVIEW', 'department_codes') IS NOT NULL AND COL_LENGTH('HR_INTERVIEW', 'DEPARTMENT_CODES') IS NULL EXEC sp_rename 'HR_INTERVIEW.department_codes', 'DEPARTMENT_CODES', 'COLUMN';
    IF COL_LENGTH('HR_INTERVIEW', 'level_codes') IS NOT NULL AND COL_LENGTH('HR_INTERVIEW', 'LEVEL_CODES') IS NULL EXEC sp_rename 'HR_INTERVIEW.level_codes', 'LEVEL_CODES', 'COLUMN';
    IF COL_LENGTH('HR_INTERVIEW', 'interview_round') IS NOT NULL AND COL_LENGTH('HR_INTERVIEW', 'INTERVIEW_ROUND') IS NULL EXEC sp_rename 'HR_INTERVIEW.interview_round', 'INTERVIEW_ROUND', 'COLUMN';
    IF COL_LENGTH('HR_INTERVIEW', 'attachment_required') IS NOT NULL AND COL_LENGTH('HR_INTERVIEW', 'ATTACHMENT_REQUIRED') IS NULL EXEC sp_rename 'HR_INTERVIEW.attachment_required', 'ATTACHMENT_REQUIRED', 'COLUMN';
    IF COL_LENGTH('HR_INTERVIEW', 'interview_attachment') IS NOT NULL AND COL_LENGTH('HR_INTERVIEW', 'INTERVIEW_ATTACHMENT') IS NULL EXEC sp_rename 'HR_INTERVIEW.interview_attachment', 'INTERVIEW_ATTACHMENT', 'COLUMN';
    IF COL_LENGTH('HR_INTERVIEW', 'status') IS NOT NULL AND COL_LENGTH('HR_INTERVIEW', 'STATUS') IS NULL EXEC sp_rename 'HR_INTERVIEW.status', 'STATUS', 'COLUMN';
    IF COL_LENGTH('HR_INTERVIEW', 'created_by') IS NOT NULL AND COL_LENGTH('HR_INTERVIEW', 'CREATED_USER') IS NULL EXEC sp_rename 'HR_INTERVIEW.created_by', 'CREATED_USER', 'COLUMN';
    IF COL_LENGTH('HR_INTERVIEW', 'created_at') IS NOT NULL AND COL_LENGTH('HR_INTERVIEW', 'CREATED_DATE') IS NULL EXEC sp_rename 'HR_INTERVIEW.created_at', 'CREATED_DATE', 'COLUMN';
    IF COL_LENGTH('HR_INTERVIEW', 'updated_by') IS NOT NULL AND COL_LENGTH('HR_INTERVIEW', 'UPDATED_USER') IS NULL EXEC sp_rename 'HR_INTERVIEW.updated_by', 'UPDATED_USER', 'COLUMN';
    IF COL_LENGTH('HR_INTERVIEW', 'updated_at') IS NOT NULL AND COL_LENGTH('HR_INTERVIEW', 'UPDATED_DATE') IS NULL EXEC sp_rename 'HR_INTERVIEW.updated_at', 'UPDATED_DATE', 'COLUMN';
END
GO

IF OBJECT_ID('HR_INTERVIEW', 'U') IS NOT NULL
BEGIN
    ALTER TABLE HR_INTERVIEW ALTER COLUMN CRITERIA_DETAILS NVARCHAR(300) NOT NULL;
    ALTER TABLE HR_INTERVIEW ALTER COLUMN INTERVIEW_ATTACHMENT NVARCHAR(1000);
    ALTER TABLE HR_INTERVIEW ALTER COLUMN DEPARTMENT_CODES NVARCHAR(500);
    ALTER TABLE HR_INTERVIEW ALTER COLUMN LEVEL_CODES NVARCHAR(500);
    ALTER TABLE HR_INTERVIEW ALTER COLUMN STATUS NVARCHAR(20);
    ALTER TABLE HR_INTERVIEW ALTER COLUMN CREATED_USER NVARCHAR(100);
    ALTER TABLE HR_INTERVIEW ALTER COLUMN CREATED_DATE DATETIME;
    ALTER TABLE HR_INTERVIEW ALTER COLUMN UPDATED_USER NVARCHAR(100);
    ALTER TABLE HR_INTERVIEW ALTER COLUMN UPDATED_DATE DATETIME;

    IF COL_LENGTH('HR_INTERVIEW', 'IS_ACTIVE') IS NULL
        ALTER TABLE HR_INTERVIEW ADD IS_ACTIVE BIT DEFAULT 1;
END
GO

-- PK
IF OBJECT_ID('HR_INTERVIEW', 'U') IS NOT NULL
BEGIN
    DECLARE @int_pk NVARCHAR(256);
    SELECT TOP 1 @int_pk = name FROM sys.key_constraints WHERE parent_object_id = OBJECT_ID('HR_INTERVIEW') AND type = 'PK';
    IF @int_pk IS NOT NULL AND @int_pk <> 'PK_HR_INTERVIEW' AND NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE referenced_object_id = OBJECT_ID('HR_INTERVIEW'))
    BEGIN
        DECLARE @drop_int_pk NVARCHAR(MAX) = 'ALTER TABLE HR_INTERVIEW DROP CONSTRAINT ' + @int_pk;
        EXEC(@drop_int_pk);
    END
    IF NOT EXISTS (SELECT 1 FROM sys.key_constraints WHERE parent_object_id = OBJECT_ID('HR_INTERVIEW') AND type = 'PK')
    BEGIN
        ALTER TABLE HR_INTERVIEW ADD CONSTRAINT PK_HR_INTERVIEW PRIMARY KEY (id);
    END
END
GO


-- ==========================================
-- 5. HR_INDUCTION_ROUND (from hr_induction_round_master)
-- ==========================================
IF OBJECT_ID('dbo.sp_RenameTableCasingAndPrefix', 'P') IS NOT NULL
BEGIN
    EXEC dbo.sp_RenameTableCasingAndPrefix 'hr_induction_round_master', 'HR_INDUCTION_ROUND';
END
ELSE
BEGIN
    IF OBJECT_ID('hr_induction_round_master', 'U') IS NOT NULL AND OBJECT_ID('HR_INDUCTION_ROUND', 'U') IS NULL
        EXEC sp_rename 'hr_induction_round_master', 'HR_INDUCTION_ROUND';
END
GO

IF OBJECT_ID('HR_INDUCTION_ROUND', 'U') IS NOT NULL
BEGIN
    IF COL_LENGTH('HR_INDUCTION_ROUND', 'round_name') IS NOT NULL AND COL_LENGTH('HR_INDUCTION_ROUND', 'ROUND_NAME') IS NULL EXEC sp_rename 'HR_INDUCTION_ROUND.round_name', 'ROUND_NAME', 'COLUMN';
    IF COL_LENGTH('HR_INDUCTION_ROUND', 'description') IS NOT NULL AND COL_LENGTH('HR_INDUCTION_ROUND', 'DESCRIPTION') IS NULL EXEC sp_rename 'HR_INDUCTION_ROUND.description', 'DESCRIPTION', 'COLUMN';
    IF COL_LENGTH('HR_INDUCTION_ROUND', 'status') IS NOT NULL AND COL_LENGTH('HR_INDUCTION_ROUND', 'STATUS') IS NULL EXEC sp_rename 'HR_INDUCTION_ROUND.status', 'STATUS', 'COLUMN';
    IF COL_LENGTH('HR_INDUCTION_ROUND', 'display_order') IS NOT NULL AND COL_LENGTH('HR_INDUCTION_ROUND', 'DISPLAY_ORDER') IS NULL EXEC sp_rename 'HR_INDUCTION_ROUND.display_order', 'DISPLAY_ORDER', 'COLUMN';
    IF COL_LENGTH('HR_INDUCTION_ROUND', 'created_by') IS NOT NULL AND COL_LENGTH('HR_INDUCTION_ROUND', 'CREATED_BY') IS NULL EXEC sp_rename 'HR_INDUCTION_ROUND.created_by', 'CREATED_BY', 'COLUMN';
    IF COL_LENGTH('HR_INDUCTION_ROUND', 'created_at') IS NOT NULL AND COL_LENGTH('HR_INDUCTION_ROUND', 'CREATED_DATE') IS NULL EXEC sp_rename 'HR_INDUCTION_ROUND.created_at', 'CREATED_DATE', 'COLUMN';
    IF COL_LENGTH('HR_INDUCTION_ROUND', 'updated_by') IS NOT NULL AND COL_LENGTH('HR_INDUCTION_ROUND', 'UPDATED_BY') IS NULL EXEC sp_rename 'HR_INDUCTION_ROUND.updated_by', 'UPDATED_BY', 'COLUMN';
    IF COL_LENGTH('HR_INDUCTION_ROUND', 'updated_at') IS NOT NULL AND COL_LENGTH('HR_INDUCTION_ROUND', 'UPDATED_DATE') IS NULL EXEC sp_rename 'HR_INDUCTION_ROUND.updated_at', 'UPDATED_DATE', 'COLUMN';
END
GO

IF OBJECT_ID('HR_INDUCTION_ROUND', 'U') IS NOT NULL
BEGIN
    DECLARE @index_name NVARCHAR(256);
    SELECT @index_name = i.name
    FROM sys.indexes i
    JOIN sys.index_columns ic ON i.object_id = ic.object_id AND i.index_id = ic.index_id
    JOIN sys.columns c ON ic.object_id = c.object_id AND ic.column_id = c.column_id
    WHERE i.object_id = OBJECT_ID('HR_INDUCTION_ROUND') AND c.name = 'ROUND_NAME';
    
    IF @index_name IS NOT NULL
    BEGIN
        DECLARE @drop_sql NVARCHAR(MAX) = '';
        IF EXISTS (SELECT 1 FROM sys.objects WHERE name = @index_name AND parent_object_id = OBJECT_ID('HR_INDUCTION_ROUND') AND type = 'UQ')
            SET @drop_sql = 'ALTER TABLE HR_INDUCTION_ROUND DROP CONSTRAINT ' + QUOTENAME(@index_name);
        ELSE
            SET @drop_sql = 'DROP INDEX ' + QUOTENAME(@index_name) + ' ON HR_INDUCTION_ROUND';
        EXEC(@drop_sql);
    END

    ALTER TABLE HR_INDUCTION_ROUND ALTER COLUMN ROUND_NAME NVARCHAR(100) NOT NULL;

    IF NOT EXISTS (SELECT 1 FROM sys.key_constraints WHERE parent_object_id = OBJECT_ID('HR_INDUCTION_ROUND') AND name = 'UQ_HR_INDUCTION_ROUND_ROUND_NAME')
       AND NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID('HR_INDUCTION_ROUND') AND name = 'UQ_HR_INDUCTION_ROUND_ROUND_NAME')
    BEGIN
        ALTER TABLE HR_INDUCTION_ROUND ADD CONSTRAINT UQ_HR_INDUCTION_ROUND_ROUND_NAME UNIQUE (ROUND_NAME);
    END

    ALTER TABLE HR_INDUCTION_ROUND ALTER COLUMN DESCRIPTION NVARCHAR(500);
    ALTER TABLE HR_INDUCTION_ROUND ALTER COLUMN STATUS NVARCHAR(20);
    ALTER TABLE HR_INDUCTION_ROUND ALTER COLUMN CREATED_BY NVARCHAR(100);
    ALTER TABLE HR_INDUCTION_ROUND ALTER COLUMN CREATED_DATE DATETIME;
    ALTER TABLE HR_INDUCTION_ROUND ALTER COLUMN UPDATED_BY NVARCHAR(100);
    ALTER TABLE HR_INDUCTION_ROUND ALTER COLUMN UPDATED_DATE DATETIME;

    IF COL_LENGTH('HR_INDUCTION_ROUND', 'IS_ACTIVE') IS NULL
        ALTER TABLE HR_INDUCTION_ROUND ADD IS_ACTIVE BIT DEFAULT 1;
END
GO

-- PK
IF OBJECT_ID('HR_INDUCTION_ROUND', 'U') IS NOT NULL
BEGIN
    DECLARE @rnd_pk NVARCHAR(256);
    SELECT TOP 1 @rnd_pk = name FROM sys.key_constraints WHERE parent_object_id = OBJECT_ID('HR_INDUCTION_ROUND') AND type = 'PK';
    IF @rnd_pk IS NOT NULL AND @rnd_pk <> 'PK_HR_INDUCTION_ROUND' AND NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE referenced_object_id = OBJECT_ID('HR_INDUCTION_ROUND'))
    BEGIN
        DECLARE @drop_rnd_pk NVARCHAR(MAX) = 'ALTER TABLE HR_INDUCTION_ROUND DROP CONSTRAINT ' + @rnd_pk;
        EXEC(@drop_rnd_pk);
    END
    IF NOT EXISTS (SELECT 1 FROM sys.key_constraints WHERE parent_object_id = OBJECT_ID('HR_INDUCTION_ROUND') AND type = 'PK')
    BEGIN
        ALTER TABLE HR_INDUCTION_ROUND ADD CONSTRAINT PK_HR_INDUCTION_ROUND PRIMARY KEY (id);
    END
END
GO


-- ==========================================
-- 6. HR_VERIFICATION_CRITERIA (from IND_VERIFICATION_CRITERIA)
-- ==========================================
IF OBJECT_ID('dbo.sp_RenameTableCasingAndPrefix', 'P') IS NOT NULL
BEGIN
    EXEC dbo.sp_RenameTableCasingAndPrefix 'IND_VERIFICATION_CRITERIA', 'HR_VERIFICATION_CRITERIA';
END
ELSE
BEGIN
    IF OBJECT_ID('IND_VERIFICATION_CRITERIA', 'U') IS NOT NULL AND OBJECT_ID('HR_VERIFICATION_CRITERIA', 'U') IS NULL
        EXEC sp_rename 'IND_VERIFICATION_CRITERIA', 'HR_VERIFICATION_CRITERIA';
END
GO

IF OBJECT_ID('HR_VERIFICATION_CRITERIA', 'U') IS NOT NULL
BEGIN
    IF COL_LENGTH('HR_VERIFICATION_CRITERIA', 'type') IS NOT NULL AND COL_LENGTH('HR_VERIFICATION_CRITERIA', 'TYPE') IS NULL EXEC sp_rename 'HR_VERIFICATION_CRITERIA.type', 'TYPE', 'COLUMN';
    IF COL_LENGTH('HR_VERIFICATION_CRITERIA', 'description') IS NOT NULL AND COL_LENGTH('HR_VERIFICATION_CRITERIA', 'DESCRIPTION') IS NULL EXEC sp_rename 'HR_VERIFICATION_CRITERIA.description', 'DESCRIPTION', 'COLUMN';
    IF COL_LENGTH('HR_VERIFICATION_CRITERIA', 'status') IS NOT NULL AND COL_LENGTH('HR_VERIFICATION_CRITERIA', 'STATUS') IS NULL EXEC sp_rename 'HR_VERIFICATION_CRITERIA.status', 'STATUS', 'COLUMN';
    IF COL_LENGTH('HR_VERIFICATION_CRITERIA', 'created_by') IS NOT NULL AND COL_LENGTH('HR_VERIFICATION_CRITERIA', 'CREATED_USER') IS NULL EXEC sp_rename 'HR_VERIFICATION_CRITERIA.created_by', 'CREATED_USER', 'COLUMN';
    IF COL_LENGTH('HR_VERIFICATION_CRITERIA', 'created_at') IS NOT NULL AND COL_LENGTH('HR_VERIFICATION_CRITERIA', 'CREATED_DATE') IS NULL EXEC sp_rename 'HR_VERIFICATION_CRITERIA.created_at', 'CREATED_DATE', 'COLUMN';
    IF COL_LENGTH('HR_VERIFICATION_CRITERIA', 'updated_by') IS NOT NULL AND COL_LENGTH('HR_VERIFICATION_CRITERIA', 'UPDATED_USER') IS NULL EXEC sp_rename 'HR_VERIFICATION_CRITERIA.updated_by', 'UPDATED_USER', 'COLUMN';
    IF COL_LENGTH('HR_VERIFICATION_CRITERIA', 'updated_at') IS NOT NULL AND COL_LENGTH('HR_VERIFICATION_CRITERIA', 'UPDATED_DATE') IS NULL EXEC sp_rename 'HR_VERIFICATION_CRITERIA.updated_at', 'UPDATED_DATE', 'COLUMN';
END
GO

IF OBJECT_ID('HR_VERIFICATION_CRITERIA', 'U') IS NOT NULL
BEGIN
    ALTER TABLE HR_VERIFICATION_CRITERIA ALTER COLUMN TYPE NVARCHAR(100) NOT NULL;
    ALTER TABLE HR_VERIFICATION_CRITERIA ALTER COLUMN DESCRIPTION NVARCHAR(2000) NOT NULL;
    ALTER TABLE HR_VERIFICATION_CRITERIA ALTER COLUMN STATUS NVARCHAR(20);
    ALTER TABLE HR_VERIFICATION_CRITERIA ALTER COLUMN CREATED_USER NVARCHAR(100);
    ALTER TABLE HR_VERIFICATION_CRITERIA ALTER COLUMN CREATED_DATE DATETIME;
    ALTER TABLE HR_VERIFICATION_CRITERIA ALTER COLUMN UPDATED_USER NVARCHAR(100);
    ALTER TABLE HR_VERIFICATION_CRITERIA ALTER COLUMN UPDATED_DATE DATETIME;

    IF COL_LENGTH('HR_VERIFICATION_CRITERIA', 'IS_ACTIVE') IS NULL
        ALTER TABLE HR_VERIFICATION_CRITERIA ADD IS_ACTIVE BIT DEFAULT 1;
END
GO

-- PK
IF OBJECT_ID('HR_VERIFICATION_CRITERIA', 'U') IS NOT NULL
BEGIN
    DECLARE @ver_pk NVARCHAR(256);
    SELECT TOP 1 @ver_pk = name FROM sys.key_constraints WHERE parent_object_id = OBJECT_ID('HR_VERIFICATION_CRITERIA') AND type = 'PK';
    IF @ver_pk IS NOT NULL AND @ver_pk <> 'PK_HR_VERIFICATION_CRITERIA' AND NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE referenced_object_id = OBJECT_ID('HR_VERIFICATION_CRITERIA'))
    BEGIN
        DECLARE @drop_ver_pk NVARCHAR(MAX) = 'ALTER TABLE HR_VERIFICATION_CRITERIA DROP CONSTRAINT ' + @ver_pk;
        EXEC(@drop_ver_pk);
    END
    IF NOT EXISTS (SELECT 1 FROM sys.key_constraints WHERE parent_object_id = OBJECT_ID('HR_VERIFICATION_CRITERIA') AND type = 'PK')
    BEGIN
        ALTER TABLE HR_VERIFICATION_CRITERIA ADD CONSTRAINT PK_HR_VERIFICATION_CRITERIA PRIMARY KEY (id);
    END
END
GO


-- ==========================================
-- 7. HR_EMAIL_CONTENT (from IND_EMAIL_CONTENT)
-- ==========================================
IF OBJECT_ID('dbo.sp_RenameTableCasingAndPrefix', 'P') IS NOT NULL
BEGIN
    EXEC dbo.sp_RenameTableCasingAndPrefix 'IND_EMAIL_CONTENT', 'HR_EMAIL_CONTENT';
END
ELSE
BEGIN
    IF OBJECT_ID('IND_EMAIL_CONTENT', 'U') IS NOT NULL AND OBJECT_ID('HR_EMAIL_CONTENT', 'U') IS NULL
        EXEC sp_rename 'IND_EMAIL_CONTENT', 'HR_EMAIL_CONTENT';
END
GO

IF OBJECT_ID('HR_EMAIL_CONTENT', 'U') IS NOT NULL
BEGIN
    IF COL_LENGTH('HR_EMAIL_CONTENT', 'type') IS NOT NULL AND COL_LENGTH('HR_EMAIL_CONTENT', 'TYPE') IS NULL EXEC sp_rename 'HR_EMAIL_CONTENT.type', 'TYPE', 'COLUMN';
    IF COL_LENGTH('HR_EMAIL_CONTENT', 'subject') IS NOT NULL AND COL_LENGTH('HR_EMAIL_CONTENT', 'SUBJECT') IS NULL EXEC sp_rename 'HR_EMAIL_CONTENT.subject', 'SUBJECT', 'COLUMN';
    IF COL_LENGTH('HR_EMAIL_CONTENT', 'body_content') IS NOT NULL AND COL_LENGTH('HR_EMAIL_CONTENT', 'BODY_CONTENT') IS NULL EXEC sp_rename 'HR_EMAIL_CONTENT.body_content', 'BODY_CONTENT', 'COLUMN';
    IF COL_LENGTH('HR_EMAIL_CONTENT', 'yours_windfully') IS NOT NULL AND COL_LENGTH('HR_EMAIL_CONTENT', 'YOURS_WINDFULLY') IS NULL EXEC sp_rename 'HR_EMAIL_CONTENT.yours_windfully', 'YOURS_WINDFULLY', 'COLUMN';
    IF COL_LENGTH('HR_EMAIL_CONTENT', 'status') IS NOT NULL AND COL_LENGTH('HR_EMAIL_CONTENT', 'STATUS') IS NULL EXEC sp_rename 'HR_EMAIL_CONTENT.status', 'STATUS', 'COLUMN';
    IF COL_LENGTH('HR_EMAIL_CONTENT', 'created_by') IS NOT NULL AND COL_LENGTH('HR_EMAIL_CONTENT', 'CREATED_USER') IS NULL EXEC sp_rename 'HR_EMAIL_CONTENT.created_by', 'CREATED_USER', 'COLUMN';
    IF COL_LENGTH('HR_EMAIL_CONTENT', 'created_at') IS NOT NULL AND COL_LENGTH('HR_EMAIL_CONTENT', 'CREATED_DATE') IS NULL EXEC sp_rename 'HR_EMAIL_CONTENT.created_at', 'CREATED_DATE', 'COLUMN';
    IF COL_LENGTH('HR_EMAIL_CONTENT', 'updated_by') IS NOT NULL AND COL_LENGTH('HR_EMAIL_CONTENT', 'UPDATED_USER') IS NULL EXEC sp_rename 'HR_EMAIL_CONTENT.updated_by', 'UPDATED_USER', 'COLUMN';
    IF COL_LENGTH('HR_EMAIL_CONTENT', 'updated_at') IS NOT NULL AND COL_LENGTH('HR_EMAIL_CONTENT', 'UPDATED_DATE') IS NULL EXEC sp_rename 'HR_EMAIL_CONTENT.updated_at', 'UPDATED_DATE', 'COLUMN';
END
GO

IF OBJECT_ID('HR_EMAIL_CONTENT', 'U') IS NOT NULL
BEGIN
    ALTER TABLE HR_EMAIL_CONTENT ALTER COLUMN TYPE NVARCHAR(100) NOT NULL;
    ALTER TABLE HR_EMAIL_CONTENT ALTER COLUMN SUBJECT NVARCHAR(500) NOT NULL;
    ALTER TABLE HR_EMAIL_CONTENT ALTER COLUMN YOURS_WINDFULLY NVARCHAR(200) NOT NULL;
    ALTER TABLE HR_EMAIL_CONTENT ALTER COLUMN STATUS NVARCHAR(20);
    ALTER TABLE HR_EMAIL_CONTENT ALTER COLUMN CREATED_USER NVARCHAR(100);
    ALTER TABLE HR_EMAIL_CONTENT ALTER COLUMN CREATED_DATE DATETIME;
    ALTER TABLE HR_EMAIL_CONTENT ALTER COLUMN UPDATED_USER NVARCHAR(100);
    ALTER TABLE HR_EMAIL_CONTENT ALTER COLUMN UPDATED_DATE DATETIME;

    IF COL_LENGTH('HR_EMAIL_CONTENT', 'IS_ACTIVE') IS NULL
        ALTER TABLE HR_EMAIL_CONTENT ADD IS_ACTIVE BIT DEFAULT 1;
END
GO

-- PK
IF OBJECT_ID('HR_EMAIL_CONTENT', 'U') IS NOT NULL
BEGIN
    DECLARE @eml_pk NVARCHAR(256);
    SELECT TOP 1 @eml_pk = name FROM sys.key_constraints WHERE parent_object_id = OBJECT_ID('HR_EMAIL_CONTENT') AND type = 'PK';
    IF @eml_pk IS NOT NULL AND @eml_pk <> 'PK_HR_EMAIL_CONTENT' AND NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE referenced_object_id = OBJECT_ID('HR_EMAIL_CONTENT'))
    BEGIN
        DECLARE @drop_eml_pk NVARCHAR(MAX) = 'ALTER TABLE HR_EMAIL_CONTENT DROP CONSTRAINT ' + @eml_pk;
        EXEC(@drop_eml_pk);
    END
    IF NOT EXISTS (SELECT 1 FROM sys.key_constraints WHERE parent_object_id = OBJECT_ID('HR_EMAIL_CONTENT') AND type = 'PK')
    BEGIN
        ALTER TABLE HR_EMAIL_CONTENT ADD CONSTRAINT PK_HR_EMAIL_CONTENT PRIMARY KEY (id);
    END
END
GO


-- ==========================================
-- Re-establish Foreign Keys
-- ==========================================
IF OBJECT_ID('HR_INDUCTION_TRAINING', 'U') IS NOT NULL AND OBJECT_ID('HR_INDUCTION_ASSIGNMENT', 'U') IS NOT NULL
BEGIN
    ALTER TABLE HR_INDUCTION_TRAINING ADD CONSTRAINT FK_HR_INDUCTION_TRAINING_ASSIGN FOREIGN KEY (ASSIGNMENT_ID) REFERENCES HR_INDUCTION_ASSIGNMENT(id);
END
GO

IF OBJECT_ID('HR_INDUCTION_TRAINING', 'U') IS NOT NULL AND OBJECT_ID('HR_INDUCTION', 'U') IS NOT NULL
BEGIN
    ALTER TABLE HR_INDUCTION_TRAINING ADD CONSTRAINT FK_HR_INDUCTION_TRAINING_MASTER FOREIGN KEY (INDUCTION_MASTER_ID) REFERENCES HR_INDUCTION(id);
END
GO
