-- V001__Master_Module.sql
-- Module 1: Master (Global Common) Schema Standardization
-- Renames and normalizes:
-- 1. MASTER_COUNTRY -> MST_COUNTRY
-- 2. MASTER_STATE -> MST_STATE
-- 3. product_master -> MST_PRODUCT
-- 4. FREIGHT_MASTER -> MST_FREIGHT
-- 5. MODE_OF_DESPATCH -> MST_DESPATCH_MODE

-- ==========================================
-- 1. MASTER_COUNTRY -> MST_COUNTRY
-- ==========================================
IF OBJECT_ID('MASTER_COUNTRY', 'U') IS NOT NULL
BEGIN
    IF OBJECT_ID('MST_COUNTRY', 'U') IS NULL
    BEGIN
        EXEC sp_rename 'MASTER_COUNTRY', 'MST_COUNTRY';
    END
    ELSE
    BEGIN
        DROP TABLE MASTER_COUNTRY;
    END
END
GO

IF COL_LENGTH('MST_COUNTRY', 'created_by') IS NOT NULL AND COL_LENGTH('MST_COUNTRY', 'CREATED_BY') IS NULL
BEGIN
    EXEC sp_rename 'MST_COUNTRY.created_by', 'CREATED_BY', 'COLUMN';
END
GO
IF COL_LENGTH('MST_COUNTRY', 'created_at') IS NOT NULL AND COL_LENGTH('MST_COUNTRY', 'CREATED_DATE') IS NULL
BEGIN
    EXEC sp_rename 'MST_COUNTRY.created_at', 'CREATED_DATE', 'COLUMN';
END
GO
IF COL_LENGTH('MST_COUNTRY', 'updated_by') IS NOT NULL AND COL_LENGTH('MST_COUNTRY', 'UPDATED_BY') IS NULL
BEGIN
    EXEC sp_rename 'MST_COUNTRY.updated_by', 'UPDATED_BY', 'COLUMN';
END
GO
IF COL_LENGTH('MST_COUNTRY', 'updated_at') IS NOT NULL AND COL_LENGTH('MST_COUNTRY', 'UPDATED_DATE') IS NULL
BEGIN
    EXEC sp_rename 'MST_COUNTRY.updated_at', 'UPDATED_DATE', 'COLUMN';
END
GO

IF OBJECT_ID('MST_COUNTRY', 'U') IS NOT NULL
BEGIN
    ALTER TABLE MST_COUNTRY ALTER COLUMN COUNTRY NVARCHAR(100) NOT NULL;
    ALTER TABLE MST_COUNTRY ALTER COLUMN STATUS NVARCHAR(20);
    ALTER TABLE MST_COUNTRY ALTER COLUMN CREATED_BY NVARCHAR(100);
    ALTER TABLE MST_COUNTRY ALTER COLUMN CREATED_DATE DATETIME;
    ALTER TABLE MST_COUNTRY ALTER COLUMN UPDATED_BY NVARCHAR(100);
    ALTER TABLE MST_COUNTRY ALTER COLUMN UPDATED_DATE DATETIME;
END
GO

IF OBJECT_ID('MST_COUNTRY', 'U') IS NOT NULL
BEGIN
    IF COL_LENGTH('MST_COUNTRY', 'IS_ACTIVE') IS NULL
    BEGIN
        ALTER TABLE MST_COUNTRY ADD IS_ACTIVE BIT DEFAULT 1;
    END
END
GO

-- Recreate Country Primary Key Constraint with Named PK
IF OBJECT_ID('MST_COUNTRY', 'U') IS NOT NULL
BEGIN
    DECLARE @country_pk NVARCHAR(256);
    SELECT TOP 1 @country_pk = name 
    FROM sys.key_constraints 
    WHERE parent_object_id = OBJECT_ID('MST_COUNTRY') AND type = 'PK';
    
    IF @country_pk IS NOT NULL AND @country_pk <> 'PK_MST_COUNTRY'
    BEGIN
        DECLARE @drop_country_pk NVARCHAR(MAX) = 'ALTER TABLE MST_COUNTRY DROP CONSTRAINT ' + @country_pk;
        EXEC(@drop_country_pk);
    END
    
    IF NOT EXISTS (SELECT 1 FROM sys.key_constraints WHERE parent_object_id = OBJECT_ID('MST_COUNTRY') AND name = 'PK_MST_COUNTRY')
    BEGIN
        ALTER TABLE MST_COUNTRY ADD CONSTRAINT PK_MST_COUNTRY PRIMARY KEY (id);
    END
END
GO


-- ==========================================
-- 2. MASTER_STATE -> MST_STATE
-- ==========================================
IF OBJECT_ID('MASTER_STATE', 'U') IS NOT NULL
BEGIN
    IF OBJECT_ID('MST_STATE', 'U') IS NULL
    BEGIN
        EXEC sp_rename 'MASTER_STATE', 'MST_STATE';
    END
    ELSE
    BEGIN
        DROP TABLE MASTER_STATE;
    END
END
GO

IF COL_LENGTH('MST_STATE', 'created_by') IS NOT NULL AND COL_LENGTH('MST_STATE', 'CREATED_BY') IS NULL
BEGIN
    EXEC sp_rename 'MST_STATE.created_by', 'CREATED_BY', 'COLUMN';
END
GO
IF COL_LENGTH('MST_STATE', 'created_at') IS NOT NULL AND COL_LENGTH('MST_STATE', 'CREATED_DATE') IS NULL
BEGIN
    EXEC sp_rename 'MST_STATE.created_at', 'CREATED_DATE', 'COLUMN';
END
GO
IF COL_LENGTH('MST_STATE', 'updated_by') IS NOT NULL AND COL_LENGTH('MST_STATE', 'UPDATED_BY') IS NULL
BEGIN
    EXEC sp_rename 'MST_STATE.updated_by', 'UPDATED_BY', 'COLUMN';
END
GO
IF COL_LENGTH('MST_STATE', 'updated_at') IS NOT NULL AND COL_LENGTH('MST_STATE', 'UPDATED_DATE') IS NULL
BEGIN
    EXEC sp_rename 'MST_STATE.updated_at', 'UPDATED_DATE', 'COLUMN';
END
GO

IF OBJECT_ID('MST_STATE', 'U') IS NOT NULL
BEGIN
    ALTER TABLE MST_STATE ALTER COLUMN COUNTRY_NAME NVARCHAR(100) NOT NULL;
    ALTER TABLE MST_STATE ALTER COLUMN STATE_NAME NVARCHAR(100) NOT NULL;
    ALTER TABLE MST_STATE ALTER COLUMN STATE_CODE NVARCHAR(20) NOT NULL;
    ALTER TABLE MST_STATE ALTER COLUMN STATUS NVARCHAR(20);
    ALTER TABLE MST_STATE ALTER COLUMN CREATED_BY NVARCHAR(100);
    ALTER TABLE MST_STATE ALTER COLUMN CREATED_DATE DATETIME;
    ALTER TABLE MST_STATE ALTER COLUMN UPDATED_BY NVARCHAR(100);
    ALTER TABLE MST_STATE ALTER COLUMN UPDATED_DATE DATETIME;
END
GO

IF OBJECT_ID('MST_STATE', 'U') IS NOT NULL
BEGIN
    IF COL_LENGTH('MST_STATE', 'IS_ACTIVE') IS NULL
    BEGIN
        ALTER TABLE MST_STATE ADD IS_ACTIVE BIT DEFAULT 1;
    END
END
GO

-- Recreate State Primary Key Constraint with Named PK
IF OBJECT_ID('MST_STATE', 'U') IS NOT NULL
BEGIN
    DECLARE @state_pk NVARCHAR(256);
    SELECT TOP 1 @state_pk = name 
    FROM sys.key_constraints 
    WHERE parent_object_id = OBJECT_ID('MST_STATE') AND type = 'PK';
    
    IF @state_pk IS NOT NULL AND @state_pk <> 'PK_MST_STATE'
    BEGIN
        DECLARE @drop_state_pk NVARCHAR(MAX) = 'ALTER TABLE MST_STATE DROP CONSTRAINT ' + @state_pk;
        EXEC(@drop_state_pk);
    END
    
    IF NOT EXISTS (SELECT 1 FROM sys.key_constraints WHERE parent_object_id = OBJECT_ID('MST_STATE') AND name = 'PK_MST_STATE')
    BEGIN
        ALTER TABLE MST_STATE ADD CONSTRAINT PK_MST_STATE PRIMARY KEY (id);
    END
END
GO

-- Unique Index and Foreign Key
IF OBJECT_ID('MST_COUNTRY', 'U') IS NOT NULL
BEGIN
    IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID('MST_COUNTRY') AND name = 'UQ_MST_COUNTRY_NAME')
    BEGIN
        ALTER TABLE MST_COUNTRY ADD CONSTRAINT UQ_MST_COUNTRY_NAME UNIQUE (COUNTRY);
    END
END
GO

IF OBJECT_ID('MST_STATE', 'U') IS NOT NULL AND OBJECT_ID('MST_COUNTRY', 'U') IS NOT NULL
BEGIN
    -- Delete invalid country names to prevent FK constraint failure
    DELETE FROM MST_STATE WHERE COUNTRY_NAME NOT IN (SELECT COUNTRY FROM MST_COUNTRY);

    IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE object_id = OBJECT_ID('FK_MST_STATE_COUNTRY'))
    BEGIN
        ALTER TABLE MST_STATE ADD CONSTRAINT FK_MST_STATE_COUNTRY FOREIGN KEY (COUNTRY_NAME) REFERENCES MST_COUNTRY(COUNTRY);
    END
END
GO


-- ==========================================
-- 3. product_master -> MST_PRODUCT
-- ==========================================
IF OBJECT_ID('product_master', 'U') IS NOT NULL
BEGIN
    IF OBJECT_ID('MST_PRODUCT', 'U') IS NULL
    BEGIN
        EXEC sp_rename 'product_master', 'MST_PRODUCT';
    END
    ELSE
    BEGIN
        DROP TABLE product_master;
    END
END
GO

IF OBJECT_ID('MST_PRODUCT', 'U') IS NOT NULL
BEGIN
    -- Alter existing columns to standardize sizes and remove NVARCHAR(MAX) on product details
    ALTER TABLE MST_PRODUCT ALTER COLUMN product_title NVARCHAR(255);
    ALTER TABLE MST_PRODUCT ALTER COLUMN product_slug NVARCHAR(255);
    ALTER TABLE MST_PRODUCT ALTER COLUMN product_desc NVARCHAR(1000);
    ALTER TABLE MST_PRODUCT ALTER COLUMN product_features NVARCHAR(1000);
    ALTER TABLE MST_PRODUCT ALTER COLUMN status NVARCHAR(50);
    
    -- Add standard audit columns
    IF COL_LENGTH('MST_PRODUCT', 'CREATED_BY') IS NULL
        ALTER TABLE MST_PRODUCT ADD CREATED_BY NVARCHAR(100) DEFAULT 'Admin';
    IF COL_LENGTH('MST_PRODUCT', 'CREATED_DATE') IS NULL
        ALTER TABLE MST_PRODUCT ADD CREATED_DATE DATETIME DEFAULT GETDATE();
    IF COL_LENGTH('MST_PRODUCT', 'UPDATED_BY') IS NULL
        ALTER TABLE MST_PRODUCT ADD UPDATED_BY NVARCHAR(100) DEFAULT 'Admin';
    IF COL_LENGTH('MST_PRODUCT', 'UPDATED_DATE') IS NULL
        ALTER TABLE MST_PRODUCT ADD UPDATED_DATE DATETIME DEFAULT GETDATE();
    IF COL_LENGTH('MST_PRODUCT', 'IS_ACTIVE') IS NULL
        ALTER TABLE MST_PRODUCT ADD IS_ACTIVE BIT DEFAULT 1;
END
GO

-- Recreate Product Primary Key Constraint with Named PK
IF OBJECT_ID('MST_PRODUCT', 'U') IS NOT NULL
BEGIN
    DECLARE @prod_pk NVARCHAR(256);
    SELECT TOP 1 @prod_pk = name 
    FROM sys.key_constraints 
    WHERE parent_object_id = OBJECT_ID('MST_PRODUCT') AND type = 'PK';
    
    IF @prod_pk IS NOT NULL AND @prod_pk <> 'PK_MST_PRODUCT'
    BEGIN
        DECLARE @drop_prod_pk NVARCHAR(MAX) = 'ALTER TABLE MST_PRODUCT DROP CONSTRAINT ' + @prod_pk;
        EXEC(@drop_prod_pk);
    END
    
    IF NOT EXISTS (SELECT 1 FROM sys.key_constraints WHERE parent_object_id = OBJECT_ID('MST_PRODUCT') AND name = 'PK_MST_PRODUCT')
    BEGIN
        ALTER TABLE MST_PRODUCT ADD CONSTRAINT PK_MST_PRODUCT PRIMARY KEY (id);
    END
END
GO


-- ==========================================
-- 4. FREIGHT_MASTER -> MST_FREIGHT
-- ==========================================
IF OBJECT_ID('FREIGHT_MASTER', 'U') IS NOT NULL
BEGIN
    IF OBJECT_ID('MST_FREIGHT', 'U') IS NULL
    BEGIN
        EXEC sp_rename 'FREIGHT_MASTER', 'MST_FREIGHT';
    END
    ELSE
    BEGIN
        DROP TABLE FREIGHT_MASTER;
    END
END
GO

IF COL_LENGTH('MST_FREIGHT', 'freight_type') IS NOT NULL AND COL_LENGTH('MST_FREIGHT', 'FREIGHT_TYPE') IS NULL
BEGIN
    EXEC sp_rename 'MST_FREIGHT.freight_type', 'FREIGHT_TYPE', 'COLUMN';
END
GO
IF COL_LENGTH('MST_FREIGHT', 'description') IS NOT NULL AND COL_LENGTH('MST_FREIGHT', 'DESCRIPTION') IS NULL
BEGIN
    EXEC sp_rename 'MST_FREIGHT.description', 'DESCRIPTION', 'COLUMN';
END
GO
IF COL_LENGTH('MST_FREIGHT', 'status') IS NOT NULL AND COL_LENGTH('MST_FREIGHT', 'STATUS') IS NULL
BEGIN
    EXEC sp_rename 'MST_FREIGHT.status', 'STATUS', 'COLUMN';
END
GO
IF COL_LENGTH('MST_FREIGHT', 'created_by') IS NOT NULL AND COL_LENGTH('MST_FREIGHT', 'CREATED_BY') IS NULL
BEGIN
    EXEC sp_rename 'MST_FREIGHT.created_by', 'CREATED_BY', 'COLUMN';
END
GO
IF COL_LENGTH('MST_FREIGHT', 'created_date') IS NOT NULL AND COL_LENGTH('MST_FREIGHT', 'CREATED_DATE') IS NULL
BEGIN
    EXEC sp_rename 'MST_FREIGHT.created_date', 'CREATED_DATE', 'COLUMN';
END
GO
IF COL_LENGTH('MST_FREIGHT', 'updated_by') IS NOT NULL AND COL_LENGTH('MST_FREIGHT', 'UPDATED_BY') IS NULL
BEGIN
    EXEC sp_rename 'MST_FREIGHT.updated_by', 'UPDATED_BY', 'COLUMN';
END
GO
IF COL_LENGTH('MST_FREIGHT', 'updated_date') IS NOT NULL AND COL_LENGTH('MST_FREIGHT', 'UPDATED_DATE') IS NULL
BEGIN
    EXEC sp_rename 'MST_FREIGHT.updated_date', 'UPDATED_DATE', 'COLUMN';
END
GO

IF OBJECT_ID('MST_FREIGHT', 'U') IS NOT NULL
BEGIN
    ALTER TABLE MST_FREIGHT ALTER COLUMN FREIGHT_TYPE NVARCHAR(100) NOT NULL;
    ALTER TABLE MST_FREIGHT ALTER COLUMN DESCRIPTION NVARCHAR(1000);
    ALTER TABLE MST_FREIGHT ALTER COLUMN STATUS NVARCHAR(50) NOT NULL;
    ALTER TABLE MST_FREIGHT ALTER COLUMN CREATED_BY NVARCHAR(100);
    ALTER TABLE MST_FREIGHT ALTER COLUMN CREATED_DATE DATETIME;
    ALTER TABLE MST_FREIGHT ALTER COLUMN UPDATED_BY NVARCHAR(100);
    ALTER TABLE MST_FREIGHT ALTER COLUMN UPDATED_DATE DATETIME;
END
GO

IF OBJECT_ID('MST_FREIGHT', 'U') IS NOT NULL
BEGIN
    IF COL_LENGTH('MST_FREIGHT', 'IS_ACTIVE') IS NULL
    BEGIN
        ALTER TABLE MST_FREIGHT ADD IS_ACTIVE BIT DEFAULT 1;
    END
END
GO

-- Recreate Freight Primary Key Constraint with Named PK
IF OBJECT_ID('MST_FREIGHT', 'U') IS NOT NULL
BEGIN
    DECLARE @freight_pk NVARCHAR(256);
    SELECT TOP 1 @freight_pk = name 
    FROM sys.key_constraints 
    WHERE parent_object_id = OBJECT_ID('MST_FREIGHT') AND type = 'PK';
    
    IF @freight_pk IS NOT NULL AND @freight_pk <> 'PK_MST_FREIGHT'
    BEGIN
        DECLARE @drop_freight_pk NVARCHAR(MAX) = 'ALTER TABLE MST_FREIGHT DROP CONSTRAINT ' + @freight_pk;
        EXEC(@drop_freight_pk);
    END
    
    IF NOT EXISTS (SELECT 1 FROM sys.key_constraints WHERE parent_object_id = OBJECT_ID('MST_FREIGHT') AND name = 'PK_MST_FREIGHT')
    BEGIN
        ALTER TABLE MST_FREIGHT ADD CONSTRAINT PK_MST_FREIGHT PRIMARY KEY (id);
    END
END
GO


-- ==========================================
-- 5. MODE_OF_DESPATCH -> MST_DESPATCH_MODE
-- ==========================================
IF OBJECT_ID('MODE_OF_DESPATCH', 'U') IS NOT NULL
BEGIN
    IF OBJECT_ID('MST_DESPATCH_MODE', 'U') IS NULL
    BEGIN
        EXEC sp_rename 'MODE_OF_DESPATCH', 'MST_DESPATCH_MODE';
    END
    ELSE
    BEGIN
        DROP TABLE MODE_OF_DESPATCH;
    END
END
GO

IF COL_LENGTH('MST_DESPATCH_MODE', 'mode_name') IS NOT NULL AND COL_LENGTH('MST_DESPATCH_MODE', 'MODE_NAME') IS NULL
BEGIN
    EXEC sp_rename 'MST_DESPATCH_MODE.mode_name', 'MODE_NAME', 'COLUMN';
END
GO
IF COL_LENGTH('MST_DESPATCH_MODE', 'description') IS NOT NULL AND COL_LENGTH('MST_DESPATCH_MODE', 'DESCRIPTION') IS NULL
BEGIN
    EXEC sp_rename 'MST_DESPATCH_MODE.description', 'DESCRIPTION', 'COLUMN';
END
GO
IF COL_LENGTH('MST_DESPATCH_MODE', 'status') IS NOT NULL AND COL_LENGTH('MST_DESPATCH_MODE', 'STATUS') IS NULL
BEGIN
    EXEC sp_rename 'MST_DESPATCH_MODE.status', 'STATUS', 'COLUMN';
END
GO
IF COL_LENGTH('MST_DESPATCH_MODE', 'created_by') IS NOT NULL AND COL_LENGTH('MST_DESPATCH_MODE', 'CREATED_BY') IS NULL
BEGIN
    EXEC sp_rename 'MST_DESPATCH_MODE.created_by', 'CREATED_BY', 'COLUMN';
END
GO
IF COL_LENGTH('MST_DESPATCH_MODE', 'created_date') IS NOT NULL AND COL_LENGTH('MST_DESPATCH_MODE', 'CREATED_DATE') IS NULL
BEGIN
    EXEC sp_rename 'MST_DESPATCH_MODE.created_date', 'CREATED_DATE', 'COLUMN';
END
GO
IF COL_LENGTH('MST_DESPATCH_MODE', 'updated_by') IS NOT NULL AND COL_LENGTH('MST_DESPATCH_MODE', 'UPDATED_BY') IS NULL
BEGIN
    EXEC sp_rename 'MST_DESPATCH_MODE.updated_by', 'UPDATED_BY', 'COLUMN';
END
GO
IF COL_LENGTH('MST_DESPATCH_MODE', 'updated_date') IS NOT NULL AND COL_LENGTH('MST_DESPATCH_MODE', 'UPDATED_DATE') IS NULL
BEGIN
    EXEC sp_rename 'MST_DESPATCH_MODE.updated_date', 'UPDATED_DATE', 'COLUMN';
END
GO

IF OBJECT_ID('MST_DESPATCH_MODE', 'U') IS NOT NULL
BEGIN
    ALTER TABLE MST_DESPATCH_MODE ALTER COLUMN MODE_NAME NVARCHAR(100) NOT NULL;
    ALTER TABLE MST_DESPATCH_MODE ALTER COLUMN DESCRIPTION NVARCHAR(1000);
    ALTER TABLE MST_DESPATCH_MODE ALTER COLUMN STATUS NVARCHAR(50) NOT NULL;
    ALTER TABLE MST_DESPATCH_MODE ALTER COLUMN CREATED_BY NVARCHAR(100);
    ALTER TABLE MST_DESPATCH_MODE ALTER COLUMN CREATED_DATE DATETIME;
    ALTER TABLE MST_DESPATCH_MODE ALTER COLUMN UPDATED_BY NVARCHAR(100);
    ALTER TABLE MST_DESPATCH_MODE ALTER COLUMN UPDATED_DATE DATETIME;
END
GO

IF OBJECT_ID('MST_DESPATCH_MODE', 'U') IS NOT NULL
BEGIN
    IF COL_LENGTH('MST_DESPATCH_MODE', 'IS_ACTIVE') IS NULL
    BEGIN
        ALTER TABLE MST_DESPATCH_MODE ADD IS_ACTIVE BIT DEFAULT 1;
    END
END
GO

-- Recreate Despatch Mode Primary Key Constraint with Named PK
IF OBJECT_ID('MST_DESPATCH_MODE', 'U') IS NOT NULL
BEGIN
    DECLARE @mode_pk NVARCHAR(256);
    SELECT TOP 1 @mode_pk = name 
    FROM sys.key_constraints 
    WHERE parent_object_id = OBJECT_ID('MST_DESPATCH_MODE') AND type = 'PK';
    
    IF @mode_pk IS NOT NULL AND @mode_pk <> 'PK_MST_DESPATCH_MODE'
    BEGIN
        DECLARE @drop_mode_pk NVARCHAR(MAX) = 'ALTER TABLE MST_DESPATCH_MODE DROP CONSTRAINT ' + @mode_pk;
        EXEC(@drop_mode_pk);
    END
    
    IF NOT EXISTS (SELECT 1 FROM sys.key_constraints WHERE parent_object_id = OBJECT_ID('MST_DESPATCH_MODE') AND name = 'PK_MST_DESPATCH_MODE')
    BEGIN
        ALTER TABLE MST_DESPATCH_MODE ADD CONSTRAINT PK_MST_DESPATCH_MODE PRIMARY KEY (id);
    END
END
GO
