-- V010__Add_Is_Active_Checklist_Assignment.sql
-- Add missing IS_ACTIVE columns to dynamic schemas

-- 1. QMS_CHECKLIST_ASSIGNMENT
IF OBJECT_ID('QMS_CHECKLIST_ASSIGNMENT', 'U') IS NOT NULL
BEGIN
    IF COL_LENGTH('QMS_CHECKLIST_ASSIGNMENT', 'IS_ACTIVE') IS NULL
    BEGIN
        ALTER TABLE QMS_CHECKLIST_ASSIGNMENT ADD IS_ACTIVE BIT DEFAULT 1;
    END
END
GO

-- 2. HR_INDUCTION_ROUND
IF OBJECT_ID('HR_INDUCTION_ROUND', 'U') IS NOT NULL
BEGIN
    IF COL_LENGTH('HR_INDUCTION_ROUND', 'IS_ACTIVE') IS NULL
    BEGIN
        ALTER TABLE HR_INDUCTION_ROUND ADD IS_ACTIVE BIT DEFAULT 1;
    END
END
GO
